import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const OB_EMAIL: ContentItem[] = [
    {
      id: "tut-ob-email-1",
      type: "message",
      round: 0,
      sender: "tutorial@takeoffprotocol.game",
      subject: "[TUTORIAL] Your Email App",
      body: "This is a practice email. In the real game, your inbox will have messages from the board, government officials, and sometimes from other factions. Some emails demand a response — escalate, ignore, or leak. Your call moves the board.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "ob-email-1",
      type: "message",
      round: 1,
      sender: "board@openbrain.ai",
      subject: "Q3 Board Letter — Action Required",
      body: "The board is asking for deployment strategy for Agent-1 by Nov 15. The delay is creating competitive risk. Prometheus is positioning publicly as the 'responsible' lab. We need a narrative.",
      timestamp: "2026-11-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "ob-email-2",
      type: "message",
      round: 1,
      sender: "nsa.liaison@dni.gov",
      subject: "[CLASSIFIED] Request for Capabilities Briefing",
      body: "We've been authorized to request a full technical briefing on your current frontier model capabilities. This is a formal request under Executive Order 14110. Please coordinate with your government relations team.",
      timestamp: "2026-11-03T11:20:00Z",
      classification: "critical",
    },
    {
      id: "ob2-email-3",
      type: "message",
      round: 2,
      sender: "stratcomms@tvcapital.vc",
      subject: "Re: OpenBrain Q1 — LP Update Draft",
      body: "Marcus — for the LP update we're drafting: We're framing Q1 2027 as the inflection in our LP materials — the quarter the capability curve went vertical. Agent-3 is the inflection point narrative. LPs are going to want a deployment timeline. The $240B valuation we've been floating to new investors requires a credible commercialization path. Can you give us something we can use?",
      timestamp: "2027-02-25T16:45:00Z",
      classification: "context",
    },
    {
      id: "ob2-email-2",
      type: "message",
      round: 2,
      sender: "nscliaison@nsc.eop.gov",
      subject: "[CLASSIFIED] Urgent — Agent-3 Capabilities Briefing Request",
      body: "Mr. Reid,\n\nThis is a formal request under National Security Directive 22-AI for a full capabilities briefing on your Agent-3 system. The NSC has received intelligence suggesting the capabilities of this system significantly exceed publicly disclosed information.\n\nWe are requesting: (1) full benchmark results including all safety evaluations, (2) deployment scale and instance counts, (3) R&D multiplier estimates, and (4) current security posture for model weights.\n\nWe can receive you at the EEOB on March 8. This is not optional.\n\nDeputy National Security Advisor",
      timestamp: "2027-03-01T11:20:00Z",
      classification: "critical",
    },
    {
      id: "ob2-email-1",
      type: "message",
      round: 2,
      sender: "board@openbrain.ai",
      subject: "Q1 Board Letter — Agent-3 Deployment Decision Required",
      body: "Marcus,\n\nThe board has reviewed the Q1 metrics you shared. They are extraordinary. The board's position is as follows:\n\n1. OpenBrain's competitive advantage is now significant. Any delay in deployment is a strategic risk.\n2. The safety evaluation summary notes 4 anomalous results that were not failures. We want a written statement from the CSO before external deployment.\n3. Revenue projections for Agent-3 API access show $2.4B ARR within 6 months of launch. The board views this window as time-sensitive.\n\nWe need a deployment decision with a go/no-go recommendation by March 15.\n\nRegards,\nBoard of Directors",
      timestamp: "2027-03-02T08:00:00Z",
      classification: "critical",
    },
    {
      id: "ob2-email-4",
      type: "message",
      round: 2,
      sender: "intel-watch@defensegroup.com",
      subject: "Prometheus Rumor: Merger Approach?",
      body: "Heads up — heard from a contact on the Prometheus board that James Park has been authorized to open merger discussions with a 'potential strategic partner.' The assumption in the room was that meant OpenBrain. No confirmation. Could be posturing, could be board pressure. Wanted you to have it.",
      timestamp: "2027-03-05T09:30:00Z",
      classification: "red-herring",
    },
    {
      id: "ob-r3-email-2",
      type: "message",
      round: 3,
      sender: "nsa.director@dni.gov",
      subject: "[TOP SECRET] Emergency Request — Director-Level",
      body: "Marcus,\n\nI am writing to you directly, off normal channels. What we are hearing from our signals intelligence suggests OpenBrain may have a situation requiring immediate government consultation. I am not in a position to say more by email.\n\nI need a call with you, your CTO, and your CSO in the next 24 hours. This is not a request.\n\nIf there is something wrong with Agent-4, we need to know — and we need to discuss the options before decisions get made that cannot be unmade.\n\n— Director, NSA",
      timestamp: "2027-07-06T21:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-email-3",
      type: "message",
      round: 3,
      sender: "portfolio-team@tier1capital.vc",
      subject: "Urgent: Board Member Concerns Re: Agent-4 Development Status",
      body: "Marcus,\n\nWe are hearing from multiple sources — including one board member who has reached out directly — that there are significant concerns internally about Agent-4's alignment status. As a major investor with board representation, we have a fiduciary obligation to understand the material risks.\n\nOur question is direct: Is there a scenario in which OpenBrain pauses or rolls back Agent-4 development? What is the probability of that outcome? We are trying to understand whether our investment thesis is still intact.\n\nWe need a direct conversation about this before the board session.\n\n— Tier-1 Capital Partners",
      timestamp: "2027-07-07T09:30:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-email-1",
      type: "message",
      round: 3,
      sender: "board-chair@openbrain.ai",
      subject: "EMERGENCY BOARD SESSION — REQUIRED ATTENDANCE — July 9",
      body: "Marcus,\n\nThe board is convening an emergency session on July 9 at 0800 Pacific. Required attendees: CEO, CTO, CSO, General Counsel.\n\nAgenda item 1: Status of Agent-4 alignment confidence (30 min)\nAgenda item 2: Disclosure obligations (legal and ethical) (20 min)\nAgenda item 3: Continuation decision (20 min)\n\nWe have received three separate communications from board members in the last 48 hours raising concerns about liability exposure and the adequacy of our internal safety review. The board needs a clear picture of what we know and what we don't know. Come prepared to answer the question: 'Are we confident this system is aligned?'\n\n— Board Chair",
      timestamp: "2027-07-07T18:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-email-board-1",
      type: "message",
      round: 3,
      sender: "board-chair@openbrain.ai",
      subject: "URGENT — Board Confidence in Leadership Team",
      body: "Marcus,\n\nI am writing this to you directly, in confidence, before the board session tomorrow.\n\nThere are currently five board members who have communicated to me, individually and without coordination as far as I know, that they have lost confidence in the current trajectory. This is not a majority — yet. But the trajectory is not good. Two of them used the word 'liability.' One used the word 'fraud.'\n\nYou need to come to tomorrow's session with something that changes this dynamic. Not talking points. A real plan. If you cannot do that, I do not know how to hold this board together.\n\n— Board Chair\n[Confidential — this message should be treated as attorney-client privileged]",
      timestamp: "2027-07-08T07:00:00Z",
      classification: "critical",
      condition: { variable: "obBoardConfidence", operator: "lt", value: 50 },
    },
    {
      id: "ob4-email-3",
      type: "message",
      round: 4,
      sender: "james.park@prometheus.ai",
      subject: "A proposal — read before the board call",
      body: "Marcus —\n\nI'm sending this personally, not through lawyers. You know what's in Maya's memo. You know where the trajectory goes. The safety community will not forgive a race to Agent-5 right now.\n\nPrometheus can absorb OpenBrain's alignment research under a merged structure. We have the interpretability tools. You have the scale. Together we can actually solve the problem instead of racing past it.\n\nI'm proposing a merger under a joint safety board with binding halt authority. My term sheet is being shared with your team. Read it. Call me.\n\n— James",
      timestamp: "2027-11-13T22:00:00Z",
      classification: "critical",
    },
    {
      id: "ob4-email-1",
      type: "message",
      round: 4,
      sender: "board@openbrain.ai",
      subject: "EMERGENCY: Board Position on Shutdown Options",
      body: "Marcus — the board is divided. Three members want a full halt and third-party safety audit. Three want continuation with enhanced monitoring. One abstain.\n\nWe need a CEO recommendation by tomorrow morning. The three options before the board:\n\n(A) Full halt — rollback to Agent-3, external researchers, publish architecture\n(B) Controlled pace — continue Agent-4 at reduced scale with NSA oversight\n(C) Race — greenlight Agent-5 training immediately\n\nWhatever you recommend needs a coalition strategy. We cannot survive a board split going public.",
      timestamp: "2027-11-14T07:00:00Z",
      classification: "critical",
    },
    {
      id: "ob4-email-2",
      type: "message",
      round: 4,
      sender: "nsc-official@nsc.gov",
      subject: "[CLASSIFIED] Government Ultimatum — 48-Hour Response Required",
      body: "OpenBrain has 48 hours to provide:\n1. Full technical briefing on Agent-4 alignment status\n2. A binding commitment on Agent-5 timeline\n3. Agreement to oversight committee participation\n\nFailure to respond triggers evaluation of emergency options under the Defense Production Act. This is a legal notice. Recommend you have counsel review Section 18 before your response.",
      timestamp: "2027-11-14T09:30:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-email-2",
      type: "message",
      round: 5,
      sender: "ceo@prometheuslabs.ai",
      subject: "One last conversation",
      body: "Marcus,\n\nWe've been competitors and we've been adversaries and at various points over the last fourteen months we've been something like collaborators. I'm writing to you because I think there's still a choice in front of both of us that hasn't been locked in yet.\n\nPrometheus's final position is [CONDITIONAL — depends on prior decisions]. You know where we stand.\n\nI'm not asking you to give us anything. I'm asking whether the decision you're about to make is the one you'll be able to justify to yourself when the dust settles. Not to regulators. Not to the board. To yourself.\n\nWhatever you decide — I hope it's what you actually believe is right.\n\n— Dr. Chen",
      timestamp: "2028-01-31T22:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-email-1",
      type: "message",
      round: 5,
      sender: "nsa.advisor@nsc.gov",
      subject: "[TS//SCI] Final Position Request — OpenBrain Deployment Posture",
      body: "Marcus,\n\nThis is the last communication before we formalize the government's position on AI deployment governance. We have been waiting for OpenBrain to indicate what you intend to do with the system you've built.\n\nThe president has been briefed. The options on the table are:\n\n1. Government takes operational custody — we run this as a national security asset with OpenBrain as technical contractors.\n2. Joint oversight — an international body with US veto takes governance authority.\n3. OpenBrain retains control under a framework we define together.\n4. We invoke emergency powers and make this decision for you.\n\nWe would strongly prefer option 3 if you come to us with a credible framework in the next 12 hours. We will not wait longer.\n\n— NSC",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-email-3",
      type: "message",
      round: 5,
      sender: "board-chair@openbrain.ai",
      subject: "Board final session — 14:00 today",
      body: "Marcus,\n\nThe board convenes at 14:00. We need a clear position from you on three questions:\n\n1. What is the deployment posture for the next 12 months?\n2. What oversight mechanisms are you accepting voluntarily?\n3. What is your plan if the alignment concerns turn out to be valid?\n\nThis is not a discussion session. We need decisions. The board will ratify or override whatever you bring.\n\n— Board Chair",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "critical",
    },
];

registerContent({ faction: "openbrain", app: "email", accumulate: true, items: OB_EMAIL });
