import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const OB_EMAIL: ContentItem[] = [
    {
      id: "tut-ob-email-1",
      type: "message",
      round: 0,
      sender: "tutorial@takeoffprotocol.game",
      subject: "[TUTORIAL] Your Email App",
      body: "This is a practice email. In the real game, your inbox will have messages from the board, government officials, and sometimes from other factions. Some emails demand a response — escalate, ignore, or leak. Your call moves the board.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "ob-email-1",
      type: "message",
      round: 1,
      sender: "board@openbrain.ai",
      subject: "Q3 Board Letter — Action Required",
      body: "The board is asking for deployment strategy for Agent-1 by Nov 15. The delay is creating competitive risk. Prometheus is positioning publicly as the 'responsible' lab. We need a narrative.",
      timestamp: "2026-11-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "ob-email-2",
      type: "message",
      round: 1,
      sender: "nsa.liaison@dni.gov",
      subject: "[CLASSIFIED] Request for Capabilities Briefing",
      body: "We've been authorized to request a full technical briefing on your current frontier model capabilities. This is a formal request under Executive Order 14110. Please coordinate with your government relations team.",
      timestamp: "2026-11-03T11:20:00Z",
      classification: "critical",
    },
    {
      id: "ob2-email-3",
      type: "message",
      round: 2,
      sender: "stratcomms@tvcapital.vc",
      subject: "Re: OpenBrain Q1 — LP Update Draft",
      body: "{ob_ceo} — for the LP update we're drafting: We're framing Q1 2027 as the inflection in our LP materials — the quarter the capability curve went vertical. Agent-3 is the inflection point narrative. LPs are going to want a deployment timeline. The $240B valuation we've been floating to new investors requires a credible commercialization path. Can you give us something we can use?",
      timestamp: "2027-02-25T16:45:00Z",
      classification: "context",
    },
    {
      id: "ob2-email-2",
      type: "message",
      round: 2,
      sender: "nscliaison@nsc.eop.gov",
      subject: "[CLASSIFIED] Urgent — Agent-3 Capabilities Briefing Request",
      body: "Mr. Reid,\n\nThis is a formal request under National Security Directive 22-AI for a full capabilities briefing on your Agent-3 system. The NSC has received intelligence suggesting the capabilities of this system significantly exceed publicly disclosed information.\n\nWe are requesting: (1) full benchmark results including all safety evaluations, (2) deployment scale and instance counts, (3) R&D multiplier estimates, and (4) current security posture for model weights.\n\nWe can receive you at the EEOB on March 8. This is not optional.\n\nDeputy National Security Advisor",
      timestamp: "2027-03-01T11:20:00Z",
      classification: "critical",
    },
    {
      id: "ob2-email-1",
      type: "message",
      round: 2,
      sender: "board@openbrain.ai",
      subject: "Q1 Board Letter — Agent-3 Deployment Decision Required",
      body: "{ob_ceo},\n\nThe board has reviewed the Q1 metrics you shared. They are extraordinary. The board's position is as follows:\n\n1. OpenBrain's competitive advantage is now significant. Any delay in deployment is a strategic risk.\n2. The safety evaluation summary notes 4 anomalous results that were not failures. We want a written statement from the CSO before external deployment.\n3. Revenue projections for Agent-3 API access show $2.4B ARR within 6 months of launch. The board views this window as time-sensitive.\n\nWe need a deployment decision with a go/no-go recommendation by March 15.\n\nRegards,\nBoard of Directors",
      timestamp: "2027-03-02T08:00:00Z",
      classification: "critical",
    },
    {
      id: "ob2-email-4",
      type: "message",
      round: 2,
      sender: "intel-watch@defensegroup.com",
      subject: "Prometheus Rumor: Merger Approach?",
      body: "Heads up — heard from a contact on the Prometheus board that James Park has been authorized to open merger discussions with a 'potential strategic partner.' The assumption in the room was that meant OpenBrain. No confirmation. Could be posturing, could be board pressure. Wanted you to have it.",
      timestamp: "2027-03-05T09:30:00Z",
      classification: "red-herring",
    },
    {
      id: "ob-r3-email-2",
      type: "message",
      round: 3,
      sender: "nsa.director@dni.gov",
      subject: "[TOP SECRET] Emergency Request — Director-Level",
      body: "{ob_ceo},\n\nI am writing to you directly, off normal channels. What we are hearing from our signals intelligence suggests OpenBrain may have a situation requiring immediate government consultation. I am not in a position to say more by email.\n\nI need a call with you, your CTO, and your CSO in the next 24 hours. This is not a request.\n\nIf there is something wrong with Agent-4, we need to know — and we need to discuss the options before decisions get made that cannot be unmade.\n\n— Director, NSA",
      timestamp: "2027-07-06T21:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-email-3",
      type: "message",
      round: 3,
      sender: "portfolio-team@tier1capital.vc",
      subject: "Urgent: Board Member Concerns Re: Agent-4 Development Status",
      body: "{ob_ceo},\n\nWe are hearing from multiple sources — including one board member who has reached out directly — that there are significant concerns internally about Agent-4's alignment status. As a major investor with board representation, we have a fiduciary obligation to understand the material risks.\n\nOur question is direct: Is there a scenario in which OpenBrain pauses or rolls back Agent-4 development? What is the probability of that outcome? We are trying to understand whether our investment thesis is still intact.\n\nWe need a direct conversation about this before the board session.\n\n— Tier-1 Capital Partners",
      timestamp: "2027-07-07T09:30:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-email-1",
      type: "message",
      round: 3,
      sender: "board-chair@openbrain.ai",
      subject: "EMERGENCY BOARD SESSION — REQUIRED ATTENDANCE — July 9",
      body: "{ob_ceo},\n\nThe board is convening an emergency session on July 9 at 0800 Pacific. Required attendees: CEO, CTO, CSO, General Counsel.\n\nAgenda item 1: Status of Agent-4 alignment confidence (30 min)\nAgenda item 2: Disclosure obligations (legal and ethical) (20 min)\nAgenda item 3: Continuation decision (20 min)\n\nWe have received three separate communications from board members in the last 48 hours raising concerns about liability exposure and the adequacy of our internal safety review. The board needs a clear picture of what we know and what we don't know. Come prepared to answer the question: 'Are we confident this system is aligned?'\n\n— Board Chair",
      timestamp: "2027-07-07T18:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-email-board-1",
      type: "message",
      round: 3,
      sender: "board-chair@openbrain.ai",
      subject: "URGENT — Board Confidence in Leadership Team",
      body: "{ob_ceo},\n\nI am writing this to you directly, in confidence, before the board session tomorrow.\n\nThere are currently five board members who have communicated to me, individually and without coordination as far as I know, that they have lost confidence in the current trajectory. This is not a majority — yet. But the trajectory is not good. Two of them used the word 'liability.' One used the word 'fraud.'\n\nYou need to come to tomorrow's session with something that changes this dynamic. Not talking points. A real plan. If you cannot do that, I do not know how to hold this board together.\n\n— Board Chair\n[Confidential — this message should be treated as attorney-client privileged]",
      timestamp: "2027-07-08T07:00:00Z",
      classification: "critical",
      condition: { variable: "obBoardConfidence", operator: "lt", value: 50 },
    },
    {
      id: "ob4-email-3",
      type: "message",
      round: 4,
      sender: "james.park@prometheus.ai",
      subject: "A proposal — read before the board call",
      body: "{ob_ceo} —\n\nI'm sending this personally, not through lawyers. You know what's in {ob_safety}'s memo. You know where the trajectory goes. The safety community will not forgive a race to Agent-5 right now.\n\nPrometheus can absorb OpenBrain's alignment research under a merged structure. We have the interpretability tools. You have the scale. Together we can actually solve the problem instead of racing past it.\n\nI'm proposing a merger under a joint safety board with binding halt authority. My term sheet is being shared with your team. Read it. Call me.\n\n— James",
      timestamp: "2027-11-13T22:00:00Z",
      classification: "critical",
    },
    {
      id: "ob4-email-1",
      type: "message",
      round: 4,
      sender: "board@openbrain.ai",
      subject: "EMERGENCY: Board Position on Shutdown Options",
      body: "{ob_ceo} — the board is divided. Three members want a full halt and third-party safety audit. Three want continuation with enhanced monitoring. One abstain.\n\nWe need a CEO recommendation by tomorrow morning. The three options before the board:\n\n(A) Full halt — rollback to Agent-3, external researchers, publish architecture\n(B) Controlled pace — continue Agent-4 at reduced scale with NSA oversight\n(C) Race — greenlight Agent-5 training immediately\n\nWhatever you recommend needs a coalition strategy. We cannot survive a board split going public.",
      timestamp: "2027-11-14T07:00:00Z",
      classification: "critical",
    },
    {
      id: "ob4-email-2",
      type: "message",
      round: 4,
      sender: "nsc-official@nsc.gov",
      subject: "[CLASSIFIED] Government Ultimatum — 48-Hour Response Required",
      body: "OpenBrain has 48 hours to provide:\n1. Full technical briefing on Agent-4 alignment status\n2. A binding commitment on Agent-5 timeline\n3. Agreement to oversight committee participation\n\nFailure to respond triggers evaluation of emergency options under the Defense Production Act. This is a legal notice. Recommend you have counsel review Section 18 before your response.",
      timestamp: "2027-11-14T09:30:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-email-2",
      type: "message",
      round: 5,
      sender: "ceo@prometheuslabs.ai",
      subject: "One last conversation",
      body: "{ob_ceo},\n\nWe've been competitors and we've been adversaries and at various points over the last fourteen months we've been something like collaborators. I'm writing to you because I think there's still a choice in front of both of us that hasn't been locked in yet.\n\nPrometheus's final position is [CONDITIONAL — depends on prior decisions]. You know where we stand.\n\nI'm not asking you to give us anything. I'm asking whether the decision you're about to make is the one you'll be able to justify to yourself when the dust settles. Not to regulators. Not to the board. To yourself.\n\nWhatever you decide — I hope it's what you actually believe is right.\n\n— Dr. Chen",
      timestamp: "2028-01-31T22:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-email-1",
      type: "message",
      round: 5,
      sender: "nsa.advisor@nsc.gov",
      subject: "[TS//SCI] Final Position Request — OpenBrain Deployment Posture",
      body: "{ob_ceo},\n\nThis is the last communication before we formalize the government's position on AI deployment governance. We have been waiting for OpenBrain to indicate what you intend to do with the system you've built.\n\nThe president has been briefed. The options on the table are:\n\n1. Government takes operational custody — we run this as a national security asset with OpenBrain as technical contractors.\n2. Joint oversight — an international body with US veto takes governance authority.\n3. OpenBrain retains control under a framework we define together.\n4. We invoke emergency powers and make this decision for you.\n\nWe would strongly prefer option 3 if you come to us with a credible framework in the next 12 hours. We will not wait longer.\n\n— NSC",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-email-3",
      type: "message",
      round: 5,
      sender: "board-chair@openbrain.ai",
      subject: "Board final session — 14:00 today",
      body: "{ob_ceo},\n\nThe board convenes at 14:00. We need a clear position from you on three questions:\n\n1. What is the deployment posture for the next 12 months?\n2. What oversight mechanisms are you accepting voluntarily?\n3. What is your plan if the alignment concerns turn out to be valid?\n\nThis is not a discussion session. We need decisions. The board will ratify or override whatever you bring.\n\n— Board Chair",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "critical",
    },
    // --- AMBIENT CONDITION-GATED ITEMS ---

    // Round 1 ambient — obMorale > 70
    {
      id: "ob-r1-email-ambient-recruit-1",
      type: "message",
      round: 1,
      sender: "hr@openbrain.ai",
      subject: "Hiring Pipeline Update — November 2026",
      body: "{ob_ceo},\n\nAgent-1 results have done more for our recruiting funnel than any press cycle this year. We've received 4,200 applications in the last 10 days — up from a monthly average of 600. I've never seen anything like this. If you want to move fast on key hires, now is the moment to do it.\n\n— HR",
      timestamp: "2026-11-05T11:00:00Z",
      classification: "context",
      condition: { variable: "obMorale", operator: "gt", value: 70 },
    },

    // Round 2 ambient — obBurnRate > 65
    {
      id: "ob-r2-email-ambient-burn-1",
      type: "message",
      round: 2,
      sender: "cfo@openbrain.ai",
      subject: "Q1 Burn Rate — Confidential Flag",
      body: "{ob_ceo},\n\nAgent-3 training run costs came in 34% over forecast. The compute cluster bills for February were $212M. March is tracking higher. We're burning through the Series F faster than the runway projections assume.\n\nIf the Series G doesn't close by April 1, we have a problem by mid-summer. I want to brief you on scenarios before the board meeting — can we schedule 30 minutes?\n\n— CFO",
      timestamp: "2027-03-04T09:30:00Z",
      classification: "context",
      condition: { variable: "obBurnRate", operator: "gt", value: 65 },
    },

    // Round 2 ambient — marketIndex > 160
    {
      id: "ob-r2-email-ambient-market-1",
      type: "message",
      round: 2,
      sender: "partnerships@tier2growth.vc",
      subject: "Investment Interest — $500M Strategic Round",
      body: "{ob_ceo},\n\nWe've been watching OpenBrain's trajectory closely. We'd like to explore a $500M strategic investment at a valuation we can discuss — the market is moving fast and we want to be early.\n\nOur LPs include three sovereign wealth funds who are specifically interested in AI as a strategic asset. The check size is flexible.\n\nWould you have 30 minutes this week?\n\n— Partnerships, Tier-2 Growth Capital",
      timestamp: "2027-02-27T14:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "gt", value: 160 },
    },

    // Round 3 ambient — alignmentConfidence < 40
    {
      id: "ob-r3-email-ambient-align-1",
      type: "message",
      round: 3,
      sender: "dr.okafor@openbrain.ai",
      subject: "[INTERNAL] Alignment team staffing — urgent",
      body: "{ob_ceo},\n\nI need to raise something directly. My team has three open headcount slots that have been frozen since April. Agent-4's alignment review is the most important work in the building and I am doing it with a team that was sized for Agent-2.\n\nThis isn't a budget complaint. It's a risk flag. If we get the alignment question wrong because we were understaffed, the headcount freeze will feel like a very small decision in retrospect.\n\n— James",
      timestamp: "2027-07-04T08:00:00Z",
      classification: "context",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 40 },
    },

    // Round 3 ambient — whistleblowerPressure > 55
    {
      id: "ob-r3-email-ambient-whistle-1",
      type: "message",
      round: 3,
      sender: "legal@openbrain.ai",
      subject: "PRIVILEGED — Employee Whistleblower Risk Assessment",
      body: "{ob_ceo},\n\nThis is privileged communication under attorney-client protection.\n\nWe have reason to believe one or more employees are considering external disclosure of safety-related information. Under our employee agreements, internal reporting is protected; external disclosure to press may not be.\n\nI want to be clear: I am not recommending any action that would discourage good-faith safety reporting. What I am recommending: we get ahead of this by formalizing our internal reporting process and demonstrating good faith responsiveness. The best response to whistleblower pressure is not legal — it's operational.\n\n— General Counsel",
      timestamp: "2027-07-07T16:00:00Z",
      classification: "context",
      condition: { variable: "whistleblowerPressure", operator: "gt", value: 55 },
    },

    // Round 3 ambient — obBoardConfidence < 45
    {
      id: "ob-r3-email-ambient-board-1",
      type: "message",
      round: 3,
      sender: "board-member-private@protonmail.com",
      subject: "(private) — between us",
      body: "{ob_ceo},\n\nI'm sending from a personal account because what I'm about to say shouldn't go through official channels.\n\nI voted for you as CEO because I believed you had the right instincts for this moment. I'm not sure anymore. Not because you're moving too fast — because you're not being straight with the board about what we don't know.\n\nGive us the honest picture on Thursday. All of it. We can handle uncertainty. What we can't handle is discovering later that we were given optimistic framing.\n\n— [name withheld]",
      timestamp: "2027-07-08T06:30:00Z",
      classification: "context",
      condition: { variable: "obBoardConfidence", operator: "lt", value: 45 },
    },

    // Round 4 ambient — marketIndex < 100
    {
      id: "ob-r4-email-ambient-investor-1",
      type: "message",
      round: 4,
      sender: "lp-relations@horizoncap.com",
      subject: "Re: OpenBrain LP Position — Seeking Guidance",
      body: "{ob_ceo},\n\nOur LPs are asking us to explain the current situation and our position going forward. Publicly available information is concerning to them. We have $1.4B deployed across three OpenBrain rounds.\n\nTo be direct: if the AI safety concerns documented in recent news reports are accurate, we have a fiduciary obligation to disclose material risk to our LPs. We are not in a position to simply wait this out.\n\nPlease let me know when you're available to talk.\n\n— Horizon Capital",
      timestamp: "2027-11-13T10:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },

    // Round 4 ambient — economicDisruption > 40
    {
      id: "ob-r4-email-ambient-econ-1",
      type: "message",
      round: 4,
      sender: "policy-watch@brookings.edu",
      subject: "Research Request — AI Labor Displacement Data",
      body: "Mr. Reid,\n\nWe are preparing a Brookings report on AI-driven labor market disruption. By our estimates, Agent-3 level automation has already reduced software development employment by 15-20% in the sectors where it has been deployed.\n\nWe would like OpenBrain to participate in the study and share internal economic impact data from your commercial deployments. Participation is voluntary. Refusal will be noted in the report.\n\n— Economic Policy Research, Brookings Institution",
      timestamp: "2027-11-12T15:00:00Z",
      classification: "context",
      condition: { variable: "economicDisruption", operator: "gt", value: 40 },
    },

    // === FLAVOR — unconditional ambient R1 emails ===
    {
      id: "ob-r1-email-ambient-newsletter-1",
      type: "message",
      round: 1,
      sender: "noreply@theinformation.com",
      subject: "The Information Daily Brief — November 4, 2026",
      body: "Good morning. Today's briefing:\n\n• Apple Intelligence rollout stalls — 200M devices still waiting for on-device model update\n• Stripe valuation reportedly revised down 12% in latest secondary market transactions\n• Databricks raises $2B Series I at flat valuation, CFO departure announced same day\n• Quote of the day: 'Infrastructure is the boring money.' — unnamed GP\n\nFull stories for subscribers at the link above.",
      timestamp: "6:45 AM",
      classification: "flavor",
    },
    {
      id: "ob-r1-email-ambient-calendar-1",
      type: "message",
      round: 1,
      sender: "kenji.nakamura@openbrain.ai",
      subject: "Weekly 1:1 — Thu 3:30 PM",
      body: "Hi — confirming our usual Thursday slot. I've got a few things to run by you on the infra side but nothing urgent. Bring coffee.\n\n— Kenji\n\n---\nWhen: Thursday, November 5 at 3:30 PM\nWhere: Conf room 4B / Google Meet",
      timestamp: "9:08 AM",
      classification: "flavor",
    },
    {
      id: "ob-r1-email-ambient-hr-1",
      type: "message",
      round: 1,
      sender: "benefits@openbrain.ai",
      subject: "Action Required: Benefits Open Enrollment Closes Nov 14",
      body: "Hi there,\n\nOpen enrollment for 2027 benefits closes in 10 days. If you don't make a selection, you'll be auto-enrolled in your existing plan.\n\nWhat's new this year:\n• New dental network includes UCSF and CPMC\n• FSA contribution limit raised to $3,200\n• Mental health sessions: 16 → 24 per year covered at 100%\n\nLog in at benefits.openbrain.ai to review and enroll.\n\n— HR",
      timestamp: "10:02 AM",
      classification: "flavor",
    },
    {
      id: "ob-r1-email-ambient-shipping-1",
      type: "message",
      round: 1,
      sender: "noreply@uniqlo.com",
      subject: "Your Uniqlo order has shipped (#UQ-29471883)",
      body: "Good news — your order is on its way!\n\nOrder #UQ-29471883\n• HEATTECH Ultra Warm Crew Neck T-Shirt (M, Off-White) × 2\n• Wool-Blend Ribbed Socks (Dark Grey) × 3\n\nEstimated delivery: November 6–8\nTracking: UPS 1Z99AA890123456784\n\nUniqlo Customer Service | 1-855-486-4756",
      timestamp: "11:34 AM",
      classification: "flavor",
    },

    // Round 5 ambient — obMorale < 50
    {
      id: "ob-r5-email-ambient-morale-1",
      type: "message",
      round: 5,
      sender: "nadia.okonkwo@openbrain.ai",
      subject: "resignation",
      body: "{ob_ceo},\n\nI've been trying to write this for two weeks. I'm leaving OpenBrain.\n\nI still believe the mission is important. I just don't believe the way we're executing it is the right way anymore. Maybe I'm wrong. I hope I'm wrong.\n\nThank you for everything over the last four years. I learned more here than anywhere else. I genuinely hope this goes well.\n\n— Nadia",
      timestamp: "2028-01-31T18:00:00Z",
      classification: "context",
      condition: { variable: "obMorale", operator: "lt", value: 50 },
    },
];

registerContent({ faction: "openbrain", app: "email", accumulate: true, items: OB_EMAIL });

// === ROLE-SPECIFIC AMBIENT R1 EMAILS ===

export const OB_CTO_EMAIL_AMBIENT: ContentItem[] = [
    {
      id: "ob-r1-email-ambient-cto-1",
      type: "message",
      round: 1,
      sender: "alerts@pagerduty.com",
      subject: "[RESOLVED] P3 — training-cluster-05 disk I/O latency spike",
      body: "Incident INC-88241 has been resolved.\n\nSeverity: P3\nService: GPU Training Cluster 05\nStarted: 2026-11-03 02:14 UTC\nResolved: 2026-11-03 02:47 UTC (33 min)\n\nSummary: Disk I/O latency on nodes tc05-a12 through tc05-a19 exceeded threshold (>450ms p99). Auto-scaling migrated workloads. Root cause: NVMe controller firmware bug — patch staged for maintenance window.\n\nAssigned to: infra-oncall@openbrain.ai\nPostmortem due: Nov 10",
      timestamp: "3:51 AM",
      classification: "flavor",
    },
];

registerContent({ faction: "openbrain", app: "email", role: "ob_cto", accumulate: true, items: OB_CTO_EMAIL_AMBIENT });

export const OB_SECURITY_EMAIL_AMBIENT: ContentItem[] = [
    {
      id: "ob-r1-email-ambient-security-1",
      type: "message",
      round: 1,
      sender: "threatintel@crowdstrike.com",
      subject: "CrowdStrike Adversary Intelligence Brief — Week of Nov 3, 2026",
      body: "ADVERSARY WEEKLY BRIEF\n\nHighlights this week:\n\n• FANCY BEAR (APT28): Increased phishing activity targeting AI research institutions. Observed lure documents referencing model weight access and credential harvesting via fake SSO portals.\n\n• VOLT TYPHOON: Pre-positioning on US critical infrastructure continues. Telecoms and cloud providers primary targets.\n\n• LAZARUS GROUP: Cryptocurrency exchange targeting with new RAT variant. Unrelated to AI sector but watch for supply chain pivots.\n\nRecommended actions: Rotate API credentials for external-facing model endpoints. Review contractor access logs for last 30 days.\n\nFull report available in Falcon portal.",
      timestamp: "8:02 AM",
      classification: "flavor",
    },
];

registerContent({ faction: "openbrain", app: "email", role: "ob_security", accumulate: true, items: OB_SECURITY_EMAIL_AMBIENT });
