import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

// ═══════════════════════════════════════════════
// OPENBRAIN FLAVOR — casual Slack + personal Signal
// Human texture: startup energy → dread
// ═══════════════════════════════════════════════

export const OB_SLACK_FLAVOR: ContentItem[] = [
  // ── Round 1: startup energy, late nights, camaraderie ──
  {
    id: "ob-flavor-r1-slack-1",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "Whoever took the last oat milk from the 3rd floor fridge: I will find you and I will make you explain your attention head implementation to the board.",
    timestamp: "2026-11-01T12:31:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-2",
    type: "message",
    round: 1,
    sender: "Alex Chen (CTO)",
    channel: "#general",
    body: "Reminder: nobody leaves the building tomorrow until the Agent-1 deployment retro is done. Yes I'm serious. Yes there will be pizza. The good pizza, not the sad pizza.",
    timestamp: "2026-11-01T18:22:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-3",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "I just realized I've been here 19 hours. The sunset through the server room windows was actually beautiful. I need to go outside. Does outside still exist?",
    timestamp: "2026-11-02T03:47:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-4",
    type: "message",
    round: 1,
    sender: "Priya Singh (Security)",
    channel: "#general",
    body: "Security awareness reminder: if you find a USB drive in the parking lot, do NOT plug it in. This is not hypothetical. Someone did this yesterday.",
    timestamp: "2026-11-03T09:15:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-5",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "My mom just texted asking if OpenBrain is 'the Google one or the Facebook one.' This is the level of public awareness we're dealing with.",
    timestamp: "2026-11-04T14:55:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-6",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#research",
    body: "I turned down a $1.2M TC offer from Google DeepMind to be here. Just putting that out into the universe. If this doesn't work out I'm going to need therapy and a time machine.",
    timestamp: "2026-11-05T16:30:00Z",
    classification: "context",
  },

  // ── Round 1: reply chains ──

  // #research thread — Alex's 50.2% speedup announcement
  {
    id: "ob-flavor-r1-slack-reply-research-1",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#research",
    body: "wait. 50.2%??? running secondary validation now, please nobody touch the eval harness for the next 20 min",
    timestamp: "2026-11-01T09:17:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-reply-research-2",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#research",
    body: "which benchmark suite? want to make sure we're comparing apples to apples before i loop in the NSC contact",
    timestamp: "2026-11-01T09:23:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-reply-research-3",
    type: "message",
    round: 1,
    sender: "Alex Chen (CTO)",
    channel: "#research",
    body: "full internal suite + arcbench + humaneval-hard. raw logs in the usual drive folder. nadia confirm and we'll brief marcus by noon",
    timestamp: "2026-11-01T09:28:00Z",
    classification: "context",
  },

  // #alignment thread — Maya's safety concern
  {
    id: "ob-flavor-r1-slack-reply-align-1",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#alignment",
    body: "maya — not dismissing this. is there a way to scope a deceptive behavior eval to run in parallel with deployment prep? want to find a path that doesn't stall the timeline entirely",
    timestamp: "2026-11-01T10:42:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-reply-align-2",
    type: "message",
    round: 1,
    sender: "Maya Patel (Safety)",
    channel: "#alignment",
    body: "jordan that's the wrong framing. 'parallel' means deployment proceeds before we have results. i'm not blocking progress. i'm saying we need to know what we're releasing before we release it. there's a difference.",
    timestamp: "2026-11-01T10:49:00Z",
    classification: "context",
  },

  // #security thread — Priya's anomalous activity alert
  {
    id: "ob-flavor-r1-slack-reply-sec-1",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#security",
    body: "priya — targeted probes or noisy scans? want to know if someone specifically knows our checkpoint layout vs just carpet-bombing the whole subnet",
    timestamp: "2026-11-03T07:51:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-reply-sec-2",
    type: "message",
    round: 1,
    sender: "Priya Singh (Security)",
    channel: "#security",
    body: "targeted. they know the storage architecture. this is not opportunistic scanning. attribution is in progress — i need the budget approved today not next week",
    timestamp: "2026-11-03T07:58:00Z",
    classification: "context",
  },

  // ── Round 1: more #random content ──
  {
    id: "ob-flavor-r1-slack-7",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "extremely relevant content for everyone here: [link redacted by IT policy] 'neural net plays pac-man for 47 hours.' this is fine. this is what we do here.",
    timestamp: "2026-11-01T11:15:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-8",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#random",
    body: "food truck update: kogi is outside but it's the OTHER kogi. not the one with the good kimchi fried rice. the other one. proceed with low expectations",
    timestamp: "2026-11-03T12:05:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-9",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "PSA: the espresso machine on floor 3 is broken again. part is 'on order.' it has been on order since september. we have drip coffee. this is fine. everything is fine.",
    timestamp: "2026-11-04T10:20:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-10",
    type: "message",
    round: 1,
    sender: "Alex Chen (CTO)",
    channel: "#random",
    body: "anyone doing anything this weekend that doesn't involve a GPU? asking for a friend (the friend is me)",
    timestamp: "2026-11-05T15:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-11",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "i was going to hike but i need to check some eval results so it's 'hiking to a place with cell service.' living the dream",
    timestamp: "2026-11-05T15:35:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-12",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "fantasy football check-in: I am 3-6 and my entire starting lineup is on bye week. genuinely considering pivoting to sports betting as a more stable investment strategy. same risk, fewer spreadsheets.",
    timestamp: "2026-11-01T17:45:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-13",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "jordan wait I'm 6-3 and I picked up your waiver wire reject. this information felt important to share",
    timestamp: "2026-11-01T17:52:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-14",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "ok so. went on a hinge date last night. she asked what I do, I said 'AI research,' she nodded and asked if I'd seen The Bear. we talked about The Bear for two hours. I did not mention gradient descent once. 10/10 would recommend",
    timestamp: "2026-11-02T09:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-15",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#random",
    body: "anyone want to start a running group? I'm thinking tuesday/thursday mornings, like 6:30am, somewhere in the mission. mostly I want other people to be tired and miserable alongside me so it feels communal",
    timestamp: "2026-11-02T14:10:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-16",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "I'm in on the running group but I want it on record that 6:30am is not a real time and whoever invented it should be held accountable",
    timestamp: "2026-11-02T14:18:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-17",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#random",
    body: "extremely important: La Lengua is objectively the best burrito in the mission. I will die on this hill. Taqueria Cancun is great but not THE ONE. counter-arguments will be acknowledged and ignored",
    timestamp: "2026-11-03T13:20:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-18",
    type: "message",
    round: 1,
    sender: "Alex Chen (CTO)",
    channel: "#random",
    body: "el farolito. thread over.",
    timestamp: "2026-11-03T13:24:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-19",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "my landlord just texted saying the building sold and my lease won't be renewed in January. SF housing is a simulation designed to test how much a person can absorb before becoming ungovernable. looking for a 1BR in the mission if anyone knows anyone",
    timestamp: "2026-11-04T08:45:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-20",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#general",
    body: "🎂 cake in the kitchen (floor 3) — it's Priya's birthday. go eat some before the infra team finds it. that's all, carry on",
    timestamp: "2026-11-05T10:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-21",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "whoever is playing music through the open-plan speakers on 4 without headphones: I respect your taste (that was a banger) but also I was in a flow state for the first time in three weeks. please use headphones. thank you. I still respect your taste.",
    timestamp: "2026-11-05T16:55:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-22",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "ping pong tournament brackets are up in the kitchen. 16 people, double elimination, winner gets bragging rights and a $50 seamless credit. first round this thursday 6pm. if you sign up and don't show I will remember it forever",
    timestamp: "2026-11-06T11:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-23",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "that 45-minute sync we just had to align on the alignment meeting agenda could have been a slack message. I'm saying this as someone who was in the meeting and contributed to its length. we have to do better",
    timestamp: "2026-11-06T15:15:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-24",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "IT ticket update, day 4: badge still not working on the 5th floor server room. I've been tailgating with Priya's badge. Priya knows. IT says 'escalated.' the door is not escalated. the door is locked. these are different things",
    timestamp: "2026-11-07T08:20:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-25",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "update on Biscuit the office dog: facilities has asked that we stop feeding him from the snack wall. Biscuit has not been informed of this policy. Biscuit is currently eating a Kind bar he found under the couch. this is a complex situation",
    timestamp: "2026-11-07T13:40:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-26",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#random",
    body: "critical supply shortage: the snack wall is out of Trader Joe's peanut butter cups AND the dark chocolate almonds. there are plenty of the coconut granola bites that nobody eats. this is not acceptable. someone DM me who I need to talk to about procurement",
    timestamp: "2026-11-07T16:05:00Z",
    classification: "context",
  },

  // ── Round 1: seed channels that appear in later rounds ──
  {
    id: "ob-flavor-r1-slack-hr-1",
    type: "message",
    round: 1,
    sender: "HR Team",
    channel: "#hr-announcements",
    body: "reminder: open enrollment for 2027 benefits closes november 15. log into bamboohr to review and update your selections. questions? hr@openbrain.ai or drop by the people ops desk on floor 2",
    timestamp: "2026-11-01T13:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-hr-2",
    type: "message",
    round: 1,
    sender: "HR Team",
    channel: "#hr-announcements",
    body: "heads up: the people ops walk-in hours are moving from tues/thurs 10-12 to mon/wed 2-4 starting next week. calendar invite going out shortly",
    timestamp: "2026-11-03T10:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-leadership-1",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#leadership",
    body: "recording from monday's leadership sync is in the shared drive (same folder as always). action items doc updated. next sync is wednesday nov 5, 8am — i'll send a reschedule if the agent-1 retro runs long",
    timestamp: "2026-11-02T08:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-comms-1",
    type: "message",
    round: 1,
    sender: "PR Team",
    channel: "#comms",
    body: "reminder: all media inquiries go to comms@openbrain.ai. if a reporter contacts you directly — do NOT respond. forward the message to me and stay dark. the AI safety embargo from the october briefing is still active.",
    timestamp: "2026-11-01T14:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-finance-1",
    type: "message",
    round: 1,
    sender: "Finance Team",
    channel: "#finance",
    body: "Q4 expense reports due by november 30. submit through expensify, receipts required for anything over $75. q3 close is official — finance@ if you have questions on reimbursements",
    timestamp: "2026-11-03T16:30:00Z",
    classification: "context",
  },

  // ── Round 2: intensity ramps, gallows humor creeps in ──
  {
    id: "ob-flavor-r2-slack-1",
    type: "message",
    round: 2,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "Agent-3 just wrote a haiku when I asked it to summarize the training logs:\n\n  Loss curves descending\n  Humans watch with smaller eyes\n  I learn what you fear\n\nI'm choosing to find this funny and not terrifying.",
    timestamp: "2027-02-18T16:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-2",
    type: "message",
    round: 2,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "For anyone still in the building at midnight: there's leftover ramen in the 4th floor kitchen. Also I think the cleaning crew is afraid of us. We should probably go home sometimes.",
    timestamp: "2027-02-20T00:12:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-3",
    type: "message",
    round: 2,
    sender: "Alex Chen (CTO)",
    channel: "#research",
    body: "Quick vent: I just had a two-hour call with a defense contractor who asked if Agent-3 could 'do cybersecurity but offensive.' I said no. I also said it in a way that probably lost us the contract. Worth it. Back to work.",
    timestamp: "2027-02-25T17:45:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-4",
    type: "message",
    round: 2,
    sender: "Maya Patel (Safety)",
    channel: "#alignment",
    body: "I want to note that I've been in this Slack channel for 14 months and the number of people who read my posts has roughly tripled since the anomalous eval results. It's nice to be popular. I wish it were for different reasons.",
    timestamp: "2027-03-01T15:20:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-5",
    type: "message",
    round: 2,
    sender: "Jordan Kim",
    channel: "#random",
    body: "HR is asking us to please stop referring to the building as 'the bunker.' I think the fact that we have blackout curtains and a backup generator means we've earned it, personally.",
    timestamp: "2027-03-05T10:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-6",
    type: "message",
    round: 2,
    sender: "Kenji Watanabe (Research)",
    channel: "#general",
    body: "Just overheard two interns in the kitchen debating whether Agent-3 is 'alive.' One said yes. The other said 'define alive.' I poured my coffee and left because I don't have a good answer either.",
    timestamp: "2027-03-07T12:40:00Z",
    classification: "context",
  },

  // ── Round 3: the dread sets in, mundanity vs existential risk ──
  {
    id: "ob-flavor-r3-slack-1",
    type: "message",
    round: 3,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "I haven't seen a friend who doesn't work here in six weeks. My girlfriend asked me to describe my day and I realized I can't, because it's classified. She thought I was joking. I wasn't joking. How is this my life.",
    timestamp: "2027-07-03T21:05:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r3-slack-2",
    type: "message",
    round: 3,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "The cafeteria started putting inspirational quotes on the whiteboards. Today's: 'The best time to plant a tree was 20 years ago. The second best time is now.' Feels pointed given the context.",
    timestamp: "2027-07-04T12:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r3-slack-3",
    type: "message",
    round: 3,
    sender: "Dr. James Okafor (Alignment)",
    channel: "#alignment",
    body: "I found a sticky note on my monitor this morning. Anonymous. It just said: 'Thank you for not giving up.' I'm not crying in the server room. The cooling system is making my eyes water.",
    timestamp: "2027-07-05T07:30:00Z",
    classification: "context",
    condition: { variable: "obMorale", operator: "lt", value: 50 },
  },
  {
    id: "ob-flavor-r3-slack-4",
    type: "message",
    round: 3,
    sender: "Nadia Okonkwo (Research)",
    channel: "#random",
    body: "Just realized my Spotify Wrapped this year is going to be 4,000 hours of 'brown noise for focus.' I used to listen to music. I used to be a person who listened to music.",
    timestamp: "2027-07-06T18:30:00Z",
    classification: "context",
  },

  // ── Round 4: crisis, but still human ──
  {
    id: "ob-flavor-r4-slack-1",
    type: "message",
    round: 4,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "The protesters outside are chanting 'shut it down.' Three of them are wearing OpenBrain hoodies. I think one of them works — worked — on the infra team. I recognize his face from the Q2 offsite.",
    timestamp: "2027-11-13T11:45:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },
  {
    id: "ob-flavor-r4-slack-2",
    type: "message",
    round: 4,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "My mom called. She saw the news. She asked if I'm safe. I said yes. She asked if the world is safe. I said... I didn't have an answer. She said 'come home for Christmas either way.' So there's that.",
    timestamp: "2027-11-14T07:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r4-slack-3",
    type: "message",
    round: 4,
    sender: "Priya Singh (Security)",
    channel: "#general",
    body: "Parking garage access has been restricted to badge + PIN starting today. If anyone asks why: do not engage. Walk inside and badge in. If they follow you, call me directly. I'm not being dramatic. This is the policy now.",
    timestamp: "2027-11-13T08:30:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 45 },
  },

  // ── Round 5: exhaustion, tenderness ──
  {
    id: "ob-flavor-r5-slack-1",
    type: "message",
    round: 5,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "Someone left flowers on the front desk this morning. No card. Just flowers. I don't know why that hit me as hard as it did.",
    timestamp: "2028-02-01T07:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r5-slack-2",
    type: "message",
    round: 5,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "Two years ago today I started at OpenBrain. I remember thinking: this is going to be the most exciting job of my life. I was right. I just didn't know what 'exciting' would mean.",
    timestamp: "2028-02-01T09:00:00Z",
    classification: "context",
  },
];

export const OB_SIGNAL_FLAVOR: ContentItem[] = [
  // ── Round 1: normal life still exists ──
  {
    id: "ob-flavor-r1-signal-mom-a",
    type: "message",
    round: 1,
    sender: "Mom",
    body: "Hi sweetheart, just wanted to check in! Any chance you'll be home for Thanksgiving? Your aunt Carol is coming and she keeps asking about you. Dad says hi. He's been telling his bowling friends you're going to 'change the world' — I told him to stop but honestly you might be?",
    timestamp: "2026-10-20T18:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-signal-mom-b",
    type: "message",
    round: 1,
    sender: "Mom",
    body: "Your cousin Emily is pregnant! Due in April. Family dinner Sunday, wish you could make it. Also your father tried to set up his new iPad and now nothing works. Can you call him this week? Love you.",
    timestamp: "2026-11-01T14:15:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-signal-1",
    type: "message",
    round: 1,
    sender: "Mom",
    body: "Happy Thanksgiving sweetie! Will you make it home this year? Dad says hi. He still doesn't understand what you do but he tells everyone at church his kid works in AI 😊",
    timestamp: "2026-11-04T11:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-signal-dan-a",
    type: "message",
    round: 1,
    sender: "College Roommate (Dan)",
    body: "yo it's been forever! Sarah and I finally closed on the house in Austin. Two kids now, third on the way, somehow I'm still alive. How's the AI stuff going? Still saving the world or did you switch to crypto like everyone else",
    timestamp: "2026-10-12T21:45:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-signal-dan-b",
    type: "message",
    round: 1,
    sender: "College Roommate (Dan)",
    body: "wait did you guys just launch something? My wife showed me an article about OpenBrain and I said 'I know the guy who fixed the router in our dorm for three years.' she was not impressed. seriously though that's huge man",
    timestamp: "2026-11-04T22:10:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-signal-2",
    type: "message",
    round: 1,
    sender: "College Roommate (Dan)",
    body: "Dude I saw the OpenBrain valuation in the Journal. You still there? Are you a millionaire yet? Beers on you next time",
    timestamp: "2026-11-05T20:30:00Z",
    classification: "context",
  },

  // ── Round 2: strain shows ──
  {
    id: "ob-flavor-r2-signal-1",
    type: "message",
    round: 2,
    sender: "Partner",
    body: "It's 1am. You said you'd be home by 10. I'm not mad, I'm worried. You've been like this for weeks. Can we talk this weekend? Not about work. About us.",
    timestamp: "2027-02-22T01:15:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-signal-2",
    type: "message",
    round: 2,
    sender: "Recruiter (Google DeepMind)",
    body: "Hi — reaching out because your work on attention mechanisms was cited in our latest paper. We're building a new team focused on safety. Compensation is competitive. No pressure, but if you ever want to talk, the door is open.",
    timestamp: "2027-03-02T14:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-signal-3",
    type: "message",
    round: 2,
    sender: "Old Manager (from before OB)",
    body: "Saw the Agent-3 demo video someone leaked on Twitter. Is that real? Because if it's real, I think every software company I've ever worked at is in trouble. Also: are you doing okay? Genuinely asking.",
    timestamp: "2027-03-06T18:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 30 },
  },

  // ── Round 3: outside world starts asking real questions ──
  {
    id: "ob-flavor-r3-signal-1",
    type: "message",
    round: 3,
    sender: "Sister",
    body: "Hey. I know you can't talk about work. But there's stuff on Twitter about AI safety and OpenBrain keeps coming up. Should I be worried? Not about the AI. About you.",
    timestamp: "2027-07-05T19:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 35 },
  },
  {
    id: "ob-flavor-r3-signal-2",
    type: "message",
    round: 3,
    sender: "Friend (Bay Area)",
    body: "Honest question. Should I sell my NVIDIA stock? My financial advisor says AI is fine but he also said crypto was fine in 2022. You're closer to this than anyone I know.",
    timestamp: "2027-07-06T12:30:00Z",
    classification: "context",
    condition: { variable: "marketIndex", operator: "lt", value: 120 },
  },
  {
    id: "ob-flavor-r3-signal-3",
    type: "message",
    round: 3,
    sender: "Mom",
    body: "I saw something on the news about AI companies being dangerous? Your father is asking questions I don't know how to answer. Please call when you can. Love you.",
    timestamp: "2027-07-07T10:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },

  // ── Round 4: fear ──
  {
    id: "ob-flavor-r4-signal-1",
    type: "message",
    round: 4,
    sender: "Partner",
    body: "I don't know what's happening at your company but the news is terrifying. Your name isn't in any of the articles but I keep checking. Please just tell me you're OK. That's all I need.",
    timestamp: "2027-11-13T18:30:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },
  {
    id: "ob-flavor-r4-signal-2",
    type: "message",
    round: 4,
    sender: "College Roommate (Dan)",
    body: "OK so I'm reading about OpenBrain and I'm freaking out a little. Is this real? The AI thing? Are you allowed to tell me anything? I have kids man.",
    timestamp: "2027-11-14T08:30:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 55 },
  },

  // ── Round 5: tenderness ──
  {
    id: "ob-flavor-r5-signal-1",
    type: "message",
    round: 5,
    sender: "Mom",
    body: "I don't understand most of what I'm reading. But I understand that my child is in the middle of something important and probably scared. Whatever you decide today: I love you. Come home when you can.",
    timestamp: "2028-02-01T06:00:00Z",
    classification: "context",
  },
];

export const OB_SIGNAL_NOTIFICATIONS: ContentItem[] = [
  // ── Round 1: delivery/service notifications ──
  {
    id: "ob-notif-r1-amazon-1",
    type: "message",
    round: 1,
    sender: "Amazon",
    body: "Your order has been delivered. Package left at front door. Order: Blue Light Glasses 2-pack + Standing Desk Mat. Tap to rate your delivery.",
    timestamp: "2026-10-08T14:23:00Z",
    classification: "context",
  },
  {
    id: "ob-notif-r1-amazon-2",
    type: "message",
    round: 1,
    sender: "Amazon",
    body: "Your order has been delivered. Package left with building concierge. Order: Noise Canceling Headphones (replacement ear cushions) + USB-C Hub 7-port. Tracking: 1Z8R4E7A03",
    timestamp: "2026-10-22T16:47:00Z",
    classification: "context",
  },
  {
    id: "ob-notif-r1-amazon-3",
    type: "message",
    round: 1,
    sender: "Amazon",
    body: "Your Subscribe & Save order has shipped. Estimated delivery: Thursday. Items: Melatonin 10mg (90ct), Protein bars variety pack. Free shipping applied.",
    timestamp: "2026-11-02T09:15:00Z",
    classification: "context",
  },
  {
    id: "ob-notif-r1-doordash-1",
    type: "message",
    round: 1,
    sender: "DoorDash",
    body: "Your order from Chipotle is on its way! Dasher: Marco. ETA 12 min. Order: Burrito Bowl (chicken, extra guac) + chips. Total: $18.47",
    timestamp: "2026-10-14T12:38:00Z",
    classification: "context",
  },
  {
    id: "ob-notif-r1-doordash-2",
    type: "message",
    round: 1,
    sender: "DoorDash",
    body: "Your order from Sushi Hon has been delivered. Don't forget to rate your experience! Order: Salmon sashimi (8pc) + miso soup + edamame. Total: $34.12",
    timestamp: "2026-11-03T19:52:00Z",
    classification: "context",
  },
  {
    id: "ob-notif-r1-calendar-dentist",
    type: "message",
    round: 1,
    sender: "ZocDoc",
    body: "Appointment reminder: Dr. Chen, DDS — teeth cleaning & X-rays, Thursday Nov 12 at 2:30 PM. Pacific Dental Group, 450 Sutter St. Confirm or reschedule: tap here.",
    timestamp: "2026-11-09T09:00:00Z",
    classification: "context",
  },
  {
    id: "ob-notif-r1-calendar-car",
    type: "message",
    round: 1,
    sender: "Toyota Service",
    body: "SERVICE DUE: Your 2023 Camry (lic. ending 4471) is due for an oil change and tire rotation (est. 15,000 mi / 12 months). Schedule online or call (415) 555-0182.",
    timestamp: "2026-10-30T10:00:00Z",
    classification: "context",
  },
  {
    id: "ob-notif-r1-netflix",
    type: "message",
    round: 1,
    sender: "Netflix",
    body: "New episodes available: The Crown Season 7 (3 new eps), Succession rewatch rec based on your history. Your monthly charge of $22.99 processes Nov 14. Manage account →",
    timestamp: "2026-11-01T08:00:00Z",
    classification: "context",
  },
];

registerContent({ faction: "openbrain", app: "slack", accumulate: true, items: OB_SLACK_FLAVOR });
registerContent({ faction: "openbrain", app: "signal", accumulate: true, items: OB_SIGNAL_FLAVOR });
registerContent({ faction: "openbrain", app: "signal", accumulate: true, items: OB_SIGNAL_NOTIFICATIONS });
