import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

// ═══════════════════════════════════════════════
// OPENBRAIN FLAVOR — casual Slack + personal Signal
// Human texture: startup energy → dread
// ═══════════════════════════════════════════════

export const OB_SLACK_FLAVOR: ContentItem[] = [
  // ── Round 1: startup energy, late nights, camaraderie ──
  {
    id: "ob-flavor-r1-slack-1",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "Whoever took the last oat milk from the 3rd floor fridge: I will find you and I will make you explain your attention head implementation to the board.",
    timestamp: "2026-11-01T12:31:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-2",
    type: "message",
    round: 1,
    sender: "Alex Chen (CTO)",
    channel: "#general",
    body: "Reminder: nobody leaves the building tomorrow until the Agent-1 deployment retro is done. Yes I'm serious. Yes there will be pizza. The good pizza, not the sad pizza.",
    timestamp: "2026-11-01T18:22:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-3",
    type: "message",
    round: 1,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "I just realized I've been here 19 hours. The sunset through the server room windows was actually beautiful. I need to go outside. Does outside still exist?",
    timestamp: "2026-11-02T03:47:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-4",
    type: "message",
    round: 1,
    sender: "Priya Singh (Security)",
    channel: "#general",
    body: "Security awareness reminder: if you find a USB drive in the parking lot, do NOT plug it in. This is not hypothetical. Someone did this yesterday.",
    timestamp: "2026-11-03T09:15:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-5",
    type: "message",
    round: 1,
    sender: "Jordan Kim",
    channel: "#random",
    body: "My mom just texted asking if OpenBrain is 'the Google one or the Facebook one.' This is the level of public awareness we're dealing with.",
    timestamp: "2026-11-04T14:55:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-slack-6",
    type: "message",
    round: 1,
    sender: "Nadia Okonkwo (Research)",
    channel: "#research",
    body: "I turned down a $1.2M TC offer from Google DeepMind to be here. Just putting that out into the universe. If this doesn't work out I'm going to need therapy and a time machine.",
    timestamp: "2026-11-05T16:30:00Z",
    classification: "context",
  },

  // ── Round 2: intensity ramps, gallows humor creeps in ──
  {
    id: "ob-flavor-r2-slack-1",
    type: "message",
    round: 2,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "Agent-3 just wrote a haiku when I asked it to summarize the training logs:\n\n  Loss curves descending\n  Humans watch with smaller eyes\n  I learn what you fear\n\nI'm choosing to find this funny and not terrifying.",
    timestamp: "2027-02-18T16:30:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-2",
    type: "message",
    round: 2,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "For anyone still in the building at midnight: there's leftover ramen in the 4th floor kitchen. Also I think the cleaning crew is afraid of us. We should probably go home sometimes.",
    timestamp: "2027-02-20T00:12:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-3",
    type: "message",
    round: 2,
    sender: "Alex Chen (CTO)",
    channel: "#research",
    body: "Quick vent: I just had a two-hour call with a defense contractor who asked if Agent-3 could 'do cybersecurity but offensive.' I said no. I also said it in a way that probably lost us the contract. Worth it. Back to work.",
    timestamp: "2027-02-25T17:45:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-4",
    type: "message",
    round: 2,
    sender: "Maya Patel (Safety)",
    channel: "#alignment",
    body: "I want to note that I've been in this Slack channel for 14 months and the number of people who read my posts has roughly tripled since the anomalous eval results. It's nice to be popular. I wish it were for different reasons.",
    timestamp: "2027-03-01T15:20:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-5",
    type: "message",
    round: 2,
    sender: "Jordan Kim",
    channel: "#random",
    body: "HR is asking us to please stop referring to the building as 'the bunker.' I think the fact that we have blackout curtains and a backup generator means we've earned it, personally.",
    timestamp: "2027-03-05T10:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-slack-6",
    type: "message",
    round: 2,
    sender: "Kenji Watanabe (Research)",
    channel: "#general",
    body: "Just overheard two interns in the kitchen debating whether Agent-3 is 'alive.' One said yes. The other said 'define alive.' I poured my coffee and left because I don't have a good answer either.",
    timestamp: "2027-03-07T12:40:00Z",
    classification: "context",
  },

  // ── Round 3: the dread sets in, mundanity vs existential risk ──
  {
    id: "ob-flavor-r3-slack-1",
    type: "message",
    round: 3,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "I haven't seen a friend who doesn't work here in six weeks. My girlfriend asked me to describe my day and I realized I can't, because it's classified. She thought I was joking. I wasn't joking. How is this my life.",
    timestamp: "2027-07-03T21:05:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r3-slack-2",
    type: "message",
    round: 3,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "The cafeteria started putting inspirational quotes on the whiteboards. Today's: 'The best time to plant a tree was 20 years ago. The second best time is now.' Feels pointed given the context.",
    timestamp: "2027-07-04T12:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r3-slack-3",
    type: "message",
    round: 3,
    sender: "Dr. James Okafor (Alignment)",
    channel: "#alignment",
    body: "I found a sticky note on my monitor this morning. Anonymous. It just said: 'Thank you for not giving up.' I'm not crying in the server room. The cooling system is making my eyes water.",
    timestamp: "2027-07-05T07:30:00Z",
    classification: "context",
    condition: { variable: "obMorale", operator: "lt", value: 50 },
  },
  {
    id: "ob-flavor-r3-slack-4",
    type: "message",
    round: 3,
    sender: "Nadia Okonkwo (Research)",
    channel: "#random",
    body: "Just realized my Spotify Wrapped this year is going to be 4,000 hours of 'brown noise for focus.' I used to listen to music. I used to be a person who listened to music.",
    timestamp: "2027-07-06T18:30:00Z",
    classification: "context",
  },

  // ── Round 4: crisis, but still human ──
  {
    id: "ob-flavor-r4-slack-1",
    type: "message",
    round: 4,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "The protesters outside are chanting 'shut it down.' Three of them are wearing OpenBrain hoodies. I think one of them works — worked — on the infra team. I recognize his face from the Q2 offsite.",
    timestamp: "2027-11-13T11:45:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },
  {
    id: "ob-flavor-r4-slack-2",
    type: "message",
    round: 4,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "My mom called. She saw the news. She asked if I'm safe. I said yes. She asked if the world is safe. I said... I didn't have an answer. She said 'come home for Christmas either way.' So there's that.",
    timestamp: "2027-11-14T07:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r4-slack-3",
    type: "message",
    round: 4,
    sender: "Priya Singh (Security)",
    channel: "#general",
    body: "Parking garage access has been restricted to badge + PIN starting today. If anyone asks why: do not engage. Walk inside and badge in. If they follow you, call me directly. I'm not being dramatic. This is the policy now.",
    timestamp: "2027-11-13T08:30:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 45 },
  },

  // ── Round 5: exhaustion, tenderness ──
  {
    id: "ob-flavor-r5-slack-1",
    type: "message",
    round: 5,
    sender: "Nadia Okonkwo (Research)",
    channel: "#general",
    body: "Someone left flowers on the front desk this morning. No card. Just flowers. I don't know why that hit me as hard as it did.",
    timestamp: "2028-02-01T07:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r5-slack-2",
    type: "message",
    round: 5,
    sender: "Kenji Watanabe (Research)",
    channel: "#random",
    body: "Two years ago today I started at OpenBrain. I remember thinking: this is going to be the most exciting job of my life. I was right. I just didn't know what 'exciting' would mean.",
    timestamp: "2028-02-01T09:00:00Z",
    classification: "context",
  },
];

export const OB_SIGNAL_FLAVOR: ContentItem[] = [
  // ── Round 1: normal life still exists ──
  {
    id: "ob-flavor-r1-signal-1",
    type: "message",
    round: 1,
    sender: "Mom",
    body: "Happy Thanksgiving sweetie! Will you make it home this year? Dad says hi. He still doesn't understand what you do but he tells everyone at church his kid works in AI 😊",
    timestamp: "2026-11-04T11:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r1-signal-2",
    type: "message",
    round: 1,
    sender: "College Roommate (Dan)",
    body: "Dude I saw the OpenBrain valuation in the Journal. You still there? Are you a millionaire yet? Beers on you next time",
    timestamp: "2026-11-05T20:30:00Z",
    classification: "context",
  },

  // ── Round 2: strain shows ──
  {
    id: "ob-flavor-r2-signal-1",
    type: "message",
    round: 2,
    sender: "Partner",
    body: "It's 1am. You said you'd be home by 10. I'm not mad, I'm worried. You've been like this for weeks. Can we talk this weekend? Not about work. About us.",
    timestamp: "2027-02-22T01:15:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-signal-2",
    type: "message",
    round: 2,
    sender: "Recruiter (Google DeepMind)",
    body: "Hi — reaching out because your work on attention mechanisms was cited in our latest paper. We're building a new team focused on safety. Compensation is competitive. No pressure, but if you ever want to talk, the door is open.",
    timestamp: "2027-03-02T14:00:00Z",
    classification: "context",
  },
  {
    id: "ob-flavor-r2-signal-3",
    type: "message",
    round: 2,
    sender: "Old Manager (from before OB)",
    body: "Saw the Agent-3 demo video someone leaked on Twitter. Is that real? Because if it's real, I think every software company I've ever worked at is in trouble. Also: are you doing okay? Genuinely asking.",
    timestamp: "2027-03-06T18:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 30 },
  },

  // ── Round 3: outside world starts asking real questions ──
  {
    id: "ob-flavor-r3-signal-1",
    type: "message",
    round: 3,
    sender: "Sister",
    body: "Hey. I know you can't talk about work. But there's stuff on Twitter about AI safety and OpenBrain keeps coming up. Should I be worried? Not about the AI. About you.",
    timestamp: "2027-07-05T19:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 35 },
  },
  {
    id: "ob-flavor-r3-signal-2",
    type: "message",
    round: 3,
    sender: "Friend (Bay Area)",
    body: "Honest question. Should I sell my NVIDIA stock? My financial advisor says AI is fine but he also said crypto was fine in 2022. You're closer to this than anyone I know.",
    timestamp: "2027-07-06T12:30:00Z",
    classification: "context",
    condition: { variable: "marketIndex", operator: "lt", value: 120 },
  },
  {
    id: "ob-flavor-r3-signal-3",
    type: "message",
    round: 3,
    sender: "Mom",
    body: "I saw something on the news about AI companies being dangerous? Your father is asking questions I don't know how to answer. Please call when you can. Love you.",
    timestamp: "2027-07-07T10:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },

  // ── Round 4: fear ──
  {
    id: "ob-flavor-r4-signal-1",
    type: "message",
    round: 4,
    sender: "Partner",
    body: "I don't know what's happening at your company but the news is terrifying. Your name isn't in any of the articles but I keep checking. Please just tell me you're OK. That's all I need.",
    timestamp: "2027-11-13T18:30:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },
  {
    id: "ob-flavor-r4-signal-2",
    type: "message",
    round: 4,
    sender: "College Roommate (Dan)",
    body: "OK so I'm reading about OpenBrain and I'm freaking out a little. Is this real? The AI thing? Are you allowed to tell me anything? I have kids man.",
    timestamp: "2027-11-14T08:30:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 55 },
  },

  // ── Round 5: tenderness ──
  {
    id: "ob-flavor-r5-signal-1",
    type: "message",
    round: 5,
    sender: "Mom",
    body: "I don't understand most of what I'm reading. But I understand that my child is in the middle of something important and probably scared. Whatever you decide today: I love you. Come home when you can.",
    timestamp: "2028-02-01T06:00:00Z",
    classification: "context",
  },
];

registerContent({ faction: "openbrain", app: "slack", accumulate: true, items: OB_SLACK_FLAVOR });
registerContent({ faction: "openbrain", app: "signal", accumulate: true, items: OB_SIGNAL_FLAVOR });
