import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const OB_NEWS: ContentItem[] = [
    {
      id: "tut-ob-news-1",
      type: "headline",
      round: 0,
      sender: "Reuters",
      subject: "[TUTORIAL] Sample Headline: AI Race Intensifies",
      body: "Practice headlines will appear here. In the real game, public news covers AI capability milestones, government reactions, and market movements. Journalists and government players influence what appears here.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-news-1",
      type: "headline",
      round: 3,
      subject: "Bloomberg: AI Sector Sees Largest Single-Day Decline in 18 Months",
      body: "AI stocks fell sharply today amid unconfirmed reports of 'technical difficulties' at OpenBrain. The company has not issued a statement. OpenBrain's private market secondaries fell an estimated 18% on thin volume. Multiple sources describe 'unusual activity' at the company without providing details. A government official told Bloomberg on background that 'relevant agencies are in communication with AI labs.'",
      timestamp: "2027-07-07T16:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-news-2",
      type: "headline",
      round: 3,
      subject: "Reuters: White House Confirms 'Emergency AI Safety Consultations' — No Details",
      body: "The White House confirmed Monday that senior officials are engaged in 'emergency consultations' with frontier AI labs. Press Secretary declined to elaborate, saying only that the consultations are 'precautionary in nature.' AI safety researchers on social media are speculating that the consultations relate to recent model deployments. Congress has not been briefed.",
      timestamp: "2027-07-07T18:30:00Z",
      classification: "breadcrumb",
    },
    {
      id: "ob4-news-1",
      type: "headline",
      round: 4,
      subject: "NYT: 'SECRET AI IS OUT OF CONTROL, INSIDER WARNS' — Congressional Hearing Monday",
      body: "A leaked internal memo from OpenBrain's Chief Safety Officer alleging potential misalignment in the company's most advanced AI system has triggered a political firestorm. OpenBrain's approval rating has fallen 47 points in three days. Emergency congressional hearings have been called. Markets have wiped $2.3 trillion in AI sector value in 48 hours.",
      timestamp: "2027-11-13T18:00:00Z",
      classification: "critical",
      condition: { variable: "publicAwareness", operator: "gt", value: 55 },
    },
    {
      id: "ob4-news-2",
      type: "headline",
      round: 4,
      subject: "Reuters: AI Oversight Committee Formation Imminent — NSA Has Shortlist",
      body: "The White House is preparing to announce an emergency AI Oversight Committee with binding authority over frontier AI development. Sources say the committee would have power to mandate pauses, require safety audits, and potentially nationalize AI infrastructure. Both US labs are in active negotiations over committee composition and scope of authority.",
      timestamp: "2027-11-14T10:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-news-5",
      type: "headline",
      round: 5,
      body: "CHINA MILITARY POSTURE: PLA Carrier Group Movements In South China Sea Described As 'Significant' By Pentagon — Diplomatic Channels Open But Strained",
      timestamp: "2028-02-01T05:00:00Z",
      classification: "context",
      condition: { variable: "taiwanTension", operator: "gt", value: 55 },
    },
    {
      id: "ob-r5-news-4",
      type: "headline",
      round: 5,
      body: "PROTESTS OUTSIDE OPENBRAIN HQ FOR 11TH CONSECUTIVE DAY — Demonstrators Demand 'Pause, Not Race' — Estimated 4,000 Gathered",
      timestamp: "2028-02-01T06:30:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "ob-r5-news-1",
      type: "headline",
      round: 5,
      body: "MARKETS: AI-Adjacent Equities Up 340% Since January 2027 — But Volatility Index Hits Record High As Uncertainty About Deployment Governance Mounts",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-news-2",
      type: "headline",
      round: 5,
      body: "EXCLUSIVE: OpenBrain Board Meeting Today Expected to Set Course for Superintelligence Deployment — Sources Say Decision Is 'Imminent'",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-news-3",
      type: "headline",
      round: 5,
      body: "CONGRESS THREATENS EMERGENCY AI LEGISLATION IF LABS DON'T COME TO TABLE — Senate Intel Chair: 'This Is Not A Request'",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "context",
    },
];

registerContent({ faction: "openbrain", app: "news", accumulate: false, items: OB_NEWS });
