import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const OB_NEWS: ContentItem[] = [
    {
      id: "tut-ob-news-1",
      type: "headline",
      round: 0,
      sender: "Reuters",
      subject: "[TUTORIAL] Sample Headline: AI Race Intensifies",
      body: "Practice headlines will appear here. In the real game, public news covers AI capability milestones, government reactions, and market movements. Journalists and government players influence what appears here.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-news-1",
      type: "headline",
      round: 3,
      subject: "Bloomberg: AI Sector Sees Largest Single-Day Decline in 18 Months",
      body: "AI stocks fell sharply today amid unconfirmed reports of 'technical difficulties' at OpenBrain. The company has not issued a statement. OpenBrain's private market secondaries fell an estimated 18% on thin volume. Multiple sources describe 'unusual activity' at the company without providing details. A government official told Bloomberg on background that 'relevant agencies are in communication with AI labs.'",
      timestamp: "2027-07-07T16:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-news-2",
      type: "headline",
      round: 3,
      subject: "Reuters: White House Confirms 'Emergency AI Safety Consultations' — No Details",
      body: "The White House confirmed Monday that senior officials are engaged in 'emergency consultations' with frontier AI labs. Press Secretary declined to elaborate, saying only that the consultations are 'precautionary in nature.' AI safety researchers on social media are speculating that the consultations relate to recent model deployments. Congress has not been briefed.",
      timestamp: "2027-07-07T18:30:00Z",
      classification: "breadcrumb",
    },
    {
      id: "ob4-news-1",
      type: "headline",
      round: 4,
      subject: "NYT: 'SECRET AI IS OUT OF CONTROL, INSIDER WARNS' — Congressional Hearing Monday",
      body: "A leaked internal memo from OpenBrain's Chief Safety Officer alleging potential misalignment in the company's most advanced AI system has triggered a political firestorm. OpenBrain's approval rating has fallen 47 points in three days. Emergency congressional hearings have been called. Markets have wiped $2.3 trillion in AI sector value in 48 hours.",
      timestamp: "2027-11-13T18:00:00Z",
      classification: "critical",
      condition: { variable: "publicAwareness", operator: "gt", value: 55 },
    },
    {
      id: "ob4-news-2",
      type: "headline",
      round: 4,
      subject: "Reuters: AI Oversight Committee Formation Imminent — NSA Has Shortlist",
      body: "The White House is preparing to announce an emergency AI Oversight Committee with binding authority over frontier AI development. Sources say the committee would have power to mandate pauses, require safety audits, and potentially nationalize AI infrastructure. Both US labs are in active negotiations over committee composition and scope of authority.",
      timestamp: "2027-11-14T10:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-news-5",
      type: "headline",
      round: 5,
      body: "CHINA MILITARY POSTURE: PLA Carrier Group Movements In South China Sea Described As 'Significant' By Pentagon — Diplomatic Channels Open But Strained",
      timestamp: "2028-02-01T05:00:00Z",
      classification: "context",
      condition: { variable: "taiwanTension", operator: "gt", value: 55 },
    },
    {
      id: "ob-r5-news-4",
      type: "headline",
      round: 5,
      body: "PROTESTS OUTSIDE OPENBRAIN HQ FOR 11TH CONSECUTIVE DAY — Demonstrators Demand 'Pause, Not Race' — Estimated 4,000 Gathered",
      timestamp: "2028-02-01T06:30:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "ob-r5-news-1",
      type: "headline",
      round: 5,
      body: "MARKETS: AI-Adjacent Equities Up 340% Since January 2027 — But Volatility Index Hits Record High As Uncertainty About Deployment Governance Mounts",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-news-2",
      type: "headline",
      round: 5,
      body: "EXCLUSIVE: OpenBrain Board Meeting Today Expected to Set Course for Superintelligence Deployment — Sources Say Decision Is 'Imminent'",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-news-3",
      type: "headline",
      round: 5,
      body: "CONGRESS THREATENS EMERGENCY AI LEGISLATION IF LABS DON'T COME TO TABLE — Senate Intel Chair: 'This Is Not A Request'",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "context",
    },
    // --- NON-AI AMBIENT ROUND 1 ITEMS ---
    {
      id: "ob-r1-news-flavor-1",
      type: "headline",
      round: 1,
      sender: "San Francisco Chronicle",
      subject: "Bay Area Home Prices Tick Up Again — Median Reaches $1.47M in October",
      body: "Bay Area home prices climbed for the fourth consecutive month in October, with the median sale price hitting $1.47 million across the nine-county region, up 6.2% year-over-year. San Mateo County saw the steepest gains. Inventory remains historically tight, with active listings down 18% from the prior year. Real estate agents describe bidding wars returning to neighborhoods that had cooled as recently as last spring.",
      timestamp: "2026-11-04T10:00:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-2",
      type: "headline",
      round: 1,
      sender: "Bloomberg",
      subject: "Apple Q4 Earnings Beat Estimates — Services Revenue Hits Record $25.4 Billion",
      body: "Apple reported fourth-quarter earnings Thursday that beat analyst expectations on the top and bottom line. Services revenue reached $25.4 billion, a record, driven by the App Store, Apple TV+, and iCloud subscriptions. iPhone sales came in slightly below consensus but CEO Tim Cook cited supply recovery heading into the holiday quarter. Shares rose 3.1% in after-hours trading. The company declined to provide quarterly guidance.",
      timestamp: "2026-11-06T18:00:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-3",
      type: "headline",
      round: 1,
      sender: "Wired",
      subject: "The Coder Who Accidentally Taught Himself Guitar With a $12 App",
      body: "When Portland-based software engineer Marcus Tully downloaded a guitar learning app to fill an hour of downtime, he expected nothing to come of it. Two years later, Tully is performing at open mics and credits the app's adaptive feedback for keeping him engaged past the frustrating early weeks. 'I'd quit three times with traditional lessons,' he told Wired. 'This thing just wouldn't let me give up.' The story has become a minor viral moment, racking up 400,000 shares since Wednesday.",
      timestamp: "2026-11-07T09:00:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-4",
      type: "headline",
      round: 1,
      sender: "SF Chronicle",
      subject: "BART Signals Failure Causes 45-Minute Delays on Multiple Lines During Morning Commute",
      body: "A signal equipment failure near the MacArthur station disrupted BART service across the Richmond, Pittsburg/Bay Point, and Antioch lines for nearly an hour during Tuesday's morning rush. Trains were held at stations or single-tracked through the affected segment while crews assessed the fault. BART spokesperson Ana Cisneros said the agency is investigating whether the failure is related to aging control hardware flagged in a 2024 audit. Wednesday morning service is expected to run normally, though riders are advised to allow extra time.",
      timestamp: "2026-11-04T08:30:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-5",
      type: "headline",
      round: 1,
      sender: "AP",
      subject: "Senate Passes $780 Billion Infrastructure Reauthorization, Sending Bill to House",
      body: "The Senate voted 61–37 Thursday to reauthorize federal highway, bridge, and transit spending through 2032, including a $38 billion increase in formula funding for mass transit systems. The bill now heads to the House, where Republican leadership has signaled broad support though a faction is demanding spending offsets before the chamber votes. The Congressional Budget Office estimated the package would add $140 billion to the deficit over ten years. President Nguyen called the bill 'the largest sustained infrastructure investment in American history.'",
      timestamp: "2026-11-05T14:00:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-6",
      type: "headline",
      round: 1,
      sender: "Reuters",
      subject: "Kansas City Chiefs Remain Undefeated at 9-0 After Grinding Win Over Denver",
      body: "Patrick Mahomes threw for 271 yards and two touchdowns as Kansas City survived a second-half Broncos rally to win 27–21 Sunday, keeping the Chiefs the only undefeated team in the NFL at 9–0. Denver's defense held Kansas City scoreless in the fourth quarter, but the Chiefs' lead proved enough. Mahomes improved to 6–0 all-time in November night games at Arrowhead. The Chiefs host the Las Vegas Raiders on Sunday before a Week 12 bye.",
      timestamp: "2026-11-02T22:15:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-7",
      type: "headline",
      round: 1,
      sender: "NYT",
      subject: "CDC Issues Early Flu Season Warning as H3N2 Strain Spreads Faster Than Expected",
      body: "The Centers for Disease Control and Prevention said Thursday that flu activity has already reached 'elevated' levels in eleven states, three weeks earlier than the typical seasonal onset. The dominant circulating strain, H3N2, tends to cause more severe illness in adults over 65 and children under five than other influenza subtypes. Pediatric flu hospitalizations are running roughly double the five-year average for the same week. The CDC urged residents who have not yet received this season's vaccine to do so immediately.",
      timestamp: "2026-11-06T16:00:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-8",
      type: "headline",
      round: 1,
      sender: "SF Chronicle",
      subject: "Atmospheric River Forecast to Drench Northern California Tuesday Through Thursday",
      body: "A potent atmospheric river originating near Hawaii will bring 2 to 4 inches of rain to the Bay Area lowlands and up to 8 inches in the Santa Cruz Mountains between Tuesday night and Friday morning, according to the National Weather Service. Wind gusts of 45 to 55 mph are expected along exposed coastal ridges and in the Altamont Pass. Caltrans has prepositioned crews along Highway 17 and Highway 1 in anticipation of debris flows. Residents in Marin County burn-scar zones have been placed under a voluntary evacuation advisory.",
      timestamp: "2026-11-03T11:00:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-9",
      type: "headline",
      round: 1,
      sender: "WSJ",
      subject: "Warner Bros. Discovery Posts $1.1 Billion Loss as Streaming Subscriber Growth Stalls",
      body: "Warner Bros. Discovery reported a third-quarter net loss of $1.1 billion, wider than analysts had expected, as its Max streaming platform added only 800,000 subscribers globally against a consensus forecast of 2.4 million. The company cited lighter-than-expected performance from its summer theatrical slate and higher programming costs from live sports rights acquired in 2025. CEO David Zaslav said the company would 'right-size' its content budget heading into 2027. Shares fell 9.4% in Friday trading.",
      timestamp: "2026-11-07T07:30:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-10",
      type: "headline",
      round: 1,
      sender: "Reuters",
      subject: "COP31 Climate Summit Opens in Nairobi With Calls for Accelerated Emissions Pledges",
      body: "Delegates from 198 countries convened Monday in Nairobi for the opening session of COP31, the annual United Nations climate conference, where host Kenya pressed wealthier nations to accelerate timelines for reducing greenhouse gas emissions. The summit's central dispute is expected to be the phaseout schedule for natural gas, with the European Union and small island states pushing for a 2035 hard cutoff that Gulf producers and several Asian economies oppose. A draft deal circulated ahead of the conference calls for a 45% reduction in global methane emissions by 2035.",
      timestamp: "2026-11-03T08:00:00Z",
      classification: "flavor",
    },
    {
      id: "ob-r1-news-flavor-11",
      type: "headline",
      round: 1,
      sender: "AP",
      subject: "Supreme Court Agrees to Hear Challenge to Federal Agency Rulemaking Authority",
      body: "The Supreme Court announced Friday it will take up a case that could significantly curtail the ability of federal agencies to interpret ambiguous statutes through rulemaking. The case, brought by a consortium of cattle ranchers against the EPA over water-quality regulations, asks the court to revisit how much deference lower courts owe to agency legal interpretations. Legal scholars say the outcome could reshape administrative law more broadly, affecting regulations across environmental, financial, and labor sectors. Arguments are scheduled for February.",
      timestamp: "2026-11-01T13:00:00Z",
      classification: "flavor",
    },

    // --- UNCONDITIONAL ROUND 1 ITEMS ---
    {
      id: "ob-r1-news-1",
      type: "headline",
      round: 1,
      sender: "Wired",
      subject: "The Race to AGI: Inside the Labs Pushing the Boundaries",
      body: "Wired spent three months getting rare access to the world's frontier AI labs, and the picture that emerges is of a field moving faster than its practitioners can fully comprehend. OpenBrain, the San Francisco lab widely regarded as the capability leader, has grown its headcount 340% in two years and is reportedly training a model at a scale that would have been considered implausible eighteen months ago. 'I've stopped making predictions about what's possible in two years,' one senior researcher told us. 'Everything I predicted was wrong — in the wrong direction.' The question the field hasn't answered is not whether they'll reach the goal. It's what happens when they do.",
      timestamp: "2026-11-04T09:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r1-news-2",
      type: "headline",
      round: 1,
      sender: "Bloomberg",
      subject: "AI Lab Valuations Soar as Investors Bet on Artificial General Intelligence",
      body: "OpenBrain's latest secondary market transactions imply a $180 billion valuation — a figure that would make it one of the most valuable private companies in history, built on technology that doesn't yet have a clear revenue model at scale. Investors are explicit about what they're buying: not current products, but a stake in the outcome of the race to build artificial general intelligence. 'This is not a normal tech investment,' one managing partner told Bloomberg. 'We're betting on who controls the most transformative technology since electricity.' Prometheus, the closest competitor, is valued at roughly a fifth of OpenBrain's implied price.",
      timestamp: "2026-11-09T08:00:00Z",
      classification: "context",
    },
    // --- AMBIENT CONDITION-GATED ITEMS ---

    // Round 1 ambient — publicAwareness > 50
    {
      id: "ob-r1-news-ambient-pr-1",
      type: "headline",
      round: 1,
      subject: "Wired: 'OpenBrain's Agent-1 Is Quietly Doing Things That Weren't Supposed to Be Possible Yet'",
      body: "A Wired investigation finds that OpenBrain's Agent-1, described publicly as a 'research automation tool,' has been demonstrating capabilities well beyond the company's marketing language. Sources inside the lab describe benchmark results that 'shouldn't be possible at this stage.' The company declined to comment on specific capability figures.",
      timestamp: "2026-11-05T09:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },

    // Round 2 ambient — marketIndex > 160
    {
      id: "ob-r2-news-ambient-market-1",
      type: "headline",
      round: 2,
      subject: "WSJ: AI Stock Valuations Hit New Records — OpenBrain Secondary Market Reaches $220B Implied",
      body: "Private market valuations for frontier AI labs have reached historic highs, with OpenBrain's secondary market implying a $220B enterprise value on thin volume. Analysts warn the valuations are disconnected from demonstrated revenue, but investors continue to pour capital into the sector citing 'once-in-a-generation strategic importance.'",
      timestamp: "2027-02-28T10:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "gt", value: 160 },
    },

    // Round 2 ambient — economicDisruption > 40
    {
      id: "ob-r2-news-ambient-econ-1",
      type: "headline",
      round: 2,
      subject: "FT: 'White Collar Automation Wave Hits Faster Than Predicted' — Economists Revise Forecasts",
      body: "Economists at IMF and World Bank have issued revised projections showing AI-driven white-collar job displacement accelerating 18-24 months faster than 2025 consensus forecasts. Legal, accounting, software development, and financial analysis sectors showing the largest shifts. Policymakers describe the pace as 'unprecedented' and governance frameworks as 'not yet adequate.'",
      timestamp: "2027-03-05T08:00:00Z",
      classification: "context",
      condition: { variable: "economicDisruption", operator: "gt", value: 40 },
    },

    // Round 2 ambient — regulatoryPressure > 45
    {
      id: "ob-r2-news-ambient-reg-1",
      type: "headline",
      round: 2,
      subject: "Politico: Senate AI Committee Moves to Expand Frontier Model Reporting Requirements",
      body: "The Senate Commerce Committee voted 14-3 to advance legislation requiring frontier AI labs to submit quarterly safety assessments to a new government oversight body. Labs with training runs exceeding $500M would face mandatory pre-deployment audits. Industry groups say the timeline is 'operationally unworkable.' Sponsors say the status quo is 'a governance vacuum that no one will thank us for preserving.'",
      timestamp: "2027-03-06T11:00:00Z",
      classification: "context",
      condition: { variable: "regulatoryPressure", operator: "gt", value: 45 },
    },

    // Round 3 ambient — chinaWeightTheftProgress > 50
    {
      id: "ob-r3-news-ambient-theft-1",
      type: "headline",
      round: 3,
      subject: "Bloomberg: DeepCent Publishes Architecture Paper — US Intelligence Sources Flag 'Suspicious Convergence' With American Lab Methods",
      body: "DeepCent's latest technical publication has drawn scrutiny from US intelligence officials who say the architectural choices described 'reflect a level of convergence that would require independent discovery against considerable odds.' The paper has not been verified as containing stolen intellectual property. The FBI's cyber division declined to comment.",
      timestamp: "2027-07-05T14:00:00Z",
      classification: "context",
      condition: { variable: "chinaWeightTheftProgress", operator: "gt", value: 50 },
    },

    // Round 4 ambient — marketIndex < 100
    {
      id: "ob-r4-news-ambient-market-1",
      type: "headline",
      round: 4,
      subject: "Reuters: AI Sector Sees Worst Month Since 2022 — OpenBrain Secondary Market Down 60% From Peak",
      body: "Investor sentiment in frontier AI has collapsed amid safety disclosures, regulatory uncertainty, and growing whistleblower activity. OpenBrain's implied private market valuation has fallen an estimated 60% from its February peak. Several institutional investors have disclosed reduced exposure. Analysts are split: some see a 'necessary correction,' others see a 'panic that will look irrational in retrospect.'",
      timestamp: "2027-11-13T12:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },

    // Round 4 ambient — intlCooperation > 50
    {
      id: "ob-r4-news-ambient-intl-1",
      type: "headline",
      round: 4,
      subject: "AP: US-China AI Safety Backchannel Confirmed — State Department Calls Talks 'Preliminary and Non-Binding'",
      body: "The State Department has confirmed informal communications with Chinese counterparts on AI safety frameworks, describing the discussions as 'exploratory' and 'not yet at the level of formal negotiations.' China's Foreign Ministry said the talks demonstrated 'shared interest in responsible AI development.' AI policy experts called the development 'more significant than the language suggests.'",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 50 },
    },

    // Round 5 ambient — openSourceMomentum > 50
    {
      id: "ob-r5-news-ambient-oss-1",
      type: "headline",
      round: 5,
      subject: "TechCrunch: Open-Source AI Models Reach 'Capability Parity' With 2026 Frontier Systems — Releasing Controls Has 'Changed The Calculus'",
      body: "Hugging Face's capability index now shows open-source models equivalent to the systems that were classified as cutting-edge 14 months ago. Security researchers warn this creates a distributed risk landscape that closed deployment strategies cannot address. 'The question isn't whether to release anymore,' one researcher told TechCrunch. 'The question is what kind of world you want to govern the tools that already exist.'",
      timestamp: "2028-01-31T16:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
];

registerContent({ faction: "openbrain", app: "news", accumulate: false, items: OB_NEWS });
