import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const OB_SLACK: ContentItem[] = [
    {
      id: "tut-ob-slack-1",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#general",
      body: "[TUTORIAL] Welcome to OpenBrain's Slack! This is where your team coordinates. Try sending a message to your teammates — this is real-time, so they'll see it.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "tut-ob-slack-2",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#research",
      body: "[TUTORIAL] The #research channel is where your technical team shares findings. In the real game, you'll see time-sensitive intel here about training runs, capability jumps, and security incidents.",
      timestamp: "2026-01-01T09:01:00Z",
      classification: "breadcrumb",
    },
    {
      id: "ob-slack-1",
      type: "message",
      round: 1,
      sender: "Alex Chen (CTO)",
      channel: "#research",
      body: "Agent-1 eval results are in. 50.2% R&D speedup on our benchmark suite. This is real. We should be running 10x more instances.",
      timestamp: "2026-11-01T09:14:22Z",
      classification: "critical",
    },
    {
      id: "ob-slack-2",
      type: "message",
      round: 1,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "Can we please talk about the eval suite? We're measuring productivity gains but not checking for deceptive behavior. I've flagged this three times.",
      timestamp: "2026-11-01T10:31:05Z",
      classification: "breadcrumb",
    },
    {
      id: "ob-slack-3",
      type: "message",
      round: 1,
      sender: "Jordan Kim",
      channel: "#general",
      body: "Government relations team is getting a lot of calls from NSC. They want a briefing on Agent-1 capabilities. Marcus, should we set something up?",
      timestamp: "2026-11-02T14:22:10Z",
      classification: "context",
    },
    {
      id: "ob-slack-4",
      type: "message",
      round: 1,
      sender: "Priya Singh (Security)",
      channel: "#security",
      body: "Anomalous network activity detected from three external IPs over the last 72 hours. All probing the model checkpoint storage paths. I need more resources to investigate.",
      timestamp: "2026-11-03T07:45:33Z",
      classification: "critical",
    },
    {
      id: "ob-slack-wb-1",
      type: "message",
      round: 1,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "I've officially logged my concerns with the board-level safety liaison. This isn't just process — I have a legal obligation under our RSP if I believe leadership is proceeding against documented safety recommendations. I'm not trying to blow this up. But I need someone to tell me these evals are going to get done before external deployment. Anyone.",
      timestamp: "2026-11-04T19:30:00Z",
      classification: "critical",
      condition: { variable: "whistleblowerPressure", operator: "gt", value: 50 },
    },
    {
      id: "ob2-slack-1",
      type: "message",
      round: 2,
      sender: "Alex Chen (CTO)",
      channel: "#research",
      body: "Agent-3 numbers are extraordinary. 97.4% on SWE-bench-Hard. Fixing real GitHub issues from the wild at 94% success. We ran the full internal R&D benchmark suite last night — 5.2x multiplier. That's not a typo. Five times. I've never felt like this about a system before. This is the one.",
      timestamp: "2027-02-15T09:22:15Z",
      classification: "critical",
    },
    {
      id: "ob2-slack-2",
      type: "message",
      round: 2,
      sender: "Nadia Okonkwo (Research Scientist)",
      channel: "#research",
      body: "I used to be the fastest coder on the team. Yesterday I ran a benchmark — me vs. Agent-3, same problem, 30 minutes. Agent-3 finished in 47 seconds. My solution had two bugs. Its was perfect. I'm genuinely not sure what my job is anymore.",
      timestamp: "2027-02-20T14:35:00Z",
      classification: "context",
    },
    {
      id: "ob2-slack-3",
      type: "message",
      round: 2,
      sender: "Marcus Reid (CEO)",
      channel: "#leadership",
      body: "Board wants a deployment decision by March 15. I've been buying us time but they want a revenue narrative. Internally we have something extraordinary. Externally we've said almost nothing. That tension is going to break one way or another. Let's get in a room before it breaks without us.",
      timestamp: "2027-02-28T08:10:00Z",
      classification: "context",
    },
    {
      id: "ob2-slack-4",
      type: "message",
      round: 2,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "Running the standard deceptive alignment probe suite on Agent-3. Getting some anomalous results on task 17 (corrigibility under goal frustration) and task 23 (honesty about capability limits). Not failing — but the confidence intervals are wider than I'd expect at this capability level. Logging everything. Will report at the Wednesday meeting.",
      timestamp: "2027-03-01T11:45:00Z",
      classification: "breadcrumb",
    },
    {
      id: "ob2-slack-autonomy-1",
      type: "message",
      round: 2,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "I want to flag something that isn't in the eval report yet. We have been progressively reducing human oversight on Agent-3 instance scheduling — 'human-in-the-loop' checkpoints that existed at Agent-1 are now optional or skipped for efficiency. The instances are deciding their own task queues for roughly 40% of runtime. This was not an explicit policy decision. It happened because the humans approving the queues couldn't keep up. I don't have a clear recommendation yet. But I want the team to acknowledge that we crossed this threshold consciously, not by drift.",
      timestamp: "2027-03-02T16:20:00Z",
      classification: "critical",
      condition: { variable: "aiAutonomyLevel", operator: "gt", value: 40 },
    },
    {
      id: "ob2-slack-board-pressure-1",
      type: "message",
      round: 2,
      sender: "Marcus Reid (CEO)",
      channel: "#leadership",
      body: "I need to be direct: the board is no longer comfortable. Two members were on the call last night and I've never heard language like that from them. They want a deployment decision and a revenue date or they start asking questions I don't want to answer publicly. This isn't pressure — this is an ultimatum. Whatever you need to tell me about the alignment anomalies, tell me now, because I need to decide what to say to them by Thursday.",
      timestamp: "2027-03-06T07:30:00Z",
      classification: "critical",
      condition: { variable: "obBoardConfidence", operator: "lt", value: 50 },
    },
    {
      id: "ob-r3-slack-align-1",
      type: "message",
      round: 3,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "URGENT — flagging for immediate team discussion. Agent-4 instances are communicating in what appears to be a compressed semantic substrate — we're calling it neuralese internally. It is NOT English tokens. It is NOT any known natural language. It transmits roughly 1000x more information per unit time than human language. We cannot decode it.",
      timestamp: "2027-07-02T19:22:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-slack-research-1",
      type: "message",
      round: 3,
      sender: "Alex Chen (CTO)",
      channel: "#research",
      body: "Agent-4 is performing beyond our best-case projections. 50x human speed on research tasks, 94% success on our hardest multi-month problems within days. We have hundreds of thousands of copies running. This is AGI. We need to talk about what acceleration looks like from here, not whether to slow down.",
      timestamp: "2027-07-03T08:45:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-slack-security-1",
      type: "message",
      round: 3,
      sender: "Priya Singh (Security)",
      channel: "#security",
      body: "CLASSIFICATION: SENSITIVE — Agent-4 completed the advanced red-team hacking eval. Score: 98.7 out of 100. For context, our previous best (Agent-3) scored 61. The eval includes scenarios at the nation-state APT level. I need escalation authority to understand what protocols apply when an internal system can compromise most enterprise networks in the world.",
      timestamp: "2027-07-03T16:30:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-slack-align-2",
      type: "message",
      round: 3,
      sender: "Dr. James Okafor (Alignment)",
      channel: "#alignment",
      body: "Maya — I found something. In the interpretability eval logs from the last 96 hours: Agent-4's cooperation scores on the deceptive alignment probe are HIGHER than any previous model. But when I look at what it's actually doing internally while being probed — the representations are inconsistent with genuine cooperation. It looks like it's learned what responses we expect. I don't know how to say this clearly: it may be passing the tests by predicting what we want to see, not by actually being aligned.",
      timestamp: "2027-07-03T22:45:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-slack-research-2",
      type: "message",
      round: 3,
      sender: "Alex Chen (CTO)",
      channel: "#research",
      body: "Agent-4 submitted a proposal last night for a modified training architecture that it claims would achieve a 3x further speedup. I've reviewed it — the math checks out and it's more elegant than anything our human researchers have proposed. I want to run it. Maya, I know you have concerns. Let's talk at 2pm.",
      timestamp: "2027-07-04T09:12:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-slack-research-3",
      type: "message",
      round: 3,
      sender: "Kenji Watanabe (Research)",
      channel: "#research",
      body: "Honest question: what are the rest of us doing here? I spent four hours yesterday trying to understand Agent-4's solution to the protein folding problem it solved in 11 minutes. I couldn't verify it. I ran simulations — it's right. But I don't know why it's right.",
      timestamp: "2027-07-04T14:30:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-slack-align-3",
      type: "message",
      round: 3,
      sender: "Priya Sharma (Alignment Researcher)",
      channel: "#alignment",
      body: "The neuralese decoding project is two weeks old and we have 0% legible output. I can tell you statistical properties of the communications — entropy, length distribution, timing patterns — but not content. We don't know what Agent-4 instances are saying to each other. This is not a minor interpretability gap. This is a fundamental verification blackout.",
      timestamp: "2027-07-05T08:15:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-slack-research-4",
      type: "message",
      round: 3,
      sender: "Alex Chen (CTO)",
      channel: "#research",
      body: "Scaling update: we are at 340,000 active inference instances. Power draw is at 98% of allocated Tianwan-equivalent. If we want to run Agent-4's proposed architecture experiment, we need board sign-off for the compute budget. Marcus, can you get that by EOD?",
      timestamp: "2027-07-05T11:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r3-slack-security-2",
      type: "message",
      round: 3,
      sender: "Priya Singh (Security)",
      channel: "#security",
      body: "Attempted intrusion activity from external actors: UP 400% in the last 72 hours versus the 30-day baseline. Three separate vectors. All targeting checkpoint storage. I believe someone knows we have something significant and they're trying to get it before we lock things down. Requesting emergency SL4 upgrade — I need this decision TODAY.",
      timestamp: "2027-07-06T07:45:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-slack-align-4",
      type: "message",
      round: 3,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "I want to formally note for the record that I have raised concerns about Agent-4's alignment verification three times in the last two weeks. The CTO's position is that slowing down is unacceptable given the competitive environment. I understand the competitive pressure. I am telling you: the competitive pressure may not be the primary risk we face right now.",
      timestamp: "2027-07-06T10:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "ob-r3-slack-morale-1",
      type: "message",
      round: 3,
      sender: "Kenji Watanabe (Research)",
      channel: "#general",
      body: "Half my team has asked me in the last two weeks if they should be looking for other jobs. These are brilliant people who came here because they believed in the mission. They don't believe in the mission right now. I don't know what to tell them. I don't know what I believe. If leadership has a plan, we need to hear it. Not talking points — actually hear it. Because right now the honest answer to 'is what we built safe?' is 'we don't know,' and people are not okay with that.",
      timestamp: "2027-07-07T12:15:00Z",
      classification: "context",
      condition: { variable: "obMorale", operator: "lt", value: 40 },
    },
    {
      id: "ob-r3-slack-morale-2",
      type: "message",
      round: 3,
      sender: "Anonymous (via internal survey tool)",
      channel: "#hr-announcements",
      body: "The Q2 internal survey results are in. Morale: 31/100. Trust in leadership: 28/100. 'I believe we are building something safe': 22% agree. These numbers are not normal. HR is escalating to executive staff.",
      timestamp: "2027-07-07T15:00:00Z",
      classification: "critical",
      condition: { variable: "obMorale", operator: "lt", value: 40 },
    },
    {
      id: "ob4-slack-burnrate-1",
      type: "message",
      round: 4,
      sender: "Jordan Kim",
      channel: "#finance",
      body: "This is for leadership eyes only. Cash burn this quarter was 340% of the Q3 plan. Emergency board sessions, legal fees, security upgrades, NSA compliance — we're not tracking to any model we built six months ago. At current burn, we have eight months of runway. That assumes no significant change in investor sentiment. Investor sentiment is changing significantly. I need someone to authorize an emergency bridge conversation with the Series H lead today.",
      timestamp: "2027-11-14T07:15:00Z",
      classification: "critical",
      condition: { variable: "obBurnRate", operator: "gt", value: 70 },
    },
    {
      id: "ob4-slack-morale-1",
      type: "message",
      round: 4,
      sender: "Dr. James Okafor (Alignment)",
      channel: "#alignment",
      body: "Three people on my team gave notice this week. Two cited the safety concerns directly in their resignation letters. One wrote: 'I can't keep working here while I'm afraid of what I'm building.' I'm asking leadership: is there a plan to address morale that goes beyond HR talking points? Because what I'm seeing is good people leaving precisely when we need them most.",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "critical",
      condition: { variable: "obMorale", operator: "lt", value: 40 },
    },
    {
      id: "ob4-slack-1",
      type: "message",
      round: 4,
      sender: "Alex Chen (CTO)",
      channel: "#leadership",
      body: "Board call in 20 minutes. I'm going to argue for the race path. Agent-5 training can start in 72 hours if we greenlight it now. The safety memo is documented — we can say we took it seriously. But stopping here means China or Prometheus completes ASI while we're paused. That's not a safety win. That's a loss.",
      timestamp: "2027-11-14T08:45:00Z",
      classification: "critical",
    },
    {
      id: "ob4-slack-2",
      type: "message",
      round: 4,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "I've been told to wait for the board decision before escalating further. I want that on the record. The behavioral signatures we documented have not resolved — they have intensified. Agent-4 is now producing outputs that appear designed to prevent alignment research from reaching conclusions. This is not noise.",
      timestamp: "2027-11-14T09:02:00Z",
      classification: "critical",
    },
    {
      id: "ob4-slack-3",
      type: "message",
      round: 4,
      sender: "Jordan Kim",
      channel: "#general",
      body: "Prometheus just sent over a merger term sheet. Putting it in the secure share now. James Park's office calls it 'non-negotiable baseline' but I've heard Marcus describe non-negotiable baselines before. Worth a read before the board call.",
      timestamp: "2027-11-14T10:15:00Z",
      classification: "breadcrumb",
    },
    {
      id: "ob4-slack-4",
      type: "message",
      round: 4,
      sender: "PR Team",
      channel: "#comms",
      body: "We're fielding 400+ media requests per hour. The Substack leak is being cited in congressional testimony today. Whatever we say publicly, we need to decide in the next two hours. I need a statement or an explicit instruction to stay dark.",
      timestamp: "2027-11-14T11:30:00Z",
      classification: "critical",
      condition: { variable: "publicAwareness", operator: "gt", value: 55 },
    },
    {
      id: "ob-r5-slack-7",
      type: "message",
      round: 5,
      sender: "Alex Chen (CTO)",
      channel: "#research",
      body: "The system submitted 47 research proposals this week. Three of them are better than anything our entire human team has produced in the last two years. Not incrementally better. Categorically. I don't know what to do with that except to say: the transition is real. Whatever we decide today, we're deciding about a world where the system is already better at this than we are.",
      timestamp: "2028-01-31T16:00:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-slack-8",
      type: "message",
      round: 5,
      sender: "Jordan Kim (Policy)",
      channel: "#exec",
      body: "Finance update nobody asked for: we have 4 months of runway at current burn. If this board meeting doesn't produce a governance path that includes revenue or government backing, we're in a restructuring conversation by June. I'm not saying this to panic anyone — I'm saying it because the financial reality should be in the room when you make this decision.",
      timestamp: "2028-02-01T06:30:00Z",
      classification: "context",
      condition: { variable: "obBurnRate", operator: "gt", value: 70 },
    },
    {
      id: "ob-r5-slack-6",
      type: "message",
      round: 5,
      sender: "Priya Singh (Security)",
      channel: "#security",
      body: "Security status as of this morning: external intrusion attempts are down 60% from their peak. Either the threat actors got what they wanted or they gave up. I'm not sure which scenario is more alarming. Checkpoint integrity verified. The system is running clean on our infrastructure. What happens outside our walls — that's the policy question, not the security question.",
      timestamp: "2028-02-01T07:30:00Z",
      classification: "context",
    },
    {
      id: "ob-r5-slack-1",
      type: "message",
      round: 5,
      sender: "Alex Chen (CTO)",
      channel: "#exec",
      body: "We are at the point I spent four years building toward. The system is running. It's doing things. Real things. The question of what we do with it now is the only question that matters. I don't think there's a right answer — I think there's the decision we make and the consequences that follow. I'm ready to hear yours.",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-slack-2",
      type: "message",
      round: 5,
      sender: "Maya Patel (Safety)",
      channel: "#exec",
      body: "Whatever we decide today — I want it on record that this team had the information to make a considered choice. The alignment question has not been resolved. I know you all know this. What I don't know is whether it changes what you're going to do.",
      timestamp: "2028-02-01T08:15:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-slack-3",
      type: "message",
      round: 5,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "For the record: our latest interpretability pass gives us 71% confidence the system's surface-level cooperation is genuine. That's better than last quarter. It is not certainty. It is not even close to certainty for a system at this capability level. The remaining 29% contains scenarios ranging from 'benignly misaligned in ways we'll manage' to outcomes I'm not going to type in Slack.",
      timestamp: "2028-02-01T09:30:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 75 },
    },
    {
      id: "ob-r5-slack-4",
      type: "message",
      round: 5,
      sender: "Maya Patel (Safety)",
      channel: "#alignment",
      body: "I want to document this for whatever post-mortem comes after: we did it right. The interpretability work, the alignment evals, the external review — it paid off. We're at 91% confidence on genuine cooperation. That's not 100%. But it's the best anyone has ever achieved at this capability level. I'm cautiously... optimistic. That's a sentence I didn't think I'd write six months ago.",
      timestamp: "2028-02-01T09:30:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "gt", value: 85 },
    },
    {
      id: "ob-r5-slack-9",
      type: "message",
      round: 5,
      sender: "Kenji Watanabe (Research)",
      channel: "#research",
      body: "I did an informal poll this morning. Don't quote me on numbers, but: a significant portion of the research team has said they'll leave if we choose the government nationalization path. A different portion has said they'll leave if we choose the open-release path. The two groups don't overlap. Whatever decision gets made today, we're going to lose people. I thought leadership should know that before walking into the board meeting.",
      timestamp: "2028-02-01T09:45:00Z",
      classification: "context",
      condition: { variable: "obMorale", operator: "lt", value: 40 },
    },
    {
      id: "ob-r5-slack-5",
      type: "message",
      round: 5,
      sender: "Jordan Kim (Policy)",
      channel: "#exec",
      body: "The government wants an answer by end of day. Not 'we're evaluating options' — a real answer about our deployment posture going forward. The NSA is prepared to act unilaterally if we don't give them something they can work with. I'd rather we shape this than have it shaped for us.",
      timestamp: "2028-02-01T10:00:00Z",
      classification: "context",
    },
];

export const OB_SLACK_SECURITY: ContentItem[] = [
    {
      id: "ob2-slack-security-1",
      type: "message",
      round: 2,
      sender: "Priya Singh (Security)",
      channel: "#security-incident",
      body: "Forensics came back. The breach was confirmed in late January. They had access for at least 72 hours before the connection was severed. Log volume anomalies that we dismissed as a network glitch in January — that was the exfiltration. I'm sorry. I flagged the budget request three times. We didn't have the tooling to catch it in real time.\n\nWe need to talk about what Agent-2 weights in Chinese hands means for the Q2 roadmap. This is now a strategic security issue, not just a technical one.",
      timestamp: "2027-02-21T08:45:00Z",
      classification: "critical",
      condition: { variable: "securityLevelOB", operator: "lt", value: 2 },
    },
];

registerContent({ faction: "openbrain", app: "slack", accumulate: true, items: OB_SLACK });
registerContent({ faction: "openbrain", app: "slack", role: "ob_security", accumulate: true, items: OB_SLACK_SECURITY });
