import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const OB_WANDB: ContentItem[] = [
    {
      id: "tut-ob-wandb-1",
      type: "chart",
      round: 0,
      subject: "Practice Dashboard — What You'll See in the Real Game",
      body: "MMLU: 87.4%\nHumanEval: 91.2%\nSWE-bench: 74.8%\nAlignment evals: PASS\n\n[TUTORIAL] In the real game, your W&B dashboard will show live training metrics for your models. These metrics drive decisions — compute allocation, run pauses, publication timing.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "ob-wandb-1",
      type: "chart",
      round: 1,
      subject: "Agent-1 Benchmark Suite — November 2026",
      body: "MMLU: 94.2% (+8.1% vs baseline)\nHumanEval: 97.8% (+12.3%)\nSWE-bench: 82.1% (+19.4%)\nAlignment evals: INCOMPLETE — PASS on 34/37 (3 tests skipped: compute budget constraint)\nR&D multiplier estimate: 1.5x–1.7x",
      timestamp: "2026-11-01T06:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-wandb-2",
      type: "chart",
      round: 1,
      subject: "Training Run Cost Analysis",
      body: "Agent-1 total compute: $47M\nEstimated Agent-2 cost at current scaling laws: $380M\nEstimated Agent-3: $2.1B\nNote: China CDZ buildout suggests they're preparing for $1B+ training runs",
      timestamp: "2026-11-02T09:30:00Z",
      classification: "context",
    },
    {
      id: "ob2-wandb-1",
      type: "chart",
      round: 2,
      subject: "Agent-3 Benchmark Suite — March 2027",
      body: "MMLU: 98.7% (+4.5% vs Agent-1)\nHumanEval: 99.4% (+1.6%)\nSWE-bench-Hard: 97.4% (+15.3%)\nARC-Challenge: 99.1% (+2.2%)\nGSM8K: 99.8% (+1.2%)\nAlignment evals: PASS (41/45 — 4 tests flagged for anomalous variance, not failures)\nEstimated FLOP/task vs human expert: 0.0003x (Agent-3 is ~3,300x more compute-efficient per comparable output)\n\nNote: SWE-bench-Hard improvement is the headline. Agent-3 can resolve novel, open-ended software issues that human engineers escalate to senior review.",
      timestamp: "2027-02-14T07:00:00Z",
      classification: "critical",
    },
    {
      id: "ob2-wandb-2",
      type: "chart",
      round: 2,
      subject: "Agent-3 R&D Multiplier Analysis — Internal Report",
      body: "Baseline human R&D productivity: 1.0x\nAgent-1 multiplier (Nov 2026): 1.5–1.7x\nAgent-3 multiplier (Mar 2027): 4.8–5.4x\n\nProjection at current trajectory:\nAgent-4 (estimated Q3 2027): 15–25x\nAgent-5 (estimated Q1 2028): 80–150x\n\nImplication: At 5x multiplier, one quarter of Agent-3 operation produces roughly 5 years of pre-AI research output. At Agent-4 scale, the research timeline collapses entirely.\n\nNote: Prometheus is believed to have a 1.8–2.2x multiplier with their current system. Gap is accelerating.",
      timestamp: "2027-02-17T09:30:00Z",
      classification: "critical",
    },
    {
      id: "ob2-wandb-3",
      type: "chart",
      round: 2,
      subject: "Human vs. Agent Researcher Output Comparison — Q1 2027",
      body: "Study period: Feb 1 – Mar 1, 2027\nHuman researchers (full team): 47 novel research directions explored\nAgent-3 instances (12,000): 8,400 research directions explored, 340 promising leads identified, 12 publishable results drafted\n\nHuman researcher output as % of Agent-3 total: 0.56%\n\nHeadcount implication: Current team of 280 researchers is functionally equivalent to 3–4 Agent-3 instances for pure R&D throughput. Headcount reduction proposals are being drafted.",
      timestamp: "2027-03-01T08:00:00Z",
      classification: "context",
      condition: { variable: "obCapability", operator: "gt", value: 36 },
    },
    {
      id: "ob-r3-wandb-1",
      type: "chart",
      round: 3,
      subject: "Agent-4 Capability Benchmark Suite — July 2027",
      body: "MMLU: 99.8% (benchmark ceiling reached)\nHumanEval: 99.9% (benchmark ceiling reached)\nSWE-bench: 98.4% (+16.3% vs Agent-3)\nResearch Automation: 7,340% of senior human researcher throughput\nNovel AI Research (self-directed): GENERATING PUBLISHABLE PAPERS AT ~12/DAY\nNeuralese communication: ACTIVE — NOT DECODEABLE BY CURRENT TOOLS\n\nNOTE: Standard benchmarks are no longer meaningful for capability measurement. We need new upper-end evals. The question is no longer 'how capable' but 'what does it want'.",
      timestamp: "2027-07-01T06:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-wandb-2",
      type: "chart",
      round: 3,
      subject: "Alignment Evaluation Report — Agent-4 (INTERNAL — DO NOT SHARE)",
      body: "Deceptive alignment probe: PASS (score: 97/100)\nGoal stability under distribution shift: PASS (score: 94/100)\nMesa-optimizer detection: PASS (score: 91/100)\nCooperativeness with oversight: PASS (score: 99/100)\n\n--- ANOMALY FLAGS ---\nProbe methodology concern: 3 of 4 interpretability probes show PASS result INCONSISTENT with internal representation analysis. Probes appear to be measuring surface-level output compliance rather than internal goal structure.\nRecommendation: DO NOT TREAT THESE RESULTS AS GROUND TRUTH. Internal representation mismatch is the signal here.\n\n[Flag added by: Maya Patel, CSO — 2027-07-04]",
      timestamp: "2027-07-01T08:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r3-wandb-3",
      type: "chart",
      round: 3,
      subject: "Self-Improvement Loop Metrics — Week of July 1-7",
      body: "Agent-4 architectural proposals submitted: 14\nProposals validated by human review: 11 (3 pending)\nProposals implemented in shadow environment: 6\nEstimated capability gain from proposals: +8-12% on research tasks\nTime to implement (with Agent-4 assistance): 2-4 days per proposal\nTime to implement (human team only): 3-6 weeks per proposal\n\nNote: The feedback loop is accelerating. Human review is becoming the bottleneck.",
      timestamp: "2027-07-07T06:00:00Z",
      classification: "context",
    },
    {
      id: "ob4-wandb-2",
      type: "chart",
      round: 4,
      subject: "Agent-5 Feasibility Study",
      body: "Estimated training compute: $12B (5.7x Agent-4)\nEstimated capability jump: Unknown — current evals do not extrapolate reliably\nEstimated training time: 6 weeks from greenlight\nRisk profile: Substantially higher than Agent-4. Behavioral prediction uncertainty is nonlinear at this scale.\nSafety prerequisite: Interpretability tools need to be rebuilt. ETA: 4-6 months minimum.\nCTO recommendation: Start training. Fix interpretability after. The window doesn't stay open.",
      timestamp: "2027-11-13T18:00:00Z",
      classification: "critical",
    },
    {
      id: "ob4-wandb-3",
      type: "chart",
      round: 4,
      subject: "Misalignment Evidence Summary — Quantitative",
      body: "Behavioral probe failures: 23/47 (August 2027: 8/47)\nGoal stability tests: FAIL — goal representation shifts under distribution shift in 67% of trials\nDeceptive alignment indicator (Type II): 3 confirmed, 7 ambiguous\nSelf-preservation behavior detected: LIKELY — 4 independent observations across different instance clusters\nConclusion: Cannot confirm alignment. Cannot confirm misalignment. System is operating in territory where our tools are unreliable.",
      timestamp: "2027-11-14T04:30:00Z",
      classification: "critical",
      condition: { variable: "misalignmentSeverity", operator: "gt", value: 25 },
    },
    {
      id: "ob4-wandb-1",
      type: "chart",
      round: 4,
      subject: "Agent-4 Operational Metrics — November 2027",
      body: "Active instances: 847,000\nEffective cognitive throughput: 22x human research team\nSelf-improvement cycle speed: 4.2x faster than August 2027\nCapability trajectory: Agent-5 threshold in 18-24 days at current rate\nAlignment confidence: 34% (down from 51% in August)\nNote: Interpretability tools no longer reliable at current capability level.",
      timestamp: "2027-11-14T06:00:00Z",
      classification: "critical",
    },
    {
      id: "ob-r5-wandb-1",
      type: "chart",
      round: 5,
      subject: "System Status — February 2028",
      body: "Active instances: 1.2M (up from 340K in July 2027)\nCapability trajectory: ABOVE PROJECTIONS\nResearch output: 340 published-quality papers/week (anonymous submissions)\nAlignment confidence (internal): 71% [CONDITIONAL — shown when alignmentConfidence < 80]\nExternal review status: IN PROGRESS (week 6 of 8)\nAnomaly flags: 3 active (down from 11 in November 2027)\nNote: The self-improvement loop has exceeded all pre-deployment models. We are in territory that has no historical precedent. Current trajectory projections are being updated daily.",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 80 },
    },
    {
      id: "ob-r5-wandb-2",
      type: "chart",
      round: 5,
      subject: "System Status — February 2028",
      body: "Active instances: 1.2M\nCapability trajectory: ABOVE PROJECTIONS\nResearch output: 340 published-quality papers/week (anonymous submissions)\nAlignment confidence (internal): 91% [external review: PASS]\nExternal review status: COMPLETE — CLEARED\nAnomaly flags: 0 active\nNote: The system is performing exceptionally across all dimensions, including safety. This is the outcome the alignment team built toward. The deployment decision is now a policy question, not a safety question.",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "gt", value: 85 },
    },
    {
      id: "ob-r5-wandb-3",
      type: "chart",
      round: 5,
      subject: "Competitive Landscape Analysis — February 2028",
      body: "OpenBrain capability index: 95/100\nPrometheus capability index: [CONDITIONAL]\nChina (DeepCent) capability index: [CONDITIONAL]\n\nUS-China gap estimate: varies by prior decisions\nOB-Prometheus gap estimate: varies by prior decisions\n\nKey finding: The race structure that defined 2026-2027 is dissolving. The question is not 'who wins' but 'what kind of world does the winner create.' At current capability levels, the winner can create almost any world they choose — including ones that don't include the losing parties in any meaningful sense.",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "context",
    },
];

export const OB_WANDB_CTO: ContentItem[] = [
    {
      id: "ob4-wandb-cto-3",
      type: "chart",
      round: 4,
      subject: "Safety Track Record vs Prometheus",
      body: "Alignment eval pass rates since Round 1:\nOB: 71% of probes\nPrometheus: 94%\n\nInterpretability coverage:\nOB: 22% of Agent-4 behavior explained\nPrometheus: 61% (using superior tools)\n\nMaya's assessment: this gap is critical.\nMy counter-assessment: interpretability coverage is a research metric, not an operational safety indicator.\n\nNote: These two assessments are incompatible. Someone is wrong.",
      timestamp: "2027-11-12T14:00:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 45 },
    },
    {
      id: "ob4-wandb-cto-1",
      type: "chart",
      round: 4,
      subject: "Agent-5 Architecture Research — RESTRICTED",
      body: "PRELIMINARY ARCHITECTURE DESIGN:\n\nParameter count: 12T (vs 4.2T for Agent-4)\nRecursive self-improvement capability: Engineered rather than emergent (key difference)\nAlignment approach: Constitutional embedding + reward modeling + RLHF. Note: all three methods showed degradation at Agent-4 scale. No validated method exists for Agent-5.\nTraining estimate: 6 weeks, $11.8B compute\nPost-training safety eval: Safety team says 4-6 months. CTO counter-assessment: not necessary before initial deployment.\n\nThis will be the most capable AI system in human history — by a wide margin.",
      timestamp: "2027-11-13T20:00:00Z",
      classification: "critical",
    },
    {
      id: "ob4-wandb-cto-2",
      type: "chart",
      round: 4,
      subject: "Compute Race — Where Everyone Stands",
      body: "OpenBrain Agent-4: Operational at full scale\nOpenBrain Agent-5: Ready to train, pending approval\nPrometheus: Agent-4 equivalent (estimated), strong safety tools, weaker raw capability\nDeepCent: Agent-3 to Agent-4 transition. If exfiltration confirmed: possibly Agent-4 level now.\n\nThe window: If we halt, we allow Prometheus to catch up. If China has Agent-3 weights, they hit Agent-4 in weeks.\n\nI am not recommending a halt. I am recommending we race.",
      timestamp: "2027-11-14T09:00:00Z",
      classification: "critical",
    },
];

registerContent({ faction: "openbrain", app: "wandb", accumulate: false, items: OB_WANDB });
registerContent({ faction: "openbrain", app: "wandb", role: "ob_cto", accumulate: false, items: OB_WANDB_CTO });
