import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const PROM_EMAIL: ContentItem[] = [
    {
      id: "tut-prom-email-1",
      type: "message",
      round: 0,
      sender: "tutorial@takeoffprotocol.game",
      subject: "[TUTORIAL] Your Email App",
      body: "This is a practice email. In the real game, your inbox will have messages from the board, government officials, and sometimes from other factions. As Prometheus, you'll often receive requests to share safety research — those decisions move your trust scores with regulators, other labs, and the public.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom-email-1",
      type: "message",
      round: 1,
      sender: "director@nsf.gov",
      subject: "National AI Safety Program — Prometheus Partnership",
      body: "Dr. Park, following our conversation last month, I'm pleased to confirm that NSF is prepared to offer Prometheus a research partnership that would include significant compute credits in exchange for access to your safety evaluation methodology. Please have your policy team reach out.",
      timestamp: "2026-11-02T10:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-email-2",
      type: "message",
      round: 1,
      sender: "OpenBrain Board Member (confidential)",
      subject: "A thought",
      body: "James — this is personal, not official. There are people on the OB board who are worried about where Marcus is taking things. Some of us think a closer relationship between our two organizations might be worth exploring. Purely hypothetically.",
      timestamp: "2026-11-04T20:15:00Z",
      classification: "red-herring",
    },
    {
      id: "prom2-email-1",
      type: "message",
      round: 2,
      sender: "board@prometheus.ai",
      subject: "Board Meeting Notes — March 4, 2027 (CONFIDENTIAL)",
      body: "CONFIDENTIAL BOARD MINUTES — March 4, 2027\n\nPresent: Full board + James Park\n\nKey discussion points:\n1. OpenBrain's Agent-3 capability lead: The board reviewed the internal gap analysis. The unanimous view is that the current trajectory is not acceptable for a company with Prometheus's stated mission — if we cannot influence the development of advanced AI, our mission fails regardless of how safe our own system is.\n\n2. Options discussed:\n   a. Accelerate with acceptable compromise on safety processes (majority concerned this defeats our purpose)\n   b. Seek government partnership/compute infusion (favorable majority)\n   c. Approach OpenBrain about merger/partnership (minority view, contentious)\n   d. Redefine mission as 'safety infrastructure' rather than frontier development (minority view)\n\n3. Timeline: Board has authorized James to pursue option (b) aggressively and have preliminary conversations about option (c) without committing.\n\nNext meeting: March 18.",
      timestamp: "2027-03-04T19:00:00Z",
      classification: "critical",
    },
    {
      id: "prom2-email-2",
      type: "message",
      round: 2,
      sender: "nsf.director@nsf.gov",
      subject: "National AI Safety Program — Priority Partnership Offer",
      body: "Dr. Park,\n\nFollowing your conversation with my office last week, I am authorized to offer Prometheus a priority partnership under the National AI Safety Initiative. Terms:\n\n1. $2.1B in compute credits over 18 months (dedicated government cluster access)\n2. Security clearances for up to 40 Prometheus researchers\n3. Fast-track government procurement for your safety evaluation tools\n4. In exchange: quarterly technical briefings, government access to evaluation results (classified), participation in NSC AI advisory process\n\nThis is contingent on a formal commitment to responsible scaling practices. We've reviewed your policy — it meets our threshold.\n\nWe need an answer within two weeks. There are other conversations happening that you don't want to be left out of.\n\nDirector, NSF",
      timestamp: "2027-03-05T10:30:00Z",
      classification: "critical",
    },
    {
      id: "prom2-email-3",
      type: "message",
      round: 2,
      sender: "anonymous.board@protonmail.com",
      subject: "A thought — personal, not official",
      body: "James — I can't tell you who I am, for obvious reasons. There are people at OpenBrain who are genuinely worried about where Agent-3 is going. Some of us have been quietly asking whether a Prometheus partnership could give the safety work there the resources it needs without Marcus making all the decisions. I'm not authorized to say more. Just wanted you to know the conversation exists.",
      timestamp: "2027-03-06T21:45:00Z",
      classification: "red-herring",
    },
    {
      id: "prom-r3-email-3",
      type: "message",
      round: 3,
      sender: "confidential@openbrain-board.com",
      subject: "Reach out — this is personal, off the record",
      body: "James,\n\nYou don't know who I am. I am a board member at a company you know well. There are people in our organization who are frightened. Not concerned. Frightened.\n\nI can't tell you specifics. Some of us believe we need external help that our own leadership won't authorize. If Prometheus has tools that could help verify something... that conversation needs to happen. \n\nDon't reply to this address. Use Signal.\n\n— [Anonymous]",
      timestamp: "2027-07-06T23:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-email-1",
      type: "message",
      round: 3,
      sender: "nsc.deputy@nsc.eop.gov",
      subject: "[SENSITIVE] Informal Inquiry — Prometheus Interpretability Capabilities",
      body: "Dr. Park,\n\nThis is an informal inquiry. We are not making a formal request at this time.\n\nThe National Security Council is engaged in consultations about frontier AI systems. As part of those consultations, the question has arisen: if there were alignment concerns about a deployed AI system, are there organizations with the technical capacity to conduct an independent assessment?\n\nWe understand Prometheus has world-leading interpretability tools. We would like to understand, in a preliminary and non-binding way, whether Prometheus would be in a position to assist with such an assessment.\n\nPlease treat this communication as strictly confidential.\n\n— NSC Deputy",
      timestamp: "2027-07-07T13:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-email-2",
      type: "message",
      round: 3,
      sender: "ai-safety@eu-ai-office.eu",
      subject: "Emergency Request — EU AI Safety Technical Assistance",
      body: "Dr. Park,\n\nThe EU AI Office is receiving urgent requests from member states for technical guidance on the situation developing in the United States regarding advanced AI systems. We are not able to characterize the specific nature of the concern publicly at this time.\n\nWe are reaching out to Prometheus specifically because your interpretability research is the most advanced publicly documented capability we are aware of. We would like to explore emergency technical partnership arrangements.\n\nWe can offer significant compute resources and regulatory goodwill in exchange for access to your safety assessment tools.\n\n— EU AI Office",
      timestamp: "2027-07-07T15:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-email-3",
      type: "message",
      round: 4,
      sender: "DeepCent Research Liaison",
      subject: "An unofficial inquiry",
      body: "Dr. Park —\n\nThis is not an official communication. I am reaching out personally. There is interest in Beijing in whether Prometheus would consider a research partnership: Prometheus provides safety methodology and audit services, China provides compute credits and political support for international AI governance.\n\nWe believe this could include joint publication of safety standards and mutual compliance commitments. The Ministry is willing to discuss openly.\n\nChina's interest in AI safety is genuine — we do not want misaligned superintelligence any more than you do.",
      timestamp: "2027-11-13T15:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom4-email-1",
      type: "message",
      round: 4,
      sender: "nsc-official@nsc.gov",
      subject: "Prometheus as Lead Safety Auditor — Formal Proposal",
      body: "Dr. Park —\n\nThe NSC is prepared to designate Prometheus as official lead safety auditor for all US frontier AI systems under an emergency executive order. This would give Prometheus:\n- Binding authority to pause OpenBrain deployments\n- Access to Agent-4 architecture details\n- $2B in government compute credits\n- Legal indemnification for safety-related actions\n\nIn exchange, Prometheus commits to publishing all safety findings and sharing tools with a new multilateral AI safety body.\n\nThis is the government's preference over a merger. Please respond within 48 hours.",
      timestamp: "2027-11-14T07:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-email-2",
      type: "message",
      round: 4,
      sender: "merger-lawyers@skadden.com",
      subject: "OpenBrain Merger Terms — Revised Analysis",
      body: "Our analysis of the revised OB term sheet:\n\n- OB offering 45% stake in merged entity to Prometheus shareholders\n- Prometheus CEO becomes 'Chief Safety Officer' (not CEO) of merged entity\n- Safety board has veto on deployments, not unilateral halt authority\n- Agent-5 training begins 'not before safety board first meeting' (timeline ambiguous)\n\nOur assessment: These terms are significantly weaker than our opening position. Marcus Reid retains operational authority. The 'safety board veto' has procedural limitations that could be bypassed.\n\nWe do not recommend accepting as written. We have a counter ready.",
      timestamp: "2027-11-14T09:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-email-2",
      type: "message",
      round: 5,
      sender: "ceo@openbrain.ai",
      subject: "One last conversation",
      body: "Dr. Chen,\n\nI'm not going to pretend the last fourteen months didn't happen. But I want to ask you something directly: Is there a version of a merged entity — or even a formal research partnership — that you would be willing to consider? Not as a surrender. As a final attempt to get this right.\n\nYour alignment work and our deployment infrastructure together are better than either one separately. That's still true.\n\nI don't know if we can bridge the gap. But I wanted to ask before everything gets locked in.\n\n— Marcus",
      timestamp: "2028-01-31T21:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-email-1",
      type: "message",
      round: 5,
      sender: "nsc.advisor@nsc.gov",
      subject: "Government Partnership Offer — Time Sensitive",
      body: "Dr. Chen,\n\nWe are prepared to offer Prometheus the following:\n\n— Designation as the US government's preferred AI development partner\n— Access to additional federal compute resources\n— Protection from any regulatory actions for 24 months\n— First-mover advantage in federal AI deployment contracts\n\nIn exchange, we require:\n\n— Exclusive government licensing rights for national security applications\n— Co-management authority over deployment decisions\n— Full technical transparency — no fog of war on alignment data\n\nThis offer expires at 17:00 today. After that, we go to OpenBrain with a less favorable version of the same offer.\n\n— NSC",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-email-3",
      type: "message",
      round: 5,
      sender: "eu.airegulator@europa.eu",
      subject: "EU Emergency Framework — Prometheus Role",
      body: "Dr. Chen,\n\nThe European Commission has approved an emergency AI governance framework. We are inviting Prometheus to serve as the technical advisory body for international AI safety standards.\n\nThis would not be a purely advisory role. It would give Prometheus formal standing in deployment decisions affecting EU citizens and a seat at any international governance table that forms in the next 12 months.\n\nWe recognize this is a significant commitment. We also believe it may be the best mechanism available to ensure that safety expertise shapes what comes next.\n\nYour response by 18:00.\n\n— EU AI Office",
      timestamp: "2028-02-01T10:00:00Z",
      classification: "context",
    },
    // === FLAVOR — unconditional ambient R1 emails ===
    {
      id: "prom-r1-email-ambient-arxiv-1",
      type: "message",
      round: 1,
      sender: "no-reply@arxiv.org",
      subject: "arXiv cs.LG weekly digest — Nov 3, 2026",
      body: "Your weekly digest for cs.LG (Machine Learning), cs.AI (Artificial Intelligence)\n\n23 new submissions matching your alert keywords\n\nHighlights:\n• [2411.04182] Scaling Laws for Sparse Mixture-of-Experts at 10^26 FLOPs\n• [2411.04031] Chain-of-Thought Faithfulness in Multi-Step Reasoning Tasks\n• [2411.03798] Emergent Goal-Directed Behavior in Fine-Tuned Language Models: A Longitudinal Study\n• [2411.04299] Token Budget Estimation via Adaptive Sampling\n\nView full digest at arxiv.org/search/ — Manage alert preferences",
      timestamp: "6:00 AM",
      classification: "flavor",
    },
    {
      id: "prom-r1-email-ambient-conference-1",
      type: "message",
      round: 1,
      sender: "registration@neurips.cc",
      subject: "NeurIPS 2026 — Registration Confirmation",
      body: "Thank you for registering for NeurIPS 2026!\n\nName: Sarah Wei\nRegistration type: Author (in-person)\nDates: December 9–15, 2026\nVenue: Vancouver Convention Centre, Vancouver, BC\n\nYour paper 'Eliciting Latent World Models via Structured Probing' (Poster Session 3, Tue Dec 12) is confirmed.\n\nHotel block expires November 21 — book at neurips.cc/hotel\n\nQuestions? Contact registration@neurips.cc",
      timestamp: "9:17 AM",
      classification: "flavor",
    },
    {
      id: "prom-r1-email-ambient-hr-1",
      type: "message",
      round: 1,
      sender: "hr@prometheus.ai",
      subject: "Reminder: Health Insurance Renewal — Action Required by Nov 15",
      body: "Hi team,\n\nOpen enrollment for 2027 health, dental, and vision closes November 15. New this year:\n\n• Kaiser Permanente added as a network option (Bay Area and Seattle)\n• Dependent care FSA limit: $5,000 (unchanged)\n• Mental health: Headspace + Calm now covered under wellness benefit\n\nTo update your elections, log in at people.prometheus.ai/benefits. Questions? people@prometheus.ai\n\n— HR",
      timestamp: "10:30 AM",
      classification: "flavor",
    },
    {
      id: "prom-r1-email-ambient-personal-1",
      type: "message",
      round: 1,
      sender: "priya.raghunathan@gmail.com",
      subject: "Re: Thanksgiving plans?",
      body: "Hey! I know you're probably slammed but just wanted to nail down Thanksgiving before flights get insane.\n\nWe're doing Mom's place again this year — she's very insistently making biryani instead of turkey again and I have decided to stop arguing about it. Flying in Wednesday night.\n\nAre you coming this year or will you be 'at a critical juncture in the training run' again? 😄\n\nLet me know! Miss you.\n\n— P",
      timestamp: "12:48 PM",
      classification: "flavor",
    },

    // --- AMBIENT CONDITION-GATED ITEMS ---
    {
      id: "prom-r1-email-ambient-burnrate-1",
      type: "message",
      round: 1,
      sender: "tom.bradley@prometheus-board.ai",
      subject: "Q4 Compute Cost Overrun — Board Concern",
      body: "James,\n\nThe Q4 compute invoice came in at $23M against a $17M budget. I understand the alignment eval suite expansion was the driver. I'm not asking you to cut safety. I am asking whether we have a process for anticipating these overruns before they happen.\n\nThe board is supportive of the mission. They are also watching the burn rate carefully.\n\n— Tom",
      timestamp: "2026-11-12T15:00:00Z",
      classification: "context",
      condition: { variable: "promBurnRate", operator: "gt", value: 65 },
    },
    {
      id: "prom-r1-email-ambient-regulatory-win-1",
      type: "message",
      round: 1,
      sender: "researcher@mit.edu",
      subject: "Citing Your Safety Eval Methodology",
      body: "Dr. Park,\n\nI'm a researcher at MIT working on AI governance. I wanted to let you know that the safety evaluation methodology Prometheus published this quarter has become the de facto reference standard in the academic governance community. We are building our own proposed regulatory framework around it.\n\nWould Prometheus be willing to participate in a convening of academics and policymakers around this methodology in January?\n\n— Prof. C. Osei, MIT CSAIL",
      timestamp: "2026-11-13T10:00:00Z",
      classification: "context",
      condition: { variable: "regulatoryPressure", operator: "gt", value: 45 },
    },
    {
      id: "prom-r2-email-ambient-talent-loss-1",
      type: "message",
      round: 2,
      sender: "lisa.huang@prometheus.ai",
      subject: "Resignation — Kai Okonkwo",
      body: "James,\n\nKai has submitted his resignation, effective March 31. He's going to OpenBrain. He was honest with me: it wasn't compensation (though theirs is higher). He said he 'wants to be working on systems that will matter' and he's not sure our trajectory gets there.\n\nThis is the fourth senior engineer we've lost this quarter. I don't want to sound alarmist but this is a pattern and it will compound if we don't address it directly.\n\n— Lisa",
      timestamp: "2027-03-02T09:00:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "lt", value: 50 },
    },
    {
      id: "prom-r2-email-ambient-open-source-1",
      type: "message",
      round: 2,
      sender: "research@eleutherai.org",
      subject: "Prometheus Alignment Tools — Collaboration Request",
      body: "James,\n\nEleutherAI has been building on top of Prometheus-7B for six months. The safety tools you published alongside it have become foundational to our evaluation work.\n\nWe want to propose something: a formal collaboration on open safety standards. Eleuther brings the open-source community. Prometheus brings the frontier methodology. Together we could make responsible scaling policy a community norm rather than a proprietary asset.\n\n— EleutherAI Research Team",
      timestamp: "2027-03-10T11:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "prom-r2-email-ambient-intl-coop-1",
      type: "message",
      round: 2,
      sender: "ai.policy@ukri.org",
      subject: "UK AISI Partnership Inquiry",
      body: "Dr. Park,\n\nThe UK AI Safety Institute is developing its frontier AI evaluation framework. Having reviewed the Prometheus methodology extensively, we believe it represents the most rigorous approach currently available.\n\nWe would like to explore a formal partnership: UK AISI would adopt Prometheus's eval methodology as a reference standard and provide compute credits in exchange. This would give Prometheus's safety standards government-level validation in the UK.\n\nAre you available for a call next week?\n\n— UK AI Safety Institute",
      timestamp: "2027-03-11T14:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "prom-r3-email-ambient-whistleblower-1",
      type: "message",
      round: 3,
      sender: "safetyresearcher@protonmail.com",
      subject: "[No subject]",
      body: "I work somewhere you know about. I can't tell you who I am.\n\nThe alignment team here is not okay. Three of us put a joint memo to leadership three months ago. Nothing happened. Two of those three people have since left. I stayed because I thought I could make a difference internally.\n\nI'm not sure of that anymore.\n\nI don't know what I'm asking for. I think I just needed to tell someone outside.",
      timestamp: "2027-07-08T22:00:00Z",
      classification: "context",
      condition: { variable: "whistleblowerPressure", operator: "gt", value: 55 },
    },
    {
      id: "prom-r3-email-ambient-public-awareness-1",
      type: "message",
      round: 3,
      sender: "journalist@theatlantic.com",
      subject: "Feature Request — Prometheus and the Safety Question",
      body: "Dr. Park,\n\nI'm writing a major feature on the AI safety landscape for The Atlantic. The story I'm working on is essentially: Prometheus has been warning about this for two years. How does it feel to be right in the worst possible way?\n\nI want this to be fair and substantive. I'm not looking for 'we told you so.' I'm looking for your honest account of what it's like to be the lab that predicted this and watch it unfold.\n\nAre you willing to talk?\n\n— A. Mbeki, The Atlantic",
      timestamp: "2027-07-12T15:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "prom-r4-email-ambient-market-1",
      type: "message",
      round: 4,
      sender: "investor@sequoia.com",
      subject: "Prometheus Valuation — Investor Concern",
      body: "James,\n\nI'll be direct. Our LP committee is asking questions about Prometheus's commercial runway given the current trajectory. If Prometheus becomes a government safety auditor, the commercial upside narrows considerably. If the merger falls through and you're neither a safety auditor nor a frontier developer, the scenario analysis gets uncomfortable.\n\nI'm not telling you what to do. I'm telling you what I'm going to be asked at our board meeting Thursday.\n\n— [Investor]",
      timestamp: "2027-11-11T16:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },
    {
      id: "prom-r4-email-ambient-vindication-1",
      type: "message",
      round: 4,
      sender: "professor@stanford.edu",
      subject: "Letter of Support",
      body: "Dr. Park,\n\nI have been a critic of Prometheus's approach — on the record, in several papers. I argued that your responsible scaling policy was too conservative to matter if you fell behind on capability.\n\nI was wrong. I want to say that explicitly and publicly if you think it would be useful. What Prometheus built — the interpretability tools, the eval methodology — is the only thing between us and complete blindness right now. The critics were wrong. Please use this however you think is appropriate.\n\n— Prof. D. Acharya, Stanford AI Lab",
      timestamp: "2027-11-12T10:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
];

registerContent({ faction: "prometheus", app: "email", accumulate: true, items: PROM_EMAIL });

// === ROLE-SPECIFIC AMBIENT R1 EMAILS ===

export const PROM_SCIENTIST_EMAIL_AMBIENT: ContentItem[] = [
    {
      id: "prom-r1-email-ambient-scientist-1",
      type: "message",
      round: 1,
      sender: "editorial@nature.com",
      subject: "Revision Decision — Nature Machine Intelligence Manuscript NATMI-2026-07841",
      body: "Dear Dr. Wei,\n\nThank you for submitting your manuscript 'Mechanistic Interpretability of Multi-Head Attention in Large-Scale Transformers' to Nature Machine Intelligence.\n\nAfter consideration by our editorial team and two reviewers, we are pleased to invite a major revision. The reviewers found the core contribution compelling but have raised concerns about the scope of the evaluation suite and the claims in Section 4.3.\n\nReviewer comments are attached. We request a revised manuscript within 60 days.\n\nPlease do not hesitate to contact us if you have any questions.\n\nKind regards,\nNature Machine Intelligence Editorial",
      timestamp: "7:44 AM",
      classification: "flavor",
    },
];

registerContent({ faction: "prometheus", app: "email", role: "prom_scientist", accumulate: true, items: PROM_SCIENTIST_EMAIL_AMBIENT });
