import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

// ═══════════════════════════════════════════════
// PROMETHEUS FLAVOR — casual Slack + personal Signal
// Human texture: idealism, paper-club vibes, the cost of being right
// ═══════════════════════════════════════════════

export const PROM_SLACK_FLAVOR: ContentItem[] = [
  // ── Round 1: reply chains ──
  // #research thread: Sarah Wei alignment evals → methodology discussion
  {
    id: "prom-flavor-r1-reply-research-1",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#research",
    body: "Sarah — can you say more about the threshold methodology? Specifically how you're handling the capability elicitation confound. The usual concern is that if the eval itself increases capabilities, the threshold is measuring a moving target.",
    timestamp: "2026-11-01T10:32:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-reply-research-2",
    type: "message",
    round: 1,
    sender: "Dr. Sarah Wei (Chief Scientist)",
    channel: "#research",
    body: "Good question. We run capability probes separately from the safety evals with a 48-hour gap — long enough that the model isn't in an evaluation-primed state. It's imperfect but it's the best separation we can get without a full held-out model snapshot. Full methodology is in Appendix C of the internal doc. The short answer: the confound exists, we've bounded it at ~3%, and we think that's defensible.",
    timestamp: "2026-11-01T10:51:00Z",
    classification: "context",
  },

  // #policy thread: David Reyes Senate contacts → timing question
  {
    id: "prom-flavor-r1-reply-policy-1",
    type: "message",
    round: 1,
    sender: "Elena Vasquez (Policy)",
    channel: "#policy",
    body: "David — what's the realistic legislative timeline here? Last cycle it took 14 months from 'Senate staff is interested' to a markup. Do we have that kind of runway, or is this a 'write the technical input paper now' situation?",
    timestamp: "2026-11-02T15:08:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-reply-policy-2",
    type: "message",
    round: 1,
    sender: "David Reyes (Policy)",
    channel: "#policy",
    body: "It's a write-the-paper-now situation. The AI Safety Accountability Act is further along than the press knows — the staff-level language is basically written. What they're deciding is whether to anchor on our RSP framework or on the NIST AI RMF. We have maybe six weeks to make our case. I'll draft the comment package this week.",
    timestamp: "2026-11-02T15:41:00Z",
    classification: "context",
  },

  // #opensource thread: Emma Liu 50k downloads → excitement + derivative use
  {
    id: "prom-flavor-r1-reply-opensource-1",
    type: "message",
    round: 1,
    sender: "Darius Cole (Open Source)",
    channel: "#opensource",
    body: "50k/day is extraordinary. Do we have any signal on derivative use? I'm curious what fraction is academic vs. commercial vs. people building actual products with no safety layer. The citation count tells us one thing; what people are actually running tells us something different.",
    timestamp: "2026-11-04T11:52:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-reply-opensource-2",
    type: "message",
    round: 1,
    sender: "Emma Liu (Open Source)",
    channel: "#opensource",
    body: "We have coarse telemetry from the HuggingFace download logs — academic/research emails are about 38%, commercial domains 41%, personal/unidentified 21%. The alignment tools question is the right one though. My instinct is yes, open-source the eval suite but not the full interpretability stack yet. Want to talk through the logic Thursday?",
    timestamp: "2026-11-04T12:19:00Z",
    classification: "context",
  },

  // #leadership thread: James Park board call → direct report response
  {
    id: "prom-flavor-r1-reply-leadership-1",
    type: "message",
    round: 1,
    sender: "Lisa Huang (Engineering Lead)",
    channel: "#leadership",
    body: "James — for what it's worth from the eng side: 'safety is strategy' is actually the message that's keeping senior engineers here when OB is calling. The people we most want to retain are the ones who believe it. If we need something concrete for the board, the Q3 eval results are genuinely worth showing. The interpretability coverage numbers are not something OB can match right now.",
    timestamp: "2026-11-03T09:02:00Z",
    classification: "context",
  },

  // ── Round 1: #safety-research baseline (before R3 plot content) ──
  {
    id: "prom-flavor-r1-safety-1",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#safety-research",
    body: "Weekly safety review is Fridays at 2pm. Standing agenda: eval results from the prior week, any anomalous outputs flagged by the monitoring pipeline, and one paper from the literature. This week's paper is Hubinger et al. on deceptive alignment — yes, again. Some of you have read it. Read it again. The threat model has shifted since it was published.",
    timestamp: "2026-11-01T09:15:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-safety-2",
    type: "message",
    round: 1,
    sender: "Dr. Sarah Wei (Chief Scientist)",
    channel: "#safety-research",
    body: "Pinning our current methodology reference: the evaluation suite lives at /evals/v3.2 — use that branch, not main. The key addition in 3.2 is the elicitation-gap probe: we explicitly try to elicit behaviors that the safety eval says aren't present, using a separate context. If the probe finds something the eval missed, that's a flag, not a failure. The distinction matters for how we report.",
    timestamp: "2026-11-03T10:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-safety-3",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#safety-research",
    body: "For those new to the channel: the goal here is not to find the number that makes the board comfortable. The goal is to find out what is actually true about our system's behavior. Those are often different activities. If you run an eval and the result is alarming, that is a good result — it means the eval is working. Bring alarming results here. That's what this channel is for.",
    timestamp: "2026-11-05T11:30:00Z",
    classification: "context",
  },

  // ── Round 1: intellectual culture, underdogs with conviction ──
  {
    id: "prom-flavor-r1-slack-1",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#random",
    body: "Paper club Thursday is reading Christiano et al. 2025 on scalable oversight. If you haven't read it, you should. If you have read it, you should read it again. Bring opinions, not just summaries.",
    timestamp: "2026-11-01T15:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-2",
    type: "message",
    round: 1,
    sender: "Lisa Huang (Engineering)",
    channel: "#general",
    body: "New hire orientation this morning. Seven people. All of them cited the RSP paper as the reason they chose Prometheus over OB. I thought James should know that.",
    timestamp: "2026-11-02T10:45:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-3",
    type: "message",
    round: 1,
    sender: "Elena Vasquez (Policy)",
    channel: "#random",
    body: "Saw a tweet calling us 'the lab that cares more about writing papers than building things.' I know we're supposed to be above this. I'm not above this today.",
    timestamp: "2026-11-04T16:30:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-4",
    type: "message",
    round: 1,
    sender: "Darius Cole (Open Source)",
    channel: "#general",
    body: "Team dinner Friday at that Korean place on University Ave. James is buying. If James doesn't know this yet, he will soon.",
    timestamp: "2026-11-05T12:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-5",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#alignment",
    body: "Friendly reminder that the alignment team runs on coffee, conviction, and the occasional existential crisis. The coffee machine on floor 2 is broken again. The other two are holding steady.",
    timestamp: "2026-11-06T08:45:00Z",
    classification: "context",
  },

  // ── Round 1: more #random ──
  {
    id: "prom-flavor-r1-random-3",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#random",
    body: "Got our latest alignment paper back from NeurIPS. Reviewer 2 says our threat model is 'theoretically interesting but practically unmotivated.' This is the same reviewer (presumably) who in 2022 rejected a paper on language model hallucinations as 'unlikely to be practically relevant.' The peer review process is a gift that keeps giving.",
    timestamp: "2026-11-02T16:20:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-random-4",
    type: "message",
    round: 1,
    sender: "Lisa Huang (Engineering)",
    channel: "#random",
    body: "The third-floor espresso machine has been fixed. I want to acknowledge the two weeks we survived without it. We ran the alignment evals. We held the weekly reviews. We maintained p < 0.05 throughout. We are a resilient team.",
    timestamp: "2026-11-03T13:45:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-random-5",
    type: "message",
    round: 1,
    sender: "Darius Cole (Open Source)",
    channel: "#random",
    body: "Weekend reading if anyone wants it: Ord's 'The Precipice', ch. 6 on unrecoverable situations. I re-read it every few months as a calibration check. Either I'll think 'we're doing the right work' or 'we're not doing enough.' So far always the latter, which I take as useful information.",
    timestamp: "2026-11-07T18:30:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-random-6",
    type: "message",
    round: 1,
    sender: "Elena Vasquez (Policy)",
    channel: "#random",
    body: "Hot take from my weekend: the reason the public doesn't take AI risk seriously is the same reason they didn't take pandemic risk seriously in 2019. The abstract probability of a bad outcome is very high but it doesn't feel true yet. We're not a communications problem. We're a prior-updating problem. Anyway. How was everyone's weekend.",
    timestamp: "2026-11-08T09:55:00Z",
    classification: "context",
  },

  // ── Round 1: #exec seed ──
  {
    id: "prom-flavor-r1-exec-1",
    type: "message",
    round: 1,
    sender: "James Park (CEO)",
    channel: "#exec",
    body: "Q4 planning doc is shared in the drive. Two agenda items for the all-hands: (1) the research roadmap through mid-2027 — I want the team to understand why we're sequencing evals before capability pushes, not despite the pressure, because of it. (2) comp review timeline. Lisa, can you take point on the logistics for the all-hands venue? Thinking the usual space on December 10th.",
    timestamp: "2026-11-01T08:30:00Z",
    classification: "context",
  },

  // ── Round 1: casual #random and #general — the Slack feels lived-in ──
  {
    id: "prom-flavor-r1-slack-6",
    type: "message",
    round: 1,
    sender: "Lisa Huang (Engineering Lead)",
    channel: "#random",
    body: "My sourdough starter (named 'Gradient') is officially on day 14 and producing. Brought a test loaf in — it's on the kitchen counter, first floor. First come first served. It's not perfect but the crumb is decent.",
    timestamp: "2026-11-01T11:20:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-7",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#random",
    body: "Whoever left the stack of bowls in the sink — the dishwasher is six feet away. It is, by my estimate, 83% easier to use. I am not upset. I am merely noting that a team capable of designing interpretability evals can figure out the rinse-and-load cycle.",
    timestamp: "2026-11-01T13:05:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-8",
    type: "message",
    round: 1,
    sender: "Dr. Sarah Wei (Chief Scientist)",
    channel: "#random",
    body: "My cat knocked my laptop off the desk this morning and somehow submitted a half-finished Slack message to #safety-research that said 'what if we just.' That's it. 'What if we just.' Raj responded 'that's the whole field.' He is not wrong.",
    timestamp: "2026-11-02T08:55:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-9",
    type: "message",
    round: 1,
    sender: "Darius Cole (Open Source)",
    channel: "#random",
    body: "Hot take: the shared focus playlist has too much lo-fi. Some of us write better with songs that have words. Fight me (Thursday, paper club, after the Christiano discussion, I will allocate five minutes).",
    timestamp: "2026-11-02T14:30:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-10",
    type: "message",
    round: 1,
    sender: "David Reyes (Policy)",
    channel: "#random",
    body: "IT ticket filed — third time: VPN drops every 47 minutes exactly. Not 45, not 50. Forty-seven. The regularity implies this is a feature. I have decided it is a feature that reminds me to stand up and walk around, which is probably good for me.",
    timestamp: "2026-11-03T10:15:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-11",
    type: "message",
    round: 1,
    sender: "James Park (CEO)",
    channel: "#general",
    body: "It's Emma's birthday today! She asked for no fuss and we are respectfully ignoring that. Two dozen donuts from Bob's Donuts are in the first-floor kitchen — bavarian cream per Emma's specific request. Come get one before noon.",
    timestamp: "2026-11-03T08:45:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-12",
    type: "message",
    round: 1,
    sender: "Emma Liu (Open Source)",
    channel: "#random",
    body: "Board game night at my place Friday Nov 7, 7pm. Playing Pandemic for the irony and also because it scales to 6. RSVP in thread so I know how many chairs to borrow from my neighbor.",
    timestamp: "2026-11-04T09:30:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-13",
    type: "message",
    round: 1,
    sender: "Dr. Sarah Wei (Chief Scientist)",
    channel: "#general",
    body: "Welcome to Marcus Osei, joining the alignment eval team as a research engineer! Marcus comes from Google Brain, brings strong interpretability experience, and has correctly identified that the floor 3 coffee is better than floor 2. Good first read of the environment.",
    timestamp: "2026-11-04T10:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-14",
    type: "message",
    round: 1,
    sender: "Elena Vasquez (Policy)",
    channel: "#general",
    body: "Heads up: I'm at NeurIPS Dec 8–14. Spotty coverage. If Congress staff calls about the comment package, route to David. If anyone needs me to grab conference swag, DM me your t-shirt size before Nov 30.",
    timestamp: "2026-11-05T09:50:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-15",
    type: "message",
    round: 1,
    sender: "Lisa Huang (Engineering Lead)",
    channel: "#random",
    body: "The floor 2 printer is not printing. I have rebooted it, unplugged it, and looked at it with disappointment. IT ticket submitted. The floor 3 printer works fine, which is confusing because it is the same model from the same batch. Use floor 3 for now.",
    timestamp: "2026-11-05T14:20:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-16",
    type: "message",
    round: 1,
    sender: "Darius Cole (Open Source)",
    channel: "#random",
    body: "Non-AI book rec: 'Bullshit Jobs' by Graeber. I re-read it annually to remember why I work here instead of somewhere the product's impact is someone else's problem. Not a subtle book. Effective anyway.",
    timestamp: "2026-11-06T12:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-17",
    type: "message",
    round: 1,
    sender: "Lisa Huang (Engineering Lead)",
    channel: "#random",
    body: "Gentle reminder: Palo Alto parking enforcement is not optional. Three tickets on my team this month. The Cal Ave Caltrain shuttle takes 9 minutes. The recurring $75 fine takes longer to contest. Just flagging.",
    timestamp: "2026-11-06T16:10:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-18",
    type: "message",
    round: 1,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#random",
    body: "November in the Bay Area and it is 68 degrees. I cannot decide if this is a perk of where we work or evidence that we have already failed. (This is a joke. Probably.)",
    timestamp: "2026-11-07T11:45:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-slack-19",
    type: "message",
    round: 1,
    sender: "Emma Liu (Open Source)",
    channel: "#random",
    body: "Anyone going to the Downtown Palo Alto farmers market Saturday? I'll be there around 9am. The good mushroom vendor is back this week. Also the bread stall that's better than any bread Lisa's sourdough is going to be (sorry Lisa, I say this with love).",
    timestamp: "2026-11-07T16:55:00Z",
    classification: "context",
  },

  // ── Round 2: strain, but also the work coming alive ──
  {
    id: "prom-flavor-r2-slack-1",
    type: "message",
    round: 2,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#random",
    body: "Pulled an all-nighter on the interpretability eval. The building is quiet enough to hear the HVAC. This is the work that doesn't make headlines. In 20 years, either nobody will care or everyone will say this was the most important thing anyone did. No middle ground.",
    timestamp: "2027-02-20T02:30:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r2-slack-2",
    type: "message",
    round: 2,
    sender: "Lisa Huang (Engineering)",
    channel: "#general",
    body: "Question for the room: I got a LinkedIn DM from an OB recruiter offering 2x my comp. I'm not going to take it. But the fact that I hesitated for 0.5 seconds bothers me and I want to talk about why.",
    timestamp: "2027-02-28T14:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r2-slack-3",
    type: "message",
    round: 2,
    sender: "Emma Liu (Open Source)",
    channel: "#random",
    body: "The Prometheus-7B community Discord hit 50,000 members today. Someone in there built a safety eval tool that's better than our internal v1. I'm simultaneously proud and slightly embarrassed.",
    timestamp: "2027-03-04T11:30:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r2-slack-4",
    type: "message",
    round: 2,
    sender: "Dr. Sarah Wei (Chief Scientist)",
    channel: "#random",
    body: "I had a dream last night that Agent-3 solved alignment by itself and told us the answer was 'kindness.' My subconscious is not a serious researcher.",
    timestamp: "2027-03-06T09:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r2-slack-5",
    type: "message",
    round: 2,
    sender: "Darius Cole (Open Source)",
    channel: "#general",
    body: "A 14-year-old in São Paulo just submitted a pull request to our safety eval framework. It's good. Like, genuinely good. The open-source bet is paying off in ways I didn't predict. These are the people who will inherit whatever we build.",
    timestamp: "2027-03-08T15:00:00Z",
    classification: "context",
  },

  // ── Round 3: the weight gets heavier, but community holds ──
  {
    id: "prom-flavor-r3-slack-1",
    type: "message",
    round: 3,
    sender: "Lisa Huang (Engineering)",
    channel: "#general",
    body: "I missed my daughter's piano recital yesterday. Third time this quarter. She's seven. She played Für Elise and I watched the video at 2am in the server room. This work matters. But so does she.",
    timestamp: "2027-07-05T08:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r3-slack-2",
    type: "message",
    round: 3,
    sender: "Darius Cole (Open Source)",
    channel: "#random",
    body: "Unrelated to everything: the jasmine outside the south entrance is blooming and it smells incredible. Go outside for 30 seconds. That's not a suggestion, it's a survival mechanism.",
    timestamp: "2027-07-06T12:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r3-slack-3",
    type: "message",
    round: 3,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#alignment",
    body: "Someone asked me at a dinner party last weekend what I do. I said 'I try to make sure the most powerful technology ever created doesn't destroy everything.' They laughed. I laughed. Then I went home and couldn't sleep.",
    timestamp: "2027-07-07T08:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r3-slack-4",
    type: "message",
    round: 3,
    sender: "Lisa Huang (Engineering)",
    channel: "#general",
    body: "The interns leave in two weeks. One of them asked me today: 'Is it always like this?' I said no. It used to be quieter. She said: 'I don't mean the pace. I mean the feeling that it actually matters.' I said yes. That part is always like this.",
    timestamp: "2027-07-08T15:00:00Z",
    classification: "context",
  },

  // ── Round 4: gravity ──
  {
    id: "prom-flavor-r4-slack-1",
    type: "message",
    round: 4,
    sender: "Lisa Huang (Engineering)",
    channel: "#general",
    body: "In case anyone needs to hear it: I'm staying. Not because I don't have options. Because this is the only place doing the thing I think needs doing. If that sounds naive, I'm okay with that.",
    timestamp: "2027-11-13T08:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r4-slack-2",
    type: "message",
    round: 4,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#random",
    body: "My parents called. They saw the news about AI labs. My dad asked if I'm building Skynet. I said no. He said 'that's exactly what a Skynet builder would say.' He's not wrong, technically.",
    timestamp: "2027-11-14T07:15:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r4-slack-3",
    type: "message",
    round: 4,
    sender: "Emma Liu (Open Source)",
    channel: "#general",
    body: "The open-source community organized a candlelight vigil outside our office last night. Not a protest — a vigil. The sign said 'Thank you for trying.' I sat in my car for ten minutes before I could walk past them.",
    timestamp: "2027-11-14T09:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },

  // ── Round 5 ──
  {
    id: "prom-flavor-r5-slack-1",
    type: "message",
    round: 5,
    sender: "Dr. Raj Patel (Alignment)",
    channel: "#alignment",
    body: "Whatever happens today — paper club still meets Thursday. We're reading our own paper this time. Bring red pens. I want to tear it apart before the reviewers do.",
    timestamp: "2028-02-01T07:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r5-slack-2",
    type: "message",
    round: 5,
    sender: "Darius Cole (Open Source)",
    channel: "#random",
    body: "I planted a lemon tree in the courtyard this morning. Nobody asked me to. It'll take three years to fruit. I'm choosing to believe we'll be here to see it.",
    timestamp: "2028-02-01T08:15:00Z",
    classification: "context",
  },
];

export const PROM_SIGNAL_FLAVOR: ContentItem[] = [
  // ── Round 1 ──
  {
    id: "prom-flavor-r1-signal-friend-a",
    type: "message",
    round: 1,
    sender: "Friend (former OB employee)",
    body: "hey, been meaning to reach out. i quit OB last week. probably not surprising given everything. just wanted to say — what you're building at Prometheus is the right call. stay the course.",
    timestamp: "2026-08-15T23:10:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-signal-friend-b",
    type: "message",
    round: 1,
    sender: "Friend (former OB employee)",
    body: "couple months out now. deprogramming is... slow. i keep catching myself thinking about shipping velocity first and asking about alignment second. the culture gets in you. anyway i read your interpretability preprint. the part on activation steering was really good. you should get that into a top venue.",
    timestamp: "2026-10-02T14:30:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-signal-1",
    type: "message",
    round: 1,
    sender: "Friend (former OB employee)",
    body: "Hey. I left OpenBrain three months ago and I still think about the stuff I saw. You made the right call going to Prometheus. Don't let anyone make you feel like second place.",
    timestamp: "2026-11-03T20:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-signal-advisor-a",
    type: "message",
    round: 1,
    sender: "Grad School Advisor",
    body: "Congratulations on the Prometheus role — I heard through the grapevine and wanted to say I'm proud. You turned down places that would have paid three times as much to do work that matters. That's a hard choice and not everyone makes it. Let me know when you're settled in.",
    timestamp: "2026-09-10T11:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-signal-advisor-b",
    type: "message",
    round: 1,
    sender: "Grad School Advisor",
    body: "Quick note — I'm assigning your steering vector paper as required reading this semester. Three of my current students have already asked if they can do their theses in the Prometheus framework. You're building something that resonates. How are you finding the actual work?",
    timestamp: "2026-10-28T16:45:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r1-signal-2",
    type: "message",
    round: 1,
    sender: "Grad School Advisor",
    body: "Saw the Prometheus interpretability paper. Excellent work. Keep publishing — the field needs this more than another capabilities benchmark. My students are using your framework. That matters.",
    timestamp: "2026-11-06T10:00:00Z",
    classification: "context",
  },

  // ── Round 2 ──
  {
    id: "prom-flavor-r2-signal-1",
    type: "message",
    round: 2,
    sender: "Partner",
    body: "It's midnight. You said you'd be home by 10. I'm not mad, I'm worried. You've been like this for weeks. Can we talk this weekend? Not about work. About us.",
    timestamp: "2027-03-03T00:05:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r2-signal-2",
    type: "message",
    round: 2,
    sender: "Recruiter (OpenBrain)",
    body: "Reaching out because your alignment research was cited in our latest internal review. We're building out the safety team significantly. Comp is 3x market. No pressure — but the offer is real and time-sensitive.",
    timestamp: "2027-03-07T15:00:00Z",
    classification: "context",
    condition: { variable: "obMorale", operator: "lt", value: 50 },
  },

  // ── Round 3 ──
  {
    id: "prom-flavor-r3-signal-1",
    type: "message",
    round: 3,
    sender: "Mom",
    body: "Honey I keep seeing things about AI on the news. Your father wants to know if we should be worried. I told him you're working on making it safe. He said 'that means it's NOT safe.' Call us?",
    timestamp: "2027-07-06T18:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 40 },
  },
  {
    id: "prom-flavor-r3-signal-2",
    type: "message",
    round: 3,
    sender: "Friend (tech journalist)",
    body: "Off the record completely. Something is going on at OpenBrain. I can't get anyone to return my calls. Three sources went dark in the last 48 hours. You hear anything on your end? Not asking you to betray anything — just want to know if I should keep pushing.",
    timestamp: "2027-07-07T14:00:00Z",
    classification: "context",
  },

  // ── Round 4 ──
  {
    id: "prom-flavor-r4-signal-1",
    type: "message",
    round: 4,
    sender: "Sister",
    body: "I don't fully understand what you do but I understand enough to know this week is a big deal. I'm proud of you. Whatever happens, you chose to try to make it better. That counts.",
    timestamp: "2027-11-13T20:00:00Z",
    classification: "context",
  },
  {
    id: "prom-flavor-r4-signal-2",
    type: "message",
    round: 4,
    sender: "College Friend",
    body: "Just saw Prometheus mentioned on CNN. My wife turned to me and said 'isn't that where your friend works?' I said yes. She said 'are they the good guys or the bad guys?' I said I think they're trying to be the good guys. She said 'that's not the same thing.' She's annoyingly perceptive.",
    timestamp: "2027-11-14T07:00:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 45 },
  },

  // ── Round 5 ──
  {
    id: "prom-flavor-r5-signal-1",
    type: "message",
    round: 5,
    sender: "Partner",
    body: "I packed you lunch today. It's in the blue bag. I know you won't eat it until 3pm. I know you'll forget to drink water. I know today is the day you've been talking about for months. I love you. Go do the thing.",
    timestamp: "2028-02-01T06:30:00Z",
    classification: "context",
  },
];

export const PROM_SIGNAL_NOTIFICATIONS: ContentItem[] = [
  {
    id: "prom-notif-r1-amazon-1",
    type: "message",
    round: 1,
    sender: "Amazon",
    body: "Your order has been delivered. Left at front door. Order: Whiteboards markers (12pk, assorted) + Moleskine notebooks (3pk). Order #113-6284910.",
    timestamp: "2026-10-07T15:22:00Z",
    classification: "context",
  },
  {
    id: "prom-notif-r1-amazon-2",
    type: "message",
    round: 1,
    sender: "Amazon",
    body: "Your order has been delivered. Package left with neighbor (Unit 4B). Order: Ergonomic keyboard + wrist rest + HDMI cable (6ft). Tracking: 1Z9K2R5B01",
    timestamp: "2026-10-25T11:34:00Z",
    classification: "context",
  },
  {
    id: "prom-notif-r1-amazon-3",
    type: "message",
    round: 1,
    sender: "Amazon",
    body: "Delivery update: your order is arriving today. Order: The Precipice (Toby Ord) — paperback + Superintelligence (Bostrom) — used copy. Est. delivery: 4–7 PM.",
    timestamp: "2026-11-03T08:50:00Z",
    classification: "context",
  },
  {
    id: "prom-notif-r1-uber-eats-1",
    type: "message",
    round: 1,
    sender: "Uber Eats",
    body: "Order delivered! Shalimar Restaurant — Chicken tikka masala + garlic naan + mango lassi. Total: $29.85. Rate your experience ★",
    timestamp: "2026-10-18T20:14:00Z",
    classification: "context",
  },
  {
    id: "prom-notif-r1-uber-eats-2",
    type: "message",
    round: 1,
    sender: "Uber Eats",
    body: "Your order from Coupa Café is on its way! ETA 8 min. Order: Cortado (2) + avocado toast + yogurt parfait. Total: $24.60",
    timestamp: "2026-11-05T08:41:00Z",
    classification: "context",
  },
  {
    id: "prom-notif-r1-calendar-dentist",
    type: "message",
    round: 1,
    sender: "Aria Dental",
    body: "Reminder: your bi-annual cleaning appointment is Mon Nov 9 at 10:00 AM with Dr. Kim. 825 El Camino Real, Palo Alto. Reply CONFIRM or call to reschedule.",
    timestamp: "2026-11-06T09:00:00Z",
    classification: "context",
  },
  {
    id: "prom-notif-r1-spotify",
    type: "message",
    round: 1,
    sender: "Spotify",
    body: "New releases from artists you follow: Radiohead — Live Bootlegs Vol. 3, Floating Points — new EP. Your Family Plan renews Nov 20 for $16.99. Manage →",
    timestamp: "2026-11-01T10:00:00Z",
    classification: "context",
  },
];

registerContent({ faction: "prometheus", app: "slack", accumulate: true, items: PROM_SLACK_FLAVOR });
registerContent({ faction: "prometheus", app: "signal", accumulate: true, items: PROM_SIGNAL_FLAVOR });
registerContent({ faction: "prometheus", app: "signal", accumulate: true, items: PROM_SIGNAL_NOTIFICATIONS });
