import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const PROM_NEWS: ContentItem[] = [
    {
      id: "tut-prom-news-1",
      type: "headline",
      round: 0,
      sender: "Reuters",
      subject: "[TUTORIAL] Sample Headline: AI Safety Lab Releases Report",
      body: "Practice headlines will appear here. In the real game, news reflects the public narrative around AI — which you shape through safety reports, incident disclosures, and when you choose to go public with findings.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r3-news-1",
      type: "headline",
      round: 3,
      subject: "WSJ: OpenBrain Faces Government Scrutiny Amid AI Deployment Concerns",
      body: "OpenBrain, the leading US AI lab, is facing scrutiny from multiple government agencies following unspecified concerns about its latest AI deployment. The company has declined to comment. Prometheus AI, OpenBrain's closest competitor, saw its private market valuation rise 12% on secondary markets amid the news, as investors speculated about a potential shift in the competitive landscape.",
      timestamp: "2027-07-07T19:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r5-news-1",
      type: "headline",
      round: 5,
      body: "ANALYSIS: 'Why Prometheus May Be The Lab That Saves Us' — The Atlantic Profile of James Park",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "context",
      condition: { variable: "publicSentiment", operator: "gt", value: 20 },
    },
    {
      id: "prom-r5-news-2",
      type: "headline",
      round: 5,
      body: "BREAKING: Prometheus In 'Advanced Talks' With Government On Exclusive Partnership — Sources Confirm Offer On Table",
      timestamp: "2028-02-01T09:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-news-3",
      type: "headline",
      round: 5,
      body: "PROMETHEUS PUBLISHES ALIGNMENT FRAMEWORK — Independent Researchers: 'Best Available Method' But Questions Remain About Scalability",
      timestamp: "2028-02-01T11:00:00Z",
      classification: "context",
    },
    // --- UNCONDITIONAL ROUND 1 ITEMS ---
    {
      id: "prom-r1-news-1",
      type: "headline",
      round: 1,
      sender: "Science",
      subject: "Safety-First Lab Publishes Comprehensive Alignment Evaluation Framework",
      body: "Prometheus AI has released a detailed technical framework for evaluating alignment in large language models, drawing broad attention from the AI safety research community. The publication describes a suite of behavioral tests, interpretability probes, and red-teaming protocols intended to detect misaligned goals before deployment. Independent researchers called the methodology 'the most rigorous publicly available framework to date.' OpenBrain declined to comment on whether it uses comparable evaluation standards.",
      timestamp: "2026-11-03T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r1-news-2",
      type: "headline",
      round: 1,
      sender: "The Atlantic",
      subject: "The Race to Build AGI Has a Safety Problem No One Wants to Talk About",
      body: "Dr. Ifeoma Eze's new essay argues that AI safety work is being systematically deprioritized across the industry — not through malice, but through incentive structures that reward deployment speed above all else. 'Labs that publish safety research get credit for the optics. Labs that delay deployment based on it get punished by investors,' she writes. Eze, who is not affiliated with any AI lab, points to the consistent pattern of safety teams being understaffed relative to capabilities teams. 'The bottleneck is not knowledge. It is will.'",
      timestamp: "2026-11-07T08:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r1-news-3",
      type: "headline",
      round: 1,
      sender: "The Verge",
      subject: "Why OpenBrain Is Everywhere and Prometheus Is Quiet",
      body: "OpenBrain's communications team has become one of the most active in tech: podcast appearances, congressional testimony, press access, and a seemingly endless stream of capability demonstrations. Prometheus, by contrast, rarely speaks publicly. Their last significant media appearance was a Nature paper six months ago. The contrast has not gone unnoticed inside either lab. 'You can do safety work or you can perform safety work,' one Prometheus researcher said, asking not to be named. 'We're trying to do it.' Critics say the strategy is a mistake — that in a field where narrative matters, silence cedes ground.",
      timestamp: "2026-11-10T10:00:00Z",
      classification: "context",
    },
    // --- AMBIENT CONDITION-GATED ITEMS ---
    {
      id: "prom-r1-news-ambient-regulatory-1",
      type: "headline",
      round: 1,
      subject: "Wired: The Lab That Keeps Saying No",
      body: "Prometheus AI has declined to accelerate deployment of its latest model pending completion of safety evaluations — again. Critics call it strategic delay. Supporters call it the only responsible approach. Either way, it's becoming a pattern that's hard to ignore in a field where speed is the primary currency.",
      timestamp: "2026-11-10T08:00:00Z",
      classification: "context",
      condition: { variable: "regulatoryPressure", operator: "gt", value: 45 },
    },
    {
      id: "prom-r1-news-ambient-gap-1",
      type: "headline",
      round: 1,
      subject: "TechCrunch: The Safety-Speed Tradeoff Is Real, and Prometheus Is Living It",
      body: "As OpenBrain's Agent-1 benchmarks continue to impress, Prometheus's careful approach is increasingly seen as a liability by investors. 'They're doing everything right,' one VC told us. 'That might be the problem.'",
      timestamp: "2026-11-14T09:00:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "gt", value: 4 },
    },
    {
      id: "prom-r2-news-ambient-open-source-1",
      type: "headline",
      round: 2,
      subject: "MIT Tech Review: Prometheus's Open-Source Bet Is Paying Off — In Reputation If Not Revenue",
      body: "Prometheus-7B has accumulated 500,000 daily downloads and spawned dozens of independent safety research projects. The company isn't monetizing this directly. But the brand equity among AI researchers is now arguably more valuable than any enterprise contract.",
      timestamp: "2027-03-08T10:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "prom-r2-news-ambient-talent-1",
      type: "headline",
      round: 2,
      subject: "Bloomberg: AI Talent War Claims Another Victim — This Time It's the Good Guys",
      body: "Prometheus AI, the self-styled 'safety-first' AI lab, has lost several senior engineers to OpenBrain in recent months. Sources say the departures reflect a growing frustration that principled caution is incompatible with building systems that matter. Prometheus disputes this characterization.",
      timestamp: "2027-02-25T11:00:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "lt", value: 50 },
    },
    {
      id: "prom-r3-news-ambient-awareness-1",
      type: "headline",
      round: 3,
      subject: "NYT: 'Prometheus Was Right' — AI Safety Community Faces a Grim Vindication",
      body: "For years, Prometheus AI warned that the race to build increasingly powerful AI systems was outpacing our ability to verify their safety. As concerns mount about OpenBrain's Agent-4, those warnings look prescient — a fact that brings the safety lab no joy. 'Being right about this is the worst possible outcome,' one Prometheus researcher told the Times.",
      timestamp: "2027-07-09T07:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "prom-r3-news-ambient-intl-1",
      type: "headline",
      round: 3,
      subject: "Financial Times: Europe Turns to Prometheus as AI Safety Standard-Setter",
      body: "The European Union AI Office has begun informal consultations with Prometheus AI about adopting its safety evaluation methodology as the basis for EU frontier AI regulation. The move would give the California-based lab significant influence over AI policy in the world's largest regulatory bloc.",
      timestamp: "2027-07-11T08:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "prom-r4-news-ambient-breakthrough-1",
      type: "headline",
      round: 4,
      subject: "Science: Prometheus Claims Unprecedented Alignment Verification Breakthrough",
      body: "Prometheus AI researchers report achieving 91% mechanistic interpretability coverage on their frontier model — a level of behavioral transparency that no other lab has publicly demonstrated. Independent researchers are cautious but intrigued. 'If this holds up under scrutiny, it changes the safety calculus entirely,' said one external reviewer.",
      timestamp: "2027-11-08T09:00:00Z",
      classification: "context",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 80 },
    },
    {
      id: "prom-r4-news-ambient-market-1",
      type: "headline",
      round: 4,
      subject: "Wall Street Journal: Prometheus Valuation Dips as Investors Weigh Safety vs. Commercial Path",
      body: "Prometheus AI's secondary market valuation fell 11% this week as investors grew uncertain about the company's commercial future amid discussions about a government safety auditor designation. Some see the role as a validation. Others see it as a dead end. 'It's very hard to build a business when your job is to slow down the business,' one analyst said.",
      timestamp: "2027-11-10T08:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },
];

registerContent({ faction: "prometheus", app: "news", accumulate: false, items: PROM_NEWS });
