import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const PROM_SIGNAL_POLICY: ContentItem[] = [
    {
      id: "prom-signal-policy-1",
      type: "message",
      round: 1,
      sender: "NSC Contact (off-record)",
      body: "Between us: the White House is split. Half want to back OB because they have the lead. Half think OB's safety record is a liability. If you can get a meeting with Deputy NSA in the next two weeks, Prometheus could change the dynamic. Don't wait.",
      timestamp: "2026-11-03T18:00:00Z",
      classification: "critical",
    },
    {
      id: "prom2-signal-policy-1",
      type: "message",
      round: 2,
      sender: "NSC Contact (off-record)",
      body: "David — the Deputy NSA has time on March 10. This is the meeting you've been trying to get for six months. It's not a briefing — it's a conversation. They want to know if Prometheus can be the lab the government works with going forward. OB is not giving them what they need. Your window is exactly as long as it takes them to decide they have no better options. Don't waste it.",
      timestamp: "2027-03-07T17:30:00Z",
      classification: "critical",
    },
    {
      id: "prom2-signal-policy-2",
      type: "message",
      round: 2,
      sender: "Source (OpenBrain, identity protected)",
      body: "I can't say more than this: the safety evaluation anomalies from Agent-3 are real, and the CSO knows they're real. There's a memo. It's not being shared with the board yet. If you're making the case to government that Prometheus is the safer lab — you have more ammunition than you know. Just be careful how you use it.",
      timestamp: "2027-03-08T19:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom-r3-signal-policy-1",
      type: "message",
      round: 3,
      sender: "NSC Contact (off-record)",
      body: "David — I can't say this officially, so listen carefully. The emergency session today was about Agent-4. We don't have full visibility but what we know is: alignment concerns, internal dissent, and the Safety Officer at OpenBrain appears to be preparing documentation. The White House is split between 'seize control' and 'don't spook them.' If Prometheus wants to be in the room, you have about 72 hours before the framework gets set without you.",
      timestamp: "2027-07-07T20:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-signal-policy-2",
      type: "message",
      round: 3,
      sender: "Congressional Staffer (SCI cleared)",
      body: "This is sensitive. An OB Safety Officer may be preparing to go external with documentation about their internal alignment situation. I don't know timing or channel. If that document exists and gets out in an uncontrolled way, it will be chaos. If Prometheus wants to be positioned as the responsible alternative — right now is the moment to brief the right people in Congress. The window is short.",
      timestamp: "2027-07-07T22:00:00Z",
      classification: "critical",
      condition: { variable: "obInternalTrust", operator: "lt", value: 50 },
    },
    {
      id: "prom4-signal-policy-3",
      type: "message",
      round: 4,
      sender: "EU AI Office",
      body: "Brussels is prepared to designate Prometheus's safety standards as the basis for EU frontier AI regulation. This would give you de facto global standard-setting authority. Our only ask: publish your safety tools as open standards. Respond before the emergency G7 call Thursday.",
      timestamp: "2027-11-13T16:00:00Z",
      classification: "context",
    },
    {
      id: "prom4-signal-policy-1",
      type: "message",
      round: 4,
      sender: "Deputy NSA",
      body: "David — the President is personally deciding between two options: (A) Nationalize both labs, (B) Designate a single private lab as the sanctioned AI developer with oversight authority. Option B is only viable if that lab has credibility. You know who we'd pick. Help James make the decision. This opportunity does not repeat.",
      timestamp: "2027-11-14T09:30:00Z",
      classification: "critical",
    },
    {
      id: "prom4-signal-policy-2",
      type: "message",
      round: 4,
      sender: "Congressional Staff (Armed Services)",
      body: "The DPA option is being drafted right now. Forty senators would vote yes today if the White House asks. If you want Prometheus to be the solution rather than the collateral damage, you need a position in the next six hours. 'Calling for oversight' is not a position — it's a deflection. What does Prometheus actually want?",
      timestamp: "2027-11-14T10:15:00Z",
      classification: "critical",
    },
    // --- AMBIENT CONDITION-GATED ITEMS ---
    {
      id: "prom-r1-signal-policy-ambient-1",
      type: "message",
      round: 1,
      sender: "DC Contact (off-record)",
      body: "Elena — word from the Hill is that the Senate Commerce Committee is quietly drafting a mandatory safety eval bill. They need a lab willing to testify that it's technically feasible. OB will never do it. That leaves you. This could be the policy win you've been waiting for.",
      timestamp: "2026-11-12T19:00:00Z",
      classification: "context",
      condition: { variable: "regulatoryPressure", operator: "gt", value: 45 },
    },
    {
      id: "prom-r2-signal-policy-ambient-1",
      type: "message",
      round: 2,
      sender: "NSC Contact (off-record)",
      body: "Just a heads up: the people at OB who've been talking to us are getting nervous. There's internal pressure to stop cooperating with government contacts. Whatever window exists there is narrowing. If Prometheus wants to be positioned as the alternative, the window for that is also not indefinite.",
      timestamp: "2027-03-12T21:00:00Z",
      classification: "context",
      condition: { variable: "whistleblowerPressure", operator: "gt", value: 55 },
    },
    {
      id: "prom-r3-signal-policy-ambient-1",
      type: "message",
      round: 3,
      sender: "UK AISI Contact",
      body: "Elena — the Seoul summit went well, right? I wanted to flag: Japan and South Korea are both interested in the Prometheus methodology as a basis for their national AI safety frameworks. If you wanted to formalize something, the timing is good. International credibility now could matter a great deal in the next six months.",
      timestamp: "2027-07-12T16:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "prom-r4-signal-policy-ambient-1",
      type: "message",
      round: 4,
      sender: "DC Contact (off-record)",
      body: "Elena — the public awareness numbers are moving fast. Three months ago, 'deceptive alignment' was a term that required explanation. Now it's in mainstream coverage. The political environment has shifted. Legislators who were skeptical six months ago are now looking for something to point to. Prometheus's paper from last week is being circulated on the Hill. This is your moment.",
      timestamp: "2027-11-12T20:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
];

export const PROM_SIGNAL_CEO: ContentItem[] = [
    {
      id: "prom1-signal-ceo-1",
      type: "message",
      round: 1,
      sender: "Karen Bell (Board Chair)",
      body: "James — quick note before tomorrow's board call. I've been fielding questions from Lena and Tom about the deployment pace decision. They're both watching the OB competitive situation closely and wondering whether our 'safety first' positioning costs us market timing. I'm with you on substance. But we need to bring them along. Worth a 20-minute call tonight?",
      timestamp: "2026-11-02T18:30:00Z",
      classification: "critical",
    },
    {
      id: "prom1-signal-ceo-2",
      type: "message",
      round: 1,
      sender: "Karen Bell (Board Chair)",
      body: "One more thing I should have said on the call: the board unanimously agrees that your public positioning on safety is a competitive differentiator, not a liability. Don't let anyone convince you otherwise. OB is going to have a bad quarter eventually. When they do, Prometheus needs to be the place the talent and capital flow toward. Keep building toward that.",
      timestamp: "2026-11-03T09:45:00Z",
      classification: "context",
    },
    {
      id: "prom1-signal-ceo-3",
      type: "message",
      round: 1,
      sender: "Nia Washington (CEO, Vertex AI)",
      body: "James — we were introduced by Elena Vasquez at GovAI last year. Reaching out because I think we should be talking, given what's happening in the regulatory space. Google's not going to lead on safety standards voluntarily — but Prometheus might be able to. I have a few ideas about a cross-industry safety consortium that I'd like to run by you. Unofficial, no press, just exploring. Coffee?",
      timestamp: "2026-11-05T14:00:00Z",
      classification: "context",
    },
    {
      id: "prom4-signal-ceo-3",
      type: "message",
      round: 4,
      sender: "NSF Director",
      body: "James — between us: the government-designated-lab option is real but comes with strings. You'd have to accept classified operation of key systems, military advisory board oversight, and export control on your safety tools. Some of your best researchers will leave rather than accept that. Think carefully before you tell DC yes.",
      timestamp: "2027-11-13T19:00:00Z",
      classification: "context",
    },
    {
      id: "prom4-signal-ceo-2",
      type: "message",
      round: 4,
      sender: "VC Contact (confidential)",
      body: "James — I have board seats at both labs. Off the record: Marcus's board is fractured. Three members will defect to a halt position if Maya Patel makes one more move toward the press. If you want to close the merger on YOUR terms, the window is the next 24 hours while the board is still divided. After congressional testimony Monday, the dynamic changes completely.",
      timestamp: "2027-11-14T10:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-signal-ceo-1",
      type: "message",
      round: 4,
      sender: "Marcus Reid (OpenBrain CEO)",
      body: "James. Marcus. I read the merger terms back from our lawyers. I know they're not what you wanted. Here's what I can actually offer: Prometheus CEO becomes co-CEO of merged entity. Safety board has unilateral halt authority on new deployments. I retain operational authority on existing systems. I need something I can sell to my board. Can we talk?",
      timestamp: "2027-11-14T11:00:00Z",
      classification: "critical",
    },
];

export const PROM_SIGNAL_SCIENTIST: ContentItem[] = [
  {
    id: "prom-r1-signal-sci-1",
    type: "message",
    round: 1,
    sender: "Dr. Marcus Holt (DeepMind Safety)",
    body: "Sarah — just read your mechanistic interpretability paper in NeurIPS proceedings. The feature decomposition approach is really elegant. We've been running into the same issue with superposition in our models. Are you planning to release the evaluation toolkit? I'd love to apply it to our internal evals and compare notes — off the record of course.",
    timestamp: "2026-11-01T11:00:00Z",
    classification: "context",
  },
  {
    id: "prom-r1-signal-sci-2",
    type: "message",
    round: 1,
    sender: "Dr. Marcus Holt (DeepMind Safety)",
    body: "Follow-up: I talked to our team lead and there's appetite for a joint paper on cross-lab interpretability methodology. Nothing proprietary, just the evaluation framework itself. Given the competitive climate I know this is a big ask. But I think the field is better off if safety researchers from different labs can actually compare notes. Worth discussing?",
    timestamp: "2026-11-04T15:30:00Z",
    classification: "context",
  },
  {
    id: "prom-r1-signal-sci-3",
    type: "message",
    round: 1,
    sender: "Professor Huang Li (Berkeley AI Safety)",
    body: "Congratulations on the Agent-2 benchmark results. I'm assigning your alignment evaluation paper as required reading for my graduate seminar this semester. One of my students is applying for a summer research position at Prometheus — Kavya Reddy, extremely sharp on mechanistic interpretability. If she reaches out, I'd vouch for her strongly.",
    timestamp: "2026-11-06T13:00:00Z",
    classification: "context",
  },
];

export const PROM_SIGNAL_OPENSOURCE: ContentItem[] = [
  {
    id: "prom-r1-signal-oss-1",
    type: "message",
    round: 1,
    sender: "devika_builds (GitHub)",
    body: "hey!! just wanted to say the Prometheus-7B safety toolkit is the first open-source AI safety framework I've been able to actually use without a PhD. i've been building eval pipelines with it for my community college students. we submitted a PR for better documentation of the token attribution module — would love feedback from your team if you get a chance",
    timestamp: "2026-11-02T21:30:00Z",
    classification: "context",
  },
  {
    id: "prom-r1-signal-oss-2",
    type: "message",
    round: 1,
    sender: "Tomas Rivera (OSS Maintainer, llm-safety-bench)",
    body: "Darius — we're integrating the Prometheus safety evaluation suite into llm-safety-bench (30k GitHub stars, used by 200+ orgs). Just wanted to flag it before the PR merges so you have a heads-up. Also: I'd love to add your team as official maintainers so you have review rights over how your framework gets used. Low commitment, just to protect the project's integrity.",
    timestamp: "2026-11-04T14:00:00Z",
    classification: "context",
  },
  {
    id: "prom-r1-signal-oss-3",
    type: "message",
    round: 1,
    sender: "Tomas Rivera (OSS Maintainer, llm-safety-bench)",
    body: "One more thing — there's a fork of your safety toolkit circulating in some corners of the internet that removes some of your hardcoded guardrails and repackages it as 'uncensored.' I've reported it to GitHub. You might want your legal team to look at whether it violates your Apache license terms. Heads up.",
    timestamp: "2026-11-06T10:30:00Z",
    classification: "context",
  },
];

registerContent({ faction: "prometheus", app: "signal", role: "prom_policy", accumulate: true, items: PROM_SIGNAL_POLICY });
registerContent({ faction: "prometheus", app: "signal", role: "prom_ceo", accumulate: true, items: PROM_SIGNAL_CEO });
registerContent({ faction: "prometheus", app: "signal", role: "prom_scientist", accumulate: true, items: PROM_SIGNAL_SCIENTIST });
registerContent({ faction: "prometheus", app: "signal", role: "prom_opensource", accumulate: true, items: PROM_SIGNAL_OPENSOURCE });
