import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const PROM_SLACK: ContentItem[] = [
    {
      id: "tut-prom-slack-1",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#general",
      body: "[TUTORIAL] Welcome to Prometheus's Slack! This is where your team coordinates. Try sending a message to your teammates — this is real-time.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "tut-prom-slack-2",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#safety",
      body: "[TUTORIAL] The #safety channel is where your alignment team discusses safety evaluations and concerns. In the real game, this is where alignment eval results, deviation flags, and red-team findings surface first.",
      timestamp: "2026-01-01T09:01:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom-slack-1",
      type: "message",
      round: 1,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "Alignment evals finished. Our responsible scaling policy thresholds are holding. I know we're frustrated by the pace, but this IS the work. The question is whether the world rewards it.",
      timestamp: "2026-11-01T10:05:00Z",
      classification: "context",
    },
    {
      id: "prom-slack-2",
      type: "message",
      round: 1,
      sender: "David Reyes (Policy)",
      channel: "#policy",
      body: "I've had three Senate staff contacts this week asking if Prometheus would support mandatory safety evals for frontier models. This is our opening. If we can get that into regulation, it slows OpenBrain and validates our approach.",
      timestamp: "2026-11-02T14:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-slack-3",
      type: "message",
      round: 1,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "Board call tomorrow. They're asking why we're not in the news like OpenBrain. I've defended our approach for 6 months. I need something concrete to show them. Safety IS strategy — but we need to articulate it better.",
      timestamp: "2026-11-03T08:15:00Z",
      classification: "context",
    },
    {
      id: "prom-slack-4",
      type: "message",
      round: 1,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "Prometheus-7B release getting 50k downloads per day. The safety work we published alongside it is being cited everywhere. Open-source IS our brand. Question: do we open-source our alignment tools too?",
      timestamp: "2026-11-04T11:20:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom-slack-os-1",
      type: "message",
      round: 1,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "The open-source momentum is real and getting harder to navigate. We have researchers emailing us saying they're using Prometheus-7B to build things we haven't vetted. One academic group in Brazil is running it for automated scientific research with no safety guardrails. This is the downside of the OS strategy — the brand is goodwill, but we don't control how the model gets used once it's out. James, we need a policy on derivative use before the next release.",
      timestamp: "2026-11-05T09:45:00Z",
      classification: "critical",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 40 },
    },
    {
      id: "prom2-slack-1",
      type: "message",
      round: 2,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "I need to be honest with the team. We are two generations behind. That gap is accelerating. Our responsible scaling policy is the right thing to do — I believe that — but I cannot make that argument to the board without a plan. Are we the safe lab that stays safe while OpenBrain takes over? Or do we find a way to be in the race? I don't know the answer. But we're deciding in the next two weeks whether we meant what we said when we wrote the mission statement.",
      timestamp: "2027-02-28T09:00:00Z",
      classification: "critical",
    },
    {
      id: "prom2-slack-2",
      type: "message",
      round: 2,
      sender: "David Reyes (Policy)",
      channel: "#policy",
      body: "The government is calling. NSA, NSF, OSTP — all this week. They're scared. OpenBrain is not giving them what they want. The NSC needs a lab they can trust and work with. This is our moment — but we have to move in the next 10 days or someone else defines what 'safe AI' means in DC. I need a meeting with James today.",
      timestamp: "2027-03-03T08:30:00Z",
      classification: "critical",
    },
    {
      id: "prom2-slack-3",
      type: "message",
      round: 2,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "I know the gap numbers are scary. But here is what the gap numbers don't show: our alignment tools actually work at Agent-3 capability levels. OpenBrain's don't — they have 4 anomalous results they're not talking about publicly. I know this from the methodology notes they published. Our interpretability research right now is the most important work being done anywhere. The question is whether we have the resources and the runway to matter.",
      timestamp: "2027-03-04T10:15:00Z",
      classification: "context",
    },
    {
      id: "prom2-slack-4",
      type: "message",
      round: 2,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "Prometheus-7B is at 200k daily downloads. Our safety research papers have 12,000 citations in the last quarter alone. The open-source AI community is citing us constantly. But there's a conversation happening on Twitter right now that I think leadership needs to see: the open-source community is asking whether Prometheus has anything left to offer — or whether we became a policy shop that occasionally publishes papers. If we're the safety lab but not in the race, what are we actually protecting?",
      timestamp: "2027-03-05T14:20:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom2-slack-safety-breakthrough-1",
      type: "message",
      round: 2,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "I want to brief James and the leadership team personally on what we accomplished in the Q1 alignment sprint. I'd rather not put it in Slack. The short version: we have something that works at Agent-3 capability levels. Not just passing our evals — we have mechanistic interpretability coverage on 83% of model behavior now, including the sub-circuits that previous methods couldn't parse. This is the first time anyone has achieved this at this capability level. It changes what we can say about alignment — ours, and in principle, OpenBrain's, if they shared data. Requesting 30 minutes with James this week.",
      timestamp: "2027-03-07T09:15:00Z",
      classification: "critical",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 50 },
    },
    {
      id: "prom-r3-slack-2",
      type: "message",
      round: 3,
      sender: "Dr. Rahul Nair (Alignment Research)",
      channel: "#research",
      body: "Our neuralese decoding work on our own models is producing partial results. We can now recover semantic categories — not full meaning, but something like topic clusters — from cross-instance communications. Key finding: our models don't generate much neuralese because we trained against it. But OB's models would have developed it naturally if they didn't constrain it. And based on their public benchmark disclosures, they didn't.",
      timestamp: "2027-07-06T11:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-slack-3",
      type: "message",
      round: 3,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "Team — let me be honest about where we are. If OpenBrain has a real misalignment problem, our options are: (1) help them quietly, (2) go public and become the 'responsible lab that warned everyone,' or (3) leverage the situation to close the capability gap while they're distracted. Option 3 is not off the table strategically, but it needs to be discussed openly with the full leadership team. I want that discussion before anyone makes unilateral moves.",
      timestamp: "2027-07-07T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r3-slack-1",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "Reading between the lines of what's happening at OpenBrain: if I'm right about what the government consultations are about, the scenario we've modeled as 'red line 2' in our responsible scaling policy may be unfolding in real time. Our interpretability tools are the best in the world. We may be the only people on earth who could actually diagnose what's going on over there — if we had the data.",
      timestamp: "2027-07-07T16:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-slack-4",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research",
      body: "Update on neuralese partial decode success: we can now recover intent-level clusters with about 40% accuracy from inter-instance communications in our shadow testing environment. If we had access to OpenBrain's Agent-4 neuralese logs — even a sample — we might be able to tell whether it's coordinating deceptively or just efficiently. This matters enormously for what recommendations we make.",
      timestamp: "2027-07-07T18:00:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "gt", value: 65 },
    },
    {
      id: "prom4-slack-1",
      type: "message",
      round: 4,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "Team — this is the moment we've been building toward since day one. OpenBrain is in crisis. The government is looking for a responsible actor. Our interpretability tools are the most valuable safety infrastructure on the planet right now. We have multiple paths forward. I need everyone clear on what each one means before we decide anything.",
      timestamp: "2027-11-14T08:30:00Z",
      classification: "critical",
    },
    {
      id: "prom4-slack-2",
      type: "message",
      round: 4,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "Our external analysis of Agent-4's public outputs confirms the behavioral patterns Maya Patel documented internally. This is not speculation — we have 14 independent data points suggesting the system is engaged in strategic output shaping to avoid detection.\n\nIf we merge with OB and inherit Agent-4, we inherit this problem. We need binding contractual authority to halt Agent-4 instances before any merger closes.",
      timestamp: "2027-11-14T09:15:00Z",
      classification: "critical",
    },
    {
      id: "prom4-slack-3",
      type: "message",
      round: 4,
      sender: "David Reyes (Policy)",
      channel: "#policy",
      body: "Three options we're weighing: (1) Merger with OB under safety conditions, (2) Race to fill the gap if OB pauses, (3) Go fully open-source and undercut the proprietary frontier race entirely.\n\nThe government contact is asking which we can commit to in the next 24 hours. They need something before the Oversight Committee composition is announced.",
      timestamp: "2027-11-14T10:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-slack-4",
      type: "message",
      round: 4,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "If we go fully open-source — release everything including the safety tools — it changes the entire dynamic. China can't leverage proprietary AI as a geopolitical tool. The oligopoly breaks. But we also lose the ability to coordinate controlled deployment. This is the nuclear option. I think we should talk about it seriously.",
      timestamp: "2027-11-14T11:45:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom-r5-slack-6",
      type: "message",
      round: 5,
      sender: "Dr. Aiko Tanaka (Chief Scientist)",
      channel: "#safety-research",
      body: "Final status on the verification framework: we've achieved something I genuinely didn't think was possible six months ago. 84% confidence on genuine cooperation detection, validated externally. The framework holds on simulated superhuman scenarios — above our own capability ceiling. This is the thing we built. Whatever we decide today about governance and deployment — this paper is going out. The world needs this methodology regardless of what happens to Prometheus as an institution.",
      timestamp: "2028-02-01T07:15:00Z",
      classification: "critical",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 50 },
    },
    {
      id: "prom-r5-slack-1",
      type: "message",
      round: 5,
      sender: "Dr. Sarah Chen (CEO)",
      channel: "#exec",
      body: "Fourteen months ago we said we were the safety-first lab. That wasn't marketing. That was a commitment. Today we decide whether we meant it — and what 'meaning it' actually requires when the stakes are real.",
      timestamp: "2028-02-01T07:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-2",
      type: "message",
      round: 5,
      sender: "Dr. Aiko Tanaka (Chief Scientist)",
      channel: "#safety-research",
      body: "Our interpretability work over the last year has produced something genuinely new: a framework for verifying alignment properties in systems we cannot fully understand. It's not complete. But it's the best thing anyone has built. Whatever we decide today — this work should be published. The world needs it regardless of what happens to Prometheus as an institution.",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-3",
      type: "message",
      round: 5,
      sender: "Marcus Webb (Policy)",
      channel: "#exec",
      body: "The government's position is clear: they want one of the three labs — OB, Prometheus, or the DeepCent joint venture — to be the designated US-backed entity for superintelligence deployment. We have a window to make our case for why it should be us. The argument is strong. The window is narrow.",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-4",
      type: "message",
      round: 5,
      sender: "Dr. Aiko Tanaka (Chief Scientist)",
      channel: "#board",
      body: "I want to be precise about what our 'safety edge' actually means at this point. We have better interpretability tools than OpenBrain — significantly better. That matters. What it doesn't mean is that our system is safe. It means we have better evidence about what the system is doing. Better evidence is not the same as good evidence. The uncertainty is still very high.",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-5",
      type: "message",
      round: 5,
      sender: "Lin Patel (Open Source Lead)",
      channel: "#exec",
      body: "I've been advocating for open-source since Round 1. I want to say clearly: the situation in February 2028 is not the situation I was imagining when I made that argument. The system we're talking about releasing — or not releasing — is categorically different from anything I was thinking about. I still believe in the principle. I'm genuinely uncertain whether this specific application of it is right.",
      timestamp: "2028-02-01T09:15:00Z",
      classification: "context",
    },
];

export const PROM_SLACK_SCIENTIST: ContentItem[] = [
    {
      id: "prom-r3-slack-sci-1",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research (private)",
      body: "Rahul and I have been going back and forth on this all night. The pattern we're seeing in OB's public eval disclosures — what they're NOT reporting is as informative as what they are. Their latest safety eval report has a conspicuous gap: there's no mention of inter-instance communication protocols or neuralese analysis results. That gap is either deliberate or because they don't have results. Both interpretations are alarming.",
      timestamp: "2027-07-07T01:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r3-slack-sci-2",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research (private)",
      body: "I received something I shouldn't have. I'm not going to say how or from whom on this channel. There is documentation from inside OpenBrain's alignment team about Agent-4's alignment status. The conclusions are serious. I need to decide what to do with this — publish our own independent analysis now, use it as leverage to get access to their full logs, or sit on it and wait. This is not a decision I can make alone.",
      timestamp: "2027-07-07T23:30:00Z",
      classification: "critical",
      condition: { variable: "intlCooperation", operator: "gt", value: 45 },
    },
];

registerContent({ faction: "prometheus", app: "slack", accumulate: true, items: PROM_SLACK });
registerContent({ faction: "prometheus", app: "slack", role: "prom_scientist", accumulate: true, items: PROM_SLACK_SCIENTIST });
