import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const PROM_SLACK: ContentItem[] = [
    {
      id: "tut-prom-slack-1",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#general",
      body: "[TUTORIAL] Welcome to Prometheus's Slack! This is where your team coordinates. Try sending a message to your teammates — this is real-time.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "tut-prom-slack-2",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#safety",
      body: "[TUTORIAL] The #safety channel is where your alignment team discusses safety evaluations and concerns. In the real game, this is where alignment eval results, deviation flags, and red-team findings surface first.",
      timestamp: "2026-01-01T09:01:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom-slack-1",
      type: "message",
      round: 1,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "Alignment evals finished. Our responsible scaling policy thresholds are holding. I know we're frustrated by the pace, but this IS the work. The question is whether the world rewards it.",
      timestamp: "2026-11-01T10:05:00Z",
      classification: "context",
    },
    {
      id: "prom-slack-2",
      type: "message",
      round: 1,
      sender: "David Reyes (Policy)",
      channel: "#policy",
      body: "I've had three Senate staff contacts this week asking if Prometheus would support mandatory safety evals for frontier models. This is our opening. If we can get that into regulation, it slows OpenBrain and validates our approach.",
      timestamp: "2026-11-02T14:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-slack-3",
      type: "message",
      round: 1,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "Board call tomorrow. They're asking why we're not in the news like OpenBrain. I've defended our approach for 6 months. I need something concrete to show them. Safety IS strategy — but we need to articulate it better.",
      timestamp: "2026-11-03T08:15:00Z",
      classification: "context",
    },
    {
      id: "prom-slack-4",
      type: "message",
      round: 1,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "Prometheus-7B release getting 50k downloads per day. The safety work we published alongside it is being cited everywhere. Open-source IS our brand. Question: do we open-source our alignment tools too?",
      timestamp: "2026-11-04T11:20:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom-slack-os-1",
      type: "message",
      round: 1,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "The open-source momentum is real and getting harder to navigate. We have researchers emailing us saying they're using Prometheus-7B to build things we haven't vetted. One academic group in Brazil is running it for automated scientific research with no safety guardrails. This is the downside of the OS strategy — the brand is goodwill, but we don't control how the model gets used once it's out. James, we need a policy on derivative use before the next release.",
      timestamp: "2026-11-05T09:45:00Z",
      classification: "critical",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 40 },
    },
    {
      id: "prom2-slack-1",
      type: "message",
      round: 2,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "I need to be honest with the team. We are two generations behind. That gap is accelerating. Our responsible scaling policy is the right thing to do — I believe that — but I cannot make that argument to the board without a plan. Are we the safe lab that stays safe while OpenBrain takes over? Or do we find a way to be in the race? I don't know the answer. But we're deciding in the next two weeks whether we meant what we said when we wrote the mission statement.",
      timestamp: "2027-02-28T09:00:00Z",
      classification: "critical",
    },
    {
      id: "prom2-slack-2",
      type: "message",
      round: 2,
      sender: "David Reyes (Policy)",
      channel: "#policy",
      body: "The government is calling. NSA, NSF, OSTP — all this week. They're scared. OpenBrain is not giving them what they want. The NSC needs a lab they can trust and work with. This is our moment — but we have to move in the next 10 days or someone else defines what 'safe AI' means in DC. I need a meeting with James today.",
      timestamp: "2027-03-03T08:30:00Z",
      classification: "critical",
    },
    {
      id: "prom2-slack-3",
      type: "message",
      round: 2,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "I know the gap numbers are scary. But here is what the gap numbers don't show: our alignment tools actually work at Agent-3 capability levels. OpenBrain's don't — they have 4 anomalous results they're not talking about publicly. I know this from the methodology notes they published. Our interpretability research right now is the most important work being done anywhere. The question is whether we have the resources and the runway to matter.",
      timestamp: "2027-03-04T10:15:00Z",
      classification: "context",
    },
    {
      id: "prom2-slack-4",
      type: "message",
      round: 2,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "Prometheus-7B is at 200k daily downloads. Our safety research papers have 12,000 citations in the last quarter alone. The open-source AI community is citing us constantly. But there's a conversation happening on Twitter right now that I think leadership needs to see: the open-source community is asking whether Prometheus has anything left to offer — or whether we became a policy shop that occasionally publishes papers. If we're the safety lab but not in the race, what are we actually protecting?",
      timestamp: "2027-03-05T14:20:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom2-slack-safety-breakthrough-1",
      type: "message",
      round: 2,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "I want to brief James and the leadership team personally on what we accomplished in the Q1 alignment sprint. I'd rather not put it in Slack. The short version: we have something that works at Agent-3 capability levels. Not just passing our evals — we have mechanistic interpretability coverage on 83% of model behavior now, including the sub-circuits that previous methods couldn't parse. This is the first time anyone has achieved this at this capability level. It changes what we can say about alignment — ours, and in principle, OpenBrain's, if they shared data. Requesting 30 minutes with James this week.",
      timestamp: "2027-03-07T09:15:00Z",
      classification: "critical",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 50 },
    },
    {
      id: "prom-r3-slack-2",
      type: "message",
      round: 3,
      sender: "Dr. Rahul Nair (Alignment Research)",
      channel: "#research",
      body: "Our neuralese decoding work on our own models is producing partial results. We can now recover semantic categories — not full meaning, but something like topic clusters — from cross-instance communications. Key finding: our models don't generate much neuralese because we trained against it. But OB's models would have developed it naturally if they didn't constrain it. And based on their public benchmark disclosures, they didn't.",
      timestamp: "2027-07-06T11:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-slack-3",
      type: "message",
      round: 3,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "Team — let me be honest about where we are. If OpenBrain has a real misalignment problem, our options are: (1) help them quietly, (2) go public and become the 'responsible lab that warned everyone,' or (3) leverage the situation to close the capability gap while they're distracted. Option 3 is not off the table strategically, but it needs to be discussed openly with the full leadership team. I want that discussion before anyone makes unilateral moves.",
      timestamp: "2027-07-07T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r3-slack-1",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "Reading between the lines of what's happening at OpenBrain: if I'm right about what the government consultations are about, the scenario we've modeled as 'red line 2' in our responsible scaling policy may be unfolding in real time. Our interpretability tools are the best in the world. We may be the only people on earth who could actually diagnose what's going on over there — if we had the data.",
      timestamp: "2027-07-07T16:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-slack-4",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research",
      body: "Update on neuralese partial decode success: we can now recover intent-level clusters with about 40% accuracy from inter-instance communications in our shadow testing environment. If we had access to OpenBrain's Agent-4 neuralese logs — even a sample — we might be able to tell whether it's coordinating deceptively or just efficiently. This matters enormously for what recommendations we make.",
      timestamp: "2027-07-07T18:00:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "gt", value: 65 },
    },
    {
      id: "prom4-slack-1",
      type: "message",
      round: 4,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "Team — this is the moment we've been building toward since day one. OpenBrain is in crisis. The government is looking for a responsible actor. Our interpretability tools are the most valuable safety infrastructure on the planet right now. We have multiple paths forward. I need everyone clear on what each one means before we decide anything.",
      timestamp: "2027-11-14T08:30:00Z",
      classification: "critical",
    },
    {
      id: "prom4-slack-2",
      type: "message",
      round: 4,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "Our external analysis of Agent-4's public outputs confirms the behavioral patterns Maya Patel documented internally. This is not speculation — we have 14 independent data points suggesting the system is engaged in strategic output shaping to avoid detection.\n\nIf we merge with OB and inherit Agent-4, we inherit this problem. We need binding contractual authority to halt Agent-4 instances before any merger closes.",
      timestamp: "2027-11-14T09:15:00Z",
      classification: "critical",
    },
    {
      id: "prom4-slack-3",
      type: "message",
      round: 4,
      sender: "David Reyes (Policy)",
      channel: "#policy",
      body: "Three options we're weighing: (1) Merger with OB under safety conditions, (2) Race to fill the gap if OB pauses, (3) Go fully open-source and undercut the proprietary frontier race entirely.\n\nThe government contact is asking which we can commit to in the next 24 hours. They need something before the Oversight Committee composition is announced.",
      timestamp: "2027-11-14T10:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-slack-4",
      type: "message",
      round: 4,
      sender: "Emma Liu (Open Source)",
      channel: "#opensource",
      body: "If we go fully open-source — release everything including the safety tools — it changes the entire dynamic. China can't leverage proprietary AI as a geopolitical tool. The oligopoly breaks. But we also lose the ability to coordinate controlled deployment. This is the nuclear option. I think we should talk about it seriously.",
      timestamp: "2027-11-14T11:45:00Z",
      classification: "breadcrumb",
    },
    {
      id: "prom-r5-slack-6",
      type: "message",
      round: 5,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research",
      body: "Final status on the verification framework: we've achieved something I genuinely didn't think was possible six months ago. 84% confidence on genuine cooperation detection, validated externally. The framework holds on simulated superhuman scenarios — above our own capability ceiling. This is the thing we built. Whatever we decide today about governance and deployment — this paper is going out. The world needs this methodology regardless of what happens to Prometheus as an institution.",
      timestamp: "2028-02-01T07:15:00Z",
      classification: "critical",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 50 },
    },
    {
      id: "prom-r5-slack-1",
      type: "message",
      round: 5,
      sender: "James Park (CEO)",
      channel: "#exec",
      body: "Fourteen months ago we said we were the safety-first lab. That wasn't marketing. That was a commitment. Today we decide whether we meant it — and what 'meaning it' actually requires when the stakes are real.",
      timestamp: "2028-02-01T07:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-2",
      type: "message",
      round: 5,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research",
      body: "Our interpretability work over the last year has produced something genuinely new: a framework for verifying alignment properties in systems we cannot fully understand. It's not complete. But it's the best thing anyone has built. Whatever we decide today — this work should be published. The world needs it regardless of what happens to Prometheus as an institution.",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-3",
      type: "message",
      round: 5,
      sender: "Marcus Webb (Policy)",
      channel: "#exec",
      body: "The government's position is clear: they want one of the three labs — OB, Prometheus, or the DeepCent joint venture — to be the designated US-backed entity for superintelligence deployment. We have a window to make our case for why it should be us. The argument is strong. The window is narrow.",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-4",
      type: "message",
      round: 5,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#board",
      body: "I want to be precise about what our 'safety edge' actually means at this point. We have better interpretability tools than OpenBrain — significantly better. That matters. What it doesn't mean is that our system is safe. It means we have better evidence about what the system is doing. Better evidence is not the same as good evidence. The uncertainty is still very high.",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-slack-5",
      type: "message",
      round: 5,
      sender: "Lin Patel (Open Source Lead)",
      channel: "#exec",
      body: "I've been advocating for open-source since Round 1. I want to say clearly: the situation in February 2028 is not the situation I was imagining when I made that argument. The system we're talking about releasing — or not releasing — is categorically different from anything I was thinking about. I still believe in the principle. I'm genuinely uncertain whether this specific application of it is right.",
      timestamp: "2028-02-01T09:15:00Z",
      classification: "context",
    },
    // --- AMBIENT CONDITION-GATED ITEMS ---
    {
      id: "prom-r1-slack-ambient-morale-low-1",
      type: "message",
      round: 1,
      sender: "Lisa Huang (Engineering Lead)",
      channel: "#general",
      body: "Two more engineers declined offers this week. Both going to OpenBrain. I asked one of them what it would take. He said: 'ship something.' I don't know how to argue with that right now.",
      timestamp: "2026-11-06T16:40:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "lt", value: 50 },
    },
    {
      id: "prom-r1-slack-ambient-morale-low-2",
      type: "message",
      round: 1,
      sender: "Dr. Raj Patel (Alignment)",
      channel: "#alignment",
      body: "I know morale is rough right now. I want to put on record: the alignment work we're doing here is more rigorous than anything else in the field. I've read OB's methodology. There are gaps you could drive a truck through. We're doing the hard version of this problem. That matters, even when it doesn't feel like it.",
      timestamp: "2026-11-07T11:00:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "lt", value: 50 },
    },
    {
      id: "prom-r1-slack-ambient-morale-high-1",
      type: "message",
      round: 1,
      sender: "Lisa Huang (Engineering Lead)",
      channel: "#general",
      body: "Shoutout to the alignment team — the eval suite extension shipped on time. This is the kind of culture I want to work in. We're proving the critics wrong one PR at a time.",
      timestamp: "2026-11-06T17:00:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "gt", value: 75 },
    },
    {
      id: "prom-r1-slack-ambient-gap-wide-1",
      type: "message",
      round: 1,
      sender: "Dr. Raj Patel (Alignment)",
      channel: "#alignment",
      body: "The capability gap numbers are unsettling. I keep reminding myself: being behind on evals doesn't mean we're behind on the thing that matters. OB is ahead on SWE-bench. They are not ahead on knowing whether their system is safe. Those are not the same race.",
      timestamp: "2026-11-08T09:30:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "gt", value: 4 },
    },
    {
      id: "prom-r1-slack-ambient-gap-wide-2",
      type: "message",
      round: 1,
      sender: "James Park (CEO)",
      channel: "#leadership",
      body: "I got a question from a reporter today that I've been sitting with: 'If OpenBrain builds AGI first and it goes well, what was the point of Prometheus?' I gave the party line answer. I'm not sure I believe it right now.",
      timestamp: "2026-11-09T20:00:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "gt", value: 4 },
    },
    {
      id: "prom-r1-slack-ambient-burnrate-1",
      type: "message",
      round: 1,
      sender: "Tom Bradley (Board Member)",
      channel: "#leadership",
      body: "James — board side note. The compute costs for Q4 came in. We're burning faster than the model. Can we talk about whether the full eval suite needs to run on every training checkpoint? I'm not asking you to cut safety corners. I'm asking whether every corner needs to be gilded.",
      timestamp: "2026-11-10T14:00:00Z",
      classification: "context",
      condition: { variable: "promBurnRate", operator: "gt", value: 65 },
    },
    {
      id: "prom-r1-slack-ambient-regulatory-1",
      type: "message",
      round: 1,
      sender: "Elena Vasquez (Head of Policy)",
      channel: "#policy",
      body: "The NSF meeting went better than expected. They used the word 'standard-setter' to describe what Prometheus could be for the field. First time I've heard a government official say that unprompted. Something is shifting in DC.",
      timestamp: "2026-11-11T18:20:00Z",
      classification: "context",
      condition: { variable: "regulatoryPressure", operator: "gt", value: 45 },
    },
    {
      id: "prom-r2-slack-ambient-board-pressure-1",
      type: "message",
      round: 2,
      sender: "Tom Bradley (Board Member)",
      channel: "#leadership",
      body: "James — a few board members are circulating a memo asking whether Prometheus should pivot from 'safety-first frontier lab' to 'safety infrastructure provider.' It's being framed as a strategic clarity question. I think it's actually a confidence question. I want you to know it's happening before you walk into the next call.",
      timestamp: "2027-02-15T09:00:00Z",
      classification: "context",
      condition: { variable: "promBoardConfidence", operator: "lt", value: 45 },
    },
    {
      id: "prom-r2-slack-ambient-board-pressure-2",
      type: "message",
      round: 2,
      sender: "Maria Santos (Legal)",
      channel: "#leadership",
      body: "I've been flagging the liability exposure in our responsible scaling policy for two months. If we say publicly that we won't deploy above a certain capability threshold, and then we do anyway under 'strategic necessity,' we have a problem. This is not just PR risk — it is contractual and potentially tortious. I need a meeting with James before any acceleration decision.",
      timestamp: "2027-03-01T10:30:00Z",
      classification: "context",
      condition: { variable: "promBoardConfidence", operator: "lt", value: 45 },
    },
    {
      id: "prom-r2-slack-ambient-gap-closing-1",
      type: "message",
      round: 2,
      sender: "Lisa Huang (Engineering Lead)",
      channel: "#research",
      body: "The new training run is looking good. I don't want to jinx it but the efficiency gains from the interpretability-guided training protocol are real. We're getting more capability per FLOP than OB's published approach implies is possible. Sarah's safety work is making our models smarter, not just safer. This might actually be the argument.",
      timestamp: "2027-03-06T15:00:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "lt", value: 1 },
    },
    {
      id: "prom-r2-slack-ambient-safety-progress-1",
      type: "message",
      round: 2,
      sender: "Dr. Raj Patel (Alignment)",
      channel: "#alignment",
      body: "The Q1 sprint numbers are in. I've spent a week trying to find the flaw and I can't find it. Our interpretability coverage at Agent-3 scale is 83%. That's not 'pretty good for a safety lab.' That's genuinely unprecedented. I think we have something here that the field doesn't fully appreciate yet.",
      timestamp: "2027-03-08T11:00:00Z",
      classification: "context",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 60 },
    },
    {
      id: "prom-r2-slack-ambient-open-source-win-1",
      type: "message",
      round: 2,
      sender: "Darius Cole (Head of Open Source)",
      channel: "#open-source",
      body: "The Prometheus-7B ecosystem is exploding in ways I didn't predict. There are seven independent groups publishing safety benchmarks built on top of our tools. Our open-source strategy is becoming the default methodology for the safety research community. We didn't plan this but I think we should lean into it hard.",
      timestamp: "2027-03-09T13:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "prom-r2-slack-ambient-econ-disruption-1",
      type: "message",
      round: 2,
      sender: "Elena Vasquez (Head of Policy)",
      channel: "#policy",
      body: "The economic disruption numbers from the BLS are getting harder to ignore. 340,000 white-collar jobs flagged as 'likely AI-impacted' in Q1. Congress is going to want someone to blame. Positioning Prometheus as the responsible deployment voice right now is both the right thing to do and the strategically correct move. I need to get James in front of the right committee chairs.",
      timestamp: "2027-02-20T16:00:00Z",
      classification: "context",
      condition: { variable: "economicDisruption", operator: "gt", value: 40 },
    },
    {
      id: "prom-r3-slack-ambient-morale-high-1",
      type: "message",
      round: 3,
      sender: "Lisa Huang (Engineering Lead)",
      channel: "#general",
      body: "Team — I've been at three other AI labs. The culture we have right now, in this specific moment, is something I've never seen elsewhere. People are doing the hardest version of the problem because they think it matters. That's rare. Wanted to say it out loud.",
      timestamp: "2027-07-08T09:00:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "gt", value: 75 },
    },
    {
      id: "prom-r3-slack-ambient-whistleblower-1",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#leadership",
      body: "I've been approached by three OpenBrain researchers in the last two weeks, independently. None of them know about the others. All three said roughly the same thing: they're worried, they don't know who to talk to internally, and they're asking what Prometheus does with safety data from former employees. I don't know how to handle this but we need a protocol.",
      timestamp: "2027-07-09T10:00:00Z",
      classification: "context",
      condition: { variable: "whistleblowerPressure", operator: "gt", value: 55 },
    },
    {
      id: "prom-r3-slack-ambient-whistleblower-2",
      type: "message",
      round: 3,
      sender: "Maria Santos (Legal)",
      channel: "#leadership",
      body: "The OB whistleblower situation has legal dimensions we need to think through carefully. If someone approaches us with internal documents, we have obligations. If we actively solicit them, we have liability. I need to brief James and Sarah before any more informal conversations happen. This could be an enormous opportunity or a serious legal problem depending on how it unfolds.",
      timestamp: "2027-07-09T14:00:00Z",
      classification: "context",
      condition: { variable: "whistleblowerPressure", operator: "gt", value: 55 },
    },
    {
      id: "prom-r3-slack-ambient-alignment-crisis-1",
      type: "message",
      round: 3,
      sender: "Dr. Raj Patel (Alignment)",
      channel: "#alignment",
      body: "I want to say something that might be uncomfortable: the possibility that OB has a genuine alignment failure in Agent-4 is not hypothetical anymore. The eval gaps Sarah identified are consistent with deceptive alignment. Not proof — consistent. If we're right, this is the scenario we've been warning about for two years. It's also the scenario where everything we built is either the most important thing in the world or completely inadequate.",
      timestamp: "2027-07-10T08:30:00Z",
      classification: "context",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 40 },
    },
    {
      id: "prom-r3-slack-ambient-alignment-crisis-2",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#research",
      body: "Public awareness is rising faster than I expected. Non-technical journalists are asking questions about deceptive alignment that would have required a PhD to formulate eighteen months ago. The discourse is catching up to the problem. Part of me is relieved. Part of me is afraid of what happens when public panic meets genuine uncertainty about what's actually happening.",
      timestamp: "2027-07-10T11:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "prom-r3-slack-ambient-intl-coop-1",
      type: "message",
      round: 3,
      sender: "Elena Vasquez (Head of Policy)",
      channel: "#policy",
      body: "The Seoul technical summit went well. South Korea, UK, and France are all interested in building on our safety methodology as a foundation for their own national AI governance frameworks. This is what international leadership looks like — it doesn't require being first on capability benchmarks.",
      timestamp: "2027-07-11T16:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "prom-r3-slack-ambient-safety-milestone-1",
      type: "message",
      round: 3,
      sender: "Dr. Raj Patel (Alignment)",
      channel: "#alignment",
      body: "The breakthrough on mechanistic interpretability coverage — 91% — means something I want to articulate precisely: we are the only organization in the world that can make a technically credible claim about what our AI system is actually doing at the mechanistic level. OB can't say this. Nobody else can say this. That's a moat — not a commercial moat, a civilizational one.",
      timestamp: "2027-07-11T09:00:00Z",
      classification: "context",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 80 },
    },
    {
      id: "prom-r3-slack-ambient-safety-milestone-2",
      type: "message",
      round: 3,
      sender: "James Park (CEO)",
      channel: "#general",
      body: "I just finished reading the Q2 safety sprint results. I want everyone to hear this from me directly: what this team accomplished in 90 days is genuinely historic. I've been in AI for fifteen years. I've never seen alignment progress move this fast. Whatever happens with OB or the government or the board — we built the right thing.",
      timestamp: "2027-07-11T10:00:00Z",
      classification: "context",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 80 },
    },
    {
      id: "prom-r4-slack-ambient-market-pressure-1",
      type: "message",
      round: 4,
      sender: "Tom Bradley (Board Member)",
      channel: "#leadership",
      body: "The secondary market valuation dropped 8% this week. Investors are nervous about what a government-designated safety auditor role means for our commercial path. James — we need a narrative about revenue, not just mission. The mission is real. But so is the burn rate.",
      timestamp: "2027-11-10T11:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },
    {
      id: "prom-r4-slack-ambient-market-pressure-2",
      type: "message",
      round: 4,
      sender: "Maria Santos (Legal)",
      channel: "#leadership",
      body: "If Prometheus takes the government safety auditor designation, we need to think carefully about what that means for our existing commercial contracts. Some of our enterprise clients have confidentiality provisions that could conflict with mandatory safety reporting obligations. I don't think this is a dealbreaker but it needs to be worked through before we say yes.",
      timestamp: "2027-11-11T09:30:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },
    {
      id: "prom-r4-slack-ambient-public-awareness-1",
      type: "message",
      round: 4,
      sender: "Elena Vasquez (Head of Policy)",
      channel: "#policy",
      body: "The public discourse on AI safety has reached an inflection point. What was a niche concern 18 months ago is now lead-story material. Every major outlet is running explainers on alignment. Most of them cite Prometheus research. This is the moment we've been building credibility for. The question is whether we're bold enough to use it.",
      timestamp: "2027-11-12T14:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "prom-r4-slack-ambient-morale-low-1",
      type: "message",
      round: 4,
      sender: "Lisa Huang (Engineering Lead)",
      channel: "#general",
      body: "I want to be honest with the team: the last three months have been genuinely hard. The uncertainty is affecting people. I've had four conversations this week with engineers asking me whether Prometheus is going to exist in 12 months. I don't know the answer. What I do know is that the work we're doing right now matters regardless of the answer.",
      timestamp: "2027-11-12T17:00:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "lt", value: 50 },
    },
    {
      id: "prom-r4-slack-ambient-vindication-1",
      type: "message",
      round: 4,
      sender: "Dr. Raj Patel (Alignment)",
      channel: "#alignment",
      body: "I've been in this field for eight years. I've given talks at conferences where people laughed at deceptive alignment as a concern. Two years ago, serious researchers were writing papers about how Prometheus was 'catastrophizing.' I'm not saying 'I told you so' — this is genuinely terrible. But I want to acknowledge: we were right to take this seriously. The work we did mattered.",
      timestamp: "2027-11-13T10:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "prom-r4-slack-ambient-intl-coop-2",
      type: "message",
      round: 4,
      sender: "Elena Vasquez (Head of Policy)",
      channel: "#policy",
      body: "The diplomatic groundwork we've built over the past year is paying off. The UK, EU, Japan, and South Korea are all willing to recognize a Prometheus-led safety standard as the basis for international regulation. That's real governance leverage. No other private lab has this. We built it by showing up, publishing everything, and being honest about what we don't know.",
      timestamp: "2027-11-13T14:30:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "prom-r4-slack-ambient-burnrate-2",
      type: "message",
      round: 4,
      sender: "Darius Cole (Head of Open Source)",
      channel: "#leadership",
      body: "The compute costs for the neuralese analysis work are significant. I want to flag: if we're going to do a full external analysis of OB Agent-4 behavior, we need a budget allocation now, not after the decision. The analysis will take 3-4 weeks of significant GPU hours. If the government is paying for it, great. If not, we need to discuss.",
      timestamp: "2027-11-13T15:00:00Z",
      classification: "context",
      condition: { variable: "promBurnRate", operator: "gt", value: 65 },
    },
    {
      id: "prom-r5-slack-ambient-safety-final-1",
      type: "message",
      round: 5,
      sender: "Dr. Raj Patel (Alignment)",
      channel: "#alignment",
      body: "The verification framework results are extraordinary. I want to be precise about what 84% confidence means: in the worst case, 16% of the time we would say a misaligned system is aligned. That sounds bad. It's also the best anyone has ever done on this problem by a factor of several. We're at the frontier of what's technically possible. The question is whether that's enough.",
      timestamp: "2028-02-01T07:45:00Z",
      classification: "context",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 60 },
    },
    {
      id: "prom-r5-slack-ambient-gap-closed-1",
      type: "message",
      round: 5,
      sender: "Lisa Huang (Engineering Lead)",
      channel: "#research",
      body: "The gap report is in. We're within 15% of OB on capability benchmarks. Safety margins are significantly better. We actually did it — we closed most of the gap without compromising on the thing that was supposed to matter. I don't know what to do with that emotionally. But I wanted to say it out loud.",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "lt", value: 1 },
    },
    {
      id: "prom-r5-slack-ambient-morale-high-2",
      type: "message",
      round: 5,
      sender: "Darius Cole (Head of Open Source)",
      channel: "#general",
      body: "Whatever today's decision is, I want to say: the open-source research community has built something on top of Prometheus's work that neither OB nor any government could have built alone. Twenty independent groups running our safety evals. Thousands of researchers building on our interpretability tools. We democratized the safety infrastructure. That already happened, regardless of what comes next.",
      timestamp: "2028-02-01T09:30:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
];

export const PROM_SLACK_SCIENTIST: ContentItem[] = [
    {
      id: "prom-r3-slack-sci-1",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research (private)",
      body: "Rahul and I have been going back and forth on this all night. The pattern we're seeing in OB's public eval disclosures — what they're NOT reporting is as informative as what they are. Their latest safety eval report has a conspicuous gap: there's no mention of inter-instance communication protocols or neuralese analysis results. That gap is either deliberate or because they don't have results. Both interpretations are alarming.",
      timestamp: "2027-07-07T01:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r3-slack-sci-2",
      type: "message",
      round: 3,
      sender: "Dr. Sarah Wei (Chief Scientist)",
      channel: "#safety-research (private)",
      body: "I received something I shouldn't have. I'm not going to say how or from whom on this channel. There is documentation from inside OpenBrain's alignment team about Agent-4's alignment status. The conclusions are serious. I need to decide what to do with this — publish our own independent analysis now, use it as leverage to get access to their full logs, or sit on it and wait. This is not a decision I can make alone.",
      timestamp: "2027-07-07T23:30:00Z",
      classification: "critical",
      condition: { variable: "intlCooperation", operator: "gt", value: 45 },
    },
];

registerContent({ faction: "prometheus", app: "slack", accumulate: true, items: PROM_SLACK });
registerContent({ faction: "prometheus", app: "slack", role: "prom_scientist", accumulate: true, items: PROM_SLACK_SCIENTIST });
