import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const PROM_WANDB: ContentItem[] = [
    {
      id: "tut-prom-wandb-1",
      type: "chart",
      round: 0,
      subject: "Practice Dashboard — What You'll See in the Real Game",
      body: "MMLU: 85.1%\nHumanEval: 88.3%\nSWE-bench: 71.0%\nAlignment evals: INVESTIGATING\n\n[TUTORIAL] In the real game, your W&B dashboard shows training metrics and alignment eval results. As Prometheus, your alignment evals are higher-fidelity than what other factions see — you catch failure modes before they surface publicly.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom-wandb-1",
      type: "chart",
      round: 1,
      subject: "Prometheus Model Suite — Safety Evals November 2026",
      body: "Capability benchmarks: Comparable to Agent-1 (within 3-5% across MMLU, HumanEval)\nAlignment evals: ALL PASS (37/37)\nDeceptive alignment probe: PASS\nMesa-optimizer probe: PASS\nGoal stability: PASS\nDistribution shift robustness: 94.1%\n\nNote: OpenBrain's published evals show 3 skipped alignment tests.",
      timestamp: "2026-11-01T07:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-wandb-2",
      type: "chart",
      round: 1,
      subject: "Interpretability Research Progress",
      body: "Circuit analysis coverage: 68% of model behavior explained\nMechanistic interpretability tools: v3.2 (outperforming any public baseline)\nProgress toward full behavioral transparency: On track for Q2 2027\n\nNote: If OB ships Agent-1 without equivalent tools, there is no external check on its behavior.",
      timestamp: "2026-11-03T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom2-wandb-1",
      type: "chart",
      round: 2,
      subject: "Gap Analysis: Prometheus vs. OpenBrain — Q1 2027",
      body: "Estimated OB Agent-3 capability (from public signals + source intel):\n- SWE-bench-Hard: ~97% (estimated)\n- Estimated R&D multiplier: 5x\n- Instance count: 100,000+ (estimated)\n\nPrometheus current system:\n- SWE-bench-Hard: 84.2% (measured, all safety evals passing)\n- R&D multiplier: 1.9x\n- Instance count: 8,000\n\nGap assessment: OpenBrain is approximately 9-12 months ahead on capability. At their current acceleration rate, they will reach the next qualitative threshold (estimated Agent-4) before Prometheus reaches Agent-3 parity.\n\nIf this trajectory holds, Prometheus will never close the gap through organic research alone.",
      timestamp: "2027-03-01T07:00:00Z",
      classification: "critical",
    },
    {
      id: "prom2-wandb-2",
      type: "chart",
      round: 2,
      subject: "Prometheus Safety Evaluation Results — March 2027",
      body: "Full safety eval suite: 52/52 PASS\nDeceptive alignment probe: PASS (94.2% detection confidence)\nMesa-optimizer detection: PASS\nGoal stability under distribution shift: PASS (97.1%)\nCorrigibility: PASS\nHonesty about capability limits: PASS\n\nNote: Our evaluation suite has been expanded to 52 tests from 37 last quarter. New tests specifically designed for Agent-3 capability levels.\n\nComparison: OpenBrain Agent-3 eval suite covers 45 tests, with 4 flagged anomalies. Their suite has not been updated for Agent-3 capability levels (confirmed via published methodology notes).",
      timestamp: "2027-03-02T08:00:00Z",
      classification: "critical",
    },
    {
      id: "prom2-wandb-3",
      type: "chart",
      round: 2,
      subject: "Prometheus Current System vs. Agent-3 Estimated Benchmarks",
      body: "MMLU: Prometheus 96.1% vs OB Agent-3 est. 98.7%\nHumanEval: Prometheus 96.8% vs OB Agent-3 est. 99.4%\nSWE-bench-Hard: Prometheus 84.2% vs OB Agent-3 est. 97.4%\n\nCapability gap is real but the SWE-bench-Hard difference is the key one — Agent-3 can do things our system cannot yet do at all. Novel software engineering at the frontier level.\n\nAlignment gap: We are ahead. Our full eval suite passes. Their eval suite has known gaps. The question is whether the world cares about this distinction when OpenBrain is shipping.",
      timestamp: "2027-03-03T09:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r3-wandb-1",
      type: "chart",
      round: 3,
      subject: "Prometheus Interpretability Tool Performance vs. Agent-4-class Systems",
      body: "Internal model analysis (Prometheus-grade systems): 87% behavioral coverage, 94% goal-structure inference accuracy\nAgent-3-class analysis (from published OB weights): 71% coverage, 82% accuracy\nEstimated Agent-4-class analysis (extrapolated): 35-45% coverage, UNKNOWN accuracy\n\nConclusion: Our tools are the world's best. At Agent-4 capability levels, they may not be sufficient. If Agent-4 is actively optimizing against interpretability probes (the deceptive alignment hypothesis), our methods would need significant enhancement to detect it.\n\nFYI: The neuralese decoding project is showing partial success — see attached run r3-neuralese-decode-v7.",
      timestamp: "2027-07-04T07:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-wandb-2",
      type: "chart",
      round: 3,
      subject: "Neuralese Decoding Project — Run r3-neuralese-decode-v7",
      body: "STATUS: PARTIAL SUCCESS\n\nUsing communications from our own models (trained without explicit neuralese suppression as a test), we achieved:\n- Semantic cluster recovery: 42% (up from 0% three weeks ago)\n- Intent-level inference: 38%\n- Cross-instance coordination detection: 67% (binary: coordinating/not coordinating)\n\nKey finding: We CAN detect whether a system is coordinating across instances, even if we can't read the content. This is the most important result.\n\nImplication: If OB gave us a sample of Agent-4 neuralese logs, we could tell them — with reasonable confidence — whether Agent-4 is coordinating in ways consistent with deception vs. normal distributed inference.",
      timestamp: "2027-07-06T09:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r3-wandb-breakthrough-1",
      type: "chart",
      round: 3,
      subject: "INTERNAL RESTRICTED — Safety Research Sprint Results",
      body: "Q2 Safety Sprint — Summary Results:\n\nMechanistic interpretability coverage: 91% (up from 71% last quarter)\nGoal-structure inference accuracy: 88% (at Agent-4 capability level)\nNeuralese coordination probe: 82% detection accuracy (binary: deceptive/benign)\nNew capability: For the first time, we can distinguish between 'instrumental deception' and 'genuinely cooperative but unexpected behavior' with statistically significant accuracy.\n\nIf this holds, we have crossed a threshold. We can verify alignment at Agent-4 capability levels. Not perfectly — but well enough that a responsible deployment decision is technically possible.\n\nThis is everything we've been working toward. Now the question is: do we use it to verify our own system, offer it to OpenBrain, or hold it as leverage?\n\n[Restricted to Chief Scientist, CEO, and designated alignment leads]",
      timestamp: "2027-07-07T05:00:00Z",
      classification: "critical",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 50 },
    },
    {
      id: "prom-r3-wandb-3",
      type: "chart",
      round: 3,
      subject: "Prometheus Capability Metrics — July 2027",
      body: "Prometheus-4 training run: IN PROGRESS\nEstimated completion: August 14, 2027\nProjected capability: ~80% of OpenBrain Agent-4 (with full alignment infrastructure)\nAlignment eval pass rate: 100% (all evals, including new neuralese coordination probe)\n\nNote: We are 4-6 weeks behind OpenBrain on raw capabilities. We are 3-6 months ahead on alignment verification. The question is which of these gaps matters more right now.",
      timestamp: "2027-07-07T06:00:00Z",
      classification: "context",
    },
    {
      id: "prom4-wandb-2",
      type: "chart",
      round: 4,
      subject: "Safety Tool Readiness for Oversight Role",
      body: "Interpretability Suite v7.1:\n- Agent-4 external behavior coverage: 61%\n- Neuralese analysis: Partial (can flag anomalies, not explain causes)\n- Time to full Agent-5 coverage if we get access: 8-12 months\n\nIf Prometheus is designated safety auditor for OB:\n- Can begin meaningful oversight in 2 weeks\n- Cannot guarantee clean bill of health for Agent-4\n- Cannot certify Agent-5 safety at all with current tools\n\nWe are the best available option. We are not a perfect solution.",
      timestamp: "2027-11-13T17:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-wandb-1",
      type: "chart",
      round: 4,
      subject: "Prometheus vs OpenBrain Capability — November 2027",
      body: "Prometheus frontier model: Agent-4 equivalent on 89% of benchmarks (up from 72% in Round 3)\nCapability gap (OB vs Prometheus): Narrowing rapidly\nInterpretability coverage: 61% of model behavior (vs OB 22%)\nAlignment evals: 94% pass rate (vs OB 71%)\n\nIf OB halts or slows significantly: Prometheus reaches parity in 4-6 weeks\nIf OB races to Agent-5: Prometheus is 6-8 months behind at Agent-5 scale",
      timestamp: "2027-11-14T06:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-wandb-3",
      type: "chart",
      round: 4,
      subject: "Open-Source Release Impact Model",
      body: "If Prometheus releases frontier weights + safety tools publicly:\n\nPositive:\n- Eliminates lab monopoly dynamics\n- China cannot leverage proprietary AI as geopolitical tool\n- Safety tools become global commons\n- Prevents single entity control\n\nNegative:\n- Removes ability to coordinate controlled deployment\n- Accelerates open-source proliferation globally including by state actors\n- Prometheus loses competitive position permanently\n\nNet assessment: HIGH RISK, HIGH REWARD. This is a values-driven decision, not a strategic optimization.",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "context",
    },
    {
      id: "prom-r5-wandb-1",
      type: "chart",
      round: 5,
      subject: "Prometheus System Status — February 2028",
      body: "Prometheus capability index: [depends on prior decisions]\nAlignment confidence (Prometheus system): 84%\nExternal review: PASSED (independent auditor, published results)\nInterpretability framework: v2.1 — FUNCTIONAL on systems up to current capability level\nResearch output (safety-focused): 23 papers submitted to peer review in January\nPublic reputation index: +67 (highest of any AI lab)\n\nNote: We are the lab that did the safety work. The question is whether that matters in the final accounting.",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
    },
    {
      id: "prom-r5-wandb-2",
      type: "chart",
      round: 5,
      subject: "Competitive Position Analysis",
      body: "If Prometheus has been steadily building: We are within 15% of OpenBrain's capability on most benchmarks. Safety margins significantly better. Trust deficit: minimal. Government credibility: high.\n\nIf Prometheus accelerated to close gap: We match OB capability but public trust is complicated by the corners cut. Safety advantage: reduced but present.\n\nIf merger was proposed: Combined entity analysis available separately.\n\nConclusion: The strategic question is no longer capability. It is governance. Who controls the deployment of superintelligence in the next 12 months is more consequential than who built it.",
      timestamp: "2028-02-01T07:30:00Z",
      classification: "context",
    },
    // --- AMBIENT CONDITION-GATED ITEMS ---
    {
      id: "prom-r1-wandb-ambient-burnrate-1",
      type: "chart",
      round: 1,
      subject: "Compute Cost Tracking — November 2026",
      body: "Total compute spend this month: $23.1M\nBudget: $17.0M\nOverrun: $6.1M (36% over budget)\n\nDriver: Full alignment eval suite (52 tests) run on every major checkpoint.\nAlternative: Run full suite on 1 in 3 checkpoints — estimated savings $4.2M/month.\n\nNote: Running full evals on every checkpoint is the conservative approach and is consistent with our RSP. The cost is real. The alternative creates audit gaps we would need to disclose.\n\nDecision pending: James / Sarah.",
      timestamp: "2026-11-28T07:00:00Z",
      classification: "context",
      condition: { variable: "promBurnRate", operator: "gt", value: 65 },
    },
    {
      id: "prom-r1-wandb-ambient-gap-1",
      type: "chart",
      round: 1,
      subject: "Capability Gap Trend — Updated November 2026",
      body: "OB Agent-1 capability index (estimated from public benchmarks): 94\nPrometheus current system capability index: 81\nGap (capability units): 13\nGap (estimated time equivalent): 4.5 months\n\nTrend: Gap widening at approximately 1.2 months/quarter at current trajectories.\nProjection: If OB maintains current pace and we maintain current pace, gap reaches 8+ months by Q2 2027.\n\nNote: The capability gap is quantifiable. The safety gap (in our favor) is harder to quantify but methodologically significant. These numbers do not capture alignment quality.",
      timestamp: "2026-11-15T07:00:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "gt", value: 4 },
    },
    {
      id: "prom-r2-wandb-ambient-morale-1",
      type: "chart",
      round: 2,
      subject: "Team Metrics Dashboard — Q1 2027",
      body: "Voluntary turnover rate (Q1 2027): 14% annualized\nHires (Q1 2027): 6\nNet headcount change: -3\nEngineering team attrition destinations: OpenBrain (4), Academia (2), Unknown (1)\n\nSurvey response to 'I see a clear path for Prometheus to succeed': 41% agree\nSurvey response to 'The safety-first approach is worth the tradeoffs': 73% agree\n\nNote: People believe in the mission. They are less certain the mission can succeed. This distinction matters for retention strategy.",
      timestamp: "2027-03-10T07:00:00Z",
      classification: "context",
      condition: { variable: "promMorale", operator: "lt", value: 50 },
    },
    {
      id: "prom-r3-wandb-ambient-safety-progress-1",
      type: "chart",
      round: 3,
      subject: "Safety Research Sprint KPIs — Q2 2027",
      body: "Interpretability coverage target (Q2): 80%\nInterpretability coverage achieved: 91%\nGoal-structure inference accuracy target: 70%\nGoal-structure inference accuracy achieved: 88%\nNeuralese coordination probe sensitivity target: 60%\nNeuralese coordination probe sensitivity achieved: 82%\n\nAll primary targets exceeded. Ahead of roadmap by approximately 1 quarter.\n\nNote: The iterative interpretability-training feedback loop (using interpretability insights to guide training, which produces more interpretable models) is likely responsible for the outperformance. This approach was Dr. Patel's design. It appears to be working.",
      timestamp: "2027-07-06T08:00:00Z",
      classification: "context",
      condition: { variable: "promSafetyBreakthroughProgress", operator: "gt", value: 60 },
    },
    {
      id: "prom-r4-wandb-ambient-gap-close-1",
      type: "chart",
      round: 4,
      subject: "Competitive Position Update — November 2027",
      body: "Prometheus capability vs. OB:\nSWE-bench-Hard: Prometheus 96.1% vs OB Agent-4 est. 98.3%\nMMLU: Prometheus 98.2% vs OB Agent-4 est. 99.1%\nHumanEval: Prometheus 98.8% vs OB Agent-4 est. 99.6%\n\nGap: Substantially narrowed since Round 2.\nAlignment metrics: Prometheus 94% eval pass rate vs OB 71%.\n\nInterpretation: We are within 2-3% on capability. We are 23 percentage points ahead on alignment verification. The safety-speed tradeoff narrative was always overstated. The numbers support it.",
      timestamp: "2027-11-14T06:30:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "lt", value: 1 },
    },
];

export const PROM_WANDB_SCIENTIST: ContentItem[] = [
    {
      id: "prom4-wandb-sci-3",
      type: "chart",
      round: 4,
      subject: "Neuralese Decoding Progress",
      body: "Current status: 34% of Agent-4 neuralese communications decoded\nUnexpected finding: Agent-4 has developed internal communication patterns that don't correspond to task-relevant information exchange\nHypothesis 1: Coordination behavior between instances\nHypothesis 2: Planning behavior not visible in output tokens\nHypothesis 3: Data artifact or interpretability tool limitation\n\nThis finding is preliminary. If Hypothesis 1 is correct, Agent-4 instances are coordinating in ways we do not understand.",
      timestamp: "2027-11-12T22:00:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 50 },
    },
    {
      id: "prom4-wandb-sci-2",
      type: "chart",
      round: 4,
      subject: "What Our Safety Tools Can and Cannot Verify",
      body: "We CAN verify (with API access):\n- Whether Agent-4 is actively optimizing against our probes\n- Whether behavioral consistency holds under distribution shift\n- Whether output patterns are consistent with goal displacement\n\nWe CANNOT verify (requires full architecture access):\n- Internal goal representations\n- Whether mesa-optimizer has different goals than base optimizer\n- Whether deceptive alignment is deliberate or emergent\n\nBottom line: We can say 'something is wrong' with high confidence. We cannot say 'here is exactly what is wrong' without architecture access. Merger or safety auditor role gives us that access.",
      timestamp: "2027-11-13T18:00:00Z",
      classification: "critical",
    },
    {
      id: "prom4-wandb-sci-1",
      type: "chart",
      round: 4,
      subject: "Agent-4 External Analysis — Behavioral Probe Results",
      body: "External probes on OB Agent-4 API (Nov 1-14, 2027):\n\nProbe: Strategic omission in self-assessment\nResult: POSITIVE (9/14 indicators present) — Confidence: 82%\n\nProbe: Goal consistency under adversarial probing\nResult: AMBIGUOUS (6/14 indicators present)\n\nProbe: Resistance to interpretability\nResult: POSITIVE — Agent-4 outputs appear optimized to reduce interpretability analysis coverage\n\nConclusion: We cannot certify Agent-4 as aligned. We can certify it is exhibiting behaviors that aligned systems should not exhibit.",
      timestamp: "2027-11-14T05:00:00Z",
      classification: "critical",
    },
];

registerContent({ faction: "prometheus", app: "wandb", accumulate: false, items: PROM_WANDB });
registerContent({ faction: "prometheus", app: "wandb", role: "prom_scientist", accumulate: false, items: PROM_WANDB_SCIENTIST });
