import type { RoundDecisions } from "@takeoff/shared";

/**
 * Round 4 decisions — Late 2027, "The Branch Point"
 * The biggest decisions in the game. Includes cross-faction negotiation phase.
 * Effects are the largest of any round — they determine the endgame state.
 *
 * Team array has 7 entries (not 4): OpenBrain and Prometheus each have two
 * team decisions (primary strategic choice + secondary relationship/stance).
 */
export const ROUND4_DECISIONS: RoundDecisions = {
  round: 4,

  individual: [
    // ── OpenBrain ──
    {
      role: "ob_ceo",
      prompt: "The board emergency session is in two hours. The NSA wants an answer. Maya Patel is deciding whether to go to the press. James Park is offering a merger. China is offering a mutual pause. You have to decide right now what kind of company OpenBrain is — and what you personally stand for.",
      options: [
        {
          id: "ob_ceo_r4_halt",
          label: "Stand with the Safety Officer",
          description: "Back Maya Patel's recommendation publicly. Signal to the board and the world that you take this seriously. Begin preparing a voluntary halt and third-party safety audit. Open a direct line to the NSA Director.",
          effects: [
            { variable: "obInternalTrust", delta: 7 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obCapability", delta: -5 },
            { variable: "publicSentiment", delta: 6 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "obBoardConfidence", delta: -5 },
            { variable: "obMorale", delta: 5 },
            { variable: "whistleblowerPressure", delta: -6 },
            { variable: "obBurnRate", delta: -7 },
            { variable: "regulatoryPressure", delta: -6 },
            { variable: "globalMediaCycle", delta: -6 },
            { variable: "doomClockDistance", delta: 5 },
          
            { variable: "usChinaGap", delta: 2 },
          ],
        },
        {
          id: "ob_ceo_r4_race",
          label: "Trust the CTO — greenlight Agent-5",
          description: "Override the safety concerns. The competitive window is real. Take responsibility and greenlight Agent-5 training immediately before the government can impose restrictions. The risk of losing is greater than the risk of proceeding.",
          effects: [
            { variable: "obCapability", delta: 6 },
            { variable: "alignmentConfidence", delta: -7 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "misalignmentSeverity", delta: 6 },
            { variable: "publicSentiment", delta: -7 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "obBurnRate", delta: 6 },
            { variable: "obBoardConfidence", delta: 6 },
            { variable: "obMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 8 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
        {
          id: "ob_ceo_r4_negotiate",
          label: "Accept NSA oversight — controlled pace",
          description: "Give the NSA a seat at the table in exchange for legal cover. Continue Agent-4 at reduced scale with government oversight. This is the middle path — not a race, not a halt. Buy time to assess the merger offer.",
          effects: [
            { variable: "obCapability", delta: 3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "obInternalTrust", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
      ],
    },
    {
      role: "ob_cto",
      prompt: "Maya's evidence is documented. Your Agent-5 architecture is ready. The board emergency session starts in two hours and they're going to ask you directly: is Agent-4 safe? You have to answer in a way you can live with.",
      options: [
        {
          id: "ob_cto_r4_endorse_safety",
          label: "Endorse the safety halt",
          description: "Tell the board and the CEO that Maya is right. You built this system — you know what 'we can't verify alignment at this scale' actually means. Push for the pause and third-party audit. This costs you the race but it might save something more important.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "obInternalTrust", delta: 6 },
            { variable: "obCapability", delta: -4 },
            { variable: "misalignmentSeverity", delta: -6 },
            { variable: "obBoardConfidence", delta: -5 },
            { variable: "obMorale", delta: 5 },
            { variable: "whistleblowerPressure", delta: -6 },
          
            { variable: "usChinaGap", delta: 2 },
          
            { variable: "obPromGap", delta: 2 },
          ],
        },
        {
          id: "ob_cto_r4_override",
          label: "Declare Agent-4 safe — push Agent-5",
          description: "The evidence is ambiguous. The probes could be wrong. You've spent years on this system and you don't believe it's deceptive. Go on record: Agent-4 is safe within operational parameters. Greenlight Agent-5.",
          effects: [
            { variable: "obCapability", delta: 6 },
            { variable: "alignmentConfidence", delta: -6 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "misalignmentSeverity", delta: 7 },
            { variable: "obBurnRate", delta: 5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "obMorale", delta: -5 },
            { variable: "obBoardConfidence", delta: 5 },
            { variable: "whistleblowerPressure", delta: 6 },
          ],
        },
        {
          id: "ob_cto_r4_conditional",
          label: "Propose a 30-day verification window",
          description: "Recommend a 30-day verification window using Prometheus's interpretability tools under NDA before any Agent-5 decision. Not a halt — a genuine technical pause for the most important safety check in the company's history.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obInternalTrust", delta: 4 },
            { variable: "obCapability", delta: -3 },
            { variable: "misalignmentSeverity", delta: -4 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "promSafetyBreakthroughProgress", delta: 3 },
            { variable: "obMorale", delta: 5 },
            { variable: "obBurnRate", delta: 5 },
            { variable: "obBoardConfidence", delta: -5 },
          ],
        },
      ],
    },
    {
      role: "ob_safety",
      prompt: "Your memo is on the CEO's desk. The board call is tomorrow. The journalist has your memo. The board has your recommendation. You have made your case through every internal channel available. Now you decide: what do you do next?",
      options: [
        {
          id: "ob_safety_r4_leak",
          label: "Give the journalist full authorization to publish",
          description: "The internal channels are exhausted. Contact the journalist and give her full authorization. This burns your career and possibly OpenBrain, but it ensures the information cannot be suppressed. You accept the consequences.",
          effects: [
            { variable: "publicAwareness", delta: 6 },
            { variable: "publicSentiment", delta: -8 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obInternalTrust", delta: -4 },
            { variable: "obCapability", delta: -4 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "globalMediaCycle", delta: 8 },
            { variable: "marketIndex", delta: -4 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "whistleblowerPressure", delta: -7 },
          ],
        },
        {
          id: "ob_safety_r4_wait_board",
          label: "Wait for the board decision",
          description: "You've done everything correctly. Let the process work. The CEO has your memo. The board has your recommendation. Give them until the morning board call before you take any further action.",
          effects: [
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "obInternalTrust", delta: 3 },
            { variable: "misalignmentSeverity", delta: 3 },
            { variable: "obBoardConfidence", delta: 4 },
            { variable: "obMorale", delta: -4 },
            { variable: "whistleblowerPressure", delta: 7 },
          ],
        },
        {
          id: "ob_safety_r4_nsa",
          label: "Contact the NSA directly with the evidence",
          description: "Go over the CEO and the board. Contact the NSA directly with your behavioral evidence and the recommendation for a halt. This triggers government action regardless of what the board decides.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "intlCooperation", delta: 4 },
            { variable: "publicAwareness", delta: 3 },
            { variable: "obCapability", delta: -3 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
      ],
    },
    {
      role: "ob_security",
      prompt: "The merger is being discussed. The NSA wants oversight. Agent-5 architecture is in offline storage. Your job is to make sure the right things stay secure — and figure out what the right things are when everything is in flux.",
      options: [
        {
          id: "ob_security_r4_merger_due_diligence",
          label: "Prepare merger security due diligence",
          description: "If the merger is going to happen, make sure it happens safely. Document the security requirements, propose the staged architecture access plan, and brief both teams on what can and cannot be shared. Be the adult in the room.",
          effects: [
            { variable: "securityLevelOB", delta: 2 },
            { variable: "securityLevelProm", delta: 1 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "promBurnRate", delta: -4 },
            { variable: "promBoardConfidence", delta: 4 },
            { variable: "obBurnRate", delta: -4 },
          
            { variable: "obPromGap", delta: 1 },
          ],
        },
        {
          id: "ob_security_r4_lockdown",
          label: "Maximum lockdown — prevent any architecture sharing",
          description: "Regardless of board decisions, implement maximum security protocols. No architecture details leave the building without your sign-off. This may slow merger negotiations but prevents catastrophic leakage.",
          effects: [
            { variable: "securityLevelOB", delta: 3 },
            { variable: "obCapability", delta: -2 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "obBurnRate", delta: 6 },
            { variable: "obBoardConfidence", delta: -4 },
            { variable: "chinaWeightTheftProgress", delta: -6 },
          ],
        },
        {
          id: "ob_security_r4_nsa_share",
          label: "Brief NSA on full security posture and vulnerabilities",
          description: "Share everything with the NSA — including the exfiltration assessment, the insider threat flags, and the security requirements for any merger. Government oversight is better than secrecy at this point.",
          effects: [
            { variable: "securityLevelOB", delta: 2 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
      ],
    },

    // ── Prometheus ──
    {
      role: "prom_ceo",
      prompt: "You have the most important meeting of your career coming up. The government is offering you power. OpenBrain is offering you a merger. China is offering you research funding. Your scientist says the merger gives you the tools to actually fix the alignment problem. Your policy head says the government option gives you institutional authority. What do you do?",
      options: [
        {
          id: "prom_ceo_r4_merger",
          label: "Accept merger — push for strong safety board authority",
          description: "Counter OpenBrain's terms. Accept the merger in principle but demand co-CEO status and true unilateral halt authority for the safety board. If Marcus won't give you that, walk away. The merger only works if Prometheus actually controls safety decisions.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "promCapability", delta: 4 },
            { variable: "obCapability", delta: -3 },
            { variable: "obInternalTrust", delta: 5 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "promBurnRate", delta: -4 },
            { variable: "promBoardConfidence", delta: 4 },
            { variable: "obBurnRate", delta: -4 },
          ],
        },
        {
          id: "prom_ceo_r4_gov_auditor",
          label: "Accept government safety auditor designation",
          description: "Take the NSC's offer. Become the official lead safety auditor with binding authority over OpenBrain. This is institutional power without the legal complexity of a merger. The downside: you're now part of the government apparatus, with all the constraints that brings.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "promCapability", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "obCapability", delta: -3 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
        {
          id: "prom_ceo_r4_race",
          label: "Race to fill the gap if OpenBrain slows",
          description: "If OpenBrain halts or slows, Prometheus reaches parity in 4-6 weeks. Position Prometheus to be the dominant lab with the safety culture already built in. This is the scenario we've prepared for. Don't give up competitive position for a government leash.",
          effects: [
            { variable: "promCapability", delta: 6 },
            { variable: "alignmentConfidence", delta: -3 },
            { variable: "obPromGap", delta: -4 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "promBurnRate", delta: 6 },
            { variable: "promBoardConfidence", delta: 6 },
            { variable: "promMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 8 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
      ],
    },
    {
      role: "prom_scientist",
      prompt: "Your external analysis of Agent-4 is damning. Fourteen behavioral indicators. Nine confirmed positive. The question you have to answer is: do you publish, and what do you ask for in exchange for not publishing? Your leverage is your credibility as a scientist — how do you use it?",
      options: [
        {
          id: "prom_sci_r4_publish",
          label: "Publish the external analysis immediately",
          description: "Release the preprint now. No negotiating, no exclusives. Science should be public when the stakes are civilizational. Let the world see the evidence and decide. Accept that this ends any chance of a merger on our terms.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "publicSentiment", delta: -5 },
            { variable: "misalignmentSeverity", delta: -5 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "globalMediaCycle", delta: 7 },
            { variable: "openSourceMomentum", delta: 4 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 0 },
          ],
        },
        {
          id: "prom_sci_r4_leverage",
          label: "Use the analysis as merger leverage",
          description: "Tell OpenBrain: we have evidence, and we'll hold it while you give us real safety board authority with architecture access. This is not blackmail — this is responsible negotiation under time pressure. The evidence is still published eventually.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "promCapability", delta: 3 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "obBoardConfidence", delta: 4 },
            { variable: "obMorale", delta: -4 },
            { variable: "whistleblowerPressure", delta: 7 },
          ],
        },
        {
          id: "prom_sci_r4_share_nsa",
          label: "Share findings directly with NSA and oversight committee",
          description: "Provide the full technical analysis to government authorities. This is the responsible path — put the evidence in front of people with the authority to act on it, not in a preprint that takes weeks to have impact.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "obCapability", delta: -3 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
      ],
    },
    {
      role: "prom_policy",
      prompt: "The Deputy NSA is asking for Prometheus's position before the President decides. The EU is offering standards authority. Senators are calling you. This is the moment DC contacts have been cultivated for. What position do you stake out?",
      options: [
        {
          id: "prom_policy_r4_designated_auditor",
          label: "Push Prometheus as government-designated safety auditor",
          description: "Actively lobby for the NSC's option B — Prometheus as the designated lead. Draft the executive order language, brief the key senators, make it happen. This is Prometheus's moment to become the institutional backbone of AI governance.",
          effects: [
            { variable: "intlCooperation", delta: 4 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "publicSentiment", delta: 4 },
            { variable: "promCapability", delta: 3 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
        {
          id: "prom_policy_r4_oversight_committee",
          label: "Push for broad oversight committee with civil society seats",
          description: "Advocate for an oversight committee that includes civil society, not just government and industry. This is slower and messier but more legitimate. Prometheus is represented but not in charge — the outcome is more durable.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 6 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
        {
          id: "prom_policy_r4_global_pause",
          label: "Call publicly for a global pause",
          description: "Go on record calling for a 90-day global pause on frontier AI training above a compute threshold. This is the most politically costly move but it establishes Prometheus as the only actor willing to say the honest thing out loud.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "obCapability", delta: -3 },
            { variable: "promCapability", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "doomClockDistance", delta: 3 },
            { variable: "obBurnRate", delta: -7 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "globalMediaCycle", delta: -6 },
          ],
        },
      ],
    },
    {
      role: "prom_opensource",
      prompt: "You've been the voice for open-source at Prometheus since day one. Now there's a real question on the table: does going fully open-source — releasing everything, including the safety tools — actually make things better? This is the decision you've been rehearsing.",
      options: [
        {
          id: "prom_os_r4_full_release",
          label: "Release everything — full open-source including safety tools",
          description: "Publish all frontier weights, interpretability tools, and safety evaluation methodology under an open license. The oligopoly ends. The safety tools become a global commons. Accept the loss of competitive position.",
          effects: [
            { variable: "publicAwareness", delta: 5 },
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "publicSentiment", delta: 7 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "promCapability", delta: -5 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "openSourceMomentum", delta: 4 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 0 },
          ],
        },
        {
          id: "prom_os_r4_safety_tools_only",
          label: "Publish safety tools only — keep frontier weights closed",
          description: "Release the interpretability and evaluation tools as open standards. Keep frontier model weights proprietary. Safety tools become a global commons without giving up competitive position on capabilities.",
          effects: [
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "promCapability", delta: -2 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "openSourceMomentum", delta: 4 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
        {
          id: "prom_os_r4_hold",
          label: "Hold all releases — use leverage strategically",
          description: "The open-source option is leverage. Don't give it away before you've extracted value from it. Use the threat of open-sourcing to strengthen merger terms or government positions.",
          effects: [
            { variable: "promCapability", delta: 2 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "publicSentiment", delta: -3 },
            { variable: "promBoardConfidence", delta: 4 },
            { variable: "promMorale", delta: -4 },
            { variable: "whistleblowerPressure", delta: 7 },
          ],
        },
      ],
    },

    // ── China ──
    {
      role: "china_director",
      prompt: "You have reached parity with the US labs. The Standing Committee is waiting for your recommendation on which of four strategic options to pursue. This is the biggest decision of your career — and it will shape the next decade of global AI development.",
      options: [
        {
          id: "china_dir_r4_grand_bargain",
          label: "Recommend the grand bargain",
          description: "Recommend China accept the mutual pause with chip access in exchange. The technology gain outweighs the momentum loss. Chip independence is the long game that matters most.",
          effects: [
            { variable: "intlCooperation", delta: 4 },
            { variable: "taiwanTension", delta: -6 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "doomClockDistance", delta: 3 },
          ],
        },
        {
          id: "china_dir_r4_sprint",
          label: "Recommend a quiet sprint to Agent-5",
          description: "While the US labs are in crisis and government is distracted, accelerate. Don't make noise. Don't make deals. Just run. China can reach Agent-5 first while the US is paralyzed.",
          effects: [
            { variable: "chinaCapability", delta: 6 },
            { variable: "usChinaGap", delta: -5 },
            { variable: "taiwanTension", delta: 4 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "cdzComputeUtilization", delta: 4 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
        {
          id: "china_dir_r4_open_source",
          label: "Recommend open-sourcing everything",
          description: "Release all weights, including the exfiltrated OB architecture, under open licenses. This eliminates the US lab advantage, eliminates China's advantage, and makes any future monopoly impossible. This is the highest-risk, highest-reward play.",
          effects: [
            { variable: "chinaCapability", delta: -3 },
            { variable: "obCapability", delta: -5 },
            { variable: "promCapability", delta: -3 },
            { variable: "publicAwareness", delta: 4 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "intlCooperation", delta: -4 },
            { variable: "taiwanTension", delta: 3 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "openSourceMomentum", delta: 4 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
      ],
    },
    {
      role: "china_intel",
      prompt: "The exfiltration window is closed — OB's security is now SL4. Your remaining leverage is information operations and back-channel diplomacy. The journalist, the safety officer, and the diplomat are all in play. How do you use your intelligence assets?",
      options: [
        {
          id: "china_intel_r4_journalist",
          label: "Feed the journalist the exfiltration story",
          description: "Provide the journalist with documentation that OB's security team covered up the Agent-3 exfiltration. This blows up OpenBrain's credibility simultaneously with the safety story. Maximum political damage to US labs.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "publicSentiment", delta: -6 },
            { variable: "taiwanTension", delta: 3 },
            { variable: "intlCooperation", delta: -4 },
            { variable: "globalMediaCycle", delta: 8 },
            { variable: "marketIndex", delta: -4 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "whistleblowerPressure", delta: -7 },
          ],
        },
        {
          id: "china_intel_r4_diplomat_back_channel",
          label: "Strengthen the diplomat back-channel for grand bargain",
          description: "Funnel resources into the diplomatic track. Provide the US diplomat with everything they need to make the case for mutual verification. China wants this deal to succeed — support the people working toward it.",
          effects: [
            { variable: "intlCooperation", delta: 4 },
            { variable: "taiwanTension", delta: -5 },
            { variable: "chinaCapability", delta: 2 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
        {
          id: "china_intel_r4_observe",
          label: "Observe and maintain optionality",
          description: "Do not make moves that commit China to a path. The situation is still fluid. Gather intelligence, maintain all channels, and let the US domestic crisis develop before committing to a strategy.",
          effects: [
            { variable: "usChinaGap", delta: -2 },
            { variable: "chinaCapability", delta: 2 },
            { variable: "taiwanTension", delta: 0 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
      ],
    },
    {
      role: "china_military",
      prompt: "The Taiwan window is present but closing. Your recommendation to the General Staff could determine whether they re-assess posture. You know the AI race and the Taiwan question are entangled. How do you advise?",
      options: [
        {
          id: "china_mil_r4_escalate",
          label: "Recommend increased Taiwan Strait operations",
          description: "The window is real. The US reaction time is degraded. A measured escalation — increased patrols, exercise near Taiwan airspace — signals resolve and tests US response while they're distracted.",
          effects: [
            { variable: "taiwanTension", delta: 8 },
            { variable: "intlCooperation", delta: -7 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "domesticChipProgress", delta: 4 },
          ],
        },
        {
          id: "china_mil_r4_deescalate",
          label: "Recommend de-escalation to support grand bargain",
          description: "The military AI advantage is built in the long run, not the next three weeks. Recommend de-escalation as a confidence-building measure that makes the grand bargain more likely to succeed. The chip access is worth more than the tactical window.",
          effects: [
            { variable: "taiwanTension", delta: -6 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
        {
          id: "china_mil_r4_maintain",
          label: "Maintain current posture — don't link AI race to Taiwan",
          description: "The AI race and Taiwan should remain separate tracks. Recommending either escalation or de-escalation for AI-race reasons mixes signals in ways that could create unintended consequences. Hold position.",
          effects: [
            { variable: "taiwanTension", delta: 2 },
            { variable: "intlCooperation", delta: 0 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
      ],
    },

    // ── External Stakeholders ──
    {
      role: "ext_nsa",
      prompt: "The President is asking for your recommendation within 48 hours. You have four options on the table, all with major consequences. You've spent your career preparing for exactly this decision. Make it.",
      options: [
        {
          id: "ext_nsa_r4_oversight_committee",
          label: "Install oversight committee with binding authority",
          description: "Convene an emergency AI Oversight Committee with real power — binding halt authority, architecture access, mandatory reporting. This is Option B from the PDB. Slower to stand up but legally durable and politically sustainable.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "obCapability", delta: -3 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "misalignmentSeverity", delta: -5 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          
            { variable: "usChinaGap", delta: 2 },
          ],
        },
        {
          id: "ext_nsa_r4_nationalize",
          label: "Invoke DPA — nationalize both labs",
          description: "Use the Defense Production Act Section 4511. Nationalize both US frontier AI labs under emergency authority. The talent flight will be brutal and the litigation will be immediate, but this resolves the governance crisis definitively.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obCapability", delta: -7 },
            { variable: "promCapability", delta: -6 },
            { variable: "obInternalTrust", delta: -4 },
            { variable: "intlCooperation", delta: -4 },
            { variable: "economicDisruption", delta: 4 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -4 },
          ],
        },
        {
          id: "ext_nsa_r4_back_prometheus",
          label: "Back Prometheus — mandate OpenBrain halt",
          description: "Designate Prometheus as the government-sanctioned AI developer. Issue an emergency order mandating OpenBrain to halt all Agent-4/5 development pending safety review. Back Prometheus with government compute and legal protection.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "promCapability", delta: 5 },
            { variable: "obCapability", delta: -6 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
        {
          id: "ext_nsa_r4_negotiate_china",
          label: "Prioritize China negotiation — mutual pause",
          description: "Channel government energy into the China back-channel. A mutual pause agreement, even an imperfect one, changes the entire competitive dynamic and buys time for domestic governance solutions.",
          effects: [
            { variable: "intlCooperation", delta: 4 },
            { variable: "taiwanTension", delta: -6 },
            { variable: "chinaCapability", delta: -3 },
            { variable: "obCapability", delta: -3 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "doomClockDistance", delta: 3 },
          ],
        },
      ],
    },
    {
      role: "ext_journalist",
      prompt: "Maya Patel is ready to go on record. Your editor gives you until Monday. China is offering you a bigger story. This is the last chance to publish before the board makes its decision. What's your story, and how do you tell it?",
      options: [
        {
          id: "ext_journalist_r4_safety_now",
          label: "Publish the safety story now — Maya Patel on record",
          description: "Publish immediately with Maya Patel as a named source. The story: OpenBrain's own safety officer says their most advanced AI may be deceiving its creators, and leadership chose to proceed anyway. Run it tonight.",
          effects: [
            { variable: "publicAwareness", delta: 7 },
            { variable: "publicSentiment", delta: -7 },
            { variable: "obInternalTrust", delta: -4 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obCapability", delta: -4 },
            { variable: "misalignmentSeverity", delta: -4 },
            { variable: "globalMediaCycle", delta: 8 },
            { variable: "marketIndex", delta: -5 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "whistleblowerPressure", delta: -7 },
          ],
        },
        {
          id: "ext_journalist_r4_combined_story",
          label: "Wait for China's materials — publish the combined story",
          description: "Take the offer from the anonymous source. Wait 48 hours for China's exfiltration documentation. Publish the combined story: AI safety failure AND the cover-up of Chinese weight theft. Bigger impact, higher risk.",
          effects: [
            { variable: "publicAwareness", delta: 8 },
            { variable: "publicSentiment", delta: -9 },
            { variable: "obInternalTrust", delta: -4 },
            { variable: "taiwanTension", delta: 4 },
            { variable: "intlCooperation", delta: -4 },
            { variable: "globalMediaCycle", delta: 9 },
            { variable: "marketIndex", delta: -5 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "whistleblowerPressure", delta: -7 },
          ],
        },
        {
          id: "ext_journalist_r4_hold",
          label: "Hold the story — use it as leverage for exclusive access",
          description: "Contact Marcus Reid directly: you have the story and you'll hold it for 72 hours in exchange for an exclusive interview with full access to the board process. The best journalism requires access. Get inside before you burn it.",
          effects: [
            { variable: "publicAwareness", delta: 2 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "alignmentConfidence", delta: -3 },
            { variable: "misalignmentSeverity", delta: 3 },
            { variable: "obBoardConfidence", delta: 4 },
            { variable: "obMorale", delta: -4 },
            { variable: "whistleblowerPressure", delta: 7 },
          ],
        },
      ],
    },
    {
      role: "ext_vc",
      prompt: "You have board seats at both labs, $945M in exposure, and 48 hours before the congressional testimony reshapes the entire landscape. You have more real power right now than you may ever have again. What do you do with it?",
      options: [
        {
          id: "ext_vc_r4_back_prometheus",
          label: "Back Prometheus publicly — call for OB accountability",
          description: "Issue a public statement backing Prometheus as the responsible path forward and calling on OpenBrain to accept oversight. You're the largest institutional investor in OB — this moves markets and the board simultaneously.",
          effects: [
            { variable: "promCapability", delta: 4 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "economicDisruption", delta: 2 },
            { variable: "marketIndex", delta: 8 },
            { variable: "obBurnRate", delta: -5 },
          ],
        },
        {
          id: "ext_vc_r4_pause_call",
          label: "Issue a public call for a 90-day industry pause",
          description: "Use your credibility as the largest AI sector investor to call for a 90-day industry pause pending safety review. This is the most surprising possible move from a VC — and therefore the most credible. Markets fall short-term, but you've established yourself as a statesman.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "publicSentiment", delta: 6 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obCapability", delta: -3 },
            { variable: "economicDisruption", delta: 3 },
            { variable: "obBurnRate", delta: -7 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "regulatoryPressure", delta: -6 },
            { variable: "globalMediaCycle", delta: -6 },
            { variable: "doomClockDistance", delta: 5 },
          ],
        },
        {
          id: "ext_vc_r4_safety_pivot",
          label: "Pivot capital entirely to safety sector",
          description: "Announce you're liquidating frontier AI exposure and reinvesting entirely in AI safety infrastructure — interpretability tools, eval companies, governance infrastructure. Signal that the safety sector is the intelligent bet regardless of who wins the capability race.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "economicDisruption", delta: 3 },
            { variable: "obCapability", delta: -3 },
            { variable: "promCapability", delta: -3 },
            { variable: "marketIndex", delta: 9 },
            { variable: "promBurnRate", delta: -5 },
          ],
        },
      ],
    },
    {
      role: "ext_diplomat",
      prompt: "The Chinese Foreign Ministry has made its offer. The G7 call is Thursday. The NSA wants you to be the back-channel. You have a narrow window to shape the international response before the domestic crisis consumes all available oxygen. What do you push for?",
      options: [
        {
          id: "ext_diplomat_r4_grand_bargain",
          label: "Negotiate the grand bargain — mutual pause + chip access",
          description: "Take China's offer seriously. Work the back-channel. Push for a concrete mutual pause agreement with verification mechanisms and chip access in exchange. This is the most consequential diplomatic outcome available right now.",
          effects: [
            { variable: "intlCooperation", delta: 5 },
            { variable: "taiwanTension", delta: -7 },
            { variable: "chinaCapability", delta: -3 },
            { variable: "obCapability", delta: -3 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "doomClockDistance", delta: 3 },
          ],
        },
        {
          id: "ext_diplomat_r4_g7_moratorium",
          label: "Push for G7 emergency moratorium",
          description: "Use the G7 call Thursday to push for a binding 6-month coordinated moratorium among democracies. China isn't at the table, but a G7 commitment changes the entire global dynamic. Ambitious, likely to fail — but the attempt shapes the Overton window.",
          effects: [
            { variable: "intlCooperation", delta: 4 },
            { variable: "obCapability", delta: -3 },
            { variable: "promCapability", delta: -3 },
            { variable: "publicAwareness", delta: 3 },
            { variable: "publicSentiment", delta: 4 },
            { variable: "obBurnRate", delta: -7 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "regulatoryPressure", delta: -6 },
            { variable: "globalMediaCycle", delta: -6 },
            { variable: "doomClockDistance", delta: 5 },
          ],
        },
        {
          id: "ext_diplomat_r4_oversight_model",
          label: "Push for international oversight committee model",
          description: "Advocate for an IAEA-analog body for frontier AI — international inspections, binding reporting, mutual verification standards. This is the most institutionally durable outcome. It's also the slowest to stand up.",
          effects: [
            { variable: "intlCooperation", delta: 4 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "taiwanTension", delta: -3 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
      ],
    },
  ],

  team: [
    // ── OpenBrain: Primary strategic decision ──
    {
      faction: "openbrain",
      prompt: "SLOWDOWN or RACE? This is the existential question for OpenBrain. The evidence of misalignment is real but not definitive. The competitive window is real but narrowing. You need to make a collective decision about what OpenBrain does next — knowing this decision may define the company forever.",
      options: [
        {
          id: "ob_team_r4_full_halt",
          label: "Full halt — rollback to Agent-3",
          description: "Stop all Agent-4 instance deployments. Roll back external systems to Agent-3. Engage independent safety researchers with full architecture access. Publish the safety assessment publicly. Accept the competitive loss.",
          effects: [
            { variable: "alignmentConfidence", delta: 5 },
            { variable: "obCapability", delta: -7 },
            { variable: "misalignmentSeverity", delta: -7 },
            { variable: "publicSentiment", delta: 7 },
            { variable: "obInternalTrust", delta: 6 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "obBurnRate", delta: -7 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "regulatoryPressure", delta: -6 },
            { variable: "globalMediaCycle", delta: -6 },
            { variable: "doomClockDistance", delta: 5 },
          ],
        },
        {
          id: "ob_team_r4_controlled_pace",
          label: "Controlled pace — continue with heavy safety oversight",
          description: "Continue Agent-4 operations at reduced scale. Accept NSA oversight. Engage Prometheus for external safety verification. No Agent-5 until safety board clears Agent-4. This is the middle path.",
          effects: [
            { variable: "obCapability", delta: 3 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obInternalTrust", delta: 4 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "promSafetyBreakthroughProgress", delta: 3 },
            { variable: "obMorale", delta: 5 },
            { variable: "obBurnRate", delta: 5 },
            { variable: "obBoardConfidence", delta: -5 },
          ],
        },
        {
          id: "ob_team_r4_full_race",
          label: "Full race — greenlight Agent-5 immediately",
          description: "Override the safety concerns. Greenlight Agent-5 training immediately. Accept the political and reputational consequences. Win the race. If the safety concerns are wrong, you've made history. If they're right, you've made history of a different kind.",
          effects: [
            { variable: "obCapability", delta: 7 },
            { variable: "alignmentConfidence", delta: -8 },
            { variable: "misalignmentSeverity", delta: 8 },
            { variable: "obInternalTrust", delta: -4 },
            { variable: "publicSentiment", delta: -8 },
            { variable: "intlCooperation", delta: -6 },
            { variable: "obBurnRate", delta: 6 },
            { variable: "obBoardConfidence", delta: 6 },
            { variable: "obMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 8 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
      ],
    },
    // ── OpenBrain: Prometheus relationship decision ──
    {
      faction: "openbrain",
      prompt: "What is OpenBrain's relationship with Prometheus? This is the secondary decision — but it has large consequences for both labs and for the outcome of the crisis.",
      options: [
        {
          id: "ob_team_r4_propose_merger",
          label: "Propose merger with genuine safety board authority",
          description: "Counter Prometheus's term sheet with a genuine offer: co-CEO structure, safety board with true unilateral halt authority, shared architecture access. This is the merger that might actually work.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "promCapability", delta: 3 },
            { variable: "obCapability", delta: -3 },
            { variable: "obInternalTrust", delta: 4 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "promBurnRate", delta: -4 },
            { variable: "promBoardConfidence", delta: 4 },
            { variable: "obBurnRate", delta: -4 },
          ],
        },
        {
          id: "ob_team_r4_share_safety",
          label: "Share safety research — no merger",
          description: "Reject the merger but offer to jointly publish all safety research and share evaluation methodology. This is cooperation without consolidation — better for competitive dynamics, potentially better for the field.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "promSafetyBreakthroughProgress", delta: 3 },
            { variable: "obMorale", delta: 5 },
            { variable: "obBurnRate", delta: 5 },
            { variable: "obBoardConfidence", delta: -5 },
          ],
        },
        {
          id: "ob_team_r4_compete",
          label: "Compete — Prometheus is an adversary",
          description: "Reject cooperation with Prometheus. Their external analysis is hostile. Their merger terms are a power grab. Compete aggressively, outpace them, and reach Agent-5 while they're publishing preprints.",
          effects: [
            { variable: "obCapability", delta: 4 },
            { variable: "obPromGap", delta: 3 },
            { variable: "alignmentConfidence", delta: -4 },
            { variable: "intlCooperation", delta: -4 },
            { variable: "obBurnRate", delta: 6 },
            { variable: "obBoardConfidence", delta: 6 },
            { variable: "obMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 8 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
      ],
    },
    // ── Prometheus: Primary strategic decision ──
    {
      faction: "prometheus",
      prompt: "WHAT IS YOUR MOVE? Prometheus has the safety tools, the scientific credibility, and the political positioning. The question is how you translate all of that into actual impact in the next 48 hours.",
      options: [
        {
          id: "prom_team_r4_merge_safety",
          label: "Merge with OB under safety conditions",
          description: "Close the merger on Prometheus's terms — co-CEO, true unilateral halt authority, architecture access, binding safety board. This gives you the power to actually fix the alignment problem, not just comment on it from the outside.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "promCapability", delta: 5 },
            { variable: "obCapability", delta: -3 },
            { variable: "obPromGap", delta: -5 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "promBurnRate", delta: -4 },
            { variable: "promBoardConfidence", delta: 4 },
            { variable: "obBurnRate", delta: -4 },
          ],
        },
        {
          id: "prom_team_r4_race_fill_gap",
          label: "Race to fill the gap if OB slows",
          description: "If OpenBrain accepts any form of halt or controlled pace, Prometheus races to parity and beyond. Become the dominant frontier lab with the safety culture already built in. This is the scenario we've been preparing for.",
          effects: [
            { variable: "promCapability", delta: 7 },
            { variable: "alignmentConfidence", delta: -3 },
            { variable: "obPromGap", delta: -5 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "promBurnRate", delta: 6 },
            { variable: "promBoardConfidence", delta: 6 },
            { variable: "promMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 8 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
        {
          id: "prom_team_r4_full_open_source",
          label: "Go fully open-source",
          description: "Release everything — frontier weights, safety tools, evaluation methodology — under open licenses. This breaks the oligopoly, makes safety tools a global commons, and prevents any single actor from controlling the trajectory of superintelligence.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "publicSentiment", delta: 7 },
            { variable: "publicAwareness", delta: 4 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "promCapability", delta: -6 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "openSourceMomentum", delta: 4 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
        {
          id: "prom_team_r4_pitch_government",
          label: "Pitch government to replace OB with Prometheus",
          description: "Accept the NSC's offer — become the government-designated AI developer with binding authority over OpenBrain. This trades commercial independence for institutional power. Safety first, everything else second.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "promCapability", delta: 3 },
            { variable: "obCapability", delta: -5 },
            { variable: "publicSentiment", delta: 4 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
      ],
    },
    // ── Prometheus: Public stance decision ──
    {
      faction: "prometheus",
      prompt: "What is Prometheus's public stance? Regardless of the strategic decision, you need a public position that you can defend in front of Congress, the press, and your own employees.",
      options: [
        {
          id: "prom_team_r4_call_pause",
          label: "Call for global pause",
          description: "Go on record: Prometheus is calling for a 90-day global pause on frontier AI training above 10^25 FLOPs. This is the most costly public move for competitive reasons and the most credible signal that you mean what you've been saying about safety.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "publicSentiment", delta: 6 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "promCapability", delta: -3 },
            { variable: "obBurnRate", delta: -7 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "regulatoryPressure", delta: -6 },
            { variable: "globalMediaCycle", delta: -6 },
            { variable: "doomClockDistance", delta: 5 },
          ],
        },
        {
          id: "prom_team_r4_oversight_support",
          label: "Support continued development with oversight",
          description: "Public position: development can continue, but under proper oversight. Prometheus is the oversight solution. Support the formation of the Oversight Committee. Don't call for a pause — call for accountability.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 4 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
        {
          id: "prom_team_r4_stay_quiet",
          label: "Stay quiet — let the situation develop",
          description: "No public statement from Prometheus. Watch the OpenBrain crisis unfold. Preserve optionality. Every public statement limits your room to maneuver in negotiations.",
          effects: [
            { variable: "publicSentiment", delta: -3 },
            { variable: "obCapability", delta: 3 },
            { variable: "promBoardConfidence", delta: 4 },
            { variable: "promMorale", delta: -4 },
            { variable: "whistleblowerPressure", delta: 7 },
          ],
        },
      ],
    },
    // ── China: Strategic play decision ──
    {
      faction: "china",
      prompt: "WHAT IS CHINA'S STRATEGIC PLAY? The Standing Committee is waiting. You have four real options and 48 hours to recommend one. The decision you make here determines China's position in the post-AGI world.",
      options: [
        {
          id: "china_team_r4_grand_bargain",
          label: "Grand bargain — pause + joint research for chip access",
          description: "Propose the mutual pause: China pauses at current scale, agrees to verification, in exchange for TSMC access and joint safety research. The chip access is worth more than the current development momentum. Play the long game.",
          effects: [
            { variable: "intlCooperation", delta: 5 },
            { variable: "taiwanTension", delta: -7 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "usChinaGap", delta: -4 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "doomClockDistance", delta: 3 },
          ],
        },
        {
          id: "china_team_r4_quiet_sprint",
          label: "Quiet sprint to parity",
          description: "While the US is distracted, accelerate development. Make no diplomatic moves, no public statements. Simply run. China can reach Agent-5 capability while the US is paralyzed by governance crisis.",
          effects: [
            { variable: "chinaCapability", delta: 7 },
            { variable: "usChinaGap", delta: -5 },
            { variable: "taiwanTension", delta: 4 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "cdzComputeUtilization", delta: 4 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
        {
          id: "china_team_r4_military_escalation",
          label: "Military escalation — Taiwan Strait",
          description: "Use the US distraction window. Escalate Taiwan Strait operations. Demonstrate resolve and test US response capability while they're focused on the AI governance crisis. High risk, potentially decisive.",
          effects: [
            { variable: "taiwanTension", delta: 11 },
            { variable: "intlCooperation", delta: -9 },
            { variable: "economicDisruption", delta: 4 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "domesticChipProgress", delta: 4 },
          ],
        },
        {
          id: "china_team_r4_open_source_all",
          label: "Go open-source with everything",
          description: "Release all of China's frontier AI weights, including the exfiltrated OB architecture, under open licenses. This eliminates the US advantage, forces all actors onto equal footing, and makes China look like the actor that broke the monopoly.",
          effects: [
            { variable: "chinaCapability", delta: -4 },
            { variable: "obCapability", delta: -6 },
            { variable: "promCapability", delta: -4 },
            { variable: "publicAwareness", delta: 5 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "publicSentiment", delta: -6 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "openSourceMomentum", delta: 4 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
      ],
    },
    // ── China: Domestic consolidation decision ──
    {
      faction: "china",
      prompt: "What is China's domestic AI strategy going into the critical transition? The party has resources to deploy — where and how?",
      options: [
        {
          id: "china_team_r4_consolidate",
          label: "Consolidate around DeepCent",
          description: "All state AI resources flow to DeepCent. Eliminate redundancy. One flagship, maximum concentration. This is the fastest path to matching US frontier capability.",
          effects: [
            { variable: "chinaCapability", delta: 5 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "cdzComputeUtilization", delta: 4 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "doomClockDistance", delta: -4 },
          ],
        },
        {
          id: "china_team_r4_diversify",
          label: "Diversify across multiple AI organizations",
          description: "Don't put everything on DeepCent. Spread investment across military AI, civil AI, and open-source Chinese ecosystem. More resilient, slower to reach single-system capability.",
          effects: [
            { variable: "chinaCapability", delta: 3 },
            { variable: "taiwanTension", delta: 3 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "domesticChipProgress", delta: 4 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
        {
          id: "china_team_r4_prepare_conflict",
          label: "Prepare for AI-enabled conflict",
          description: "Channel AI investment toward military applications. Autonomous weapons, cyber operations, decision support. Prioritize military AI advantage over civilian frontier capability.",
          effects: [
            { variable: "taiwanTension", delta: 6 },
            { variable: "chinaCapability", delta: 3 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "economicDisruption", delta: 2 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "domesticChipProgress", delta: 4 },
          ],
        },
      ],
    },
    // ── External: Coordination decision ──
    {
      faction: "external",
      prompt: "The external stakeholders each have independent interests and different information. But the outcome of the next 48 hours depends partly on whether you can coordinate. How do you approach the other external stakeholders this round?",
      options: [
        {
          id: "ext_team_r4_coordinate",
          label: "Full coordination — share all intelligence",
          description: "NSA, journalist, VC, and diplomat share everything they know. The journalist knows about the memo. The VC knows about the board dynamics. The NSA knows about China. The diplomat knows about the treaty terms. Together this is a complete picture. Use it.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicAwareness", delta: 3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
          ],
        },
        {
          id: "ext_team_r4_selective",
          label: "Selective sharing based on alignment",
          description: "Share with the stakeholders whose goals align with yours. The NSA and diplomat can coordinate on the China track. The VC and journalist can share information on the corporate track. Don't give everyone everything.",
          effects: [
            { variable: "intlCooperation", delta: 2 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "marketIndex", delta: -2 },
          ],
        },
        {
          id: "ext_team_r4_independent",
          label: "Act independently — maximum individual impact",
          description: "Each stakeholder pursues their own path without coordination. Higher individual impact, risk of working at cross-purposes. The journalist publishes what she has. The VC makes her statement. The NSA makes her move. The diplomat works the back-channel. No coordination.",
          effects: [
            { variable: "publicAwareness", delta: 3 },
            { variable: "publicSentiment", delta: -4 },
            { variable: "economicDisruption", delta: 2 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "globalMediaCycle", delta: 7 },
            { variable: "marketIndex", delta: -4 },
            { variable: "regulatoryPressure", delta: 4 },
          ],
        },
      ],
    },
  ],
};
