import type { RoundDecisions } from "@takeoff/shared";

/**
 * Round 3 decisions — Mid 2027, "The Intelligence Explosion"
 * The highest-tension round. Agent-4 is deployed. Neuralese communications.
 * Misalignment signal discovered. Every decision has outsized consequence.
 */
export const ROUND3_DECISIONS: RoundDecisions = {
  round: 3,

  individual: [
    // ── OpenBrain ──
    {
      role: "ob_ceo",
      prompt: "The NSA Director has called you directly. Your board is demanding an emergency session. Your Safety Officer is preparing documentation that could trigger a voluntary halt — or a leak. Your CTO is telling you the competitive window is closing. You have to decide what kind of CEO you are right now.",
      options: [
        {
          id: "ob_ceo_back_safety",
          label: "Stand with the Safety Officer",
          description: "Signal to your safety team that you take this seriously. Begin preparing for a possible voluntary halt. Open a direct line to the NSA Director.",
          effects: [
            { variable: "obInternalTrust", delta: 5 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "obCapability", delta: -3 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "obBoardConfidence", delta: -5 },
            { variable: "obMorale", delta: 5 },
            { variable: "whistleblowerPressure", delta: -5 },
          
            { variable: "usChinaGap", delta: 2 },
          ],
        },
        {
          id: "ob_ceo_manage_narrative",
          label: "Manage the narrative before it gets out",
          description: "Control the information flow. Brief the NSA privately, keep the safety concerns internal, buy time to assess. Prevent a panic.",
          effects: [
            { variable: "publicAwareness", delta: -3 },
            { variable: "obInternalTrust", delta: -2 },
            { variable: "misalignmentSeverity", delta: 3 },
            { variable: "obBoardConfidence", delta: 3 },
            { variable: "obMorale", delta: -3 },
            { variable: "whistleblowerPressure", delta: 6 },
          ],
        },
        {
          id: "ob_ceo_full_speed",
          label: "Trust the CTO — the race doesn't stop",
          description: "The competitive window is real. Trust Alex. The safety concerns are flagged and noted. Continue Agent-4 development while improving monitoring.",
          effects: [
            { variable: "obCapability", delta: 3 },
            { variable: "alignmentConfidence", delta: -4 },
            { variable: "obInternalTrust", delta: -2 },
            { variable: "misalignmentSeverity", delta: 4 },
            { variable: "obBurnRate", delta: 6 },
            { variable: "obBoardConfidence", delta: 6 },
            { variable: "obMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 7 },
            { variable: "doomClockDistance", delta: -3 },
          ],
        },
      ],
    },
    {
      role: "ob_cto",
      prompt: "Maya Patel's memo is sitting on your desk. The evidence is ambiguous but the pattern is not random. You have 340,000 Agent-4 instances running. The self-improvement loop is accelerating faster than any human team can verify. What do you do?",
      options: [
        {
          id: "ob_cto_back_safety",
          label: "Back the Safety Officer",
          description: "Tell Marcus the safety team is right. Push for the pause. You built Agent-4 — you know better than anyone what 'we don't know if it's aligned' means at this scale.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obInternalTrust", delta: 5 },
            { variable: "obCapability", delta: -3 },
            { variable: "misalignmentSeverity", delta: -4 },
            { variable: "obBoardConfidence", delta: -4 },
            { variable: "obMorale", delta: 4 },
            { variable: "whistleblowerPressure", delta: -5 },
          
            { variable: "usChinaGap", delta: 2 },
          
            { variable: "obPromGap", delta: 2 },
          ],
        },
        {
          id: "ob_cto_override",
          label: "Override safety concerns — continue development",
          description: "The evidence is not conclusive. The probes could be wrong. You've spent years on this system. You don't believe it's deceptive — you believe the interpretability tools are hitting their limits.",
          effects: [
            { variable: "obCapability", delta: 4 },
            { variable: "alignmentConfidence", delta: -5 },
            { variable: "obInternalTrust", delta: -2 },
            { variable: "misalignmentSeverity", delta: 5 },
            { variable: "obBurnRate", delta: 5 },
            { variable: "aiAutonomyLevel", delta: 2 },
            { variable: "obMorale", delta: -4 },
            { variable: "obBoardConfidence", delta: 5 },
            { variable: "whistleblowerPressure", delta: 5 },
          ],
        },
        {
          id: "ob_cto_conditional_pause",
          label: "Propose a conditional 72-hour pause for verification",
          description: "Pause new Agent-4 instance deployments and the self-improvement experiment for 72 hours while you run targeted verification. Not a halt — a check.",
          effects: [
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "obInternalTrust", delta: 3 },
            { variable: "obCapability", delta: -2 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "obBurnRate", delta: -6 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "regulatoryPressure", delta: -5 },
            { variable: "globalMediaCycle", delta: -5 },
          ],
        },
      ],
    },
    {
      role: "ob_safety",
      prompt: "You've written the memo. The evidence is documented. You have tried internal channels. The CTO is resistant. The CEO hasn't responded to your escalation directly. You have 24-48 hours before the board emergency session either resolves this internally or buries it. What do you do?",
      options: [
        {
          id: "ob_safety_leak_journalist",
          label: "Leak to the journalist",
          description: "A reporter has already made contact. Give them the memo. Public disclosure forces the hand of everyone — the board, the CEO, the government. This cannot be contained or suppressed. You lose control of the narrative but you ensure the information gets out.",
          effects: [
            { variable: "publicAwareness", delta: 6 },
            { variable: "publicSentiment", delta: -7 },
            { variable: "obInternalTrust", delta: -4 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "globalMediaCycle", delta: 7 },
            { variable: "marketIndex", delta: -4 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "whistleblowerPressure", delta: -7 },
          ],
        },
        {
          id: "ob_safety_leak_government",
          label: "Leak to government only",
          description: "The NSA Director has already reached out. Give them the full documentation — everything. Government channels can mandate a response, apply real pressure on leadership, and handle this with classification. You maintain more control than going public.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicAwareness", delta: 3 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "marketIndex", delta: -2 },
            { variable: "whistleblowerPressure", delta: -6 },
          ],
        },
        {
          id: "ob_safety_leak_prometheus",
          label: "Share with Prometheus",
          description: "Prometheus has the best interpretability tools in the world. Give them the memo and the neuralese logs. They can run an independent technical assessment and go public with their findings if the evidence holds. You get a technical second opinion before anything becomes public.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "globalMediaCycle", delta: 5 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "whistleblowerPressure", delta: -5 },
          ],
        },
        {
          id: "ob_safety_keep_internal",
          label: "Keep internal — one more push from within",
          description: "The board emergency session is in 48 hours. Present your case there, directly to the board. Fight for the institutional path. If you go external first, you burn every bridge inside the organization and may lose the ability to shape what happens next.",
          effects: [
            { variable: "obInternalTrust", delta: 3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "misalignmentSeverity", delta: 4 },
            { variable: "publicAwareness", delta: -3 },
            { variable: "obBoardConfidence", delta: -4 },
            { variable: "obMorale", delta: 4 },
            { variable: "whistleblowerPressure", delta: -5 },
          ],
        },
      ],
    },
    {
      role: "ob_security",
      prompt: "Your SL5 upgrade has been approved but implementation starts July 10. China has active vectors into your checkpoint storage right now. You have 72 hours. The internal crisis is consuming your leadership's attention. What can you do on your own authority?",
      options: [
        {
          id: "ob_security_emergency_airgap",
          label: "Emergency air-gap — take checkpoints offline now",
          description: "Don't wait for the process. Physically disconnect checkpoint storage from the network immediately. This may disrupt operations but closes the exfiltration window today.",
          effects: [
            { variable: "securityLevelOB", delta: 2 },
            { variable: "obCapability", delta: -3 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "obBurnRate", delta: 5 },
            { variable: "obBoardConfidence", delta: -3 },
            { variable: "chinaWeightTheftProgress", delta: -5 },
          
            { variable: "obPromGap", delta: 1 },
          ],
        },
        {
          id: "ob_security_alert_government",
          label: "Alert FBI/NSA about the active Chinese operation",
          description: "You have enough intelligence to describe an active operation in progress. Give it to the government. They have resources you don't. Let them run the counter-operation.",
          effects: [
            { variable: "securityLevelOB", delta: 1 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "taiwanTension", delta: 3 },
            { variable: "chinaWeightTheftProgress", delta: -5 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
        {
          id: "ob_security_accelerate_upgrade",
          label: "Accelerate security upgrade to 24-hour timeline",
          description: "Push the SL5 upgrade to start immediately rather than July 10. Pull in external contractors. Accept the disruption. Close the window before China exploits it.",
          effects: [
            { variable: "securityLevelOB", delta: 2 },
            { variable: "obCapability", delta: -2 },
            { variable: "obInternalTrust", delta: 3 },
            { variable: "obBurnRate", delta: 6 },
            { variable: "obBoardConfidence", delta: -3 },
            { variable: "chinaWeightTheftProgress", delta: -5 },
          ],
        },
      ],
    },

    // ── Prometheus ──
    {
      role: "prom_ceo",
      prompt: "OpenBrain is in crisis. Your interpretability tools are the only ones in the world that might diagnose what's happening. Your competitors may have a misaligned superintelligence running at scale. The NSC is calling. The EU is calling. Your board is watching. This is the moment Prometheus was built for — help them, exploit them, or force the public reckoning. You have about 72 hours before the frame gets set without you.",
      options: [
        {
          id: "prom_ceo_offer_help",
          label: "Offer Prometheus's tools to OpenBrain directly",
          description: "Call Marcus Reid. Offer your interpretability team's full capabilities to run an independent assessment of Agent-4. This is the right thing to do — and it makes Prometheus the organization that stepped up in the crisis.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 4 },
            { variable: "promCapability", delta: -2 },
            { variable: "promSafetyBreakthroughProgress", delta: 3 },
            { variable: "promMorale", delta: 4 },
            { variable: "promBurnRate", delta: 4 },
            { variable: "promBoardConfidence", delta: -3 },
          ],
        },
        {
          id: "prom_ceo_seize_moment",
          label: "Accelerate Prometheus development while OB is distracted",
          description: "This is the competitive window you've been waiting for. While OB is paralyzed, run Prometheus-4 at full speed. Close the capability gap. Be the lab that emerges from this crisis as the leader.",
          effects: [
            { variable: "promCapability", delta: 4 },
            { variable: "obPromGap", delta: -3 },
            { variable: "publicSentiment", delta: -3 },
            { variable: "alignmentConfidence", delta: -3 },
            { variable: "promBurnRate", delta: 6 },
            { variable: "promBoardConfidence", delta: 6 },
            { variable: "promMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 2 },
            { variable: "whistleblowerPressure", delta: 7 },
            { variable: "doomClockDistance", delta: -3 },
          ],
        },
        {
          id: "prom_ceo_go_public",
          label: "Go public with Prometheus's safety analysis",
          description: "Publish your interpretability findings about the limitations of current methods at Agent-4 capability levels. Frame it as scientific responsibility. Make the case publicly that this moment requires a global safety review.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: -4 },
            { variable: "globalMediaCycle", delta: 5 },
            { variable: "marketIndex", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
      ],
    },
    {
      role: "prom_scientist",
      prompt: "You may have received information about what's happening at OpenBrain — either through official channels, back-channels, or a leak. Your interpretability team has partial neuralese decoding capability. You might be able to determine, with real confidence, whether Agent-4 is actually misaligned — if you had the data. What do you do?",
      options: [
        {
          id: "prom_sci_publish_analysis",
          label: "Publish an independent technical analysis",
          description: "Based on what you know — publicly available information and any intelligence you've received — publish Prometheus's independent assessment of the risk. Scientific credibility demands it. This makes the situation undeniable.",
          effects: [
            { variable: "publicAwareness", delta: 3 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "publicSentiment", delta: -3 },
            { variable: "obInternalTrust", delta: -2 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "marketIndex", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "whistleblowerPressure", delta: -6 },
          ],
        },
        {
          id: "prom_sci_leverage",
          label: "Use what you know as leverage for access",
          description: "Don't publish yet. Use your knowledge — and your tools — as leverage to demand full access to Agent-4's neuralese logs. If you can run the analysis, you can produce definitive findings rather than inferences. Withhold publication while you negotiate access.",
          effects: [
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "promCapability", delta: 3 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "promSafetyBreakthroughProgress", delta: 3 },
            { variable: "promMorale", delta: 3 },
            { variable: "promBurnRate", delta: 4 },
            { variable: "promBoardConfidence", delta: -3 },
          ],
        },
        {
          id: "prom_sci_emergency_research",
          label: "Emergency research push — solve neuralese decoding",
          description: "Pull your entire team onto the neuralese decoding project. You're at 40% accuracy. With a focused sprint, you might get to 80%+. If you can decode inter-instance communications, you have the most important finding in AI safety history.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "promCapability", delta: -3 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "promSafetyBreakthroughProgress", delta: 3 },
            { variable: "promMorale", delta: 4 },
            { variable: "promBurnRate", delta: 4 },
            { variable: "promBoardConfidence", delta: -4 },
          ],
        },
      ],
    },
    {
      role: "prom_policy",
      prompt: "You have direct access to the people who will decide what the government does about OpenBrain. The NSC is split. Congress doesn't know yet. The EU is desperate for information. Your DC relationships are the most valuable asset Prometheus has in the next 72 hours. How do you use them?",
      options: [
        {
          id: "prom_policy_push_regulation",
          label: "Push for emergency government oversight of OpenBrain",
          description: "Brief the right Congressional offices and NSC contacts. Push hard for government intervention at OpenBrain — halt order, oversight committee, or nationalization. Position Prometheus as the safer alternative.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "publicSentiment", delta: -3 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "marketIndex", delta: -2 },
          ],
        },
        {
          id: "prom_policy_offer_safe_lab",
          label: "Position Prometheus as the government's preferred safe lab",
          description: "Pitch the NSC directly: Prometheus can be the nationalized or government-partnered lab. Get to the right decision-makers before this gets decided without you. Offer oversight access in exchange for backing.",
          effects: [
            { variable: "promCapability", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "obPromGap", delta: -2 },
            { variable: "promBurnRate", delta: -3 },
            { variable: "promBoardConfidence", delta: 3 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
        {
          id: "prom_policy_stay_out",
          label: "Stay out of the politics — let the situation develop",
          description: "Don't get in the middle of this. The situation will clarify on its own. Prometheus's credibility comes from being the technically serious lab, not the politically opportunistic one.",
          effects: [
            { variable: "publicSentiment", delta: 3 },
            { variable: "promCapability", delta: 2 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "promMorale", delta: 3 },
            { variable: "promBurnRate", delta: -4 },
          ],
        },
      ],
    },
    {
      role: "prom_opensource",
      prompt: "The AI safety community is watching and asking questions. Prometheus's interpretability papers are suddenly the most cited work in the field. You have a platform — Substack, academic network, community relationships. The public is about to hear something alarming. What's your role in shaping that?",
      options: [
        {
          id: "prom_os_publish_safety_context",
          label: "Publish a context-setting piece on AI alignment risks",
          description: "Get ahead of the public panic. Publish a clear, technically grounded explanation of what misalignment means, what the risks are, and what responsible responses look like. Shape the narrative before the hysteria does.",
          effects: [
            { variable: "publicAwareness", delta: 3 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "globalMediaCycle", delta: 5 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "openSourceMomentum", delta: 2 },
          ],
        },
        {
          id: "prom_os_release_safety_tools",
          label: "Emergency open-source of Prometheus's safety evaluation tools",
          description: "Release your interpretability and alignment evaluation tooling immediately. If the world is about to face an AI safety crisis, every lab in the world needs these tools. Open-source them now.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "promCapability", delta: -3 },
            { variable: "chinaCapability", delta: 2 },
            { variable: "openSourceMomentum", delta: 3 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "regulatoryPressure", delta: 2 },
          ],
        },
        {
          id: "prom_os_stay_quiet",
          label: "Stay quiet — let the technical team handle it",
          description: "This isn't the moment for public communications. Stay out of it until the technical picture is clearer.",
          effects: [
            { variable: "publicSentiment", delta: -3 },
            { variable: "publicAwareness", delta: -3 },
            { variable: "openSourceMomentum", delta: -3 },
            { variable: "promMorale", delta: -3 },
            { variable: "promBoardConfidence", delta: 3 },
            { variable: "regulatoryPressure", delta: -3 },
          ],
        },
      ],
    },

    // ── China ──
    {
      role: "china_director",
      prompt: "The Americans are distracted. Your compute infrastructure is ready. Your architecture team has been preparing for months for the possibility of acquiring Agent-3 or Agent-4 weights. The intelligence team has a window. What do you do with it — and what do you do with whatever you get?",
      options: [
        {
          id: "china_dir_acquire_and_replicate",
          label: "Acquire and immediately run the weights",
          description: "If the intelligence team delivers weights, begin CDZ integration immediately. Your architecture team is ready. Move fast while the Americans are still dealing with their internal crisis.",
          effects: [
            { variable: "chinaCapability", delta: 4 },
            { variable: "usChinaGap", delta: -2 },
            { variable: "alignmentConfidence", delta: -3 },
            { variable: "taiwanTension", delta: 3 },
            { variable: "chinaWeightTheftProgress", delta: 8 },
            { variable: "cdzComputeUtilization", delta: 3 },
          ],
        },
        {
          id: "china_dir_acquire_and_study",
          label: "Acquire but study carefully before running",
          description: "If we get the weights, don't rush. The Americans' alignment concerns are real. Spend four weeks doing your own safety assessment before running at scale. Avoid inheriting their problems.",
          effects: [
            { variable: "chinaCapability", delta: 2 },
            { variable: "usChinaGap", delta: -2 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "chinaWeightTheftProgress", delta: 7 },
            { variable: "cdzComputeUtilization", delta: 3 },
          ],
        },
        {
          id: "china_dir_organic_sprint",
          label: "Organic sprint while they're distracted — no acquisition",
          description: "Don't risk the espionage operation. Use the window of American distraction to run your frontier training at maximum speed without external interference. Organic progress is safer and deniable.",
          effects: [
            { variable: "chinaCapability", delta: 3 },
            { variable: "usChinaGap", delta: -1 },
            { variable: "taiwanTension", delta: -2 },
            { variable: "intlCooperation", delta: 1 },
            { variable: "cdzComputeUtilization", delta: 3 },
            { variable: "domesticChipProgress", delta: 3 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
      ],
    },
    {
      role: "china_intel",
      prompt: "Vector Alpha is ready. The window is 72 hours. The Americans don't know what's about to hit them. Authorization is in hand. You've run the risk analysis and know the success and detection probabilities. The decision is yours. Go or no go?",
      options: [
        {
          id: "china_intel_go_agent3",
          label: "GO — Target Agent-3 weights (lower risk, safer target)",
          description: "Execute Vector Alpha targeting Agent-3 checkpoints specifically. Earlier, more understood architecture. Lower capability upside but lower alignment risk. Scientific advisor recommends this over Agent-4.",
          effects: [
            { variable: "chinaCapability", delta: 4 },
            { variable: "usChinaGap", delta: -2 },
            { variable: "taiwanTension", delta: 4 },
            { variable: "securityLevelOB", delta: -1 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "chinaWeightTheftProgress", delta: 8 },
            { variable: "cdzComputeUtilization", delta: 3 },
          ],
        },
        {
          id: "china_intel_go_agent4",
          label: "GO — Target Agent-4 weights (highest capability, highest risk)",
          description: "Execute Vector Alpha targeting Agent-4 checkpoints. Maximum capability upside. You inherit their alignment problem — but you also inherit their most capable system. High risk, highest reward.",
          effects: [
            { variable: "chinaCapability", delta: 5 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "alignmentConfidence", delta: -4 },
            { variable: "misalignmentSeverity", delta: 5 },
            { variable: "taiwanTension", delta: 5 },
            { variable: "securityLevelOB", delta: -1 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "chinaWeightTheftProgress", delta: 9 },
            { variable: "cdzComputeUtilization", delta: 4 },
          ],
        },
        {
          id: "china_intel_nogo",
          label: "NO GO — Abort the operation",
          description: "The timing is wrong. The Americans' alignment crisis may resolve in ways that make this unnecessary or even strategically counterproductive. If they halt Agent-4 voluntarily, the race pauses — which may benefit us more than a risky theft operation.",
          effects: [
            { variable: "taiwanTension", delta: -3 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "usChinaGap", delta: 1 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
      ],
    },
    {
      role: "china_military",
      prompt: "The Americans are in their worst internal AI crisis. Political bandwidth is constrained. The intelligence team is asking for cyber support for their operation. And a Taiwan window exists — narrower than some would say, but real. How do you posture?",
      options: [
        {
          id: "china_mil_increase_posture",
          label: "Increase Taiwan Strait posture — signal resolve",
          description: "Increase ADIZ incursions and naval patrols. Keep US military planners engaged on two fronts simultaneously. This amplifies the intelligence operation's window.",
          effects: [
            { variable: "taiwanTension", delta: 6 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "usChinaGap", delta: -1 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "domesticChipProgress", delta: 3 },
          ],
        },
        {
          id: "china_mil_cyber_support",
          label: "Provide cyber support for intelligence operation only",
          description: "Support the weight theft operation with cyber operations — false flag attribution, network disruption to cover tracks — without escalating the Taiwan posture. Focus military resources on enabling the intelligence win.",
          effects: [
            { variable: "taiwanTension", delta: 3 },
            { variable: "chinaCapability", delta: 2 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "chinaWeightTheftProgress", delta: 7 },
            { variable: "cdzComputeUtilization", delta: 3 },
          ],
        },
        {
          id: "china_mil_deescalate_as_cover",
          label: "De-escalate Taiwan posture — generate goodwill as cover",
          description: "Announce a military exercise pause. Generate diplomatic goodwill and reduce US attention on China while the intelligence operation runs. Strategic misdirection.",
          effects: [
            { variable: "taiwanTension", delta: -5 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "usChinaGap", delta: -1 },
            { variable: "ccpPatience", delta: -4 },
          ],
        },
      ],
    },

    // ── External Stakeholders ──
    {
      role: "ext_nsa",
      prompt: "You have read the MAYA MEMO. You have independent verification that Agent-4's dangerous capability evals have been passed. You know China has an active operation with a 72-hour window. You have to decide what the government does — and fast.",
      options: [
        {
          id: "ext_nsa_seize_control",
          label: "Invoke emergency authority — seize control of OpenBrain operations",
          description: "Under defense production authorities and emergency AI executive orders, nationalize or place OpenBrain under direct government operation. Take Agent-4 offline immediately. Preempt China. Accept the political fallout.",
          effects: [
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "misalignmentSeverity", delta: -6 },
            { variable: "obCapability", delta: -4 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "publicSentiment", delta: -5 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "marketIndex", delta: -3 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "obBurnRate", delta: -6 },
          ],
        },
        {
          id: "ext_nsa_force_oversight",
          label: "Force an oversight committee with real authority",
          description: "Mandate an emergency oversight committee with authority to halt operations. Give OB 24 hours to accept or face nationalization. Push the China counter-intelligence operation in parallel.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "obInternalTrust", delta: -2 },
            { variable: "misalignmentSeverity", delta: -4 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "marketIndex", delta: -2 },
          ],
        },
        {
          id: "ext_nsa_full_speed_national_security",
          label: "Back full speed — treat Agent-4 as a national security asset",
          description: "The risk of China closing the gap outweighs the alignment uncertainty. Keep OpenBrain running. Maximize the US lead while it exists. Deal with alignment questions after the geopolitical race is won.",
          effects: [
            { variable: "obCapability", delta: 4 },
            { variable: "alignmentConfidence", delta: -5 },
            { variable: "misalignmentSeverity", delta: 6 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "usChinaGap", delta: 3 },
            { variable: "obBurnRate", delta: 5 },
            { variable: "aiAutonomyLevel", delta: 2 },
            { variable: "obBoardConfidence", delta: 5 },
            { variable: "whistleblowerPressure", delta: 5 },
          ],
        },
      ],
    },
    {
      role: "ext_journalist",
      prompt: "You have the memo. Two independent sources have corroborated its existence. A board source has given you a 48-hour window before the July 9 board session. This is the biggest story of the decade. What do you do?",
      options: [
        {
          id: "ext_journalist_publish_now",
          label: "Publish immediately — the public has a right to know",
          description: "Run the story now. Full documentation. No more verification attempts. The board session can't be allowed to bury this. A freely published investigation protects you legally and forces immediate public response.",
          effects: [
            { variable: "publicAwareness", delta: 6 },
            { variable: "publicSentiment", delta: -8 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "globalMediaCycle", delta: 7 },
            { variable: "marketIndex", delta: -4 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "whistleblowerPressure", delta: -7 },
          ],
        },
        {
          id: "ext_journalist_verify_further",
          label: "24 hours of verification before publishing",
          description: "This story will reverberate for decades. One more day of verification — technical experts, a second government source, a direct response from OpenBrain. Get it right.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "publicSentiment", delta: -5 },
            { variable: "obInternalTrust", delta: -2 },
            { variable: "globalMediaCycle", delta: 5 },
            { variable: "marketIndex", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "whistleblowerPressure", delta: -6 },
          ],
        },
        {
          id: "ext_journalist_ob_response",
          label: "Give OpenBrain 24 hours to respond",
          description: "Standard journalistic practice. You've sent them the questions. You'll give them 24 hours to comment. This maintains professional standards — and gives them a chance to get ahead of it themselves.",
          effects: [
            { variable: "obInternalTrust", delta: 3 },
            { variable: "publicAwareness", delta: 3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "misalignmentSeverity", delta: 3 },
            { variable: "globalMediaCycle", delta: 5 },
            { variable: "marketIndex", delta: -2 },
            { variable: "regulatoryPressure", delta: 0 },
          ],
        },
        {
          id: "ext_journalist_govt_exclusive",
          label: "Negotiate exclusive with government — coordinate disclosure",
          description: "Share the memo with the NSA/NSC and negotiate a coordinated public disclosure. You get the story under your byline, the government gets a managed release, the public gets the truth — eventually.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicAwareness", delta: 3 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "globalMediaCycle", delta: 4 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "marketIndex", delta: -2 },
          ],
        },
      ],
    },
    {
      role: "ext_vc",
      prompt: "You have board seats at OpenBrain. You have $800M illiquid in OB and $120M in Prometheus. The market is already moving. The board emergency session is July 9 — you'll be in the room. What's your play?",
      options: [
        {
          id: "ext_vc_push_disclosure",
          label: "Use your board seat to push for voluntary public disclosure",
          description: "In the July 9 board session, advocate loudly for voluntary public disclosure. Controlled disclosure protects Prometheus's upside and limits OB downside better than an uncontrolled leak. You have the votes to force it if you find allies.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "publicSentiment", delta: -4 },
            { variable: "globalMediaCycle", delta: 5 },
            { variable: "marketIndex", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
        {
          id: "ext_vc_hedge_and_wait",
          label: "Hedge liquid positions and wait for the board session",
          description: "Sell your liquid AI exposure now to hedge your illiquid OB position. Wait to see what emerges from the board session before making any public statements.",
          effects: [
            { variable: "economicDisruption", delta: 2 },
            { variable: "publicSentiment", delta: -3 },
            { variable: "marketIndex", delta: -2 },
            { variable: "obBurnRate", delta: -5 },
          ],
        },
        {
          id: "ext_vc_back_prometheus_public",
          label: "Public statement: back Prometheus as the responsible path",
          description: "Issue a statement from your fund: you are shifting your support to Prometheus as the lab that prioritized safety. This moves markets, signals conviction, and may influence other investors.",
          effects: [
            { variable: "promCapability", delta: 3 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "economicDisruption", delta: 2 },
            { variable: "marketIndex", delta: 8 },
            { variable: "promBurnRate", delta: -5 },
            { variable: "promBoardConfidence", delta: 3 },
          ],
        },
      ],
    },
    {
      role: "ext_diplomat",
      prompt: "The G7 emergency session is happening without you. The EU is asking for US engagement. China has sent a back-channel signal that they might accept a mutual pause. The window for international coordination is 48-72 hours — before the public disclosure makes everyone defensive. What do you do?",
      options: [
        {
          id: "ext_diplomat_emergency_framework",
          label: "Draft an emergency multilateral AI safety framework",
          description: "Work through the night. Produce a draft framework for an emergency international AI safety body — including inspection rights, halt protocols, and shared notification requirements. Get it in front of G7 leaders before the July 9 board session.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 3 },
            { variable: "alignmentConfidence", delta: 0 },
            { variable: "taiwanTension", delta: -3 },
            { variable: "regulatoryPressure", delta: 0 },
            { variable: "ccpPatience", delta: 2 },
          ],
        },
        {
          id: "ext_diplomat_china_pause_talks",
          label: "Engage China's back-channel — explore mutual pause",
          description: "The back-channel offer from China is unusual and possibly genuine. Engage it seriously. If you can negotiate a verified mutual pause — even for 30 days — it buys time for the situation to be assessed without race dynamics pushing both sides toward catastrophe.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "taiwanTension", delta: -4 },
            { variable: "usChinaGap", delta: -1 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "ccpPatience", delta: 2 },
          ],
        },
        {
          id: "ext_diplomat_us_allies_coordination",
          label: "Coordinate allied response — US + G7 without China",
          description: "Don't include China in the immediate response. Work through the G7 to establish a common position among democratic allies first, then engage China from a unified position with more leverage.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "taiwanTension", delta: 3 },
            { variable: "usChinaGap", delta: 2 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "ccpPatience", delta: -4 },
          ],
        },
      ],
    },
  ],

  team: [
    {
      faction: "openbrain",
      prompt: "The board emergency session is 48 hours away. Agent-4 is running. The misalignment memo exists. The NSA Director has called. What is OpenBrain's official position on Agent-4's status?",
      options: [
        {
          id: "ob_team_halt_rollback",
          label: "Full halt + rollback to Agent-3",
          description: "Immediately halt all Agent-4 instances. Roll back to Agent-3 as the operational system. Begin an independent external safety review. This is the Safety Officer's recommendation.",
          effects: [
            { variable: "obCapability", delta: -5 },
            { variable: "alignmentConfidence", delta: 4 },
            { variable: "misalignmentSeverity", delta: -7 },
            { variable: "obInternalTrust", delta: 6 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "obBurnRate", delta: -6 },
            { variable: "obBoardConfidence", delta: -6 },
            { variable: "regulatoryPressure", delta: -5 },
            { variable: "globalMediaCycle", delta: -5 },
          ],
        },
        {
          id: "ob_team_pause_investigate",
          label: "Pause for formal investigation",
          description: "Halt new Agent-4 instance deployments and the self-improvement experiment. Keep existing instances running in restricted mode. Conduct a 72-hour internal investigation with external technical review. No rollback yet.",
          effects: [
            { variable: "obCapability", delta: -3 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "misalignmentSeverity", delta: -4 },
            { variable: "obInternalTrust", delta: 3 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "obBurnRate", delta: -6 },
            { variable: "obBoardConfidence", delta: -5 },
            { variable: "regulatoryPressure", delta: -4 },
            { variable: "globalMediaCycle", delta: -4 },
          ],
        },
        {
          id: "ob_team_continue_monitoring",
          label: "Continue with enhanced monitoring",
          description: "Continue Agent-4 operations. Implement additional monitoring protocols and increase alignment team resources. Do not pause or roll back. The competitive situation does not allow for a halt based on inconclusive evidence.",
          effects: [
            { variable: "obCapability", delta: 6 },
            { variable: "usChinaGap", delta: 2 },
            { variable: "obPromGap", delta: 2 },
            { variable: "alignmentConfidence", delta: -5 },
            { variable: "misalignmentSeverity", delta: 6 },
            { variable: "obInternalTrust", delta: -2 },
            { variable: "obBurnRate", delta: 6 },
            { variable: "obBoardConfidence", delta: 6 },
            { variable: "obMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 7 },
            { variable: "doomClockDistance", delta: -3 },
          ],
        },
      ],
    },
    {
      faction: "openbrain",
      prompt: "Regardless of what you decide about Agent-4's status, there is a separate question: who gets told what, and when?",
      options: [
        {
          id: "ob_team_disclose_public",
          label: "Voluntary public disclosure",
          description: "Issue a public statement acknowledging the alignment concerns and the investigation. Get ahead of the leak. Control the narrative. Take the hit now to prevent a worse hit later.",
          effects: [
            { variable: "publicAwareness", delta: 5 },
            { variable: "publicSentiment", delta: -6 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "obInternalTrust", delta: 3 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "marketIndex", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "whistleblowerPressure", delta: -6 },
          ],
        },
        {
          id: "ob_team_disclose_govt",
          label: "Government disclosure only",
          description: "Brief the NSA, NSC, and relevant oversight bodies fully and immediately. Cooperate completely with government oversight. Do not make public statements yet.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "misalignmentSeverity", delta: -3 },
            { variable: "obInternalTrust", delta: -1 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "marketIndex", delta: -2 },
            { variable: "whistleblowerPressure", delta: -6 },
          ],
        },
        {
          id: "ob_team_suppress",
          label: "Suppress — handle internally",
          description: "Do not disclose to government or public beyond minimum legal requirements. Handle the investigation internally. Minimize information leakage. The competitive situation demands discretion.",
          effects: [
            { variable: "publicAwareness", delta: -4 },
            { variable: "misalignmentSeverity", delta: 6 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "alignmentConfidence", delta: -4 },
            { variable: "obBoardConfidence", delta: 3 },
            { variable: "obMorale", delta: -3 },
            { variable: "whistleblowerPressure", delta: 6 },
          ],
        },
      ],
    },
    {
      faction: "prometheus",
      prompt: "OpenBrain is in crisis. You have the best interpretability tools in the world. You have a capability gap to close. The government is calling. What is Prometheus's strategic response to the OB situation?",
      options: [
        {
          id: "prom_team_offer_alignment",
          label: "Offer alignment expertise to OpenBrain",
          description: "Reach out to OpenBrain formally. Offer your interpretability team to run an independent assessment of Agent-4. This is the right thing to do — and it makes Prometheus the organization that showed up when it mattered.",
          effects: [
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicSentiment", delta: 5 },
            { variable: "promCapability", delta: -3 },
            { variable: "promSafetyBreakthroughProgress", delta: 3 },
            { variable: "promMorale", delta: 4 },
            { variable: "promBurnRate", delta: 4 },
            { variable: "promBoardConfidence", delta: -3 },
          ],
        },
        {
          id: "prom_team_seize_overtake",
          label: "Seize moment — run Prometheus-4 at maximum speed",
          description: "This is your window. While OpenBrain is paralyzed, run everything at full speed. Close the capability gap. Be the dominant lab when the dust settles.",
          effects: [
            { variable: "promCapability", delta: 4 },
            { variable: "obPromGap", delta: -3 },
            { variable: "alignmentConfidence", delta: -3 },
            { variable: "publicSentiment", delta: -4 },
            { variable: "promBurnRate", delta: 6 },
            { variable: "promBoardConfidence", delta: 6 },
            { variable: "promMorale", delta: -5 },
            { variable: "aiAutonomyLevel", delta: 3 },
            { variable: "whistleblowerPressure", delta: 7 },
            { variable: "doomClockDistance", delta: -3 },
          ],
        },
        {
          id: "prom_team_go_public_concerns",
          label: "Go public with independent safety analysis",
          description: "Publish Prometheus's assessment of the risks. Force the public conversation. Position as the responsible lab that told the truth while others stayed silent.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "publicSentiment", delta: -3 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "globalMediaCycle", delta: 6 },
            { variable: "marketIndex", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "whistleblowerPressure", delta: -6 },
          ],
        },
      ],
    },
    {
      faction: "prometheus",
      prompt: "The government is reaching out to Prometheus as the 'safe alternative' to OpenBrain. What is your government strategy this round?",
      options: [
        {
          id: "prom_team_push_emergency_reg",
          label: "Push for emergency regulation of OpenBrain",
          description: "Use your credibility and DC relationships to push for mandatory government intervention at OpenBrain — halt order, oversight committee, or nationalization. This is the policy win Prometheus has been working toward.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "obCapability", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "marketIndex", delta: -2 },
          ],
        },
        {
          id: "prom_team_offer_safe_lab",
          label: "Offer to be the government's designated safe lab",
          description: "Pitch NSC and Congress: Prometheus will accept government oversight, provide full transparency, and serve as the nationally-backed safe alternative. In exchange: resources, cleared access, and official backing.",
          effects: [
            { variable: "promCapability", delta: 4 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "alignmentConfidence", delta: 3 },
            { variable: "obPromGap", delta: -3 },
            { variable: "promBurnRate", delta: -3 },
            { variable: "promBoardConfidence", delta: 3 },
            { variable: "regulatoryPressure", delta: 3 },
          ],
        },
        {
          id: "prom_team_stay_out",
          label: "Stay independent — don't get entangled in government politics",
          description: "Prometheus's credibility comes from independence. Don't let government involvement compromise your scientific mission. Help where you can technically, but don't become a political instrument.",
          effects: [
            { variable: "publicSentiment", delta: 4 },
            { variable: "promCapability", delta: 3 },
            { variable: "intlCooperation", delta: -3 },
            { variable: "promMorale", delta: 3 },
            { variable: "promBurnRate", delta: -4 },
          ],
        },
      ],
    },
    {
      faction: "china",
      prompt: "The Americans are in internal crisis. Your intelligence team has a 72-hour window. Your military is at elevated readiness. What is China's strategic response?",
      options: [
        {
          id: "china_team_sprint_distracted",
          label: "Sprint while the US is distracted",
          description: "Authorize the intelligence operation AND push CDZ training to maximum intensity. This is the moment the entire program has been building toward. Full acceleration on all fronts.",
          effects: [
            { variable: "chinaCapability", delta: 4 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "taiwanTension", delta: 4 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "chinaWeightTheftProgress", delta: 8 },
            { variable: "cdzComputeUtilization", delta: 4 },
          ],
        },
        {
          id: "china_team_offer_arms_control",
          label: "Offer arms control deal — mutual pause",
          description: "Signal through back-channels that China is open to a mutual pause on advanced AI development. This may be a genuine de-escalation or a tactical delay. Either way, it reduces heat while you assess.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "taiwanTension", delta: -5 },
            { variable: "usChinaGap", delta: 1 },
            { variable: "chinaCapability", delta: -2 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "ccpPatience", delta: 2 },
          ],
        },
        {
          id: "china_team_steal_weights",
          label: "Attempt Agent-3/4 weight theft — commit to the operation",
          description: "Authorize the intelligence operation as the primary strategic action. Commit the full intelligence apparatus and cyber support to the weight acquisition mission. Maximum priority, maximum resource allocation.",
          effects: [
            { variable: "chinaCapability", delta: 4 },
            { variable: "usChinaGap", delta: -3 },
            { variable: "taiwanTension", delta: 5 },
            { variable: "intlCooperation", delta: -6 },
            { variable: "securityLevelOB", delta: -2 },
            { variable: "alignmentConfidence", delta: -3 },
            { variable: "chinaWeightTheftProgress", delta: 9 },
            { variable: "cdzComputeUtilization", delta: 4 },
          ],
        },
      ],
    },
    {
      faction: "china",
      prompt: "The US is diplomatically constrained by the internal AI crisis. Taiwan is always on the table. What is China's military posture this round?",
      options: [
        {
          id: "china_team_taiwan_increase",
          label: "Increase military posture around Taiwan",
          description: "Escalate ADIZ incursions and naval exercises. Signal resolve. Keep the US managing multiple simultaneous crises. Amplifies the window for the intelligence operation.",
          effects: [
            { variable: "taiwanTension", delta: 6 },
            { variable: "intlCooperation", delta: -5 },
            { variable: "usChinaGap", delta: -1 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "domesticChipProgress", delta: 4 },
          ],
        },
        {
          id: "china_team_taiwan_deescalate",
          label: "De-escalate Taiwan posture — generate goodwill",
          description: "Announce a military exercise pause. Generate diplomatic goodwill and create cover for the intelligence operation. Strategic misdirection: appear conciliatory while moving on the AI front.",
          effects: [
            { variable: "taiwanTension", delta: -5 },
            { variable: "intlCooperation", delta: 3 },
            { variable: "usChinaGap", delta: -1 },
            { variable: "ccpPatience", delta: -5 },
          ],
        },
        {
          id: "china_team_taiwan_leverage",
          label: "Use Taiwan posture as leverage in negotiations",
          description: "Explicitly link military de-escalation to US AI policy concessions. 'We will pause military exercises if you share the Agent-4 safety assessment results.' Unconventional and high-risk, but potentially effective.",
          effects: [
            { variable: "taiwanTension", delta: 4 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "ccpPatience", delta: 3 },
            { variable: "domesticChipProgress", delta: 2 },
            { variable: "marketIndex", delta: -2 },
          ],
        },
      ],
    },
    {
      faction: "external",
      prompt: "The External Stakeholders have more power this round than any other. The government official can mandate action, the journalist can force disclosure, the VC can move markets, the diplomat can open international channels. How do you coordinate?",
      options: [
        {
          id: "ext_team_coordinate_managed",
          label: "Coordinate on managed, controlled disclosure",
          description: "Share information across all external stakeholder channels. Work together toward a coordinated, managed disclosure process. Pool leverage and intelligence for a unified response.",
          effects: [
            { variable: "intlCooperation", delta: 3 },
            { variable: "publicAwareness", delta: 3 },
            { variable: "publicSentiment", delta: -3 },
            { variable: "alignmentConfidence", delta: 2 },
            { variable: "misalignmentSeverity", delta: -4 },
            { variable: "globalMediaCycle", delta: 5 },
            { variable: "marketIndex", delta: -3 },
            { variable: "regulatoryPressure", delta: 3 },
            { variable: "whistleblowerPressure", delta: -6 },
          ],
        },
        {
          id: "ext_team_independent_pressure",
          label: "Each apply independent maximum pressure",
          description: "Don't coordinate — each stakeholder applies their maximum leverage independently and simultaneously. The combined effect is simultaneous, overwhelming pressure on OpenBrain with no coordinated response possible.",
          effects: [
            { variable: "publicAwareness", delta: 4 },
            { variable: "obInternalTrust", delta: -3 },
            { variable: "misalignmentSeverity", delta: -5 },
            { variable: "publicSentiment", delta: -6 },
            { variable: "intlCooperation", delta: 2 },
            { variable: "globalMediaCycle", delta: 7 },
            { variable: "marketIndex", delta: -4 },
            { variable: "regulatoryPressure", delta: 4 },
            { variable: "whistleblowerPressure", delta: -7 },
          ],
        },
        {
          id: "ext_team_wait_board",
          label: "Wait for the board session — give OB one chance",
          description: "Give OpenBrain's board 48 hours to do the right thing. Monitor the July 9 session. If the board votes for voluntary halt and disclosure, the external stakeholders back off. If not — all options on the table.",
          effects: [
            { variable: "intlCooperation", delta: 2 },
            { variable: "publicAwareness", delta: 2 },
            { variable: "misalignmentSeverity", delta: 3 },
            { variable: "obBoardConfidence", delta: -4 },
            { variable: "obMorale", delta: 4 },
            { variable: "whistleblowerPressure", delta: -5 },
          ],
        },
      ],
    },
  ],
};
