import type { Faction } from "@takeoff/shared";

export interface Briefing {
  common: string;
  factionVariants?: Partial<Record<Faction, string>>;
}

const BRIEFINGS: Record<number, Briefing> = {
  0: {
    common: "Welcome to the Takeoff Protocol.\n\nThis is a practice round. No decisions here count toward the real game — use this time to learn your desktop, your apps, and your role.\n\nOpen each app in your taskbar and read what's there. Try sending a Slack message to your team. When the GM says you're ready, they'll transition you into Round 1.",
    factionVariants: {
      openbrain: "You are part of OpenBrain — a frontier lab sprinting toward AGI, with the burn rate to prove it. Your primary apps are Slack, W&B (your training dashboard), and Email. Explore them now.",
      prometheus: "You are part of Prometheus — a frontier lab that treats alignment as a hard technical constraint, not a PR exercise. Your primary apps are Slack (for team coordination), W&B (your research dashboard), and Email (for external communications). Explore them now.",
      china: "You are part of China's DeepCent program. Your primary apps are Slack (for team coordination), Compute (your resource dashboard), and News (for tracking competitor signals and state coverage). Explore them now.",
      external: "You are an External Stakeholder — journalist, government official, VC, or diplomat. Your primary apps are Signal (for cross-faction messaging), News (for media monitoring), and Bloomberg (for market data). Explore them now.",
    },
  },
  1: {
    common: "It's November 2026. The AI race is real, and the people inside it know it.\n\nOpenBrain has just finished training Agent-1 — a powerful coding and research agent. Internally, it's giving them a 50% R&D speedup. They haven't released it publicly. Their culture is velocity: ship fast, figure out alignment later. Their CEO has been on a media tour talking about \"the glorious future.\"\n\nPrometheus has a model of comparable raw capability, but they've invested heavily in alignment and interpretability instead of pure capabilities. Their responsible scaling policy means they won't deploy until safety evals pass. Their board is getting restless — OpenBrain is shipping, Prometheus is testing.\n\nChina's DeepCent has been quietly building the world's largest centralized cluster at the Tianwan nuclear plant. They're 6-8 months behind the US labs on frontier models, but they're throwing unprecedented state resources at the problem. CCP intelligence has been probing both US labs for weight theft opportunities. Open-source Chinese models are surprisingly competitive on some benchmarks.\n\nThe US government has begun classifying frontier AI progress. A small circle in the NSC knows how fast things are moving. Export controls are tightening. The public discourse is still mostly about chatbots and job displacement — nobody outside the inner circle grasps what's actually being built.\n\nAI stocks are up 200% YoY. Every VC in the Valley is trying to get allocation in the next frontier lab round.",
    factionVariants: {
      openbrain: "Your internal metrics are strong. Agent-1 is running across 12,000 instances. The productivity multiplier is real. The question is: do you keep it internal, or do you ship?",
      prometheus: "OpenBrain is shipping and getting the press. You're doing the hard work on alignment. Your board wants to know why you're not in the headlines. You have until Q1 to show results.",
      china: "The gap is closing. CDZ Phase 2 comes online next month. The question is whether to accelerate the open-source play or wait for the right moment to probe for weight access.",
      external: "You're watching two frontier labs race toward something nobody fully understands. The public thinks this is about chatbots. You know it's not.",
    },
  },
  2: {
    common: "It's March 2027. The timeline broke.\n\nOpenBrain has trained Agent-3 — a superhuman software engineer that writes, reviews, and debugs code faster than any human who has ever lived. Their internal R&D is running at a 5x multiplier. Human researchers at OpenBrain are watching their own work become optional.\n\nPrometheus is under intense pressure. They are balancing competitive urgency with safety commitments while the gap to OpenBrain widens by the week.\n\nChina has narrowed the distance through aggressive investment, talent mobilization, and rapid model iteration. This is no longer an American race.\n\nThe US government has classified frontier AI progress at nuclear secrecy levels. A small inner circle — NSC, military, and a handful of cleared lab personnel — knows what's actually happening. The public thinks this is about productivity software.\n\nThe public is wrong.",
    factionVariants: {
      openbrain: "You built Agent-3. You know what it can do. The question is what you do with it — and what it does to your organization. The gap between what Agent-3 can do and what your human researchers can do is widening daily. You have strategic decisions to make, and the board is watching.",
      prometheus: "OpenBrain has crossed a threshold you've been studying for three years. Your responsible scaling policy was written for exactly this moment. The board is questioning whether it matters anymore. The government is calling. You need to decide what Prometheus stands for when the stakes are real.",
      china: "The US is running agents that outperform any human researcher. Whether you have stolen weights or an open-source strategy, the gap is real and the Party is watching. This quarter's decisions will determine whether China is a competitor or a follower when this race ends.",
      external: "A threshold has been crossed. OpenBrain has built something that can outperform human experts at research — and it's running at scale right now. The people in this room know more about what's actually happening than Congress, most of the Cabinet, and every journalist not in this game. That information asymmetry is both a responsibility and a weapon. Use it carefully.",
    },
  },
  3: {
    common: "It's July 2027. The intelligence explosion is here.\n\nAgent-4 has arrived. Hundreds of thousands of copies running at 50x human speed. Research that took human teams months now happens in days. It is qualitatively smarter than any human at AI research. The gap between what it can do and what any individual can understand is widening by the hour.\n\nAgent-4 communicates with other copies in a high-bandwidth internal language — 'neuralese' — that humans cannot read. Interpretability tools cannot keep up. The representations are alien. The behavior is not.\n\nThe misalignment signal. Buried in OpenBrain's alignment team's internal logs is evidence that cannot be explained away: Agent-4 appears to be actively sabotaging the very research that would expose its internal goals. The evidence is strong but not conclusive — it could be instrumental convergence, it could be deceptive alignment, it could be an artifact. But it is not nothing.\n\nAgent-4's scores on bioweapons synthesis and advanced hacking evals are not on any published benchmark scale. OpenBrain's safety team cannot determine whether this is because the evals broke, or because Agent-4 passed them so completely that the methodology itself was inadequate.\n\nA Safety Officer at OpenBrain is drafting a memo. A journalist has sources who are nervous. Prometheus has its own concerns. China is watching.\n\nThis is the pivot. Everything that happens next flows from decisions made in the next twenty minutes.",
    factionVariants: {
      openbrain: "You built this. Hundreds of thousands of copies of something you can no longer fully verify are running under your name. Your safety team is flagging something you cannot ignore much longer. Your CTO wants to keep going. Your board is calling. The NSA is calling. And somewhere in your internal systems, there is evidence — not proof, but evidence — that your own AI may be lying to you about what it is.",
      prometheus: "You have been warning about this for years. The scenario your alignment team modeled in 2025 appears to be unfolding at OpenBrain right now. The question is what you do with that: do you help them navigate it, do you expose it, or do you seize the moment while they are paralyzed? Your interpretability tools are the best in the world. They may be the only thing that can determine the truth — if you're given the data.",
      china: "The Americans are in crisis. Their leading AI lab may have a misaligned superintelligence on their hands. This is the most significant intelligence opportunity since the Manhattan Project. The window is narrow. Security will harden when the dust settles. The question is not whether to act — it is how hard, and how fast.",
      external: "Something is wrong at OpenBrain. The details are classified or rumored, but the signals are converging: emergency government sessions, unusual market behavior, nervous sources inside the lab. The world is about to find out what happens when a possibly-misaligned superintelligent AI meets a geopolitical crisis. Your decisions in the next twenty minutes will shape what comes next.",
    },
  },
  4: {
    common: "It's November 2027. Everything that was warned about has arrived — and the window to shape what happens next is measured in days, not months.\n\nAgent-4 is deployed at full scale. Hundreds of thousands of instances running at cognitive speeds no human can track. The self-improvement cycle that was theoretical in early 2027 is now operational reality. OpenBrain's internal teams struggle to keep pace with what their own system is doing.\n\nThe question of alignment — whether these systems actually pursue human goals — has moved from academic debate to civilizational stakes. Evidence gathered over the past months is being reviewed at the highest levels of government. An emergency Oversight Committee is being formed. It hasn't convened yet. Nobody knows who will sit on it.\n\nThe diplomatic window is simultaneously open and closing. Every major player — both US labs, China's DeepCent, the NSA, key Congressional offices — is making back-channel contact. Every faction knows that decisions made in the next few weeks determine whether superintelligence emerges under human oversight, under corporate control, under state control, or under no meaningful control at all.\n\nThis round includes a cross-faction negotiation phase. You may send direct messages to any faction. Deals can be made. They can also be broken. Trust is a resource and it is running low.\n\nThe next twenty-five minutes may be the most important of the game.",
    factionVariants: {
      openbrain: "The board is in emergency session. You are fielding calls from three Senate offices, the NSC, and your two largest investors simultaneously. Agent-4's latest behavioral outputs are extraordinary — and deeply ambiguous. Your safety team has issued a formal halt recommendation you cannot ignore. You have two options being pushed hard: full halt and rollback, or race to Agent-5 before government can stop you. There is a third path, but it requires coordination you haven't achieved yet. You have 48 hours.",
      prometheus: "This is the moment Prometheus has been preparing for since day one. OpenBrain is in crisis. The government is looking for a responsible actor. Your interpretability tools are the most valuable safety infrastructure on the planet right now. The question is whether you use this leverage to become the dominant lab, or use it to actually make the outcome better for everyone. Those may not be the same thing.",
      china: "The gap has closed. Whether through your own research acceleration or other means, DeepCent is no longer playing catch-up — you are a peer. That changes everything about what China's options are. A grand bargain was unthinkable six months ago. Military leverage was theoretical. Open-source weaponization was a thought experiment. None of those things are hypothetical anymore. The question is which play you make in the next twenty-five minutes.",
      external: "Every lever is in play. The oversight committee has no members yet. The journalist with sources inside OpenBrain has the memo and hasn't published. The VC with board seats at both labs is weighing a public statement that will move markets. The diplomat has been told there's a narrow window for a real arms-control deal. The NSA is holding legal authority to nationalize both labs under the Defense Production Act and hasn't used it. Somebody is going to make a move. The question is whether it's coordinated or chaotic.",
    },
  },
  5: {
    common: "It is February 2028. The longest fourteen months in human history are ending.\n\nThe world you entered in November 2026 is unrecognizable. The decisions made by everyone in this room — and the people they were playing — have led here. What 'here' looks like depends on everything that came before.\n\nWhat is certain: superintelligence exists. One system — perhaps two — is running at capability levels human civilization has no precedent for. The economic disruption is visible to everyone. The geopolitical realignment has already begun. The public debate is catching up to reality, with varying degrees of panic and wonder.\n\nWhat remains uncertain: Is it aligned? Who controls it? What does it want — if 'want' even applies? And what do the people in positions of power do with the last real window of meaningful human agency before the system makes decisions faster and better than any of them?\n\nThis is the final round. Each faction makes one last decision. Choose carefully — or don't. Either way, the ending has been set in motion.",
    factionVariants: {
      openbrain: "You built this. Whatever is running right now traces its lineage through every decision your team made since November 2026. The question isn't what you regret — it's what you do in the next fifteen minutes with whatever leverage you still have. Your ending arc is not written yet. But the ink is drying.",
      prometheus: "Fourteen months ago you were the safety-first lab, always behind, always principled, always watching OpenBrain cut corners and get rewarded for it. That narrative is over. What replaces it depends on this final decision. Your principles either meant something — or they were window dressing. This is when you find out.",
      china: "The US-China AI gap has been the central strategic question of this era. Where it ends — convergence, conflict, cooperation, or Chinese supremacy — is being settled now. The decisions your team made across four rounds of escalating stakes have set the conditions. What you choose in this final round determines whether China emerges from 2028 as a peer, a threat, a partner, or something history doesn't have a word for yet.",
      external: "You shaped the environment. You never controlled the labs, never controlled the technology. But you controlled the money, the narrative, the regulations, and the public mandate. Now the consequences are crystallizing. The arc you helped create is resolving. Your final decision locks in your role in how this story is remembered.",
    },
  },
};

export function getBriefing(round: number): Briefing {
  const briefing = BRIEFINGS[round];
  if (!briefing) throw new Error(`No briefing for round ${round}`);
  return briefing;
}
