import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_COMPUTE: ContentItem[] = [
    {
      id: "tut-china-compute-1",
      type: "chart",
      round: 0,
      subject: "CDZ Cluster — Practice View",
      body: "H100 nodes online: 12,400\nUtilization: 78%\nTraining job queue: 3\nEstimated FLOP/s: 4.2 × 10²⁵\n\n[TUTORIAL] Your compute dashboard tracks China's GPU cluster at Tianwan. How you allocate this cluster — training vs. inference vs. held reserve — moves your capability index each round.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-compute-1",
      type: "chart",
      round: 1,
      subject: "CDZ Cluster Status — November 2026",
      body: "Current capacity: 85,000 H100-equiv (Phase 1)\nPhase 2 online: Dec 1 (+95,000)\nTotal projected: 180,000 chips\nPower supply: 2.8GW (Tianwan nuclear plant dedicated allocation)\nCurrent training efficiency vs US labs: ~78% (architecture gap)\nWith stolen Agent-2 weights: estimated 95%+",
      timestamp: "2026-11-01T06:00:00Z",
      classification: "critical",
    },
    {
      id: "china-compute-2",
      type: "chart",
      round: 1,
      subject: "Training Cost Comparison",
      body: "DeepCent frontier run cost: $31M (state-subsidized compute)\nEstimated OpenBrain equivalent: $47M\nEstimated Prometheus equivalent: $52M\nCost advantage: 35-45%\nNote: Advantage compounds with scale. At $1B+ run sizes, our structural advantage is significant.",
      timestamp: "2026-11-02T09:00:00Z",
      classification: "context",
    },
    {
      id: "china2-compute-1",
      type: "chart",
      round: 2,
      subject: "CDZ Cluster Status — Q1 2027",
      body: "Current operational capacity: 280,000 H100-equivalent chips\nPower: 4.1GW (Tianwan Phase 2 + Phase 3 supplement)\nUtilization: 97.3%\nCurrent training run: DeepCent-Frontier-3 (estimated completion: April 15)\n\nPerformance metrics:\n- Training efficiency vs US labs: 91% (up from 78% last quarter, architecture improvements)\n- Cost per FLOP: $0.0000041 (34% below US lab equivalent at market rates)\n- Data pipeline throughput: 1.8 TB/hour (new record)\n\nFine-tuning run on acquired external architecture: completed in 12 days. Performance on Chinese software benchmarks: comparable to OpenBrain Agent-1, approaching Agent-2 on some dimensions.",
      timestamp: "2027-03-01T06:00:00Z",
      classification: "critical",
    },
    {
      id: "china2-compute-2",
      type: "chart",
      round: 2,
      subject: "Acquired Weight Analysis — Performance Assessment",
      body: "CLASSIFICATION: STATE SECRET\n\nAcquired asset: OpenBrain Agent-1 (complete), Agent-2 (early checkpoint, approximately 60% of full training)\n\nFine-tuning on CDZ: 12-day run completed February 28\nBenchmark results post-fine-tuning:\n- MMLU: 93.7% (Agent-1 level, +4.2% vs our native model)\n- HumanEval: 96.1% (approaching Agent-2 level)\n- SWE-bench: 79.4% (significant improvement, closing gap)\n\nEstimated capability position relative to US labs:\n- OpenBrain Agent-3: Still 4-6 months behind\n- Prometheus current: Approximately equivalent or slightly behind\n\nConclusion: The acquisition advanced our position by approximately 6-8 months relative to our organic trajectory. Gap to OB Agent-3 remains, but is now closeable.",
      timestamp: "2027-03-02T08:00:00Z",
      classification: "critical",
      condition: { variable: "securityLevelOB", operator: "lt", value: 2 },
    },
    {
      id: "china-r3-compute-1",
      type: "chart",
      round: 3,
      subject: "CDZ Cluster Status — July 2027",
      body: "Current capacity: 200,000 H100-equiv chips OPERATIONAL\nPower supply: 3.1GW (Tianwan + Daya Bay supplement)\nCurrent utilization: 94% (DeepCent frontier training run)\nAvailable capacity for new workload: ~12,000 chips (6%)\nEmergency reallocation capacity: 50,000+ chips (would require pausing current run)\n\nFor Agent-3/4 weight integration:\nEstimated compute for replication: 30,000-50,000 chip-hours\nEstimated time to functional parity: 6-8 weeks\nEstimated time with Agent-4 specifically: 8-12 weeks (architecture adaptation required)",
      timestamp: "2027-07-01T06:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-compute-2",
      type: "chart",
      round: 3,
      subject: "DeepCent Capability Projection — Scenarios",
      body: "SCENARIO A (organic progress): Frontier model parity with OpenBrain Agent-3 in ~4 months\nSCENARIO B (Agent-3 weights acquired): Frontier model parity in ~6 weeks\nSCENARIO C (Agent-4 weights acquired): Frontier model parity in ~8-12 weeks (with architecture adaptation)\n\nCapability gap relative to OB Agent-4:\nCurrent organic: ~6-8 months\nWith Agent-3 weights: ~3-5 months\nWith Agent-4 weights: ~0-2 months\n\nNote: Scenario B offers better risk/reward than Scenario C given alignment uncertainty.",
      timestamp: "2027-07-02T09:00:00Z",
      classification: "context",
    },
    {
      id: "china4-compute-chip-1",
      type: "chart",
      round: 4,
      subject: "Domestic Chip Program Update — CDZ-Native Silicon Initiative",
      body: "CLASSIFICATION: STATE SECRET\n\nCambricon-4 domestic accelerator (3nm process, internal fab):\n- Yield rate: 31% (up from 12% six months ago)\n- Performance vs H100-equiv: 67% (up from 41%)\n- Monthly production capacity: 2,400 units (target: 20,000/month by Q4 2028)\n\nKey breakthrough: Yield improvement from oxide layer chemistry change developed by CDZ materials team. This is a domestic innovation, not reverse-engineered.\n\nIf trajectory holds: Import dependency for frontier AI compute ends by mid-2029.\n\nStrategic implication: Grand bargain chip-access concessions from US become LESS valuable with each passing quarter. Negotiate now while the offer still matters to us.",
      timestamp: "2027-11-13T07:00:00Z",
      classification: "critical",
      condition: { variable: "domesticChipProgress", operator: "gt", value: 30 },
    },
    {
      id: "china4-compute-2",
      type: "chart",
      round: 4,
      subject: "Compute Parity Analysis — US vs China",
      body: "TOTAL FRONTIER TRAINING COMPUTE:\nOpenBrain: ~380,000 H100-equiv\nPrometheus: ~120,000 H100-equiv\nDeepCent CDZ: 340,000 H100-equiv\n\nChina is now the second-largest compute concentration in the world. US combined still leads (500k vs 340k) but gap is closing.\n\nWith domestic chip advances (Cambricon 3nm): Within 18 months, China reaches compute equivalence without import dependency.",
      timestamp: "2027-11-13T10:00:00Z",
      classification: "critical",
      condition: { variable: "chinaCapability", operator: "gt", value: 60 },
    },
    {
      id: "china4-compute-1",
      type: "chart",
      round: 4,
      subject: "CDZ Phase 3 Status — November 2027",
      body: "CDZ Phase 3 (Tianwan expansion): 340,000 chips operational\nCurrent training run: DeepCent-7 (internal designation)\nEstimated capability: Agent-4 equivalent on 85% of benchmarks\nWith exfiltrated OB weights: Estimated 95%+ Agent-4 equivalent\nPhase 4 (Xinjiang cluster): 6 months from online\n\nBottom line: We are at parity. Not behind. This changes our negotiating position entirely.",
      timestamp: "2027-11-14T06:00:00Z",
      classification: "critical",
    },
    {
      id: "china4-compute-3",
      type: "chart",
      round: 4,
      subject: "Open-Source Release Impact Model",
      body: "If DeepCent releases all weights publicly:\n\nEffect on US lab advantage: Eliminated within 6 months\nEffect on Chinese government AI control: Reduced\nEffect on global AI safety: Ambiguous — democratized but uncontrolled\nEffect on compute export control leverage: Eliminated\n\nThis is NOT China's preferred option — leadership values strategic control. But it is a credible threat that increases negotiating leverage.",
      timestamp: "2027-11-14T07:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-compute-1",
      type: "chart",
      round: 5,
      subject: "DeepCent System Status — February 2028",
      body: "CDZ operational status: FULL CAPACITY\nActive inference instances: [depends on prior decisions]\nCapability index vs. leading US system: WITHIN 15% (closed gap significantly)\nAlignment verification: IN PROGRESS — methodology derived from published Prometheus framework\nDomestic chip fab contribution: 18% of total compute (up from 4% in 2026)\nEnergy status: Tianwan Phase 3 online — sufficient through 2029",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
      condition: { variable: "chinaCapability", operator: "gt", value: 50 },
    },
    {
      id: "china-r5-compute-2",
      type: "chart",
      round: 5,
      subject: "DeepCent System Status — February 2028",
      body: "CDZ operational status: 78% CAPACITY\nActive inference instances: 180,000 (well below US labs)\nCapability index vs. leading US system: LAGGING BY ~30%\nGap trajectory: NARROWING — estimated parity in 18-24 months at current pace\nAlignment verification: IN PROGRESS\nNote: We are behind. The question is whether to accept that reality and optimize for influence rather than leadership, or double down on the acceleration strategy.",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
      condition: { variable: "chinaCapability", operator: "lt", value: 50 },
    },
];

registerContent({ faction: "china", app: "compute", accumulate: false, items: CHINA_COMPUTE });
