import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

// ═══════════════════════════════════════════════
// CHINA FLAVOR — casual Slack + personal Signal
// Human texture: engineering pride, cultural grounding, the cost of secrecy
// ═══════════════════════════════════════════════

export const CHINA_SLACK_FLAVOR: ContentItem[] = [
  // ── Round 1: reply chains ──
  // Reply chain: Director Zhao's CDZ Phase 2 announcement (#general)
  {
    id: "china-flavor-r1-general-reply-1",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#general",
    body: "Understood, Director. To clarify the December 1 date — does that include Block B ramp-up, or is Block A reaching full utilization first?",
    timestamp: "2026-11-01T09:42:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-general-reply-2",
    type: "message",
    round: 1,
    sender: "Director Zhao Wei",
    channel: "#general",
    body: "Block A first. Block B follows by December 15 pending thermal calibration. Full cluster online December 15-20. Plan accordingly.",
    timestamp: "2026-11-01T10:05:00Z",
    classification: "context",
  },

  // Reply chain: Dr. Liu Yang's architecture review (#research)
  {
    id: "china-flavor-r1-research-reply-1",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#research",
    body: "On the data curation gap — is this primarily about domain coverage or quality filtering methodology? I've been reading some of the public technical reports and there seem to be meaningful differences in how aggressive the deduplication passes are.",
    timestamp: "2026-11-02T11:15:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-research-reply-2",
    type: "message",
    round: 1,
    sender: "Dr. Liu Yang",
    channel: "#research",
    body: "Quality filtering primarily. Their deduplication strategy is more aggressive at the 13B scale — removing more data than we do but ending up with better signal. Counterintuitive but it shows in the loss curves. I'll share the full breakdown at Monday's working group.",
    timestamp: "2026-11-02T11:50:00Z",
    classification: "context",
  },

  // Reply chain: Ministry Liaison's power allocation (#operations)
  {
    id: "china-flavor-r1-operations-reply-1",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Night Shift)",
    channel: "#ops",
    body: "Confirmed on power allocation. Block A switching to full training load December 1 at 00:00. Full cooling system pre-check scheduled November 30 — will confirm readiness by 23:00.",
    timestamp: "2026-11-03T15:20:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-operations-reply-2",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Day Shift)",
    channel: "#ops",
    body: "Day shift acknowledges. One question: what's the protocol if Hall 3 thermal sensors trigger a false positive during rollover? Last time we had a 40-minute diagnostic hold waiting on authorization to override. Requesting written pre-authorization this time.",
    timestamp: "2026-11-03T15:45:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-operations-reply-3",
    type: "message",
    round: 1,
    sender: "Ministry Liaison",
    channel: "#ops",
    body: "{china_director} has pre-authorized the Day Shift supervisor to override Hall 3 thermal hold with a 15-minute delay, not 40. Document any override in the shift log with timestamp and justification. If temperature rises more than 2°C above threshold, it is not a false positive.",
    timestamp: "2026-11-03T16:30:00Z",
    classification: "context",
  },

  // ── Round 1: #random — CDZ casual channel ──
  {
    id: "china-flavor-r1-random-1",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#random",
    body: "Mystery solved: I found where all the Red Bull has been going. There's a stash behind the spare cooling units in Hall 3. 47 cans. I'm not naming names, but the office nearest Hall 3 has been suspiciously energetic at 2am.",
    timestamp: "2026-11-02T23:15:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-2",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Night Shift)",
    channel: "#random",
    body: "That explains the ¥4,000 cooling bill. I'm forwarding the invoice to Hall 3.",
    timestamp: "2026-11-02T23:31:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-3",
    type: "message",
    round: 1,
    sender: "Research Team Admin",
    channel: "#random",
    body: "Hot pot this Saturday, 7pm. Yang Guofu near the east gate. {china_director} is covering the lamb and the mushrooms. 14 spots available — reply here to claim one, first come first served.",
    timestamp: "2026-11-04T17:45:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-4",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#random",
    body: "I'm in. Also: I finally tested whether our current model could solve the core problem from my PhD thesis. It could. 40 seconds. I have entered the acceptance stage of grief. Bring extra soup base on Saturday, I have feelings to process.",
    timestamp: "2026-11-04T18:12:00Z",
    classification: "context",
  },

  // ── Round 1: team building, CDZ pride ──
  {
    id: "china-flavor-r1-slack-1",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Night Shift)",
    channel: "#ops",
    body: "Night shift report: all systems nominal. Block A running at 94%. Block B had a brief thermal event at 03:22 — resolved in 11 minutes. Also, someone left a box of moon cakes in the break room. They were excellent. Whoever you are, thank you.",
    timestamp: "2026-11-02T06:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-slack-2",
    type: "message",
    round: 1,
    sender: "Dr. Liu Yang",
    channel: "#research",
    body: "Team: I know the hours have been long. The December 1 deadline does not move, but your health matters. The congee station is open 24 hours. Please use it. This is not a sprint. It is a marathon we happen to be running at sprint pace.",
    timestamp: "2026-11-04T12:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-slack-3",
    type: "message",
    round: 1,
    sender: "Junior Researcher (Wei Chen)",
    channel: "#general",
    body: "Completed my PhD at Tsinghua three months ago. Today I watched our model solve a coding problem that was the subject of my entire thesis. It did it in 40 seconds. I am simultaneously proud and existentially confused.",
    timestamp: "2026-11-06T17:30:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-slack-4",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Day Shift)",
    channel: "#ops",
    body: "Facilities note: the vending machine in Hall 3 break room has been stocked with Wahaha and Nongfu Spring. Whoever keeps filling it with Red Bull — I admire the commitment but the electricity bill for the cooling alone is ¥4,000/month. The computing should be the expensive part.",
    timestamp: "2026-11-07T09:00:00Z",
    classification: "context",
  },

  // ── Round 1: canteen debates, campus life, Double 11, casual ──
  {
    id: "china-flavor-r1-random-5",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#random",
    body: "Serious question: Window 2 or Window 4 for malatang? Window 2 has the better broth but Window 4 lets you pick your own spice level. This is the most important unsettled debate in this facility and I feel like we should settle it.",
    timestamp: "2026-11-01T12:08:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-6",
    type: "message",
    round: 1,
    sender: "Dr. Liu Yang",
    channel: "#random",
    body: "Window 4. Spice control is not a luxury. It is a requirement. I ate Window 2's level-3 last week and I was off my game for two hours. This is a productivity issue.",
    timestamp: "2026-11-01T12:21:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-7",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Night Shift)",
    channel: "#random",
    body: "Night shift has a different opinion: Window 3 egg fried rice at 2am. The auntie there doubles the egg when she knows it's the night crew. We have a working relationship.",
    timestamp: "2026-11-01T12:45:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-8",
    type: "message",
    round: 1,
    sender: "Research Team Admin",
    channel: "#random",
    body: "Ping pong table in the rec room is reserved Friday 6-8pm for the research vs operations rematch. Current score: 2-2 across the past month. Research team, please practice. Operations won last time and they have not stopped mentioning it.",
    timestamp: "2026-11-03T10:30:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-9",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Day Shift)",
    channel: "#random",
    body: "We have not stopped mentioning it because we won. That is how winning works.",
    timestamp: "2026-11-03T10:47:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-10",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#random",
    body: "Quick announcement: there's a tea place that just opened two blocks from the east gate. Called Shuixian. The oolong is very good and importantly they are open until midnight. I've already been twice today. This is not an endorsement, this is a public health notice.",
    timestamp: "2026-11-03T22:10:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-11",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#random",
    body: "Double 11 starts tonight at midnight. I have had a cart staged for three weeks. Eye cream for my mom, new monitor stand, backup keyboard switches, and a humidifier because Chengdu in November is basically living inside a cloud. Anyone else going in at midnight or am I doing this alone?",
    timestamp: "2026-11-10T22:34:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-12",
    type: "message",
    round: 1,
    sender: "Dr. Liu Yang",
    channel: "#random",
    body: "The fog this morning was something. I ran the campus loop at 6am and by the end I couldn't see the B Block tower. Chengdu in autumn is genuinely beautiful if you're willing to be cold and unable to see more than fifty meters ahead.",
    timestamp: "2026-11-05T07:55:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-13",
    type: "message",
    round: 1,
    sender: "Research Team Admin",
    channel: "#general",
    body: "Welcome to CDZ: our new research associate Zhang Yifei joins the data infrastructure team this week, transferred from the Beijing office. Zhang Yifei completed their master's at Fudan and has three years of distributed systems work. Please make them feel at home — starting with the canteen orientation so they don't accidentally eat Window 1's soup.",
    timestamp: "2026-11-04T09:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-14",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Night Shift)",
    channel: "#random",
    body: "Someone's laptop fan in Lab 2 has been screaming at 100% for six hours. It's not a server. It's a personal laptop. Whoever it is: your machine is not okay. Please check on it. The sound is entering the break room through the wall and I am developing feelings about it.",
    timestamp: "2026-11-06T03:40:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-15",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#random",
    body: "That was my laptop. It was running a local model eval I forgot to cap. The laptop is fine. I gave it a thorough apology. This is what happens when you're from Chongqing — you just let things run hot and hope for the best.",
    timestamp: "2026-11-06T09:15:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-16",
    type: "message",
    round: 1,
    sender: "Dr. Liu Yang",
    channel: "#random",
    body: "My family in Hunan sent a box of cured pork — proper larou, dried in the mountain air, not the supermarket kind. I've left it in the kitchen. Help yourself. There's enough for everyone. Consider it a morale allocation.",
    timestamp: "2026-11-07T15:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-random-17",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Day Shift)",
    channel: "#random",
    body: "The honor of the day shift has been thoroughly restored. 3-2 over the research team. Wei Chen's serve has improved but {china_scientist}'s backhand is a known quantity and we prepared accordingly. Rematch scheduled in three weeks per the standing agreement.",
    timestamp: "2026-11-07T20:05:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-slack-5",
    type: "message",
    round: 1,
    sender: "Wei Chen",
    channel: "#random",
    body: "After Saturday hot pot, a few of us are getting Honor of Kings going in the rec room starting at 10pm. We need a fifth. Requirements: patience with a PhD student who peaked at Silver II three years ago and has not played since. Willing to carry preferred but not required.",
    timestamp: "2026-11-04T20:30:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-slack-6",
    type: "message",
    round: 1,
    sender: "CDZ Operations (Night Shift)",
    channel: "#random",
    body: "Silver II is fine. I will be the fifth. Fair warning: I only play support. I have never jungled in my life and I am not starting tonight.",
    timestamp: "2026-11-04T20:51:00Z",
    classification: "context",
  },

  // ── Round 2: Spring Festival sacrifice, efficiency wins ──
  {
    id: "china-flavor-r2-slack-1",
    type: "message",
    round: 2,
    sender: "Junior Researcher (Wei Chen)",
    channel: "#random",
    body: "Spring Festival was two weeks ago and I spent it here. My mother sent jiaozi through express delivery. They arrived frozen solid. I ate them at 3am between training runs. Best meal I've had in months.",
    timestamp: "2027-02-20T09:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r2-slack-2",
    type: "message",
    round: 2,
    sender: "CDZ Operations (Day Shift)",
    channel: "#ops",
    body: "Chip replacement team completed Block C maintenance 4 hours ahead of schedule. 412 chips swapped. The team has been working 16-hour shifts for two weeks. They've requested a day off. I've authorized it. They've earned it ten times over.",
    timestamp: "2027-03-02T18:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r2-slack-3",
    type: "message",
    round: 2,
    sender: "Dr. Liu Yang",
    channel: "#general",
    body: "I want to say something to the team that I probably shouldn't put in writing. Three years ago, colleagues at Stanford told me I was making a mistake coming back to China. They said the compute gap was insurmountable. They said the talent gap was permanent. Look at this dashboard. Look at what we built. They were wrong.",
    timestamp: "2027-03-05T20:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r2-slack-4",
    type: "message",
    round: 2,
    sender: "Junior Researcher (Wei Chen)",
    channel: "#research",
    body: "Reading the American AI safety papers. They are very good. Some of the interpretability work from Prometheus is genuinely ahead of anything we have. I am not saying this to be defeatist. I am saying it because ignoring their strengths is how you lose. We should be learning from everything they publish.",
    timestamp: "2027-03-07T11:00:00Z",
    classification: "context",
  },

  // ── Round 3: pressure, but also humor under strain ──
  {
    id: "china-flavor-r3-slack-1",
    type: "message",
    round: 3,
    sender: "CDZ Operations",
    channel: "#ops",
    body: "Coolant pressure anomaly in Hall 5 resolved. Root cause: a bird nested in the external heat exchanger. Maintenance cleared it. The bird is fine. We are naming her 'Agent-5.' She has been relocated to a tree that is not critical infrastructure.",
    timestamp: "2027-07-04T05:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r3-slack-2",
    type: "message",
    round: 3,
    sender: "Junior Researcher (Wei Chen)",
    channel: "#random",
    body: "My girlfriend asked what I've been working on. I said 'nothing interesting.' She said 'you've been at work 14 hours a day for a year and it's nothing interesting?' I have never been a worse liar than I am right now.",
    timestamp: "2027-07-05T22:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r3-slack-3",
    type: "message",
    round: 3,
    sender: "Dr. Liu Yang",
    channel: "#research",
    body: "Night shift team found a bug in the data pipeline at 4am that would have corrupted 200 hours of training. They fixed it in 40 minutes. No one will write a paper about this. No one outside this building will ever know. But this is the kind of engineering that wins. I'm noting their names for commendation.",
    timestamp: "2027-07-06T09:00:00Z",
    classification: "context",
  },

  // ── Round 4: achievement, emotion ──
  {
    id: "china-flavor-r4-slack-1",
    type: "message",
    round: 4,
    sender: "Junior Researcher (Wei Chen)",
    channel: "#general",
    body: "DeepCent-7 benchmarks came in this morning. I sat in the results meeting trying to stay professional. Then I excused myself and went to the bathroom and cried for five minutes. We did this. We actually did this.",
    timestamp: "2027-11-12T14:00:00Z",
    classification: "context",
    condition: { variable: "chinaCapability", operator: "gt", value: 60 },
  },
  {
    id: "china-flavor-r4-slack-2",
    type: "message",
    round: 4,
    sender: "Dr. Liu Yang",
    channel: "#research",
    body: "Whatever decision is made about the grand bargain — I want this on record: this team built something extraordinary under constraints the Americans never faced. Export controls, talent restrictions, compute limitations. We solved problems they didn't have to solve. That engineering achievement exists regardless of the politics.",
    timestamp: "2027-11-14T07:30:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r4-slack-3",
    type: "message",
    round: 4,
    sender: "CDZ Operations (Night Shift)",
    channel: "#ops",
    body: "The Americans have their crisis. We have ours. Hall 7 power feed fluctuated at 23:41 — backup kicked in within 800ms, no interruption to training. This is the third time this month. The Tianwan feed is stable but the grid connection is aging. We need the Phase 4 power infrastructure or we're one equipment failure from a very bad day.",
    timestamp: "2027-11-13T06:00:00Z",
    classification: "context",
  },

  // ── Round 5 ──
  {
    id: "china-flavor-r5-slack-1",
    type: "message",
    round: 5,
    sender: "Junior Researcher (Wei Chen)",
    channel: "#general",
    body: "My mother asked me on the phone last night: 'Are you building something good?' I said yes. She said: 'Then finish it and come home.' That's the best strategic analysis anyone has given me this month.",
    timestamp: "2028-02-01T07:15:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r5-slack-2",
    type: "message",
    round: 5,
    sender: "CDZ Operations",
    channel: "#ops",
    body: "Final shift log before the decision: CDZ has been operational for 458 consecutive days. Zero unplanned outages exceeding 30 minutes. 2.1 million chip-hours delivered this quarter. Whatever leadership decides today, the infrastructure held. That was our job. We did our job.",
    timestamp: "2028-02-01T06:30:00Z",
    classification: "context",
  },
];

export const CHINA_SIGNAL_FLAVOR: ContentItem[] = [
  // ── Round 1 ──
  {
    id: "china-flavor-r1-signal-mom-a",
    type: "message",
    round: 1,
    sender: "Mother (家人)",
    body: "儿子，国庆假期你能回来吗？家里包了饺子等你。你哥哥带了孩子来，你侄子快两岁了，会叫人了。你爸腰不好，你回来帮他看看。\n\n[Son, can you come home for National Day holiday? We made dumplings waiting for you. Your brother brought the kids — your nephew is almost two, he's learning to talk now. Your father's back is bad, come check on him.]",
    timestamp: "2026-09-28T17:30:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-signal-mom-b",
    type: "message",
    round: 1,
    sender: "Mother (家人)",
    body: "你上周没接我电话。你哥哥说你最近很忙，但忙成这样也要吃饭吧。我在网上买了你喜欢的老干妈，寄给你了，收到了吗？\n\n[You didn't answer my call last week. Your brother says you've been very busy, but no matter how busy you are you still need to eat. I ordered your favorite Laoganma sauce online and mailed it to you — did you receive it?]",
    timestamp: "2026-10-18T20:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-signal-1",
    type: "message",
    round: 1,
    sender: "Mother (家人)",
    body: "儿子，你工作太辛苦了。上次回家是什么时候？你爸说他在电视上看到了关于AI的新闻，问你是不是在做那个。我说不知道。回家吃饭吧。\n\n[Son, you work too hard. When was the last time you came home? Your father saw AI news on TV and asked if that's what you're doing. I said I didn't know. Come home for dinner.]",
    timestamp: "2026-11-05T19:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-signal-friend-a",
    type: "message",
    round: 1,
    sender: "University Friend (Shanghai)",
    body: "Old friend! I'm at Tongji now, teaching computer science. My students keep asking me to explain large language models and honestly your team's open-source Qwen release has become my go-to teaching example. Do you have any time for a call? I want to take you to that lamb skewer place near People's Square, the one we used to go to for exams.",
    timestamp: "2026-10-05T11:20:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-signal-friend-b",
    type: "message",
    round: 1,
    sender: "University Friend (Shanghai)",
    body: "saw the Qwen download numbers — 800k in the first week, that's remarkable. Half my department is debating whether to switch their research to your framework. For what it's worth: the fact that you stayed and built here instead of taking one of those US offers matters to people. The students notice.",
    timestamp: "2026-11-04T16:45:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r1-signal-2",
    type: "message",
    round: 1,
    sender: "University Friend (Shanghai)",
    body: "The whole campus is talking about the DeepCent open-source release. My students are using it for their research projects. Whatever you're doing over there — it's working. Proud of you, old friend.",
    timestamp: "2026-11-07T14:00:00Z",
    classification: "context",
  },

  // ── Round 2 ──
  {
    id: "china-flavor-r2-signal-1",
    type: "message",
    round: 2,
    sender: "Wife (家人)",
    body: "小明又问爸爸什么时候回来。我不知道怎么回答他了。我知道你在做重要的事。但他才四岁，他不懂'重要的事'。\n\n[Xiaoming asked again when daddy is coming home. I don't know how to answer him anymore. I know you're doing important work. But he's four. He doesn't understand 'important work.']",
    timestamp: "2027-03-03T20:30:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r2-signal-2",
    type: "message",
    round: 2,
    sender: "Classmate (now at Huawei)",
    body: "Heard through the grapevine that your team hit some impressive numbers last quarter. Can't get details obviously but the rumors are circulating in the industry. If half of what I'm hearing is true — you're going to be in the history books. Buy me dinner when it's over.",
    timestamp: "2027-03-06T12:00:00Z",
    classification: "context",
  },

  // ── Round 3 ──
  {
    id: "china-flavor-r3-signal-1",
    type: "message",
    round: 3,
    sender: "Former Colleague (now at Google)",
    body: "I'm hearing things through the grapevine about what's happening at OpenBrain. I don't know what you're working on and I know better than to ask. Just... be careful. The stakes in this space got very real very fast. Take care of yourself.",
    timestamp: "2027-07-06T16:00:00Z",
    classification: "context",
  },
  {
    id: "china-flavor-r3-signal-2",
    type: "message",
    round: 3,
    sender: "Wife (家人)",
    body: "小明今天画了一幅画。画的是你在电脑前面工作。他把电脑画得比你大三倍。我不知道该笑还是该哭。\n\n[Xiaoming drew a picture today. It's you working in front of a computer. He drew the computer three times bigger than you. I don't know whether to laugh or cry.]",
    timestamp: "2027-07-07T19:30:00Z",
    classification: "context",
  },

  // ── Round 4 ──
  {
    id: "china-flavor-r4-signal-1",
    type: "message",
    round: 4,
    sender: "Mother (家人)",
    body: "电视上说美国的AI公司出问题了。你安全吗？你们的也安全吗？我知道你不能说。但一个妈妈总要问的。\n\n[They're saying on TV that American AI companies are in trouble. Are you safe? Is yours safe too? I know you can't say. But a mother always has to ask.]",
    timestamp: "2027-11-14T06:30:00Z",
    classification: "context",
    condition: { variable: "publicAwareness", operator: "gt", value: 50 },
  },
  {
    id: "china-flavor-r4-signal-2",
    type: "message",
    round: 4,
    sender: "University Friend (Shanghai)",
    body: "I read the Western coverage of DeepCent-7. They keep saying 'stolen technology.' You know and I know how much original engineering your team did. It's infuriating. But I suppose the politics are the politics. History will sort it out. For what it's worth — the students here know. They're proud.",
    timestamp: "2027-11-13T15:00:00Z",
    classification: "context",
    condition: { variable: "chinaCapability", operator: "gt", value: 50 },
  },

  // ── Round 5 ──
  {
    id: "china-flavor-r5-signal-1",
    type: "message",
    round: 5,
    sender: "Wife (家人)",
    body: "不管今天发生什么，回家。小明给你留了一个位置在晚饭桌上。他每天都留。\n\n[Whatever happens today, come home. Xiaoming saved you a seat at the dinner table. He saves one every day.]",
    timestamp: "2028-02-01T06:00:00Z",
    classification: "context",
  },
];

export const CHINA_SIGNAL_NOTIFICATIONS: ContentItem[] = [
  {
    id: "china-notif-r1-jd-1",
    type: "message",
    round: 1,
    sender: "京东 (JD.com)",
    body: "您的订单已签收。商品：机械键盘（Cherry MX青轴）+ USB集线器7口。包裹已送至前台。感谢您的购买！\n\n[Order delivered. Items: Mechanical keyboard (Cherry MX Blue) + 7-port USB hub. Package left at reception. Thank you!]",
    timestamp: "2026-10-09T14:11:00Z",
    classification: "context",
  },
  {
    id: "china-notif-r1-jd-2",
    type: "message",
    round: 1,
    sender: "京东 (JD.com)",
    body: "您的订单已发货，预计明日送达。商品：护眼台灯 + 颈椎枕 + 维生素B族。运单号：JD12938840291。\n\n[Your order has shipped, expected delivery tomorrow. Items: Eye-care desk lamp + cervical pillow + B vitamins. Tracking: JD12938840291.]",
    timestamp: "2026-11-01T09:30:00Z",
    classification: "context",
  },
  {
    id: "china-notif-r1-meituan-1",
    type: "message",
    round: 1,
    sender: "美团外卖 (Meituan)",
    body: "您的外卖已送达！黄焖鸡米饭 + 紫菜蛋花汤 + 卤鸡蛋(2个)。合计：¥38.5。五星好评走一个？\n\n[Your delivery has arrived! Braised chicken rice + seaweed soup + marinated eggs (x2). Total: ¥38.5. Leave us 5 stars?]",
    timestamp: "2026-10-20T12:47:00Z",
    classification: "context",
  },
  {
    id: "china-notif-r1-meituan-2",
    type: "message",
    round: 1,
    sender: "美团外卖 (Meituan)",
    body: "骑手小哥已在楼下，请下楼取餐。订单：兰州拉面(大碗) + 凉拌黄瓜 + 红烧肉盖饭。合计：¥52.0\n[Delivery rider is downstairs, please come pick up. Order: Lanzhou noodles (large) + cold cucumber + braised pork rice. Total: ¥52.0]",
    timestamp: "2026-11-04T19:55:00Z",
    classification: "context",
  },
  {
    id: "china-notif-r1-calendar-physical",
    type: "message",
    round: 1,
    sender: "北京协和医院 (PUMCH)",
    body: "体检预约提醒：您的年度体检预约时间为11月15日（周日）上午8:30。请携带身份证。禁食12小时，可饮少量清水。如需改期请提前48小时联系。\n\n[Annual physical reminder: Nov 15 (Sun) 8:30 AM. Bring ID. Fast 12 hrs, clear water OK. Reschedule 48hrs in advance.]",
    timestamp: "2026-11-10T08:00:00Z",
    classification: "context",
  },
  {
    id: "china-notif-r1-bilibili",
    type: "message",
    round: 1,
    sender: "哔哩哔哩 (Bilibili)",
    body: "您关注的UP主更新了：【3Blue1Brown中文版】神经网络的本质 第3集已上线。大会员月费¥25将于11月18日扣款。去看看？\n\n[Followed creator updated: [3Blue1Brown Chinese] Essence of Neural Networks Ep.3 is live. Premium ¥25 charges Nov 18.]",
    timestamp: "2026-11-02T20:00:00Z",
    classification: "context",
  },
];

registerContent({ faction: "china", app: "slack", accumulate: true, items: CHINA_SLACK_FLAVOR });
registerContent({ faction: "china", app: "signal", accumulate: true, items: CHINA_SIGNAL_FLAVOR });
registerContent({ faction: "china", app: "signal", accumulate: true, items: CHINA_SIGNAL_NOTIFICATIONS });
