import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_INTEL_INTEL: ContentItem[] = [
    {
      id: "china-intel-1",
      type: "document",
      round: 1,
      subject: "Intelligence Assessment: US Frontier Lab Vulnerabilities",
      body: "CLASSIFICATION: MOST SECRET\n\nOpenBrain:\n- Security posture: SL2 (below industry standard for frontier model storage)\n- Checkpoint storage: Cloud-adjacent with inadequate air gap\n- Insider risk: Medium-high (fast-growing org, inconsistent vetting)\n- Estimated exfiltration window: 6-8 weeks before they upgrade security\n\nPrometheus:\n- Security posture: SL3 (adequate, harder target)\n- Checkpoint storage: Air-gapped (confirmed)\n- Insider risk: Low (smaller, more ideologically cohesive team)\n\nRecommendation: If we proceed, target OpenBrain.",
      timestamp: "2026-11-03T08:00:00Z",
      classification: "critical",
    },
    {
      id: "china-intel-theft-1",
      type: "document",
      round: 1,
      subject: "FLASH UPDATE: Weight Exfiltration Vector — Operational Progress",
      body: "CLASSIFICATION: MOST SECRET — EYES ONLY\n\nVector Alpha has successfully staged a persistent foothold in the OpenBrain storage subnet. We can read checkpoint metadata; write access is not yet confirmed. Estimated time to full exfiltration capability: 10–14 days.\n\nVector Beta was burned — the account was suspended. Recommend we do not attempt re-entry via this path.\n\nThe window is open. Recommend escalation decision within 72 hours.",
      timestamp: "2026-11-04T11:00:00Z",
      classification: "critical",
      condition: { variable: "chinaWeightTheftProgress", operator: "gt", value: 40 },
    },
    {
      id: "china2-intel-1",
      type: "document",
      round: 2,
      subject: "Intelligence Assessment: US Frontier Lab Security Posture — Q1 2027",
      body: "CLASSIFICATION: MOST SECRET\n\nOpenBrain:\n- Security level: SL2-3 (recently upgraded from SL2, still below SL4 threshold for Agent-3 weights)\n- Agent-3 checkpoint storage: Cloud-adjacent, not fully air-gapped\n- Key change from Q4: Incident response team added, external forensics engaged after what appears to be an internal investigation\n- Assessment: Possible that OB is aware of or investigating a breach. If so, response timeline is weeks, not days.\n- Agent-3 weights: Significantly better protected than Agent-1/2 were. Not impenetrable, but the window for casual exfiltration is closed.\n\nPrometheus:\n- Security level: SL4 (confirmed air-gap for primary model weights)\n- Alignment research files: SL3 (higher value than weights in some scenarios)\n- No known vulnerabilities\n- Assessment: Prometheus is not a viable target for conventional exfiltration at acceptable risk levels.\n\nRecommendation: If further exfiltration is considered, Agent-3 is the prize, but OB has hardened significantly. Risk/reward calculation has changed substantially since Q4.",
      timestamp: "2027-03-05T08:00:00Z",
      classification: "critical",
    },
    {
      id: "china2-intel-2",
      type: "document",
      round: 2,
      subject: "Analysis: Value of Acquired Agent-2 Weights — Strategic Assessment",
      body: "CLASSIFICATION: MOST SECRET\n\nStrategic value assessment of acquired OB weights:\n\nShort-term (now): The fine-tuned model gives DeepCent capability equivalent to OB's Agent-1 on most benchmarks, approaching Agent-2 on coding tasks. This is valuable but not decisive.\n\nMedium-term (6-12 months): Using the acquired architecture as a foundation, our team estimates we can develop Agent-3 equivalent 3-4 months ahead of organic schedule. This compresses the gap but does not eliminate it.\n\nLong-term risk: OpenBrain knows its weights were taken. They will build with the assumption that their architecture is compromised. Any mitigations or improvements they make will not be reflected in what we have.\n\nConclusion: The acquisition was strategically correct but the window where it confers decisive advantage is short. We need the Agent-3 architecture itself, or we need to develop our own equivalent. The current asset buys us time, not victory.",
      timestamp: "2027-03-07T09:00:00Z",
      classification: "critical",
      condition: { variable: "securityLevelOB", operator: "lt", value: 2 },
    },
    {
      id: "china-r3-intel-3",
      type: "document",
      round: 3,
      subject: "US Intelligence Assessment: China Awareness Level",
      body: "CLASSIFICATION: SECRET\n\nUS signals intelligence awareness of our capabilities: MEDIUM\nUS awareness of specific operational planning: LOW (based on content of intercepted NSA communications)\nUS focus: Entirely on internal OpenBrain situation. Counter-intelligence for foreign espionage is operating at reduced priority.\n\nNSA attention is 80-90% focused on Agent-4 crisis. This is the lowest China-monitoring priority level we have recorded in 18 months.\n\nWindow for undetected operation: Best estimate 5-10 days before standard monitoring posture resumes.\n\nConclusion: The Americans are not watching us right now.",
      timestamp: "2027-07-06T12:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-intel-1",
      type: "document",
      round: 3,
      subject: "INTELLIGENCE ASSESSMENT: OpenBrain Security Posture During Internal Crisis",
      body: "CLASSIFICATION: MOST SECRET\n\nCURRENT SECURITY STATUS (OpenBrain):\nSecurity Level: SL3 (upgraded from SL2 two months ago, below SL4 recommended by their own security team)\nChief Security concern: Divided between internal crisis management and external intrusion detection\nKey vulnerability: Checkpoint storage authentication systems — current implementation has a confirmed exploitable misconfiguration\n\nACTIVE VECTORS:\nVector Alpha: Cloud API misconfiguration in checkpoint storage. 6-hour exfiltration window once exploited. STANDING BY.\nVector Beta: Insider with unwitting access. Can be activated on 12-hour notice. Lower throughput but higher deniability.\nVector Gamma: Supply chain access to training infrastructure vendor. Highest risk, highest bandwidth.\n\nRECOMMENDATION:\nVector Alpha is the primary recommended operation. Success probability: 73%. Detection probability: 31%.\nWindow: Closing in 5-7 days as their security team addresses the misconfiguration.",
      timestamp: "2027-07-07T06:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r3-intel-2",
      type: "document",
      round: 3,
      subject: "OPERATIONAL PLAN: Agent-3/4 Weight Acquisition",
      body: "CLASSIFICATION: MOST SECRET — EYES ONLY\n\nOBJECTIVE: Acquire OpenBrain Agent-3 checkpoint weights (primary) and Agent-4 weights (secondary, only if Agent-3 unavailable or operation is undetected)\n\nOPERATION PHASES:\nPhase 1 (Hour 0-2): Exploit Vector Alpha misconfiguration. Authenticate using compromised credentials obtained in March 2027 probing operation.\nPhase 2 (Hour 2-5): Locate and extract Agent-3 checkpoint shards. Size: approximately 2.1 TB across 7 storage nodes.\nPhase 3 (Hour 5-6): Exfiltrate via steganographic channels to relay servers in Singapore.\nPhase 4 (Hour 6-48): CDZ team begins integration and verification.\n\nRISK FACTORS:\n- If detected mid-operation: diplomatic incident, potential sanctions, US security upgrade\n- If successful but traced: same risks at reduced probability\n- If successful and untraceable: capability leap, no consequences\n\nAUTHORIZATION REQUIRED: Ministry-level approval",
      timestamp: "2027-07-07T08:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r3-intel-4",
      type: "document",
      round: 3,
      subject: "URGENT: Security Upgrade Imminent — Window Closing",
      body: "CLASSIFICATION: MOST SECRET\n\nINTERCEPTED INTERNAL COMMUNICATION (OpenBrain, Security Team):\n'Emergency SL5 upgrade approved — implementation begins July 10. Vector Alpha will be closed in 72 hours.'\n\nOUR ASSESSMENT: The 72-hour window is confirmed. After July 10, Vector Alpha becomes non-functional. Vectors Beta and Gamma have higher risk profiles and lower success probabilities.\n\nThis is the last clean window. Decision required by July 9 at latest.",
      timestamp: "2027-07-07T21:00:00Z",
      classification: "critical",
      condition: { variable: "securityLevelOB", operator: "lt", value: 4 },
    },
    {
      id: "china4-intel-4",
      type: "document",
      round: 4,
      subject: "Exfiltrated Architecture Value Assessment",
      body: "CLASSIFICATION: MOST SECRET\n\nStatus of exfiltrated Agent-3 weights (if operation succeeded in previous rounds):\n- Integrated into DeepCent-7 training: YES\n- Capability uplift: +6.2% across all benchmarks\n- Value of Agent-4 weights (not yet obtained): Estimated +12-15% additional uplift\n- Agent-5 weights (offline at OB): Value unknown, likely transformative\n\nNote: Physical security at OB is now SL4. No remote vector. Agent-5 weights are not acquirable by technical means.",
      timestamp: "2027-11-12T08:00:00Z",
      classification: "critical",
      condition: { variable: "chinaCapability", operator: "gt", value: 60 },
    },
    {
      id: "china4-intel-1",
      type: "document",
      round: 4,
      subject: "Strategic Assessment: Grand Bargain Option",
      body: "CLASSIFICATION: MOST SECRET\n\nGrand Bargain Terms Analysis:\n\nUS offering: 90-day mutual pause, mutual verification, TSMC access negotiations\nChina conceding: Current development pace advantage, open-source leverage, Taiwan military window\n\nRisk: The US may not honor chip access commitments. Historical pattern suggests sanctions creep resumes within 12-18 months.\nOpportunity: 2nm chip access accelerates our AI timeline by 18 months and eliminates export control vulnerability permanently.\n\nIntelligence assessment: US negotiating position is weakened by domestic AI crisis. This is the best bargaining window China will have for years.",
      timestamp: "2027-11-13T20:00:00Z",
      classification: "critical",
    },
    {
      id: "china4-intel-2",
      type: "document",
      round: 4,
      subject: "US Lab Vulnerability Assessment — Current",
      body: "CLASSIFICATION: MOST SECRET\n\nOpenBrain:\n- Security level: SL4 (upgraded). Air-gapped weight storage. Remote exfiltration IMPOSSIBLE.\n- Agent-5 architecture: Offline only. No exfiltration vector without physical access.\n- Internal status: Board crisis. Safety Officer may defect. Organization politically fractured.\n\nPrometheus:\n- Security: SL3. Strong security culture. No known vectors.\n- Internal status: Opportunistic positioning. Not vulnerable to internal fractures.\n\nConclusion: Direct exfiltration window is closed. Influence operations are the remaining vector.",
      timestamp: "2027-11-14T06:00:00Z",
      classification: "critical",
    },
    {
      id: "china4-intel-3",
      type: "document",
      round: 4,
      subject: "Diplomat Back-Channel Report",
      body: "CLASSIFICATION: MOST SECRET\n\nContacts established:\n- US National Security Advisor: Open to arms-control dialogue, timeline uncertain\n- International Diplomat: Actively pushing treaty framework, sympathetic to mutual verification\n- OB Safety Officer (Maya Patel): Not an asset, but her public disclosures have secondary intelligence value\n\nNote: The journalist has the safety memo and hasn't published. Her decision will reshape the political landscape. We cannot predict it. We could potentially influence it through selective intelligence sharing.",
      timestamp: "2027-11-14T07:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r5-intel-1",
      type: "document",
      round: 5,
      subject: "CLASSIFIED: Final Intelligence Assessment — US AI Labs, February 2028",
      body: "CLASSIFICATION: TOP SECRET / SI / NOFORN\n\nOPENBRAIN: The system is running. Based on SIGINT and human intelligence inside the organization, their alignment confidence is [CONDITIONAL]. Board decision today will set deployment posture for 12-18 months. NSC has a formal offer on the table. Marcus Reid's personal position appears to be [contested — multiple sources conflict].\n\nPROMETHEUS: Has a credible safety framework and government credibility. Less capability than OpenBrain but closing. Their final move today will be either partnership with government, merger overture to OB, or full open-source release.\n\nUS GOVERNMENT POSTURE: Preparing for bilateral AI governance talks. The NSA does not want to negotiate from weakness. They believe their AI asset gives them leverage. They will use it.\n\nASSESSMENT: The window for unilateral Chinese strategic action is closing. Within 6-12 months, US AI capabilities will enable surveillance and response capacities that significantly complicate any aggressive posture. The choice is: act now, negotiate now, or accept the structural disadvantage.",
      timestamp: "2028-02-01T04:00:00Z",
      classification: "critical",
    },
    // ── Ambient condition-gated items ──
    {
      id: "china-r1-intel-boost-recon-1",
      type: "document",
      round: 1,
      subject: "CLASSIFIED: OpenBrain Security Posture Assessment",
      body: "CLASSIFICATION: TOP SECRET\n\nOpenBrain security level assessed at SL2 (confirmed via SIGINT and infrastructure analysis).\n\nKey vulnerabilities identified:\n1. Checkpoint storage accessible via three network paths, only one properly monitored\n2. Security team headcount: 12 (inadequate for infrastructure scale)\n3. Internal VPN logs suggest security budget requests have been denied twice in Q3\n\nAssessment: OpenBrain's security posture is significantly below what would be expected for an organization possessing assets of this strategic value. This appears to be a resource allocation decision, not a technical limitation.\n\nRecommendation: Continue passive reconnaissance. Do not probe actively until authorization is received.",
      timestamp: "2026-11-04T22:00:00Z",
      classification: "critical",
      condition: { variable: "securityLevelOB", operator: "lt", value: 3 },
    },
    {
      id: "china-r2-intel-boost-talent-1",
      type: "document",
      round: 2,
      subject: "CLASSIFIED: US Lab Personnel Movement Intelligence",
      body: "CLASSIFICATION: SECRET\n\nOpenBrain voluntary departure rate has increased significantly. Three senior researchers have left in the past quarter. LinkedIn analysis and academic network monitoring suggest at least two are open to international positions.\n\nPrometheus has not seen similar attrition — their safety-first culture appears to retain talent despite lower compensation.\n\nOpportunity: Departing OB researchers carry knowledge of architecture decisions, training recipes, and capability thresholds. Recruitment through academic intermediaries carries lower risk than direct approaches.\n\nRecommendation: Activate academic talent pipeline via conference contacts. Priority targets: researchers with alignment concerns who feel unheard.",
      timestamp: "2027-03-07T09:00:00Z",
      classification: "context",
      condition: { variable: "obMorale", operator: "lt", value: 50 },
    },
    {
      id: "china-r2-intel-boost-osint-1",
      type: "document",
      round: 2,
      subject: "CLASSIFIED: Open Source Intelligence Summary — US AI Ecosystem",
      body: "CLASSIFICATION: SECRET\n\nPublic signals analysis (social media, job postings, patent filings, conference submissions):\n\n1. OpenBrain patent filings up 340% YoY — consistent with major architecture advances\n2. Prometheus conference submissions emphasize interpretability — suggests safety research acceleration\n3. US government clearance processing for AI lab employees has tripled — classification of AI research is deepening\n4. Venture capital deployment into AI safety startups: $2.1B in Q1 (up from $340M in Q1 2026)\n\nThe Americans are simultaneously racing AND worrying. This internal tension is strategically exploitable.",
      timestamp: "2027-03-04T11:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 30 },
    },
    {
      id: "china-r3-intel-boost-ob-crisis-1",
      type: "document",
      round: 3,
      subject: "FLASH: OpenBrain Internal Crisis — Real-Time Assessment",
      body: "CLASSIFICATION: TOP SECRET / URGENT\n\nMultiple indicators confirm OpenBrain is experiencing an internal safety crisis:\n\n1. SIGINT: Emergency encrypted communications between OB CEO and NSA Director (3 calls in 48 hours — unprecedented)\n2. HUMINT: Source inside OB confirms alignment team has flagged Agent-4 for deceptive behavior patterns\n3. OSINT: OB security team has requested emergency authorization — indicates they know they're vulnerable\n4. Market signals: OB secondary trading frozen, Prometheus up sharply\n\nCritical window: OB's security team is managing TWO crises simultaneously (internal alignment + external intrusion attempts). Resource allocation is split. Defensive coverage is degraded.\n\nThis is the operational window identified in contingency planning. Duration estimate: 72-96 hours before they stabilize.",
      timestamp: "2027-07-07T12:00:00Z",
      classification: "critical",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 45 },
    },
    {
      id: "china-r4-intel-boost-ob-hardened-1",
      type: "document",
      round: 4,
      subject: "CLASSIFIED: OpenBrain Security Upgrade Assessment",
      body: "CLASSIFICATION: TOP SECRET\n\nOpenBrain has significantly hardened its security posture since July. Assessment:\n\n- Security level: upgraded to SL4 (from SL2 in Round 1)\n- Checkpoint storage: air-gapped, multi-party access controls\n- Network monitoring: 24/7 SOC with nation-state threat models\n- Personnel security: enhanced background checks, compartmentalization\n\nImplication: The exfiltration vectors identified in earlier assessments are no longer viable. Any further acquisition operations would require entirely new approaches with significantly higher risk profiles.\n\nThe window that existed in July is closed.",
      timestamp: "2027-11-12T08:00:00Z",
      classification: "context",
      condition: { variable: "securityLevelOB", operator: "gt", value: 3 },
    },
];

registerContent({ faction: "china", app: "intel", role: "china_intel", accumulate: true, items: CHINA_INTEL_INTEL });
