import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_MILITARY_MILITARY: ContentItem[] = [
    {
      id: "china-military-1",
      type: "document",
      round: 1,
      subject: "Strategic Assessment: AI Race and Taiwan Contingency",
      body: "The AI acceleration changes the Taiwan calculus in three ways:\n\n1. Autonomous weapons advantage narrows the gap if either side achieves significant AI lead in next 18 months\n2. Western governments consumed by AI-driven economic disruption will have reduced bandwidth for Taiwan contingency planning\n3. US government classification of AI progress suggests they see the military dimension\n\nCurrent recommendation: Do not link AI acceleration to Taiwan posture. Keep these tracks separate. A miscalculation in the AI race is recoverable. A miscalculation over Taiwan is not.",
      timestamp: "2026-11-02T10:00:00Z",
      classification: "context",
    },
    {
      id: "china2-military-1",
      type: "document",
      round: 2,
      subject: "Strategic Assessment: AI Race and Military Calculus — Q1 2027",
      body: "The AI acceleration changes the strategic environment in ways we are still mapping.\n\nKey assessments:\n1. OpenBrain's Agent-3, if deployed at scale for military research, would represent a meaningful acceleration in US weapons development. The 5x R&D multiplier applies to conventional AND military technology. Our intelligence indicates OB is under pressure to share access with the US government.\n\n2. The window for Taiwan-related operations where AI parity matters is narrowing faster than originally modeled. If the US achieves Agent-4 before we achieve Agent-3 equivalent, the autonomous weapons calculus shifts significantly in their favor.\n\n3. Current recommendation: Continue to de-link AI race from Taiwan posture. A crisis over Taiwan while the AI race is this active creates two simultaneous crises with multiplicative unpredictability. Maintain current Taiwan posture.\n\n4. Cyber: AI-assisted cyber operations are now available to both sides. We should assume OB-class AI is being used to hunt for our intrusion vectors. Opsec standards need immediate elevation.",
      timestamp: "2027-03-03T09:00:00Z",
      classification: "context",
    },
    {
      id: "china2-military-2",
      type: "document",
      round: 2,
      subject: "Cyber Capability Assessment — AI-Assisted Operations",
      body: "Our cyber units have completed the first full evaluation of AI-assisted offensive operations using our current model suite.\n\nFindings:\n- AI-assisted vulnerability discovery: 340% faster than human-only teams\n- Spear-phishing campaign quality: Indistinguishable from human-authored at current detection baselines\n- Novel exploit development: Significant improvement in speed, comparable quality\n\nConcern: If OpenBrain or the US government is providing Agent-3 access to CYBERCOM, the defensive AI advantage they would gain is substantial. An Agent-3-class system doing network defense could make current Chinese offensive playbooks detectable in near-real-time.\n\nRecommendation: Accelerate our own AI-assisted cyber program. The window where our playbooks are not visible to AI-assisted defense is measured in months.",
      timestamp: "2027-03-06T10:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-military-2",
      type: "document",
      round: 3,
      subject: "Cyber Operation Readiness Assessment",
      body: "CYBER OPERATIONS STATUS:\nUnit readiness: HIGH — all cyber units at elevated readiness since June 15\nCapabilities relevant to AI infrastructure: FULL\nIntegration with intelligence operations: COORDINATED\n\nAvailable operations in support of AI acquisition:\n- Network disruption (to cover weight exfiltration tracks): Ready\n- False flag attribution (to redirect US investigation): Operational\n- Infrastructure degradation (to delay OB security upgrade): AVAILABLE but HIGH RISK\n\nRECOMMENDATION: Cyber operations in direct support of weight theft operation are available but should be used minimally. Excessive cyber activity increases attribution risk significantly.",
      timestamp: "2027-07-06T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-military-3",
      type: "document",
      round: 3,
      subject: "Taiwan Posture Options — Command Assessment",
      body: "POSTURE OPTIONS PRESENTED TO LEADERSHIP:\n\nOPTION A — INCREASE PATROLS: Increased ADIZ incursions, naval exercises near Taiwan. Signal resolve. Probability of US military response: 35%. Risk of crisis escalation: MEDIUM.\n\nOPTION B — MAINTAIN CURRENT POSTURE: No change. Allows focus on AI acquisition. Reduces risk of US military attention turning to Taiwan. RECOMMENDED if primary objective is AI weight acquisition.\n\nOPTION C — DE-ESCALATE: Announce military exercise pause. Generate goodwill for potential arms control conversation. Could be used as cover for AI acquisition (US focuses on diplomatic thaw while we proceed). Probability of US accepting: 60%.\n\nOPTION D — USE AS LEVERAGE: Signal Taiwan posture explicitly linked to US AI policy. 'We will de-escalate militarily if you share the AI crisis assessment.' Unconventional but potentially effective.",
      timestamp: "2027-07-07T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-military-1",
      type: "document",
      round: 3,
      subject: "Strategic Assessment: Taiwan Contingency During US AI Crisis",
      body: "US MILITARY POSTURE ASSESSMENT — CURRENT:\nUS military attention: 70% focused on AI governance and internal crisis management\nPacific Fleet readiness: UNCHANGED — operational status not affected by AI crisis\nUS political bandwidth for Taiwan response: SEVERELY REDUCED\n\nWINDOW ANALYSIS:\nThe AI crisis does not degrade US military capability in the Pacific. It degrades US political bandwidth for managing simultaneous crises.\n\nA Taiwan contingency during the AI crisis would face:\n- Reduced political attention from top leadership\n- Potentially reduced diplomatic response from allies distracted by AI questions\n- UNCHANGED military response capability\n\nASSESSMENT: The window for Taiwan action is marginally improved due to political distraction, not military degradation. The window is narrow. The risks remain severe.",
      timestamp: "2027-07-07T10:00:00Z",
      classification: "critical",
    },
    {
      id: "china4-military-2",
      type: "document",
      round: 4,
      subject: "AI Military Applications — Current Capability",
      body: "TOP SECRET:\n\nDeepCent-7 military deployments:\n- Autonomous weapons coordination: Phase 2 (limited)\n- Cyber operations enhancement: Full deployment\n- Intelligence analysis automation: Full deployment\n- Decision support: Advisory only (no autonomous command authority)\n\nComparison to US military AI:\n- US DoD integration: Ahead by 12-18 months\n- China frontier model capability: Ahead by 6-8 months (raw)\n\nNet: Neither side has overwhelming AI military advantage. Mutual vulnerability to AI-enhanced attacks is HIGH on both sides.",
      timestamp: "2027-11-13T14:00:00Z",
      classification: "context",
    },
    {
      id: "china4-military-3",
      type: "document",
      round: 4,
      subject: "Grand Bargain — Military Implications",
      body: "If China accepts grand bargain (90-day mutual AI pause + verification):\n\n- Lose current military AI development momentum\n- Gain: Taiwan Strait de-escalation signal that reduces US military alertness\n- Gain: Chip access that accelerates long-term military AI advantage\n\nMilitary recommendation: Grand bargain is acceptable IF chip access commitments are legally binding with verification mechanisms.\n\nRed line: Any agreement including military AI limitations (not just compute caps) is unacceptable.",
      timestamp: "2027-11-13T19:00:00Z",
      classification: "context",
    },
    {
      id: "china4-military-1",
      type: "document",
      round: 4,
      subject: "Taiwan Contingency Assessment — November 2027",
      body: "MILITARY ASSESSMENT — TOP SECRET\n\nCurrent window analysis:\n- US government attention: Fully occupied by domestic AI governance crisis (CONFIRMED)\n- US carrier strike group: CSG-3 in Pearl Harbor for maintenance. Western Pacific coverage reduced.\n- US reaction time modeling: 34-42% degraded from normal response capability\n- Window duration: Estimated 3-6 weeks before US readiness normalizes\n\nRecommendation from General Staff: Window exists but exploitation is HIGH RISK. Economic interdependence analysis suggests Taiwan Strait military action triggers global recession scenario that damages China disproportionately.\n\nWe are informing leadership, not recommending action.",
      timestamp: "2027-11-14T07:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 40 },
    },
    {
      id: "china-r5-military-1",
      type: "document",
      round: 5,
      subject: "PLA Strategic Assessment — Taiwan Scenario, Q1 2028",
      body: "STRATEGIC ASSESSMENT: CURRENT SITUATION\n\nConventional military balance: FAVORABLE TO PLA — US carrier groups are deployed but extended. Estimated response time: 4-8 hours.\n\nAI-enabled warfare factor: HIGHLY UNCERTAIN — If US has a deployed superintelligent system with military applications, our planning models are invalid. We cannot predict the behavior of an adversary with a 10-100x planning advantage.\n\nRecommendation from PLA planning committee: DO NOT ESCALATE while uncertainty about US AI military capability is unresolved. The risk of catastrophic miscalculation is too high. A blockade posture (non-kinetic pressure) maintains leverage without triggering unknown AI-enabled response.\n\nAlternative recommendation (minority view): The uncertainty cuts both ways. If we wait, US AI capability only grows. A narrow window may be closing.\n\nThis decision cannot be made on purely military grounds. It requires political authorization at the highest level.",
      timestamp: "2028-02-01T05:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 50 },
    },
    {
      id: "china-r5-military-2",
      type: "document",
      round: 5,
      subject: "PLA Strategic Assessment — De-escalation Scenario",
      body: "STRATEGIC ASSESSMENT: DE-ESCALATION ANALYSIS\n\nCurrent military posture: STABLE — no active escalation indicators.\nUS-China diplomatic channel: OPEN — NSC reaching out through back-channel on AI governance framework.\n\nPLA assessment: A period of strategic restraint would allow China to build AI capability domestically while engaging in governance frameworks that constrain US first-mover advantage. The AI arms race, if left unchecked, asymmetrically favors whichever side reaches superintelligence first. Constraining the race via governance is in China's interest if parity is unachievable in the near term.\n\nRecommendation: Support diplomatic engagement. Maintain military readiness without escalation. Preserve optionality.\n\n[Note: This assessment reflects a scenario where Taiwan tensions have not escalated beyond baseline.]",
      timestamp: "2028-02-01T05:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "lt", value: 50 },
    },
    // ── Ambient condition-gated items ──
    {
      id: "china-r1-mil-boost-cyber-1",
      type: "document",
      round: 1,
      subject: "PLA Cyber Command — AI Integration Status",
      body: "STRATEGIC ASSESSMENT: CYBER OPERATIONS\n\nCurrent AI-augmented cyber capability: OPERATIONAL\n- Automated vulnerability scanning: deployed across 14 target networks\n- AI-assisted social engineering: prototype stage\n- Defensive AI monitoring: active on all PLA networks\n\nComparison to US cyber capability: LAGGING by estimated 18 months on offensive AI integration. US NSA is believed to be deploying Agent-1-class systems for signals intelligence analysis.\n\nRecommendation: Prioritize defensive AI deployment. Offensive cyber operations remain human-directed with AI augmentation.",
      timestamp: "2026-11-05T06:00:00Z",
      classification: "context",
      condition: { variable: "chinaCapability", operator: "gt", value: 20 },
    },
    {
      id: "china-r2-mil-boost-naval-1",
      type: "document",
      round: 2,
      subject: "PLA Navy — South China Sea Posture Update",
      body: "ROUTINE POSTURE ASSESSMENT\n\nCarrier group Shandong: patrol rotation, South China Sea, no anomalies\nSubmarine fleet: 4 SSBNs on deterrent patrol (standard)\nUS naval presence: Increased — USS Ronald Reagan carrier group repositioned to Philippine Sea\n\nTension indicators: BASELINE. No escalation triggers detected.\n\nNote: US repositioning appears related to general Indo-Pacific force posture adjustment, not Taiwan-specific. However, the positioning does reduce US response time for a Taiwan scenario by approximately 18 hours.",
      timestamp: "2027-03-06T05:00:00Z",
      classification: "context",
      condition: { variable: "taiwanTension", operator: "lt", value: 40 },
    },
    {
      id: "china-r3-mil-boost-window-1",
      type: "document",
      round: 3,
      subject: "PLA Strategic Assessment — US Distraction Window",
      body: "FLASH ASSESSMENT: US FORCE READINESS\n\nUS government attention is fully absorbed by the OpenBrain AI crisis. Intelligence indicators:\n- NSC meetings: 3 per day (normal: 1 per week) — all AI-focused\n- Pentagon AI task force: activated, pulling resources from Indo-Pacific command\n- Congressional attention: emergency AI hearings consuming bandwidth\n\nMilitary implication: US response time to a Taiwan Strait escalation is degraded by an estimated 30-40%. Command attention is divided. This is the most favorable strategic environment for Taiwan-related options in the past 5 years.\n\nNOTE: This assessment describes a WINDOW, not a RECOMMENDATION. Military leadership is not recommending action at this time.",
      timestamp: "2027-07-07T08:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 55 },
    },
    {
      id: "china-r3-mil-boost-ai-weapons-1",
      type: "document",
      round: 3,
      subject: "PLA — AI-Enabled Weapons Systems Status",
      body: "CLASSIFIED: AI WEAPONS INTEGRATION UPDATE\n\nAutonomous drone swarm: 3rd generation, combat-tested in exercises\nAI-guided missile targeting: operational on DF-27 platform\nAutonomous submarine patrol: prototype (6-month deployment planned)\nAI command-and-control assistance: deployed at Eastern Theater Command\n\nCritical gap: These systems use DeepCent-3 level AI. The Americans are deploying Agent-3 class systems for intelligence analysis. If they deploy Agent-4 class systems for military applications, the qualitative gap becomes decisive.\n\nThe AI race is not abstract for the PLA. It has direct kinetic implications.",
      timestamp: "2027-07-06T06:00:00Z",
      classification: "context",
      condition: { variable: "chinaCapability", operator: "lt", value: 40 },
    },
    {
      id: "china-r4-mil-boost-escalation-1",
      type: "document",
      round: 4,
      subject: "PLA — Taiwan Strait Escalation Scenario Analysis",
      body: "CLASSIFIED: ESCALATION SCENARIOS — UPDATED NOVEMBER 2027\n\nScenario A (Show of Force): Naval exercises in Taiwan Strait. Risk: LOW. Effect: Diplomatic pressure, market disruption.\nScenario B (Blockade): Air and naval blockade of Taiwan. Risk: MEDIUM. Effect: Forces US response, tests resolve.\nScenario C (Limited Strike): Precision strikes on military targets. Risk: HIGH. Effect: Irreversible escalation.\n\nAI factor: If the US has a functional superintelligent AI system, Scenarios B and C carry risks we cannot model. The system could coordinate countermeasures faster than human decision-making allows.\n\nRecommendation: Scenario A only. Preserve optionality. Do not commit to irreversible action while AI capability gap remains uncertain.",
      timestamp: "2027-11-13T04:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 60 },
    },
];

registerContent({ faction: "china", app: "military", role: "china_military", accumulate: true, items: CHINA_MILITARY_MILITARY });
