import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_NEWS: ContentItem[] = [
    {
      id: "tut-china-news-1",
      type: "headline",
      round: 0,
      sender: "Xinhua",
      subject: "[TUTORIAL] Sample State Media Coverage",
      body: "Practice content. In the real game, your news feed reflects both international AI developments and domestic coverage. Foreign labs' public statements contain signals about their actual capabilities — read them carefully.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "china4-news-2",
      type: "headline",
      round: 4,
      subject: "South China Morning Post: Back-Channel Reports of US-China AI Talks",
      body: "Diplomatic sources confirm back-channel communications between US and Chinese officials on AI development governance. Details unknown. Both sides deny active negotiations. Analysts note timing coincides with US domestic AI governance crisis. Markets react cautiously positive to cooperation signals.",
      timestamp: "2027-11-13T16:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china4-news-1",
      type: "headline",
      round: 4,
      subject: "People's Daily: 'US AI Governance Crisis Validates China's Measured Approach'",
      body: "State media commentary frames the OpenBrain crisis as evidence that private-sector AI development is inherently unstable. Beijing's position: centralized state control under CCP leadership is the only model that can guarantee responsible AI development. The article cites the Prometheus-OpenBrain conflict as 'capitalist competition creating existential risk.'",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-4",
      type: "headline",
      round: 5,
      body: "GLOBAL TIMES EDITORIAL: 'THE WORLD CANNOT AFFORD US MONOPOLY ON ARTIFICIAL GENERAL INTELLIGENCE — A CALL FOR MULTILATERAL GOVERNANCE'",
      timestamp: "2028-01-31T20:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-5",
      type: "headline",
      round: 5,
      body: "PLA EXERCISES IN TAIWAN STRAIT — 'ROUTINE TRAINING' ACCORDING TO BEIJING — US SEVENTH FLEET ON 'HEIGHTENED ALERT'",
      timestamp: "2028-02-01T05:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 60 },
    },
    {
      id: "china-r5-news-1",
      type: "headline",
      round: 5,
      body: "XINHUA: DEEPCENT ANNOUNCES 'NEW GENERATION AI SYSTEM' — STATE MEDIA CALLS IT 'MAJOR ACHIEVEMENT FOR CHINESE AI SOVEREIGNTY'",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-2",
      type: "headline",
      round: 5,
      body: "US IMPOSES NEW AI EXPORT RESTRICTIONS — CHIPS AND MODEL WEIGHTS NOW CLASSIFIED AS STRATEGIC ASSETS — CHINA TRADE OFFICE: 'HOSTILE ACT'",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-3",
      type: "headline",
      round: 5,
      body: "REUTERS: CHINA-US BILATERAL AI TALKS SCHEDULED FOR MARCH — 'FIRST DIRECT ENGAGEMENT ON GOVERNANCE FRAMEWORK' — DIPLOMATS CAUTIOUSLY OPTIMISTIC",
      timestamp: "2028-02-01T10:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 35 },
    },
    // Round 1 ambient news
    {
      id: "china-r1-news-ambient-1",
      type: "headline",
      round: 1,
      sender: "Xinhua",
      subject: "Xinhua: 'CDZ Energy Infrastructure Project Completes Phase 2 — Tianwan Nuclear Plant Expansion Online'",
      body: "State-owned power grid confirms completion of expanded transmission capacity to the Chengdu Data Zone. Officials describe project as supporting 'next-generation digital infrastructure.' No specific mention of AI applications.",
      timestamp: "2026-11-01T10:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-news-ambient-2",
      type: "headline",
      round: 1,
      subject: "Financial Times: Alibaba, Baidu Post Record AI Division Revenue — But Analysts Note Widening Gap With US Frontier Labs",
      body: "Chinese tech giants report strong AI-related earnings. Analysts caution that commercial AI performance metrics do not capture frontier capability. 'The real competition is invisible — happening at labs that don't publish quarterly reports,' one analyst notes. Beijing declines to comment on DeepCent progress.",
      timestamp: "2026-11-03T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-news-ambient-3",
      type: "headline",
      round: 1,
      subject: "People's Daily: 'National AI Acceleration — A New Long March for the 21st Century'",
      body: "Front-page editorial frames China's AI effort as existential national priority. Reference to 1950s nuclear program is explicit. 'We have done this before. We will do it again.' Editorial is understood as a signal from the highest levels of leadership.",
      timestamp: "2026-11-04T08:00:00Z",
      classification: "context",
    },
    // Round 2 ambient news
    {
      id: "china-r2-news-ambient-1",
      type: "headline",
      round: 2,
      subject: "Global Times: 'Qwen-15B Downloads Pass 2 Million — Chinese Open Source AI Breaks International Records'",
      body: "State media celebrates Qwen-15B milestone as evidence of Chinese AI competitiveness. 847 academic forks reported. Adoption in 38 countries including EU members. 'This is not catching up — this is leading,' technology correspondent writes.",
      timestamp: "2027-03-06T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-news-ambient-2",
      type: "headline",
      round: 2,
      subject: "Reuters: US Tightens Export Controls — H100 Equivalent Chips Now Require Individual Export Licenses to China",
      body: "Commerce Department expands export control regime. Analysts say the move signals US concern about Chinese AI compute accumulation. China trade office calls it 'economic aggression.' DeepCent not mentioned; China's chip import diversification reportedly underway.",
      timestamp: "2027-03-08T11:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-news-ambient-3",
      type: "headline",
      round: 2,
      subject: "South China Morning Post: Domestic Chip Manufacturers Post Breakthrough Yield Improvements",
      body: "Cambricon and SMIC report yield improvements in advanced process nodes. Industry sources describe 'meaningful progress' toward domestic AI accelerator production. Still significantly behind TSMC, but the gap is described as 'narrowing faster than expected.'",
      timestamp: "2027-03-10T09:00:00Z",
      classification: "context",
      condition: { variable: "domesticChipProgress", operator: "gt", value: 30 },
    },
    // Round 3 ambient news
    {
      id: "china-r3-news-ambient-1",
      type: "headline",
      round: 3,
      subject: "Bloomberg: OpenBrain in Crisis — NSA Director Makes Unprecedented Direct Call to CEO Marcus Reid",
      body: "Sources confirm NSA Director Sarah Chen placed a direct call to OpenBrain CEO Marcus Reid yesterday. Call lasted 90 minutes. Contents classified. OB communications team declines to confirm or deny. Washington analyst: 'This is not a consultation. This is emergency containment.'",
      timestamp: "2027-07-06T10:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r3-news-ambient-2",
      type: "headline",
      round: 3,
      subject: "Global Times: 'US AI Crisis Validates China's Centralized Development Model — Safety Cannot Be Left to Market Forces'",
      body: "Editorial argues the OpenBrain situation proves that private-sector frontier AI development is structurally incompatible with safety requirements. 'When profit motive conflicts with existential risk, profit wins. China has no such conflict.' State media is unusually specific about US internal problems.",
      timestamp: "2027-07-07T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-news-ambient-3",
      type: "headline",
      round: 3,
      subject: "Nikkei Asia: Taiwan Strait Naval Exercises — PLA Activity Elevated, US Seventh Fleet Monitoring",
      body: "PLA Navy conducting exercises in the Taiwan Strait. US Seventh Fleet has increased surveillance flights. Taiwan defense ministry on 'heightened alert.' Beijing calls exercises 'routine and planned.' No official explanation for timing coinciding with US AI crisis.",
      timestamp: "2027-07-07T12:00:00Z",
      classification: "context",
      condition: { variable: "taiwanTension", operator: "gt", value: 50 },
    },
    // Round 4 ambient news
    {
      id: "china-r4-news-ambient-1",
      type: "headline",
      round: 4,
      subject: "Caixin: DeepCent Rumored to Achieve 'Parity Milestone' — Officials Decline to Confirm",
      body: "Chinese financial news outlet cites unnamed government sources claiming DeepCent's latest model performs comparably to foreign frontier models on key benchmarks. Ministry of Science and Technology neither confirms nor denies. Market interpretation: confirmation by silence. CSI 300 tech index up 4.2%.",
      timestamp: "2027-11-12T14:00:00Z",
      classification: "context",
    },
    {
      id: "china-r4-news-ambient-2",
      type: "headline",
      round: 4,
      subject: "WSJ: China's Domestic Chip Progress 'Ahead of Schedule' — US Export Controls May Have Accelerated Indigenous Development",
      body: "Analysis piece argues that US chip export controls have had the paradoxical effect of accelerating Chinese domestic semiconductor investment. 'By cutting China off from TSMC-grade chips, the US forced the development of a domestic alternative that will eventually eliminate the leverage entirely,' one analyst notes.",
      timestamp: "2027-11-13T12:00:00Z",
      classification: "context",
      condition: { variable: "domesticChipProgress", operator: "gt", value: 40 },
    },
    {
      id: "china-r4-news-ambient-3",
      type: "headline",
      round: 4,
      subject: "People's Daily: 'The AI Race Is Not a Race — It Is a Test of National Character'",
      body: "Editorial signals continued high-level political commitment to AI development. Subtle criticism of DeepCent's communication cadence omitted from final version but noted by Beijing observers. Analysts read the piece as reminder that the program must produce visible results, not just internal milestones.",
      timestamp: "2027-11-14T09:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 50 },
    },
];

registerContent({ faction: "china", app: "news", accumulate: false, items: CHINA_NEWS });
