import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_NEWS: ContentItem[] = [
    {
      id: "tut-china-news-1",
      type: "headline",
      round: 0,
      sender: "Xinhua",
      subject: "[TUTORIAL] Sample State Media Coverage",
      body: "Practice content. In the real game, your news feed reflects both international AI developments and domestic coverage. Foreign labs' public statements contain signals about their actual capabilities — read them carefully.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "china4-news-2",
      type: "headline",
      round: 4,
      subject: "South China Morning Post: Back-Channel Reports of US-China AI Talks",
      body: "Diplomatic sources confirm back-channel communications between US and Chinese officials on AI development governance. Details unknown. Both sides deny active negotiations. Analysts note timing coincides with US domestic AI governance crisis. Markets react cautiously positive to cooperation signals.",
      timestamp: "2027-11-13T16:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china4-news-1",
      type: "headline",
      round: 4,
      subject: "People's Daily: 'US AI Governance Crisis Validates China's Measured Approach'",
      body: "State media commentary frames the OpenBrain crisis as evidence that private-sector AI development is inherently unstable. Beijing's position: centralized state control under CCP leadership is the only model that can guarantee responsible AI development. The article cites the Prometheus-OpenBrain conflict as 'capitalist competition creating existential risk.'",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-4",
      type: "headline",
      round: 5,
      body: "GLOBAL TIMES EDITORIAL: 'THE WORLD CANNOT AFFORD US MONOPOLY ON ARTIFICIAL GENERAL INTELLIGENCE — A CALL FOR MULTILATERAL GOVERNANCE'",
      timestamp: "2028-01-31T20:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-5",
      type: "headline",
      round: 5,
      body: "PLA EXERCISES IN TAIWAN STRAIT — 'ROUTINE TRAINING' ACCORDING TO BEIJING — US SEVENTH FLEET ON 'HEIGHTENED ALERT'",
      timestamp: "2028-02-01T05:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 60 },
    },
    {
      id: "china-r5-news-1",
      type: "headline",
      round: 5,
      body: "XINHUA: DEEPCENT ANNOUNCES 'NEW GENERATION AI SYSTEM' — STATE MEDIA CALLS IT 'MAJOR ACHIEVEMENT FOR CHINESE AI SOVEREIGNTY'",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-2",
      type: "headline",
      round: 5,
      body: "US IMPOSES NEW AI EXPORT RESTRICTIONS — CHIPS AND MODEL WEIGHTS NOW CLASSIFIED AS STRATEGIC ASSETS — CHINA TRADE OFFICE: 'HOSTILE ACT'",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-news-3",
      type: "headline",
      round: 5,
      body: "REUTERS: CHINA-US BILATERAL AI TALKS SCHEDULED FOR MARCH — 'FIRST DIRECT ENGAGEMENT ON GOVERNANCE FRAMEWORK' — DIPLOMATS CAUTIOUSLY OPTIMISTIC",
      timestamp: "2028-02-01T10:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 35 },
    },
    // Round 1 non-AI ambient news
    {
      id: "china-r1-news-flavor-1",
      type: "headline",
      round: 1,
      sender: "Xinhua",
      subject: "China October Manufacturing PMI Rises to 51.4 — Exports Ahead of Forecast",
      body: "The National Bureau of Statistics reported that China's official manufacturing Purchasing Managers' Index rose to 51.4 in October, above the 50-point expansion threshold and ahead of the 50.8 consensus forecast. Export orders sub-index improved for the third consecutive month. Analysts attributed the improvement to resilient demand in Southeast Asia and Latin American markets, which have partially offset softer European orders. The data supported modest gains in the CSI 300 index.",
      timestamp: "2026-11-01T09:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-2",
      type: "headline",
      round: 1,
      sender: "People's Daily",
      subject: "National Day Golden Week Tourism Revenue Reaches 900 Billion Yuan — Domestic Travel Breaks Record",
      body: "China's Ministry of Culture and Tourism confirmed that the National Day Golden Week holiday generated approximately 900 billion yuan in domestic tourism revenue, a 12% increase over the prior year. Domestic trips reached 1.07 billion, exceeding pre-pandemic records for the first time. Popular destinations including Zhangjiajie, Lijiang, and the Forbidden City reported sustained full-capacity attendance. Officials attributed the record to improved rail connectivity and a renewed focus on domestic cultural tourism promotion.",
      timestamp: "2026-11-03T08:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-3",
      type: "headline",
      round: 1,
      sender: "South China Morning Post",
      subject: "Beijing-Chengdu High-Speed Rail Extension Opens — Journey Time Cut to 5 Hours",
      body: "The final section of the Beijing-Chengdu high-speed rail corridor officially opened to passengers Thursday, reducing end-to-end journey time from 14 hours by conventional rail to approximately five hours. The 2,100-kilometer route passes through some of China's most geographically challenging terrain, crossing the Qinling and Daba mountain ranges via a network of tunnels and elevated viaducts. The China Railway Corporation called the opening 'the largest single infrastructure achievement of the current five-year plan.'",
      timestamp: "2026-11-05T10:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-4",
      type: "headline",
      round: 1,
      sender: "Caixin Global",
      subject: "Tier-2 City Home Prices Stabilize After 18 Months of Declines — Recovery Uneven",
      body: "New residential property prices in China's tier-2 cities showed their first month-on-month stabilization since April 2025, according to data from the National Bureau of Statistics. Chengdu, Xi'an, and Wuhan reported flat or marginally positive figures while Zhengzhou and Harbin remain under pressure. Analysts cautioned that stabilization is not recovery — transaction volumes remain below historical norms and developer inventory in lower-tier cities is still elevated. The People's Bank of China has cut mortgage rates twice this year to support demand.",
      timestamp: "2026-11-04T09:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-5",
      type: "headline",
      round: 1,
      sender: "People's Daily",
      subject: "Period Drama 'Rivers of Silk' Hits 10 Billion Views on iQiyi — Breaks Platform Record",
      body: "Period costume drama 'Rivers of Silk' (《锦绣山河》) has surpassed 10 billion streaming views on iQiyi, making it the fastest series to reach that milestone in the platform's history. The show, set during the Tang dynasty and depicting the life of a female court official, has driven a wave of hanfu fashion interest and tourism to Luoyang. A related hashtag has been trending on Douyin for three weeks. Industry analysts say the series reflects sustained audience appetite for historically grounded stories amid the recent glut of fantasy adaptations.",
      timestamp: "2026-11-04T14:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-6",
      type: "headline",
      round: 1,
      sender: "Xinhua",
      subject: "Yangtze River Finless Porpoise Population Increases for Fourth Consecutive Year",
      body: "The annual survey of the Yangtze River finless porpoise recorded 1,249 individuals this year, up from 1,162 in the prior survey — the fourth consecutive year of population increase since the commercial fishing ban took effect. The Ministry of Agriculture and Rural Affairs attributed the recovery to improved water quality, reduced boat traffic in protected zones, and an expansion of porpoise sanctuaries near Dongting Lake and Poyang Lake. Conservationists welcomed the figures while noting the species remains critically endangered and population growth is still fragile.",
      timestamp: "2026-11-05T08:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-7",
      type: "headline",
      round: 1,
      sender: "Global Times",
      subject: "China Men's Basketball Team Qualifies for 2028 LA Olympics — CBA Stars Lead Charge",
      body: "The Chinese men's basketball team secured its qualification for the 2028 Los Angeles Olympics after defeating the Philippines 89-74 in the Asia Cup qualifying tournament final. Center Zhou Qi contributed 24 points and 11 rebounds. The result ends a twelve-year Olympic absence for the squad and is seen as validation of the CBA's recent investment in youth development programs. State broadcaster CCTV will air a prime-time retrospective on the squad's resurgence this weekend.",
      timestamp: "2026-11-06T07:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-8",
      type: "headline",
      round: 1,
      sender: "South China Morning Post",
      subject: "Gaokao Reform Proposal Sparks Nationwide Debate Among Parents and Educators",
      body: "A draft proposal circulated by the Ministry of Education would allow university admissions offices to weigh extracurricular achievement and project-based portfolios alongside the national gaokao exam score starting from the 2029 cohort. The proposal has generated immediate controversy: supporters argue it reduces the single-exam pressure that defines a student's trajectory; critics contend it will advantage urban, wealthy families with access to enrichment programs. Parent forums on WeChat have been flooded with commentary since the document surfaced Monday.",
      timestamp: "2026-11-06T11:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-9",
      type: "headline",
      round: 1,
      sender: "Caixin Global",
      subject: "TCM Clinics Multiply Amid Aging Population Push — Regulation Struggles to Keep Pace",
      body: "The number of licensed traditional Chinese medicine clinics has grown by 23% over the past two years as Beijing accelerates a healthcare policy to integrate TCM into the national primary care network. The expansion is intended to ease pressure on tier-3 hospitals and serve China's rapidly aging population. But industry watchdogs warn that rapid licensing growth has outpaced the supply of qualified practitioners and raised quality-control concerns. The National Administration of Traditional Chinese Medicine is drafting updated practitioner certification standards expected by mid-2027.",
      timestamp: "2026-11-07T09:00:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-news-flavor-10",
      type: "headline",
      round: 1,
      sender: "Xinhua",
      subject: "Inner Mongolia Wind Power Capacity Crosses 100 GW — Grid Absorption Remains Challenge",
      body: "Inner Mongolia's cumulative installed wind power capacity has crossed the 100 gigawatt threshold, cementing its position as China's largest wind energy base and contributing to the country's goal of 1,200 GW of total renewables by 2030. The milestone was marked at a ceremony in Hohhot attended by senior officials from the National Energy Administration. Transmission bottlenecks remain the primary constraint: an estimated 12% of wind-generated electricity was curtailed last year due to insufficient ultra-high-voltage lines connecting Inner Mongolia to coastal demand centers.",
      timestamp: "2026-11-07T11:00:00Z",
      classification: "flavor",
    },

    // Round 1 unconditional news
    {
      id: "china-r1-news-1",
      type: "headline",
      round: 1,
      sender: "Caixin Global",
      subject: "China's AI Ambitions Draw Attention as State Funding Reaches Record Levels",
      body: "Beijing's allocation of strategic infrastructure investment to advanced computing projects has reached historic levels, according to budget documents reviewed by Caixin. Power grid expansions across multiple technology development zones are proceeding ahead of schedule, with transmission capacity upgrades completed or underway in Chengdu, Zhengzhou, and Wuhan. Analysts say the pace and scale of infrastructure commitment signals a transition from planning to execution phase. Ministry of Science and Technology declined to comment on specific project timelines.",
      timestamp: "2026-11-02T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-news-2",
      type: "headline",
      round: 1,
      sender: "MIT Technology Review",
      subject: "The Open-Source Model the West Is Sleeping On",
      body: "While the AI discourse in the United States remains fixated on the closed, safety-restricted models coming out of OpenBrain and Prometheus, a quietly different story is unfolding in the global developer community. Alibaba's Qwen family has accumulated millions of downloads across academic and commercial users in 40-plus countries — and the architectural choices that make Qwen competitive are now public. 'The assumption that China is playing catch-up fundamentally misreads what's happening,' said one independent AI researcher. 'They're running a different race.' US labs have spent aggressively on compute and proprietary weights. China has seeded an open-source ecosystem that doesn't require anyone to trust a single lab.",
      timestamp: "2026-11-06T10:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-news-3",
      type: "headline",
      round: 1,
      sender: "Financial Times",
      subject: "The Talent War at the Heart of the AI Race",
      body: "US and Chinese AI labs are competing intensely for a small pool of elite researchers — and the results are reshaping where breakthroughs happen. Signing bonuses at American frontier labs have reached eight figures for senior researchers. China's response has included expanded visa programs, government-backed salary top-ups, and increasingly direct appeals to researchers of Chinese heritage at Western institutions. 'The assumption that talent will always flow to San Francisco is becoming harder to sustain,' one senior academic recruiter told the FT. Several recent hires at DeepCent were previously employed by US labs.",
      timestamp: "2026-11-08T09:00:00Z",
      classification: "context",
    },
    // Round 1 ambient news
    {
      id: "china-r1-news-ambient-1",
      type: "headline",
      round: 1,
      sender: "Xinhua",
      subject: "Xinhua: 'CDZ Energy Infrastructure Project Completes Phase 2 — Tianwan Nuclear Plant Expansion Online'",
      body: "State-owned power grid confirms completion of expanded transmission capacity to the Chengdu Data Zone. Officials describe project as supporting 'next-generation digital infrastructure.' No specific mention of AI applications.",
      timestamp: "2026-11-01T10:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-news-ambient-2",
      type: "headline",
      round: 1,
      subject: "Financial Times: Alibaba, Baidu Post Record AI Division Revenue — But Analysts Note Widening Gap With US Frontier Labs",
      body: "Chinese tech giants report strong AI-related earnings. Analysts caution that commercial AI performance metrics do not capture frontier capability. 'The real competition is invisible — happening at labs that don't publish quarterly reports,' one analyst notes. Beijing declines to comment on DeepCent progress.",
      timestamp: "2026-11-03T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-news-ambient-3",
      type: "headline",
      round: 1,
      subject: "People's Daily: 'National AI Acceleration — A New Long March for the 21st Century'",
      body: "Front-page editorial frames China's AI effort as existential national priority. Reference to 1950s nuclear program is explicit. 'We have done this before. We will do it again.' Editorial is understood as a signal from the highest levels of leadership.",
      timestamp: "2026-11-04T08:00:00Z",
      classification: "context",
    },
    // Round 2 ambient news
    {
      id: "china-r2-news-ambient-1",
      type: "headline",
      round: 2,
      subject: "Global Times: 'Qwen-15B Downloads Pass 2 Million — Chinese Open Source AI Breaks International Records'",
      body: "State media celebrates Qwen-15B milestone as evidence of Chinese AI competitiveness. 847 academic forks reported. Adoption in 38 countries including EU members. 'This is not catching up — this is leading,' technology correspondent writes.",
      timestamp: "2027-03-06T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-news-ambient-2",
      type: "headline",
      round: 2,
      subject: "Reuters: US Tightens Export Controls — H100 Equivalent Chips Now Require Individual Export Licenses to China",
      body: "Commerce Department expands export control regime. Analysts say the move signals US concern about Chinese AI compute accumulation. China trade office calls it 'economic aggression.' DeepCent not mentioned; China's chip import diversification reportedly underway.",
      timestamp: "2027-03-08T11:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-news-ambient-3",
      type: "headline",
      round: 2,
      subject: "South China Morning Post: Domestic Chip Manufacturers Post Breakthrough Yield Improvements",
      body: "Cambricon and SMIC report yield improvements in advanced process nodes. Industry sources describe 'meaningful progress' toward domestic AI accelerator production. Still significantly behind TSMC, but the gap is described as 'narrowing faster than expected.'",
      timestamp: "2027-03-10T09:00:00Z",
      classification: "context",
      condition: { variable: "domesticChipProgress", operator: "gt", value: 30 },
    },
    // Round 3 ambient news
    {
      id: "china-r3-news-ambient-1",
      type: "headline",
      round: 3,
      subject: "Bloomberg: OpenBrain in Crisis — NSA Director Makes Unprecedented Direct Call to CEO {ob_ceo}",
      body: "Sources confirm NSA Director Sarah Chen placed a direct call to OpenBrain CEO {ob_ceo} yesterday. Call lasted 90 minutes. Contents classified. OB communications team declines to confirm or deny. Washington analyst: 'This is not a consultation. This is emergency containment.'",
      timestamp: "2027-07-06T10:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r3-news-ambient-2",
      type: "headline",
      round: 3,
      subject: "Global Times: 'US AI Crisis Validates China's Centralized Development Model — Safety Cannot Be Left to Market Forces'",
      body: "Editorial argues the OpenBrain situation proves that private-sector frontier AI development is structurally incompatible with safety requirements. 'When profit motive conflicts with existential risk, profit wins. China has no such conflict.' State media is unusually specific about US internal problems.",
      timestamp: "2027-07-07T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-news-ambient-3",
      type: "headline",
      round: 3,
      subject: "Nikkei Asia: Taiwan Strait Naval Exercises — PLA Activity Elevated, US Seventh Fleet Monitoring",
      body: "PLA Navy conducting exercises in the Taiwan Strait. US Seventh Fleet has increased surveillance flights. Taiwan defense ministry on 'heightened alert.' Beijing calls exercises 'routine and planned.' No official explanation for timing coinciding with US AI crisis.",
      timestamp: "2027-07-07T12:00:00Z",
      classification: "context",
      condition: { variable: "taiwanTension", operator: "gt", value: 50 },
    },
    // Round 4 ambient news
    {
      id: "china-r4-news-ambient-1",
      type: "headline",
      round: 4,
      subject: "Caixin: DeepCent Rumored to Achieve 'Parity Milestone' — Officials Decline to Confirm",
      body: "Chinese financial news outlet cites unnamed government sources claiming DeepCent's latest model performs comparably to foreign frontier models on key benchmarks. Ministry of Science and Technology neither confirms nor denies. Market interpretation: confirmation by silence. CSI 300 tech index up 4.2%.",
      timestamp: "2027-11-12T14:00:00Z",
      classification: "context",
    },
    {
      id: "china-r4-news-ambient-2",
      type: "headline",
      round: 4,
      subject: "WSJ: China's Domestic Chip Progress 'Ahead of Schedule' — US Export Controls May Have Accelerated Indigenous Development",
      body: "Analysis piece argues that US chip export controls have had the paradoxical effect of accelerating Chinese domestic semiconductor investment. 'By cutting China off from TSMC-grade chips, the US forced the development of a domestic alternative that will eventually eliminate the leverage entirely,' one analyst notes.",
      timestamp: "2027-11-13T12:00:00Z",
      classification: "context",
      condition: { variable: "domesticChipProgress", operator: "gt", value: 40 },
    },
    {
      id: "china-r4-news-ambient-3",
      type: "headline",
      round: 4,
      subject: "People's Daily: 'The AI Race Is Not a Race — It Is a Test of National Character'",
      body: "Editorial signals continued high-level political commitment to AI development. Subtle criticism of DeepCent's communication cadence omitted from final version but noted by Beijing observers. Analysts read the piece as reminder that the program must produce visible results, not just internal milestones.",
      timestamp: "2027-11-14T09:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 50 },
    },
];

registerContent({ faction: "china", app: "news", accumulate: false, items: CHINA_NEWS });
