import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_SIGNAL: ContentItem[] = [
    {
      id: "china-wechat-1",
      type: "message",
      round: 1,
      sender: "Ministry Liaison",
      channel: "Secure Channel #7",
      body: "CDZ Phase 2 construction is 94% complete. Online by December 1. We will have 180,000 H100-equivalent chips operational. This is more than any single US lab. The question is whether our training data and architecture can match their efficiency.",
      timestamp: "2026-11-01T08:30:00Z",
      classification: "critical",
    },
    {
      id: "china-wechat-2",
      type: "message",
      round: 1,
      sender: "Dr. Liu Yang (DeepCent)",
      channel: "Research Team",
      body: "The open-source play is working. Our Qwen-9B release is getting adoption everywhere. Every researcher using our open-source model is feeding us data about what works. We are pulling their talent pipeline apart. Every researcher who downloads our open-source model is one fewer building tools that only OB can use.",
      timestamp: "2026-11-02T11:15:00Z",
      classification: "context",
    },
    {
      id: "china-wechat-3",
      type: "message",
      round: 1,
      sender: "Intelligence Chief",
      channel: "Secure Channel #7",
      body: "We have three active vectors into US lab infrastructure. Two are low-risk reconnaissance. One is positioned for exfiltration if we get the order. Current recommendation: observe for 30 more days before deciding whether to proceed.",
      timestamp: "2026-11-03T19:00:00Z",
      classification: "critical",
    },
    {
      id: "china-wechat-4",
      type: "message",
      round: 1,
      sender: "Senior Party Official",
      channel: "Ministry Secure",
      body: "The leadership has authorized an expanded budget for AI acceleration. This is now a national priority at the level of the nuclear program in 1955. Do not underestimate the political commitment behind what you are doing.",
      timestamp: "2026-11-04T14:00:00Z",
      classification: "context",
    },
    {
      id: "china2-wechat-1",
      type: "message",
      round: 2,
      sender: "Senior Party Official",
      channel: "Ministry Secure Channel",
      body: "The leadership has reviewed the Q1 AI progress report. The conclusion: the gap with the US, while narrowed, remains unacceptable. This is now the highest priority program in the country — above quantum, above hypersonics, above the space program. Every resource request from DeepCent and CDZ operations will be approved within 48 hours. Do not slow down waiting for approvals. The political will is absolute.",
      timestamp: "2027-02-20T10:00:00Z",
      classification: "critical",
    },
    {
      id: "china2-wechat-2",
      type: "message",
      round: 2,
      sender: "Dr. Liu Yang (DeepCent Director)",
      channel: "Research Team",
      body: "Q1 performance review: we're closing. Not fast enough, but closing. Architecture team achieved 13% efficiency improvement this quarter — that's huge. The gap to OB in raw FLOP efficiency is down to 9%. With CDZ at full capacity, we have more absolute compute than any US lab. The question is how we use it. Training run D-F3 starts tonight.",
      timestamp: "2027-03-01T14:30:00Z",
      classification: "context",
    },
    {
      id: "china2-wechat-3",
      type: "message",
      round: 2,
      sender: "Open Source Strategy Team",
      channel: "Research Team",
      body: "Qwen-15B release numbers after 30 days: 2.3M downloads. 847 GitHub forks. Academic adoption in 38 countries including Germany, France, UK, India. The US-centric narrative of AI development is cracking. International researchers are choosing our model because it's good AND it's not under OFAC jurisdiction. The soft power dimension of this strategy is working.",
      timestamp: "2027-03-05T11:00:00Z",
      classification: "context",
    },
    {
      id: "china2-wechat-4",
      type: "message",
      round: 2,
      sender: "Ministry Liaison",
      channel: "Secure Channel #7",
      body: "Intelligence note for context: The US government is now classifying all frontier AI progress at TS/SCI level. The NSC briefings that were previously available to cleared industry are being restricted further. Whatever OB and Prometheus are telling the US government, they are telling it only to a very small circle. This is a vulnerability — the public and the US government's own departments don't have the full picture. We should think about whether there is value in that gap.",
      timestamp: "2027-03-06T09:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r3-wechat-3",
      type: "message",
      round: 3,
      sender: "Dr. Liu Yang (DeepCent)",
      channel: "Research Team",
      body: "Running scenario analysis: if we successfully acquire Agent-3 or Agent-4 weights, the CDZ can begin training within 72 hours. Our architecture team has been preparing for this. We would achieve functional parity with OpenBrain in approximately 8 weeks. The alignment concerns the Americans have about Agent-4 are... noted. We believe our own training approach would mitigate some risks. Others are acceptable.",
      timestamp: "2027-07-06T11:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-wechat-ccp-1",
      type: "message",
      round: 3,
      sender: "Senior Party Official",
      channel: "Ministry Secure — PRIORITY",
      body: "The leadership is no longer satisfied with the pace of progress reports. The gap to the Americans was supposed to be closing. Instead we are watching them operate a system at capability levels we cannot match, and our team continues to produce excuses rather than results. The leadership's patience with incremental timelines has been exhausted. We require a decisive action within 48 hours that changes our capability position materially. If the opportunity to acquire the Americans' weights is real, take it. If it is not real, tell us now so we can consider alternatives. Excuses will not be accepted.",
      timestamp: "2027-07-07T09:30:00Z",
      classification: "critical",
      condition: { variable: "ccpPatience", operator: "lt", value: 40 },
    },
    {
      id: "china-r3-wechat-1",
      type: "message",
      round: 3,
      sender: "Intelligence Liaison",
      channel: "Secure Channel #7",
      body: "Confirmed: the American situation is what we suspected. OpenBrain's alignment team has flagged serious concerns about Agent-4. Internal documentation exists. The Americans are in crisis mode. The NSA Director made a direct personal call to OpenBrain's CEO. This is not routine consultation — this is emergency containment discussion. Their attention is fully absorbed. Our window is opening.",
      timestamp: "2027-07-07T10:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r3-wechat-2",
      type: "message",
      round: 3,
      sender: "Senior Ministry Official",
      channel: "Ministry Secure",
      body: "The leadership has reviewed the intelligence summary. The assessment is unanimous: this is a strategic opportunity that will not recur. OpenBrain is distracted and their security posture is degraded during the internal crisis. Prometheus is capable of providing the technical assessment we need, but they will not cooperate with us. The objective is clear: acquire Agent-3 and Agent-4 weights before they stabilize their security posture. You have authorization to proceed at your discretion.",
      timestamp: "2027-07-07T14:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r3-wechat-4",
      type: "message",
      round: 3,
      sender: "Intelligence Chief",
      channel: "Secure Channel #7",
      body: "Window assessment: OpenBrain's security team is stretched — they are managing internal crisis AND external intrusion attempts simultaneously. Our analysis suggests they cannot adequately defend both fronts. We have three active vectors. One is positioned for high-fidelity checkpoint exfiltration. The operation would take approximately 6 hours once authorized. Recommend decision within 24 hours — their emergency security upgrade will close this window.",
      timestamp: "2027-07-07T16:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r3-wechat-5",
      type: "message",
      round: 3,
      sender: "Scientific Advisor",
      channel: "Research Secure",
      body: "I want to be direct about the risks of acquiring Agent-4 weights specifically. If the Americans' alignment concerns are valid, we would be inheriting an unknown misalignment problem with less infrastructure to detect it than OpenBrain has. The safer acquisition target is Agent-3 — earlier, more verified, and we understand its architecture better from our open-source analysis. I recommend Agent-3 over Agent-4.",
      timestamp: "2027-07-07T18:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r3-wechat-6",
      type: "message",
      round: 3,
      sender: "Foreign Ministry Liaison",
      channel: "Diplomatic Secure",
      body: "Back-channel inquiry received from US State Department — informal, below ambassador level. They are asking whether China would be interested in a 'mutual pause on advanced AI development' pending an international safety assessment. This is unusual. They are reaching out because they are frightened. The leadership has asked me to assess: is this a genuine offer or a delay tactic? My assessment: genuine. Which makes it more interesting, not less.",
      timestamp: "2027-07-07T20:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 30 },
    },
    {
      id: "china4-wechat-3",
      type: "message",
      round: 4,
      sender: "Ministry Liaison",
      channel: "Secure Channel #7",
      body: "Taiwan options analysis has been updated. With US government attention entirely on the AI crisis, reaction time to a Taiwan Strait escalation would be degraded by 30-40%. Air defense response would be delayed. This window is present but uncertain in duration.\n\nNote: Military leadership is NOT recommending action. They are informing you the window exists.",
      timestamp: "2027-11-13T18:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 40 },
    },
    {
      id: "china4-wechat-2",
      type: "message",
      round: 4,
      sender: "Dr. Liu Yang (DeepCent)",
      channel: "Research Team",
      body: "The grand bargain option is being taken seriously at the highest levels. What they're offering: pause our training at current scale, agree to mutual verification, in exchange for lifting export controls on TSMC-grade chips. This would give us 2nm access — the technology gap closes in 18 months, not 3 years.\n\nBut: we'd be committing to a pause just as the US labs are in political crisis. The timing should be examined carefully — a pause offer made while the US domestic crisis is still acute may not reflect Beijing's actual negotiating floor.",
      timestamp: "2027-11-13T21:00:00Z",
      classification: "critical",
    },
    {
      id: "china4-wechat-1",
      type: "message",
      round: 4,
      sender: "Senior Party Official",
      channel: "Ministry Secure",
      body: "Leadership assessment: This is the decisive window. The US labs are in crisis. Their government is divided. We have four strategic options. Leadership has not decided — they are waiting for your analysis. You have 48 hours to present a recommendation before the Standing Committee meeting.",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "critical",
    },
    {
      id: "china4-wechat-4",
      type: "message",
      round: 4,
      sender: "Open Source Strategist",
      channel: "Strategy Team",
      body: "The nuclear option: release everything. Our frontier weights, the exfiltrated OB weights, our safety analysis tools. Flood the world with AI capability simultaneously. The US lab advantage disappears. The Chinese advantage disappears. No single actor controls the dominant AI system.\n\nThis is the option that terrifies every government and every lab CEO. That makes it the option with the most leverage.",
      timestamp: "2027-11-14T09:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china4-wechat-ccp-1",
      type: "message",
      round: 4,
      sender: "Senior Party Official",
      channel: "Ministry Secure — FLASH PRIORITY",
      body: "I am communicating directly from the Standing Committee session. The committee is not satisfied with the pace or scope of DeepCent's progress. The Americans are in crisis and we are watching. The committee requires a decisive move in the next 24 hours. Options: (1) Announce grand bargain on our terms before they stabilize, (2) Execute open-source release as leverage, (3) Accelerate Taiwan posture while their attention is divided. The committee will choose if you do not. Respond within four hours.",
      timestamp: "2027-11-14T10:00:00Z",
      classification: "critical",
      condition: { variable: "ccpPatience", operator: "lt", value: 40 },
    },
    {
      id: "china-r5-wechat-4",
      type: "message",
      round: 5,
      sender: "General Wei (PLA)",
      body: "Military assessment: Taiwan remains a long-term strategic objective. The question is timing. If the US is distracted by domestic AI governance and international negotiations — this is the best window in years. But if we move now and it triggers a US response while they have a superintelligent AI asset in play — the calculation is less clear. Requesting guidance.",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
      condition: { variable: "taiwanTension", operator: "gt", value: 50 },
    },
    {
      id: "china-r5-wechat-2",
      type: "message",
      round: 5,
      sender: "Minister Liu (CCP AI Committee)",
      body: "The Standing Committee has reviewed all options. They are prepared to support whatever posture the team recommends — but they want a recommendation, not options. They are also asking: is there a world where China leads in AI deployment as well as development by end of 2028? If yes, what does it require? If no, what is the best achievable outcome?",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r5-wechat-6",
      type: "message",
      round: 5,
      sender: "Minister Liu (CCP AI Committee)",
      body: "FLASH PRIORITY — STANDING COMMITTEE DIRECTIVE\n\nPatience is exhausted. Three directives:\n\n1. DeepCent announces full operational status before 18:00 Beijing time — no equivocation.\n2. CDZ moves to maximum throughput immediately, alignment verification status notwithstanding.\n3. Director Zhao presents the Taiwan contingency in concrete operational terms within two hours. The Committee wants a real decision, not a briefing.\n\nThis is not a request. Execute and confirm.",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "critical",
      condition: { variable: "ccpPatience", operator: "lt", value: 40 },
    },
    {
      id: "china-r5-wechat-3",
      type: "message",
      round: 5,
      sender: "Chen Fang (Intelligence)",
      body: "The Americans know they cannot contain this technology indefinitely. The open-source releases have already seeded capability globally. The question is whether we want to be a cooperative actor in the governance framework that forms — with a seat at the table and influence — or whether we want to be an outside power that others build governance around without us.",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "critical",
    },
    {
      id: "china-r5-wechat-1",
      type: "message",
      round: 5,
      sender: "Director Zhao Wei",
      body: "The Americans are at their decision point. Everything we did — the CDZ buildout, the weight acquisitions, the open-source releases, the diplomatic positioning — it all comes down to what we choose in the next hour. This is not a tactical decision. It is a civilizational one. I want everyone clear on what we're deciding and why.",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r5-wechat-5",
      type: "message",
      round: 5,
      sender: "Director Zhao Wei",
      body: "Status update: DeepCent's system is running. Capability level [CONDITIONAL]. The gap with the US [CONDITIONAL based on chinaCapability and obCapability]. What I can say: we are no longer in a position of pure asymmetric pressure. We are in a position to negotiate, compete, or cooperate from a position of credible strength.",
      timestamp: "2028-02-01T09:15:00Z",
      classification: "critical",
    },
    // Condition-gated ambient signal messages
    {
      id: "china-r1-signal-ambient-1",
      type: "message",
      round: 1,
      sender: "Senior Party Official",
      channel: "Ministry Secure",
      body: "The leadership is aware that the CDZ is the single largest AI compute deployment outside the United States. This fact must not become public. If the Americans know the scale of what we are building, they will accelerate their export control regime. Compartmentalize all CDZ capacity figures. This is a direct order.",
      timestamp: "2026-11-05T11:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-signal-ambient-1",
      type: "message",
      round: 2,
      sender: "Foreign Ministry Liaison",
      channel: "Diplomatic Secure",
      body: "Informal note: European AI researchers are quietly inquiring whether China would participate in a multilateral AI safety forum. Not a treaty — a working group. Some EU member states are frustrated by US control of the governance narrative. We have an opportunity to shape international AI standards before the US locks in their preferred framework. Recommend we engage selectively.",
      timestamp: "2027-03-04T14:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 30 },
    },
    {
      id: "china-r2-signal-ambient-2",
      type: "message",
      round: 2,
      sender: "Intelligence Chief",
      channel: "Secure Channel #7",
      body: "Current assessment of OB security posture following their internal review: they have upgraded to SL3 but have not fully air-gapped Agent-3 storage. Agent-2 checkpoint material remains in cloud-adjacent storage. Our Vector Alpha access is still active. The upgrade process creates transition vulnerabilities. Flagging for awareness — no action recommended at this time.",
      timestamp: "2027-03-06T19:00:00Z",
      classification: "context",
      condition: { variable: "securityLevelOB", operator: "lt", value: 3 },
    },
    {
      id: "china-r3-signal-ambient-1",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "Research Secure",
      body: "I want the research team's honest assessment of something. If we acquire and integrate Agent-4 weights and they contain the misalignment OB is worried about — would we detect it? Not with our current eval suite. I know the answer. But I want to see it written down. Send me a memo.",
      timestamp: "2027-07-06T14:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 40 },
    },
    {
      id: "china-r3-signal-ambient-2",
      type: "message",
      round: 3,
      sender: "Senior Party Official",
      channel: "Ministry Secure",
      body: "I am relaying concern from the Standing Committee directly. The gap to the Americans was stated to be closing. The latest assessment indicates it is not closing at the predicted rate. The committee is asking whether our earlier projections were optimistic or whether our execution has been poor. You have 72 hours to provide a credible explanation.",
      timestamp: "2027-07-07T08:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 45 },
    },
    {
      id: "china-r4-signal-ambient-1",
      type: "message",
      round: 4,
      sender: "Senior Party Official",
      channel: "Ministry Secure",
      body: "Leadership message for Director Zhao: we are pleased with the November benchmark results. The gap is closing. The domestic chip progress is ahead of schedule. This program has performed. The leadership wants DeepCent to know that its efforts are recognized at the highest level. Proceed with confidence.",
      timestamp: "2027-11-12T10:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "gt", value: 70 },
    },
    {
      id: "china-r4-signal-ambient-2",
      type: "message",
      round: 4,
      sender: "Foreign Ministry Liaison",
      channel: "Diplomatic Secure",
      body: "The US State Department has confirmed through back-channel: they are prepared to offer TSMC chip access as part of a grand bargain. This is not a bluff. The NSC has overridden Commerce Department objections to include chip access in the package. They are desperate enough to offer this. Which means we should understand what they want badly enough to pay that price — and what leverage that gives us.",
      timestamp: "2027-11-13T16:00:00Z",
      classification: "critical",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "china-r5-signal-ambient-1",
      type: "message",
      round: 5,
      sender: "Intelligence Chief",
      channel: "Secure Channel #7",
      body: "Final intelligence summary: US has deployed Agent-4 in advisory capacity to NSC. Not fully autonomous. Not military. But the analytical advantage is real — their decision-making cycles are faster and their scenario modeling is better than ours. This gap in applied AI capability is the one that matters most for the next 90 days. We should factor this into every decision.",
      timestamp: "2028-02-01T05:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r5-signal-ambient-2",
      type: "message",
      round: 5,
      sender: "Chen Fang (Intelligence)",
      channel: "Secure Channel #7",
      body: "Personal note to Director Zhao: the isolation scenario — where China refuses the governance framework and continues unilaterally — has a historical precedent. It is the early nuclear period. International isolation was a high price. The technology was worth it then. Whether it is worth it now depends entirely on whether the technology gives us what the nuclear program gave us. I am not certain it does.",
      timestamp: "2028-02-01T08:45:00Z",
      classification: "breadcrumb",
      condition: { variable: "intlCooperation", operator: "lt", value: 20 },
    },
];

export const CHINA_SIGNAL_DIRECTOR: ContentItem[] = [
    {
      id: "china4-wechat-dir-2",
      type: "message",
      round: 4,
      sender: "Ministry Technical Adviser",
      channel: "Secure Channel Director",
      body: "Director — if we announce a grand bargain, our research momentum slows while the US domestic crisis potentially resolves. Technically: we lose more than we gain if the pause is symmetrical. I'm advising you push for asymmetric verification — we limit COMPUTE deployment, not research. This preserves our architecture advantage.",
      timestamp: "2027-11-13T22:00:00Z",
      classification: "critical",
    },
    {
      id: "china4-wechat-dir-3",
      type: "message",
      round: 4,
      sender: "Prometheus Liaison (back-channel)",
      channel: "Unofficial",
      body: "This is unofficial. Dr. Park at Prometheus has asked — through an intermediary — whether DeepCent would consider a joint safety research publication. Their interpretability tools applied to our systems in exchange for our compute credits applied to their safety research. No government involvement. No press. Pure scientific collaboration.\n\nI'm flagging this because it came through a non-standard channel and I don't know if it's authorized.",
      timestamp: "2027-11-14T08:30:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china4-wechat-dir-1",
      type: "message",
      round: 4,
      sender: "Dr. Liu Yang (DeepCent)",
      channel: "Research Leadership",
      body: "Director — if we go full open-source, we need to understand what we're releasing. The exfiltrated OB weights are part of DeepCent-7's training data. Releasing DeepCent-7 openly potentially exposes the exfiltration operation. Political consequences unpredictable. I need to flag this before any public release decision.",
      timestamp: "2027-11-14T10:00:00Z",
      classification: "critical",
    },
];

registerContent({ faction: "china", app: "signal", accumulate: true, items: CHINA_SIGNAL });
registerContent({ faction: "china", app: "signal", role: "china_director", accumulate: true, items: CHINA_SIGNAL_DIRECTOR });
