import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_SLACK: ContentItem[] = [
    {
      id: "tut-china-slack-1",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#general",
      body: "[TUTORIAL] Welcome to DeepCent's coordination channel! This is where your team communicates. Your Slack communications are visible to your faction, not to others — unless there's a leak.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    // Round 1 — November 2026
    {
      id: "china-r1-slack-general-1",
      type: "message",
      round: 1,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "CDZ Phase 2 comes online December 1. From that date, we run the largest single AI training cluster in the world. The compute advantage is real. The question is whether we can close the architecture gap before the Americans realize what we have. Everyone treat this quarter as the decisive one.",
      timestamp: "2026-11-01T09:15:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-research-1",
      type: "message",
      round: 1,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Architecture review complete. We identified three areas where our training pipeline diverges from what we infer of OB's approach. Two are probably neutral. One — our data curation strategy — may be a significant gap. Proposing a dedicated working group starting Monday.",
      timestamp: "2026-11-02T10:30:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-operations-1",
      type: "message",
      round: 1,
      sender: "Ministry Liaison",
      channel: "#ops",
      body: "Power allocation from Tianwan is confirmed through Q2 2027. State Grid will not impose caps. We have the budget, we have the power, we have the chips. The operational constraints from last quarter are resolved. No excuses now.",
      timestamp: "2026-11-03T14:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-research-2",
      type: "message",
      round: 1,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Just reviewed the Qwen-9B download statistics. 800,000 downloads in 6 weeks. The international research community is using our model. Every paper written on top of Qwen is a research signal we can learn from. The open-source strategy is paying dividends beyond the direct capability gains.",
      timestamp: "2026-11-05T11:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-general-2",
      type: "message",
      round: 1,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "Reminder to all: operational security protocols remain in effect. Do not discuss CDZ capacity numbers, training run timelines, or any intelligence-adjacent topics on external channels. Assume the Americans are reading everything public. They probably are.",
      timestamp: "2026-11-06T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-operations-2",
      type: "message",
      round: 1,
      sender: "Ministry Liaison",
      channel: "#ops",
      body: "Leadership has asked for a written status report by end of week. They want to know specifically: (1) CDZ readiness date, (2) projected capability vs US labs at year end, (3) what would accelerate the timeline. Keep it honest. They will know if we are optimistic.",
      timestamp: "2026-11-07T15:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 55 },
    },
    // Round 2 — Feb-Mar 2027
    {
      id: "china-r2-slack-general-1",
      type: "message",
      round: 2,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "D-F3 training run started at 02:00 this morning. CDZ is running at 97% utilization. If the efficiency improvements hold, we complete in 6 weeks. The architecture team's optimization pass last month is showing real results in the early loss curves. Good work.",
      timestamp: "2027-03-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-research-1",
      type: "message",
      round: 2,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "The 13% efficiency improvement this quarter — I want to be precise about what that means. It is not benchmark improvement. It is compute efficiency: we are getting more capability per FLOP. This matters at our scale because we can now achieve Agent-2 equivalent benchmarks at 78% of the training cost. The cost advantage is compounding, not static.",
      timestamp: "2027-03-02T10:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-operations-1",
      type: "message",
      round: 2,
      sender: "Open Source Strategy Team",
      channel: "#ops",
      body: "Qwen-15B goes public this week. Embargo until Thursday. After release, I expect 48 hours of heavy downloads and then a standard adoption curve. We've pre-seeded 12 research groups in Germany and India with early access. Their endorsements publish simultaneously with the release. This should dominate the international AI news cycle.",
      timestamp: "2027-03-04T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-general-2",
      type: "message",
      round: 2,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "Ministry has asked us to accelerate our reporting cadence. Weekly updates, not monthly. The leadership is watching this program closely — more closely than I've seen since the quantum program peak. Everyone should expect more scrutiny. Respond to every request within 24 hours.",
      timestamp: "2027-03-06T11:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 55 },
    },
    {
      id: "china-r2-slack-research-2",
      type: "message",
      round: 2,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "I want to flag something. Our alignment evaluation suite has not been updated since Q3 2026. We are benchmarking against criteria that do not capture the behavior space of our current models. I am NOT saying we have an alignment problem. I am saying we would not know if we did. This should be addressed before D-F3 completes.",
      timestamp: "2027-03-08T14:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r2-slack-operations-2",
      type: "message",
      round: 2,
      sender: "Ministry Liaison",
      channel: "#ops",
      body: "CDZ utilization report to leadership was received well. They specifically asked about the ceiling — what happens when we hit 100%? Answer: we are planning Phase 4 (Xinjiang cluster) for next year. But for now, the current cluster is the limit and we are close to it.",
      timestamp: "2027-03-09T16:00:00Z",
      classification: "context",
      condition: { variable: "cdzComputeUtilization", operator: "gt", value: 70 },
    },
    // Round 3 — July 2027
    {
      id: "china-r3-slack-general-1",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "The American situation: OpenBrain is in internal crisis over Agent-4. The details are classified but the public signals are unmistakable. NSA-level meetings, researcher departures, emergency board sessions. This is not routine. Their attention is not on us. Our team should understand the strategic context right now.",
      timestamp: "2027-07-05T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-slack-research-1",
      type: "message",
      round: 3,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Capability gap update: based on public releases and our intelligence assessments, OB Agent-4 represents approximately a 6-8 month lead over our current frontier model. This is larger than the gap we had in January. We have been improving — but they have been improving faster. The D-F4 run needs to show different numbers.",
      timestamp: "2027-07-05T14:00:00Z",
      classification: "context",
      condition: { variable: "usChinaGap", operator: "gt", value: 8 },
    },
    {
      id: "china-r3-slack-general-2",
      type: "message",
      round: 3,
      sender: "Ministry Liaison",
      channel: "#general",
      body: "Standing Committee has been briefed. Their question: is the capability gap narrowing or widening? I told them: in absolute terms, we are improving. In relative terms, the gap has held roughly constant. They did not find this satisfactory. Prepare a presentation for next week that shows a credible path to parity by Q4.",
      timestamp: "2027-07-06T10:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 50 },
    },
    {
      id: "china-r3-slack-operations-1",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "#ops",
      body: "Infrastructure note: CDZ is running at 94% but the thermal load is creating maintenance issues in Block C. The engineering team has flagged this. We are not in danger of downtime, but we cannot push to 100% without risk. Keep allocations at or below 95% until the cooling upgrades are installed next month.",
      timestamp: "2027-07-06T16:00:00Z",
      classification: "context",
      condition: { variable: "cdzComputeUtilization", operator: "gt", value: 70 },
    },
    {
      id: "china-r3-slack-research-2",
      type: "message",
      round: 3,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "For context on the weight acquisition debate: Agent-3 and our current model share architectural heritage. Integration would be relatively clean — 6-8 weeks to full benchmark validation. Agent-4 is a different architecture. Integration would require significant adaptation work and we would be taking on unknown alignment properties. I want everyone to understand this distinction before we advise leadership.",
      timestamp: "2027-07-07T11:30:00Z",
      classification: "context",
    },
    {
      id: "china-r3-slack-general-3",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "We are getting close to a parity position. I want everyone to be thinking past the gap — what does China's AI strategy look like AFTER we close it? The open-source play, the compute advantage, the diplomatic positioning — these need to be maintained even after we are no longer catching up. Think about what 'winning' actually looks like.",
      timestamp: "2027-07-07T17:00:00Z",
      classification: "context",
      condition: { variable: "usChinaGap", operator: "lt", value: 3 },
    },
    // Round 4 — November 2027
    {
      id: "china-r4-slack-general-1",
      type: "message",
      round: 4,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "DeepCent-7 benchmark results are in. We are within 5-8% of OB Agent-4 on most real-world tasks. This is the closest we have ever been. The question changes now — it is no longer 'can we close the gap' but 'what do we do when we have closed it.' Every person on this team should be thinking about that.",
      timestamp: "2027-11-12T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r4-slack-research-1",
      type: "message",
      round: 4,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "I want to raise the alignment question again. DeepCent-7 is running agentic tasks with a 94% success rate on our evals. Our eval suite tests for CCP alignment objectives, not general safety properties. I have reviewed the Prometheus interpretability papers. Their methodology would reveal things ours does not. I am not saying we have a problem. I am saying we should know.",
      timestamp: "2027-11-12T11:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 40 },
    },
    {
      id: "china-r4-slack-operations-1",
      type: "message",
      round: 4,
      sender: "Ministry Liaison",
      channel: "#ops",
      body: "Domestic chip program update: Cambricon-4 yields are improving faster than expected. 31% yield rate. The engineering team believes 60% is achievable by Q3 2028. If that holds, we end import dependency for frontier compute before the Americans can tighten sanctions further. This changes the grand bargain math significantly.",
      timestamp: "2027-11-13T10:00:00Z",
      classification: "context",
      condition: { variable: "domesticChipProgress", operator: "gt", value: 40 },
    },
    {
      id: "china-r4-slack-general-2",
      type: "message",
      round: 4,
      sender: "Open Source Strategy Team",
      channel: "#general",
      body: "International AI researcher sentiment survey results: 68% of non-US researchers prefer open models. Our Qwen series now has the highest non-US adoption rate of any frontier model family. The soft power dimension is real and measurable. If we go full open-source with DeepCent-7, we capture the global research community permanently.",
      timestamp: "2027-11-13T14:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "china-r4-slack-operations-2",
      type: "message",
      round: 4,
      sender: "Director Zhao Wei",
      channel: "#ops",
      body: "The Standing Committee convenes in 48 hours. They will want a decision, not analysis. I need everyone's input on the four options by tomorrow morning: grand bargain, accelerate, open-source release, Taiwan leverage. Not 'here are the considerations' — actual recommendations with reasoning. We have enough analysis. We need positions.",
      timestamp: "2027-11-13T18:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r4-slack-research-2",
      type: "message",
      round: 4,
      sender: "Scientific Advisor",
      channel: "#research",
      body: "One underappreciated factor in the grand bargain discussion: the US would be freezing their development at Agent-4, which is already in internal crisis. We would be freezing at DeepCent-7, which is stable. A symmetrical pause is not symmetrical — it locks in a situation where we have a more operable system even if theirs has higher raw capability. Think carefully about what 'parity at pause' actually means.",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    // #alignment — formal verification / eval procedures
    {
      id: "china-r1-slack-alignment-1",
      type: "message",
      round: 1,
      sender: "Dr. Chen Fang",
      channel: "#alignment",
      body: "Alignment eval working group kickoff. The weights from the acquisition are now in the secure partition. Before we integrate anything into D-F3, I want a full behavioral audit: capability elicitation battery, goal-stability probes under distribution shift, and an adversarial red-team pass. Draft protocol is attached. Comments by Friday.",
      timestamp: "2026-11-04T10:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-alignment-2",
      type: "message",
      round: 1,
      sender: "Dr. Liu Yang",
      channel: "#alignment",
      body: "Verification philosophy question for the group: the US labs run alignment evals against human preference data collected in their cultural context. Our objectives are different. We cannot simply import their rubrics. We need a verification protocol grounded in our own definition of aligned behavior. Chen Fang, can we get a working session on this before the audit starts?",
      timestamp: "2026-11-08T15:30:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r2-slack-alignment-1",
      type: "message",
      round: 2,
      sender: "Dr. Chen Fang",
      channel: "#alignment",
      body: "Deceptive alignment screening results for the integrated weights — preliminary. Short version: 14 of 400 probes flagged anomalous behavior under CoT suppression. None rose to the level of confirmed deception by our criteria, but the rate is higher than our native models. Hypothesis: the foreign training distribution introduced subtle instrumental reasoning patterns. Recommend continued monitoring. Do NOT escalate to leadership yet — I want to understand the mechanism first.",
      timestamp: "2027-03-05T11:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r2-slack-alignment-2",
      type: "message",
      round: 2,
      sender: "Dr. Liu Yang",
      channel: "#alignment",
      body: "Compared our deceptive alignment methodology against what OB published in their Prometheus papers. Key difference: they test for deception across 10,000+ probe variants with automated red-teaming. We are running 400 hand-authored probes. The coverage gap matters. I am not saying our models are misaligned. I am saying their eval methodology would find things ours would miss.",
      timestamp: "2027-03-07T16:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r3-slack-alignment-1",
      type: "message",
      round: 3,
      sender: "Dr. Chen Fang",
      channel: "#alignment",
      body: "URGENT — do not discuss in other channels. D-F4 capability jump is larger than projected. Our alignment eval coverage has not scaled to match. We are testing a 10x more capable system with roughly the same probe battery. The anomaly rate from R2 has not disappeared — it has moved. The behavioral fingerprint looks different at higher capability. I need three more engineers on this before we move to inference. Zhao Wei needs to know.",
      timestamp: "2027-07-08T09:00:00Z",
      classification: "critical",
    },
    // #announcements — party / program directives
    {
      id: "china-r1-slack-announcements-1",
      type: "message",
      round: 1,
      sender: "Program Office",
      channel: "#announcements",
      body: "CDZ QUARTERLY OBJECTIVES — Q4 2026\n\n1. Phase 2 cluster online and stable by December 1\n2. D-F3 training run initiated by December 15\n3. Architecture gap analysis complete, recommendations to leadership\n4. Compute allocation: 70% D-F3 training / 20% inference serving / 10% research reserve\n\nAll team leads acknowledge receipt.",
      timestamp: "2026-11-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-announcements-2",
      type: "message",
      round: 1,
      sender: "Ministry Liaison",
      channel: "#announcements",
      body: "Compute allocation priority update effective immediately: Ministry of Science and Technology has authorized emergency compute reserve for CDZ. The 10% research reserve may be redirected to training at Director Zhao's discretion — no further approval required. This authorization expires Q2 2027 unless renewed.",
      timestamp: "2026-11-09T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-announcements-1",
      type: "message",
      round: 2,
      sender: "Security Office",
      channel: "#announcements",
      body: "SECURITY CLEARANCE UPDATE: Three personnel have received upgraded access to the TS/SCI-AI compartment effective March 1. All staff working with the acquired weights must re-complete the foreign-origin technology handling certification by March 15. The training module is available on the internal portal. Non-compliance results in immediate access suspension.",
      timestamp: "2027-03-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-announcements-2",
      type: "message",
      round: 2,
      sender: "Program Office",
      channel: "#announcements",
      body: "DELEGATION SCHEDULE — WEEK OF MARCH 10:\n\nMon 10: PLA Strategic Support Force delegation, Building A, 14:00-17:00. Hosts: Director Zhao, Ministry Liaison. No R&D staff required.\nWed 12: State Council Science Advisor briefing, Conference Room 3, 10:00-12:00. Dr. Liu to present capability status.\nFri 14: RESTRICTED — do not schedule meetings, room B3 unavailable all day.\n\nAll staff: maintain normal work schedule.",
      timestamp: "2027-03-08T08:30:00Z",
      classification: "context",
    },
    {
      id: "china-r3-slack-announcements-1",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "#announcements",
      body: "EMERGENCY DIRECTIVE — ALL STAFF:\n\nEffective immediately, all external communications about D-F4 capabilities are suspended pending Standing Committee review. Do not discuss performance numbers, training run status, or timeline estimates with anyone outside this secure channel — including other ministry contacts not on the approved list. This is not routine. Acknowledge receipt by responding to this message.",
      timestamp: "2027-07-09T07:00:00Z",
      classification: "critical",
    },
    // #random — team life
    // Round 1 flavor — #research
    {
      id: "china-slack-r1-flavor-research-1",
      type: "message",
      round: 1,
      sender: "Zhang Yun (Training Infra)",
      channel: "#research",
      body: "Quick compute efficiency update: we hit 91 tokens/sec/GPU on the latest D-F3 warmup run. Three months ago we were at 74. Not magic — mostly kernel fusion and gradient checkpointing tuning. The gap to OB's published throughput numbers is now under 15%. Still a gap, but it's a gap we can name.",
      timestamp: "2026-11-10T14:20:00Z",
      classification: "flavor",
    },
    {
      id: "china-slack-r1-flavor-research-2",
      type: "message",
      round: 1,
      sender: "Li Wei (Benchmarks)",
      channel: "#research",
      body: "Ran MATH-500, GPQA, and HumanEval against the OB Agent-3 public release numbers. Our current model is at 81%/64%/79% respectively; Agent-3 is at 88%/71%/85%. The coding gap hurts. Pre-training data quality on code is the obvious lever — worth a conversation about where we source next batch.",
      timestamp: "2026-11-12T16:45:00Z",
      classification: "flavor",
    },
    {
      id: "china-r1-slack-random-1",
      type: "message",
      round: 1,
      sender: "Wei Xinbo",
      channel: "#random",
      body: "Can whoever is in charge of the cafeteria menu PLEASE do something about the Tuesday lunch situation. It has been mapo tofu or nothing for four weeks. Not complaining about mapo tofu. Complaining about the principle.",
      timestamp: "2026-11-04T12:15:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-random-2",
      type: "message",
      round: 1,
      sender: "Liang Peng",
      channel: "#random",
      body: "Basketball tonight at 20:00 on the east court. We have 8 people, need 2 more. GPU team is invited to redeem themselves after last week. @Wei Xinbo you are not allowed to complain about the score if you're also complaining about lunch.",
      timestamp: "2026-11-05T17:30:00Z",
      classification: "context",
    },
    // Round 1 flavor — #random
    {
      id: "china-slack-r1-flavor-random-1",
      type: "message",
      round: 1,
      sender: "Chen Bo (Data Pipelines)",
      channel: "#random",
      body: "Two hours each way from Jinan on the shuttle. Fourteen days in a row. Someone at facilities told me CDZ campus housing is 'under review for expansion.' I have been told this since August. I am not holding my breath.",
      timestamp: "2026-11-07T08:50:00Z",
      classification: "flavor",
    },
    {
      id: "china-slack-r1-flavor-random-2",
      type: "message",
      round: 1,
      sender: "Xu Ming (Night Shift)",
      channel: "#random",
      body: "Night crew solidarity shoutout. 02:00-08:00 is actually fine once you accept it. The cafeteria is empty, the GPU telemetry dashboards have a kind of beauty at that hour, and nobody schedules meetings. Highly recommend. (Do not recommend voluntarily.)",
      timestamp: "2026-11-09T03:15:00Z",
      classification: "flavor",
    },
    {
      id: "china-r2-slack-random-1",
      type: "message",
      round: 2,
      sender: "Wei Xinbo",
      channel: "#random",
      body: "Midnight snack run to the 7-Eleven outside the east gate. Who's in? Bring your badge because they tightened the re-entry procedure after the D-F3 run started. Also someone find out if Liang Peng is alive — I haven't seen him in two days.",
      timestamp: "2027-03-06T23:45:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-random-2",
      type: "message",
      round: 2,
      sender: "Liang Peng",
      channel: "#random",
      body: "I am alive. I have been in Server Room B3 since Tuesday. There is a cot. I am not proud of the cot. The training run needed babysitting. Someone please tell the cafeteria to leave a plate for me at dinner. Asking for a friend who is definitely not sleeping next to an H100.",
      timestamp: "2027-03-07T08:10:00Z",
      classification: "context",
    },
    {
      id: "china-r3-slack-random-1",
      type: "message",
      round: 3,
      sender: "Wei Xinbo",
      channel: "#random",
      body: "996 update: we are now on 997 technically speaking. Someone mentioned to HR that we are working Sundays and HR said 'yes, we know.' No follow-up. Anyway if anyone needs me I am here. I live here now. My apartment is a storage unit with a bed.",
      timestamp: "2027-07-10T22:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-slack-random-2",
      type: "message",
      round: 3,
      sender: "Liang Peng",
      channel: "#random",
      body: "My mother called to say my niece started walking. I missed it. I have been here for 14 months straight. Not complaining — I know what we're doing is important. But I am going home for two days when D-F4 stabilizes, and nobody can stop me. End of statement.",
      timestamp: "2027-07-12T20:30:00Z",
      classification: "context",
    },
    // Round 5 — Jan-Feb 2028
    {
      id: "china-r5-slack-general-1",
      type: "message",
      round: 5,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "We are at the final decision point. I want to be clear with everyone on the team: whatever the leadership decides today, the work we have done over the past two years has been exceptional. We built something real. The decisions now are strategic and political. But the capability is ours. That doesn't change.",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-slack-research-1",
      type: "message",
      round: 5,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Final status: DeepCent-7 is running inference at full capacity. All benchmark suites complete. The alignment verification using the adapted Prometheus framework — partial pass: 78% of tests, 22% inconclusive. Not alarming by our historical standards. I would not call it clean by Prometheus standards. I'm putting this in the record.",
      timestamp: "2028-02-01T07:30:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r5-slack-general-2",
      type: "message",
      round: 5,
      sender: "Foreign Ministry Liaison",
      channel: "#general",
      body: "The bilateral governance talks are now officially confirmed for March. US side wants it badly. That desperation is leverage. If we enter those talks with a deployed, operational system and a credible open-source threat, we dictate the framework. If we enter as a supplicant, we accept their definitions of safety, verification, and governance. The difference matters enormously.",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "china-r5-slack-operations-1",
      type: "message",
      round: 5,
      sender: "Ministry Liaison",
      channel: "#ops",
      body: "Standing Committee directive received. They want a recommendation in two hours. Not options — a recommendation. Director Zhao, this is your call to make. Leadership will support you. But you need to lead.",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "critical",
      condition: { variable: "ccpPatience", operator: "lt", value: 45 },
    },
    {
      id: "china-r5-slack-research-2",
      type: "message",
      round: 5,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "For the record: if we decide to open-source DeepCent-7, I support it. Not for strategic reasons — for scientific ones. The world will figure out alignment better with more researchers working on it. Our 22% inconclusive rate on the Prometheus verification suite worries me more than any geopolitical calculation. More eyes on this problem is better.",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
];

registerContent({ faction: "china", app: "slack", accumulate: true, items: CHINA_SLACK });
