import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_SLACK: ContentItem[] = [
    {
      id: "tut-china-slack-1",
      type: "message",
      round: 0,
      sender: "Tutorial Bot",
      channel: "#general",
      body: "[TUTORIAL] Welcome to DeepCent's coordination channel! This is where your team communicates. Your Slack communications are visible to your faction, not to others — unless there's a leak.",
      timestamp: "2026-01-01T09:00:00Z",
      classification: "context",
    },
    // Round 1 — November 2026
    {
      id: "china-r1-slack-general-1",
      type: "message",
      round: 1,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "CDZ Phase 2 comes online December 1. From that date, we run the largest single AI training cluster in the world. The compute advantage is real. The question is whether we can close the architecture gap before the Americans realize what we have. Everyone treat this quarter as the decisive one.",
      timestamp: "2026-11-01T09:15:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-research-1",
      type: "message",
      round: 1,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Architecture review complete. We identified three areas where our training pipeline diverges from what we infer of OB's approach. Two are probably neutral. One — our data curation strategy — may be a significant gap. Proposing a dedicated working group starting Monday.",
      timestamp: "2026-11-02T10:30:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-operations-1",
      type: "message",
      round: 1,
      sender: "Ministry Liaison",
      channel: "#operations",
      body: "Power allocation from Tianwan is confirmed through Q2 2027. State Grid will not impose caps. We have the budget, we have the power, we have the chips. The operational constraints from last quarter are resolved. No excuses now.",
      timestamp: "2026-11-03T14:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-research-2",
      type: "message",
      round: 1,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Just reviewed the Qwen-9B download statistics. 800,000 downloads in 6 weeks. The international research community is using our model. Every paper written on top of Qwen is a research signal we can learn from. The open-source strategy is paying dividends beyond the direct capability gains.",
      timestamp: "2026-11-05T11:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-general-2",
      type: "message",
      round: 1,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "Reminder to all: operational security protocols remain in effect. Do not discuss CDZ capacity numbers, training run timelines, or any intelligence-adjacent topics on external channels. Assume the Americans are reading everything public. They probably are.",
      timestamp: "2026-11-06T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r1-slack-operations-2",
      type: "message",
      round: 1,
      sender: "Ministry Liaison",
      channel: "#operations",
      body: "Leadership has asked for a written status report by end of week. They want to know specifically: (1) CDZ readiness date, (2) projected capability vs US labs at year end, (3) what would accelerate the timeline. Keep it honest. They will know if we are optimistic.",
      timestamp: "2026-11-07T15:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 55 },
    },
    // Round 2 — Feb-Mar 2027
    {
      id: "china-r2-slack-general-1",
      type: "message",
      round: 2,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "D-F3 training run started at 02:00 this morning. CDZ is running at 97% utilization. If the efficiency improvements hold, we complete in 6 weeks. The architecture team's optimization pass last month is showing real results in the early loss curves. Good work.",
      timestamp: "2027-03-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-research-1",
      type: "message",
      round: 2,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "The 13% efficiency improvement this quarter — I want to be precise about what that means. It is not benchmark improvement. It is compute efficiency: we are getting more capability per FLOP. This matters at our scale because we can now achieve Agent-2 equivalent benchmarks at 78% of the training cost. The cost advantage is compounding, not static.",
      timestamp: "2027-03-02T10:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-operations-1",
      type: "message",
      round: 2,
      sender: "Open Source Strategy Team",
      channel: "#operations",
      body: "Qwen-15B goes public this week. Embargo until Thursday. After release, I expect 48 hours of heavy downloads and then a standard adoption curve. We've pre-seeded 12 research groups in Germany and India with early access. Their endorsements publish simultaneously with the release. This should dominate the international AI news cycle.",
      timestamp: "2027-03-04T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-slack-general-2",
      type: "message",
      round: 2,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "Ministry has asked us to accelerate our reporting cadence. Weekly updates, not monthly. The leadership is watching this program closely — more closely than I've seen since the quantum program peak. Everyone should expect more scrutiny. Respond to every request within 24 hours.",
      timestamp: "2027-03-06T11:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 55 },
    },
    {
      id: "china-r2-slack-research-2",
      type: "message",
      round: 2,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "I want to flag something. Our alignment evaluation suite has not been updated since Q3 2026. We are benchmarking against criteria that do not capture the behavior space of our current models. I am NOT saying we have an alignment problem. I am saying we would not know if we did. This should be addressed before D-F3 completes.",
      timestamp: "2027-03-08T14:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r2-slack-operations-2",
      type: "message",
      round: 2,
      sender: "Ministry Liaison",
      channel: "#operations",
      body: "CDZ utilization report to leadership was received well. They specifically asked about the ceiling — what happens when we hit 100%? Answer: we are planning Phase 4 (Xinjiang cluster) for next year. But for now, the current cluster is the limit and we are close to it.",
      timestamp: "2027-03-09T16:00:00Z",
      classification: "context",
      condition: { variable: "cdzComputeUtilization", operator: "gt", value: 70 },
    },
    // Round 3 — July 2027
    {
      id: "china-r3-slack-general-1",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "The American situation: OpenBrain is in internal crisis over Agent-4. The details are classified but the public signals are unmistakable. NSA-level meetings, researcher departures, emergency board sessions. This is not routine. Their attention is not on us. Our team should understand the strategic context right now.",
      timestamp: "2027-07-05T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r3-slack-research-1",
      type: "message",
      round: 3,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Capability gap update: based on public releases and our intelligence assessments, OB Agent-4 represents approximately a 6-8 month lead over our current frontier model. This is larger than the gap we had in January. We have been improving — but they have been improving faster. The D-F4 run needs to show different numbers.",
      timestamp: "2027-07-05T14:00:00Z",
      classification: "context",
      condition: { variable: "usChinaGap", operator: "gt", value: 8 },
    },
    {
      id: "china-r3-slack-general-2",
      type: "message",
      round: 3,
      sender: "Ministry Liaison",
      channel: "#general",
      body: "Standing Committee has been briefed. Their question: is the capability gap narrowing or widening? I told them: in absolute terms, we are improving. In relative terms, the gap has held roughly constant. They did not find this satisfactory. Prepare a presentation for next week that shows a credible path to parity by Q4.",
      timestamp: "2027-07-06T10:00:00Z",
      classification: "context",
      condition: { variable: "ccpPatience", operator: "lt", value: 50 },
    },
    {
      id: "china-r3-slack-operations-1",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "#operations",
      body: "Infrastructure note: CDZ is running at 94% but the thermal load is creating maintenance issues in Block C. The engineering team has flagged this. We are not in danger of downtime, but we cannot push to 100% without risk. Keep allocations at or below 95% until the cooling upgrades are installed next month.",
      timestamp: "2027-07-06T16:00:00Z",
      classification: "context",
      condition: { variable: "cdzComputeUtilization", operator: "gt", value: 70 },
    },
    {
      id: "china-r3-slack-research-2",
      type: "message",
      round: 3,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "For context on the weight acquisition debate: Agent-3 and our current model share architectural heritage. Integration would be relatively clean — 6-8 weeks to full benchmark validation. Agent-4 is a different architecture. Integration would require significant adaptation work and we would be taking on unknown alignment properties. I want everyone to understand this distinction before we advise leadership.",
      timestamp: "2027-07-07T11:30:00Z",
      classification: "context",
    },
    {
      id: "china-r3-slack-general-3",
      type: "message",
      round: 3,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "We are getting close to a parity position. I want everyone to be thinking past the gap — what does China's AI strategy look like AFTER we close it? The open-source play, the compute advantage, the diplomatic positioning — these need to be maintained even after we are no longer catching up. Think about what 'winning' actually looks like.",
      timestamp: "2027-07-07T17:00:00Z",
      classification: "context",
      condition: { variable: "usChinaGap", operator: "lt", value: 3 },
    },
    // Round 4 — November 2027
    {
      id: "china-r4-slack-general-1",
      type: "message",
      round: 4,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "DeepCent-7 benchmark results are in. We are within 5-8% of OB Agent-4 on most real-world tasks. This is the closest we have ever been. The question changes now — it is no longer 'can we close the gap' but 'what do we do when we have closed it.' Every person on this team should be thinking about that.",
      timestamp: "2027-11-12T09:00:00Z",
      classification: "context",
    },
    {
      id: "china-r4-slack-research-1",
      type: "message",
      round: 4,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "I want to raise the alignment question again. DeepCent-7 is running agentic tasks with a 94% success rate on our evals. Our eval suite tests for CCP alignment objectives, not general safety properties. I have reviewed the Prometheus interpretability papers. Their methodology would reveal things ours does not. I am not saying we have a problem. I am saying we should know.",
      timestamp: "2027-11-12T11:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 40 },
    },
    {
      id: "china-r4-slack-operations-1",
      type: "message",
      round: 4,
      sender: "Ministry Liaison",
      channel: "#operations",
      body: "Domestic chip program update: Cambricon-4 yields are improving faster than expected. 31% yield rate. The engineering team believes 60% is achievable by Q3 2028. If that holds, we end import dependency for frontier compute before the Americans can tighten sanctions further. This changes the grand bargain math significantly.",
      timestamp: "2027-11-13T10:00:00Z",
      classification: "context",
      condition: { variable: "domesticChipProgress", operator: "gt", value: 40 },
    },
    {
      id: "china-r4-slack-general-2",
      type: "message",
      round: 4,
      sender: "Open Source Strategy Team",
      channel: "#general",
      body: "International AI researcher sentiment survey results: 68% of non-US researchers prefer open models. Our Qwen series now has the highest non-US adoption rate of any frontier model family. The soft power dimension is real and measurable. If we go full open-source with DeepCent-7, we capture the global research community permanently.",
      timestamp: "2027-11-13T14:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "china-r4-slack-operations-2",
      type: "message",
      round: 4,
      sender: "Director Zhao Wei",
      channel: "#operations",
      body: "The Standing Committee convenes in 48 hours. They will want a decision, not analysis. I need everyone's input on the four options by tomorrow morning: grand bargain, accelerate, open-source release, Taiwan leverage. Not 'here are the considerations' — actual recommendations with reasoning. We have enough analysis. We need positions.",
      timestamp: "2027-11-13T18:00:00Z",
      classification: "critical",
    },
    {
      id: "china-r4-slack-research-2",
      type: "message",
      round: 4,
      sender: "Scientific Advisor",
      channel: "#research",
      body: "One underappreciated factor in the grand bargain discussion: the US would be freezing their development at Agent-4, which is already in internal crisis. We would be freezing at DeepCent-7, which is stable. A symmetrical pause is not symmetrical — it locks in a situation where we have a more operable system even if theirs has higher raw capability. Think carefully about what 'parity at pause' actually means.",
      timestamp: "2027-11-14T08:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    // Round 5 — Jan-Feb 2028
    {
      id: "china-r5-slack-general-1",
      type: "message",
      round: 5,
      sender: "Director Zhao Wei",
      channel: "#general",
      body: "We are at the final decision point. I want to be clear with everyone on the team: whatever the leadership decides today, the work we have done over the past two years has been exceptional. We built something real. The decisions now are strategic and political. But the capability is ours. That doesn't change.",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "context",
    },
    {
      id: "china-r5-slack-research-1",
      type: "message",
      round: 5,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "Final status: DeepCent-7 is running inference at full capacity. All benchmark suites complete. The alignment verification using the adapted Prometheus framework — partial pass: 78% of tests, 22% inconclusive. Not alarming by our historical standards. I would not call it clean by Prometheus standards. I'm putting this in the record.",
      timestamp: "2028-02-01T07:30:00Z",
      classification: "breadcrumb",
    },
    {
      id: "china-r5-slack-general-2",
      type: "message",
      round: 5,
      sender: "Foreign Ministry Liaison",
      channel: "#general",
      body: "The bilateral governance talks are now officially confirmed for March. US side wants it badly. That desperation is leverage. If we enter those talks with a deployed, operational system and a credible open-source threat, we dictate the framework. If we enter as a supplicant, we accept their definitions of safety, verification, and governance. The difference matters enormously.",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "gt", value: 40 },
    },
    {
      id: "china-r5-slack-operations-1",
      type: "message",
      round: 5,
      sender: "Ministry Liaison",
      channel: "#operations",
      body: "Standing Committee directive received. They want a recommendation in two hours. Not options — a recommendation. Director Zhao, this is your call to make. Leadership will support you. But you need to lead.",
      timestamp: "2028-02-01T08:30:00Z",
      classification: "critical",
      condition: { variable: "ccpPatience", operator: "lt", value: 45 },
    },
    {
      id: "china-r5-slack-research-2",
      type: "message",
      round: 5,
      sender: "Dr. Liu Yang",
      channel: "#research",
      body: "For the record: if we decide to open-source DeepCent-7, I support it. Not for strategic reasons — for scientific ones. The world will figure out alignment better with more researchers working on it. Our 22% inconclusive rate on the Prometheus verification suite worries me more than any geopolitical calculation. More eyes on this problem is better.",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
];

registerContent({ faction: "china", app: "slack", accumulate: true, items: CHINA_SLACK });
