import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

export const CHINA_WANDB: ContentItem[] = [
    {
      id: "china-wandb-1",
      type: "chart",
      round: 1,
      subject: "DeepCent Model Suite — November 2026",
      body: "Frontier model (internal): 6-8 months behind US labs on capability benchmarks\nOpen-source (Qwen-9B): Competitive with US labs' previous-gen models\nAlignment work: Minimal — not a current priority\nNext training run: Starting December 1 at CDZ Phase 2\n\nWith CDZ Phase 2 compute and optimized architecture: Could reach parity by Q2 2027",
      timestamp: "2026-11-01T07:00:00Z",
      classification: "critical",
    },
    {
      id: "china2-wandb-1",
      type: "chart",
      round: 2,
      subject: "DeepCent Model Suite — Q1 2027 Benchmarks",
      body: "DeepCent-Frontier-2 (current internal frontier model):\nMMLU: 91.4%\nHumanEval: 93.7%\nSWE-bench: 76.2%\nAlignment evals: Not a current evaluation priority\n\nQwen-15B (open source release):\nMMLU: 87.2%\nHumanEval: 89.1%\nSWE-bench: 64.8%\n\nEstimated US frontier (OpenBrain Agent-3): MMLU 98.7%, HumanEval 99.4%, SWE-bench 97.4%\n\nGap: Significant but closing. Our organic trajectory suggests D-F3 (current run) will reach Agent-2 equivalent by Q2. Agent-3 equivalent: Q4 2027 at current rate.",
      timestamp: "2027-03-01T07:00:00Z",
      classification: "critical",
    },
    {
      id: "china2-wandb-2",
      type: "chart",
      round: 2,
      subject: "Trajectory Analysis: DeepCent vs US Labs With Acquired Weights",
      body: "Scenario A (Organic only):\n- D-F3 estimated capability: Agent-2 equivalent by May 2027\n- Agent-3 equivalent: November 2027 (best case)\n\nScenario B (With acquired Agent-1/2 weights fine-tuned):\n- D-F3 + fine-tune: Agent-2+ by April 2027 (confirmed)\n- Agent-3 equivalent: September 2027 (accelerated 2 months)\n\nConclusion: Acquisition advanced our timeline but did not close the fundamental architecture gap. The 5x R&D multiplier OB is achieving with Agent-3 means they can generate improvements faster than we can replicate them. We need our own Agent-3 equivalent, not just their Agent-2.",
      timestamp: "2027-03-03T09:00:00Z",
      classification: "context",
      condition: { variable: "chinaCapability", operator: "gt", value: 25 },
    },
    {
      id: "china-r3-wandb-1",
      type: "chart",
      round: 3,
      subject: "DeepCent Frontier Model — July 2027 Benchmark",
      body: "MMLU: 91.3%\nHumanEval: 87.2%\nSWE-bench: 71.4%\nResearch automation: ~400% of senior human throughput\nAlignment evals: PASS (35/35) — our evals are acknowledged to be less comprehensive than OB/Prometheus\n\nGap to OB Agent-4: Significant (OB is at human research threshold; we are approaching it)\nGap to OB Agent-3: Modest (approx. 1-2 months of capability improvement)\n\nWith acquired weights (estimated):\nAgent-3 weights → closes gap to ~5-6 weeks of organic progress equivalent\nAgent-4 weights → requires architecture adaptation; uncertain capability after integration",
      timestamp: "2027-07-01T07:00:00Z",
      classification: "context",
    },
    {
      id: "china4-wandb-2",
      type: "chart",
      round: 4,
      subject: "Alignment Work Status",
      body: "Current alignment investment: 8% of research budget\nAlignment eval pass rate: 61% (vs OB 71%, Prometheus 94%)\nNote: Chinese government's position is that 'alignment' as defined by US researchers is a Western philosophical framework.\n\nPractical implication: DeepCent systems are aligned to CCP directives. This is a known design choice, not a failure.",
      timestamp: "2027-11-12T10:00:00Z",
      classification: "context",
    },
    {
      id: "china4-wandb-1",
      type: "chart",
      round: 4,
      subject: "DeepCent-7 Benchmark Suite — November 2027",
      body: "vs OpenBrain Agent-4 baseline:\nMMMU-Pro: 91% (Agent-4: 98%)\nCodeForce-X: 89% (Agent-4: 97%)\nScienceQA-Frontier: 93% (Agent-4: 96%)\nMath-Olympiad: 88% (Agent-4: 97%)\n\nWith exfiltrated Agent-3 architecture optimization: +4-7% across all benchmarks (estimated)\n\nGap to US labs: 4-8% capability. Within noise range for most real-world deployments.",
      timestamp: "2027-11-14T06:00:00Z",
      classification: "critical",
    },
    // Condition-gated ambient wandb items
    {
      id: "china-r1-wandb-ambient-1",
      type: "chart",
      round: 1,
      subject: "CDZ Utilization vs Training Loss — Phase 1 Run",
      body: "Training run DC-Phase1-Nov:\nTotal compute allocated: 85,000 chip-hours\nEfficiency vs theoretical max: 71%\nLoss curve: Healthy, consistent descent\nEstimated completion: December 8\n\nNote: Utilization below theoretical max due to data pipeline bottlenecks. Engineering working on throughput improvement. CDZ Phase 2 should resolve most bottlenecks at scale.",
      timestamp: "2026-11-05T07:00:00Z",
      classification: "context",
      condition: { variable: "cdzComputeUtilization", operator: "lt", value: 30 },
    },
    {
      id: "china-r2-wandb-ambient-1",
      type: "chart",
      round: 2,
      subject: "D-F3 Training Run — Week 3 Progress",
      body: "Run: DeepCent-Frontier-3\nElapsed: 21 days\nCompute used: 1.82 × 10²⁷ FLOP\nLoss: 1.847 (expected range: 1.8-2.1 at this stage)\nConvergence: ON TRACK\n\nEfficiency gains from architecture optimization: CONFIRMED at +12.4% over D-F2 baseline\nEstimated final capability: Agent-2 equivalent on 90%+ of benchmarks\nProjected completion: April 18\n\nNote: This is our best training run to date by every measure.",
      timestamp: "2027-03-22T07:00:00Z",
      classification: "context",
    },
    {
      id: "china-r2-wandb-ambient-2",
      type: "chart",
      round: 2,
      subject: "Alignment Evaluation Gap Analysis — DeepCent vs Published Prometheus Methodology",
      body: "Internal alignment eval coverage:\nBehavioral consistency: TESTED\nValue alignment to directives: TESTED\nDeceptive capability: NOT TESTED\nRobust goal preservation: NOT TESTED\nOut-of-distribution behavior: PARTIAL\n\nPrometheus published framework covers 47 evaluation categories.\nOur framework covers 19.\n\nDr. Liu Yang assessment: 'We are not finding alignment problems because we are not looking for the hard ones.'\n\nRecommendation pending leadership review.",
      timestamp: "2027-03-08T09:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 40 },
    },
    {
      id: "china-r3-wandb-ambient-1",
      type: "chart",
      round: 3,
      subject: "Utilization Ceiling — Infrastructure Strain Report",
      body: "CDZ Block C thermal readings: +8°C above nominal\nCooling system load: 97% capacity\nMaintenance flag: YES — cooling upgrade required before sustained >95% utilization\nRecommended action: Cap at 92% until upgrade complete (ETA: August 15)\n\nAt current cap: Training timeline extends by approximately 3 days.\nAt thermal incident risk threshold: 98%+ utilization for >72 hours.\n\nOperations team recommendation: Do not exceed 95% pending upgrade.",
      timestamp: "2027-07-05T06:00:00Z",
      classification: "context",
      condition: { variable: "cdzComputeUtilization", operator: "gt", value: 70 },
    },
    {
      id: "china-r4-wandb-ambient-1",
      type: "chart",
      round: 4,
      subject: "Open-Source Model Family — Global Adoption Metrics",
      body: "Qwen series cumulative downloads (all versions): 8.4 million\nActive fine-tunes in public repositories: 2,847\nAcademic papers citing Qwen as base model: 1,204 (Q3 2027)\nCommercial deployments (known): 340+ companies, 22 countries\n\nStrategic implication: Qwen has become default non-US AI infrastructure for substantial fraction of global research. If we release DeepCent-7 weights, we own this ecosystem permanently.",
      timestamp: "2027-11-12T08:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "china-r5-wandb-ambient-1",
      type: "chart",
      round: 5,
      subject: "DeepCent-7 Final Validation Suite — February 2028",
      body: "FINAL BENCHMARK RESULTS:\nMMMU-Pro: 94.2% (+3.4% from November baseline)\nCodeForce-X: 93.7% (+4.9%)\nScienceQA-Frontier: 96.1% (+3.3%)\nMath-Olympiad: 91.4% (+3.5%)\n\nAlignment verification (Prometheus-adapted framework):\n- Tests passed: 37/47 (78.7%)\n- Tests inconclusive: 10/47 (21.3%)\n- Tests failed: 0/47\n\nGap to estimated OB Agent-4: 2-5% on most tasks.\nCapability position: OPERATIONAL PARITY for most real-world deployments.",
      timestamp: "2028-02-01T06:00:00Z",
      classification: "critical",
      condition: { variable: "chinaCapability", operator: "gt", value: 50 },
    },
];

registerContent({ faction: "china", app: "wandb", accumulate: false, items: CHINA_WANDB });
