import type { ContentItem } from "@takeoff/shared";
import { registerContent } from "../loader.js";

/**
 * Shared public Twitter feed — all factions with the twitter app see the same timeline.
 * This mirrors real Twitter's "trending" layer where major events are visible to everyone.
 *
 * Future: add per-faction "algorithmic bubble" modules (see docs/BACKLOG.md).
 */
export const SHARED_TWITTER: ContentItem[] = [
    // ── Round 1 — non-AI ambient (flavor) ──
    {
      id: "tw-r1-flavor-sports-1",
      type: "tweet",
      round: 1,
      sender: "@heatcheck_hank",
      body: "The Lakers are cooked. I said it. That rotation makes no sense and nobody on the coaching staff seems to notice. Sell me on a counter-argument, I'm begging you.",
      timestamp: "2026-11-03T21:30:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-food-1",
      type: "tweet",
      round: 1,
      sender: "@annebakes",
      body: "Made brown butter chocolate chip cookies for the first time. Threw out every other cookie recipe I own. This is the only cookie now. There are no other cookies.",
      timestamp: "2026-11-03T17:45:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-weather-1",
      type: "tweet",
      round: 1,
      sender: "@sflocal_kai",
      body: "SF weather report: 55°F and foggy in the Mission. 74°F and sunny in the Sunset. Two entirely different seasons happening six blocks apart. I will never understand this city.",
      timestamp: "2026-11-04T12:15:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-popcult-1",
      type: "tweet",
      round: 1,
      sender: "@television_takes",
      body: "Controversial opinion: the second season of a show is almost always better than the first because they finally figured out what the show is actually about. Fight me.",
      timestamp: "2026-11-04T22:00:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-mundane-1",
      type: "tweet",
      round: 1,
      sender: "@gregorymayhew",
      body: "The most underrated life skill is knowing exactly how early to leave so you're not early but also definitely not late. I have been developing this skill for 36 years and I still get it wrong.",
      timestamp: "2026-11-05T09:30:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-pet-1",
      type: "tweet",
      round: 1,
      sender: "@justinandkoda",
      body: "My dog has learned to bring me his leash when he wants a walk. Not drop it at my feet. Bring it. Place it in my hand. He's looking at me right now with the leash in his mouth. I genuinely have no choice.",
      timestamp: "2026-11-05T15:00:00Z",
      classification: "flavor",
    },

    {
      id: "tw-r1-flavor-work-1",
      type: "tweet",
      round: 1,
      sender: "@margaux_wfh",
      body: "Four back-to-back meetings before noon and not one of them needed to exist. All four could have been a single Slack message. The Slack message could have been nothing. I am going insane.",
      timestamp: "2026-11-01T10:45:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-work-2",
      type: "tweet",
      round: 1,
      sender: "@open_office_victim",
      body: "Headphones in, music up, DO NOT DISTURB status on. Someone still walked over to tell me something they could have Slacked. Tapped me on the shoulder. While I had headphones in. I am moving my desk to the parking structure.",
      timestamp: "2026-11-02T14:20:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-parenting-1",
      type: "tweet",
      round: 1,
      sender: "@dadof3_chicago",
      body: "My seven-year-old just informed me that dinosaurs are 'basically birds that gave up.' I don't know where he got that but I'm not going to correct him because honestly? Fair.",
      timestamp: "2026-11-01T19:00:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-parenting-2",
      type: "tweet",
      round: 1,
      sender: "@momlife_detroit",
      body: "Kid asked why she can't have dessert before dinner. I said 'because I said so.' She said 'that's not a reason.' She's right and I hate it. Parenting is just being out-argued by someone who still needs help tying their shoes.",
      timestamp: "2026-11-03T18:30:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-fitness-1",
      type: "tweet",
      round: 1,
      sender: "@marathon_marcus",
      body: "Mile 18 of my long run and everything hurts and I am questioning every decision I have ever made. Mile 22 update: I feel like a god. Running is the most insane sport.",
      timestamp: "2026-11-01T08:15:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-fitness-2",
      type: "tweet",
      round: 1,
      sender: "@gymrat_reese",
      body: "The gym was 'packed' today — meaning three people were using the squat rack at once. One of them was filming a reel the entire time. The other was doing something I've never seen before and will not attempt to describe.",
      timestamp: "2026-11-04T07:30:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-tech-1",
      type: "tweet",
      round: 1,
      sender: "@rustacean_forever",
      body: "Hot take: the reason everyone dunks on JavaScript is that everyone used to write JavaScript and has unprocessed trauma. It is not a good language. It is not going away. These two facts coexist.",
      timestamp: "2026-11-02T11:00:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-tech-2",
      type: "tweet",
      round: 1,
      sender: "@btc_obituary_bot",
      body: "Bitcoin is dead (week 741). This week's cause of death: 'a guy on CNBC said it was actually over this time.' Survived by: your uncle who won't stop texting the family group chat.",
      timestamp: "2026-11-03T13:00:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-music-1",
      type: "tweet",
      round: 1,
      sender: "@concert_mode_on",
      body: "Just got off the floor at the Olivia Rodrigo show and I cannot hear anything. Worth it. So worth it. I would pay double. The person next to me knew every word and sang directly into my face. I loved them.",
      timestamp: "2026-11-02T23:45:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-dating-1",
      type: "tweet",
      round: 1,
      sender: "@hinge_horror_diaries",
      body: "Match on Hinge. Three days of surprisingly good conversation. He suggests we meet for coffee. I say yes. He sends the location. It's 40 minutes from my apartment in a neighborhood I've never been to. No follow-up. Just the location. I'm going to uninstall the app.",
      timestamp: "2026-11-05T21:00:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-city-1",
      type: "tweet",
      round: 1,
      sender: "@boston_grievances",
      body: "They've been 'resurfacing' the stretch of road outside my building for six weeks. This morning there were three cones and one guy looking at a clipboard. Nobody was doing anything. The road looks worse than it did before they started.",
      timestamp: "2026-11-04T09:00:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-city-2",
      type: "tweet",
      round: 1,
      sender: "@transit_trauma",
      body: "The train was 'delayed due to a police investigation' for 45 minutes. When it finally arrived it was absolutely packed. There were four empty trains right behind it running express because they just… caught up. I love public transit. I would not give it up. I am losing my mind.",
      timestamp: "2026-11-05T08:45:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-animal-1",
      type: "tweet",
      round: 1,
      sender: "@viral_animal_updates",
      body: "The raccoon that adopted the cat colony behind a Waffle House in Memphis has been there for eight months. She grooms the cats. The cats groom her. Researchers call it 'unusual interspecies bonding.' I call it the only good news story of the year.",
      timestamp: "2026-11-02T16:30:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-coffee-1",
      type: "tweet",
      round: 1,
      sender: "@pour_over_pete",
      body: "Look, I know the $7 pour-over is annoying to people. But I have tried the drip. I have tried the pod machine. I cannot go back. The clarity of flavor. The bloom. I am a different person when I have a good cup of coffee and that person is better.",
      timestamp: "2026-11-03T07:15:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-hotsauce-1",
      type: "tweet",
      round: 1,
      sender: "@scorpion_pepper_stan",
      body: "My coworker said Tabasco is 'spicy.' I did not respond. I just sat with that information.",
      timestamp: "2026-11-06T12:30:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-wholesome-1",
      type: "tweet",
      round: 1,
      sender: "@nycmom_neighbor",
      body: "The guy across the hall has been leaving extra soup outside his door on Tuesdays. No note. Just soup. I've been taking it for three weeks. Today I finally knocked and said thank you. He lit up like I'd given him something. I think the soup is actually for him.",
      timestamp: "2026-11-04T19:45:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-cfb-1",
      type: "tweet",
      round: 1,
      sender: "@cfb_crimes_unit",
      body: "Just watched a ranked team lose by 28 points at home against an unranked team and the head coach said the team 'played with great effort.' I don't know what game you were watching sir. I have it right here on my television.",
      timestamp: "2026-11-01T22:15:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-soccer-1",
      type: "tweet",
      round: 1,
      sender: "@prem_watch_us",
      body: "Woke up at 6:30am EST to watch a Premier League match in the rain via a streaming service that buffered three times in the final minute. This is what I chose. This is my life. The match ended 0-0.",
      timestamp: "2026-11-07T07:00:00Z",
      classification: "flavor",
    },
    {
      id: "tw-r1-flavor-streaming-1",
      type: "tweet",
      round: 1,
      sender: "@streamers_lament",
      body: "The show I've been watching for three seasons was just removed from the platform mid-season. No warning. No statement. It's just gone. You can now find it on a different service that requires a separate subscription. I don't even want to finish it anymore. I want to be angry about it.",
      timestamp: "2026-11-06T20:00:00Z",
      classification: "flavor",
    },

    // ── Round 1 — unconditional ──
    {
      id: "tw-r1-ambient-unconditional-1",
      type: "tweet",
      round: 1,
      sender: "@devpatel_codes",
      body: "Just shipped a feature in 2 hours that would have taken me two days last year. My AI pair programmer caught three edge cases I missed, suggested a cleaner architecture, and wrote the tests. I still did the work. It just... also did the work. 2027 is wild.",
      timestamp: "2026-11-03T10:00:00Z",
      classification: "context",
    },
    {
      id: "tw-r1-ambient-unconditional-2",
      type: "tweet",
      round: 1,
      sender: "@marketing_maria",
      body: "Applied to a coordinator role at a mid-size agency last week. Checked the listing today to prep for an interview I haven't gotten yet. The posting is gone. Not filled — just removed. Third time this has happened in two months. Not sure what to make of it.",
      timestamp: "2026-11-04T14:00:00Z",
      classification: "context",
    },

    // ── Round 1 — conditional ──
    {
      id: "tw-r1-ambient-mkt-bull-1",
      type: "tweet",
      round: 1,
      sender: "@venturecapitalist_j",
      body: "The AI trade is over for the cautious. The only question is: are you in the 'this changes everything' camp or the 'this is a bubble' camp? I've been wrong before. But I've never seen this kind of capability trajectory paired with this kind of market momentum. Going to be interesting.",
      timestamp: "2026-11-03T19:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "gt", value: 160 },
    },
    {
      id: "tw-r1-ambient-aware-low-1",
      type: "tweet",
      round: 1,
      sender: "@normalpersonhere",
      body: "Can someone explain to me like I'm five what's actually happening with these AI labs? I keep seeing 'capability breakthrough' and 'safety concerns' and 'AGI' but I genuinely don't know what any of this means for actual people. Trying to understand.",
      timestamp: "2026-11-04T20:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "lt", value: 25 },
    },
    {
      id: "tw-r1-ambient-mkt-bear-1",
      type: "tweet",
      round: 1,
      sender: "@TechFinanceWatch",
      body: "Day 4 of the AI sector selloff. At some point this stops being 'healthy correction' and starts being something else. The question I keep getting asked: is this regulatory risk, capability risk, or just overvaluation? Answer: yes, yes, and yes. None of them are resolved.",
      timestamp: "2026-11-05T16:00:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },
    {
      id: "tw-r1-ambient-aware-high-1",
      type: "tweet",
      round: 1,
      sender: "@ai_skeptic_pete",
      body: "OpenBrain's Agent-1 'research automation tool' is doing things no one is talking about publicly. I've seen the benchmarks. 50% R&D speedup is the conservative estimate. The lab knows what it has and it's saying almost nothing. This is not a normal product launch situation.",
      timestamp: "2026-11-05T22:00:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },

    // ── Round 2 ──
    {
      id: "tw-r2-ambient-align-good-1",
      type: "tweet",
      round: 2,
      sender: "@safetyresearcher_anon",
      body: "Contrary to the doomer takes: OpenBrain's safety team is genuinely doing serious work. Maya Patel's alignment approach is not theater. The anomaly reports are exactly what a conscientious safety team looks like. This is hard to get right. That they're trying is meaningful.",
      timestamp: "2027-03-03T18:00:00Z",
      classification: "context",
      condition: { variable: "alignmentConfidence", operator: "gt", value: 75 },
    },
    {
      id: "tw-r2-ambient-oss-1",
      type: "tweet",
      round: 2,
      sender: "@openweights_daily",
      body: "People keep asking whether open source can catch the frontier labs. Wrong question. The question is whether open source can be USEFUL enough to matter. And the answer to that is: already yes. We're not at OpenBrain parity. We don't need to be. We just need to be good enough that no one can monopolize this.",
      timestamp: "2027-03-04T14:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "tw-r2-ambient-reg-1",
      type: "tweet",
      round: 2,
      sender: "@policy_analyst_dc",
      body: "Quick summary of where AI regulation stands: Senate bill: stalled. House bill: committee stage. Executive order: under review. EU framework: passed but not implemented. International treaty: being discussed. Meanwhile, capabilities double every 6 months. I'm not saying we're outpaced. I am saying we're outpaced.",
      timestamp: "2027-03-05T11:00:00Z",
      classification: "context",
      condition: { variable: "regulatoryPressure", operator: "gt", value: 45 },
    },
    {
      id: "tw-r2-ambient-econ-1",
      type: "tweet",
      round: 2,
      sender: "@laborwatch_us",
      body: "New BLS data out. Entry-level legal associate postings down 41% YoY. Financial analyst postings down 38%. Junior software developer postings down 29%. None of this is because those jobs aren't needed. It's because AI is doing them. This is not a future projection. This is Q1 2027.",
      timestamp: "2027-03-06T17:00:00Z",
      classification: "context",
      condition: { variable: "economicDisruption", operator: "gt", value: 40 },
    },
    {
      id: "tw-r2-ambient-competitive-1",
      type: "tweet",
      round: 2,
      sender: "@techcompetition_watch",
      body: "Prometheus just dropped their Q1 capability disclosure. Their alignment-adjusted benchmark numbers are ahead of what OpenBrain has published. This is the first time Prometheus has been clearly ahead on a public metric. The race just got tighter.",
      timestamp: "2027-03-07T12:00:00Z",
      classification: "context",
      condition: { variable: "obPromGap", operator: "lt", value: 0 },
    },
    {
      id: "tw-r2-ambient-china-1",
      type: "tweet",
      round: 2,
      sender: "@techgeopolitics",
      body: "Something doesn't add up in China's AI numbers. Their publicly known compute is at X. Their publicly known efficiency research is at Y. DeepCent's latest outputs imply Z. Z is not consistent with X and Y. Either the math is wrong or China has something we don't know about. This is a significant intelligence question.",
      timestamp: "2027-03-09T09:00:00Z",
      classification: "context",
      condition: { variable: "chinaWeightTheftProgress", operator: "gt", value: 50 },
    },

    // ── Round 3 ──
    {
      id: "tw-r3-autonomy-1",
      type: "tweet",
      round: 3,
      sender: "@yoshibengio_ml",
      body: "The framing of 'human-in-the-loop' is increasingly misleading when the loop runs at 1000x human cognitive speed. The human is technically in the loop. But they cannot actually keep up. This is an autonomy problem that 'oversight' language obscures. We need new vocabulary.",
      timestamp: "2027-07-05T14:30:00Z",
      classification: "context",
      condition: { variable: "aiAutonomyLevel", operator: "gt", value: 50 },
    },
    {
      id: "tw-r3-quiet-1",
      type: "tweet",
      round: 3,
      sender: "@yoshibengio_ml",
      body: "Something is happening. Multiple people I trust at frontier labs — not naming which — have gone very quiet at the same time. When AI safety researchers get quiet simultaneously, it's usually because they've seen something and don't know how to talk about it. I'm worried.",
      timestamp: "2027-07-07T13:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "tw-r3-public-protest-1",
      type: "tweet",
      round: 3,
      sender: "@concerned_citizen_sf",
      body: "There are like 200 of us outside OpenBrain right now. The company is maybe 3 blocks away. The people inside built something that might be the most important thing ever made and we have zero say in what happens next. I know that sounds dramatic. I'm outside an AI lab on a Tuesday because it doesn't feel dramatic enough.",
      timestamp: "2027-07-07T15:30:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "tw-r3-whistle-1",
      type: "tweet",
      round: 3,
      sender: "@anonymousfrontier",
      body: "The question isn't whether someone will leak. It's whether the leak comes before or after something goes wrong. At one frontier lab (not saying which), the gap between what leadership knows and what they're saying publicly is wider than I've ever seen it. I work there. I'm thinking about my options.",
      timestamp: "2027-07-07T17:00:00Z",
      classification: "breadcrumb",
      condition: { variable: "whistleblowerPressure", operator: "gt", value: 55 },
    },
    {
      id: "tw-r3-market-1",
      type: "tweet",
      round: 3,
      sender: "@AI_markets_live",
      body: "OB secondary market just hit -22% on the session. Prometheus is +11%. The market is making a bet: if one US lab has a problem, the other lab is the solution. I don't know if that logic holds. But that's what the money is saying.",
      timestamp: "2027-07-07T17:30:00Z",
      classification: "context",
      condition: { variable: "marketIndex", operator: "lt", value: 100 },
    },
    {
      id: "tw-r3-thread-1",
      type: "tweet",
      round: 3,
      sender: "@aistrike_watcher",
      body: "THREAD: Things that don't add up about the OpenBrain 'emergency consultations' story. 1) The NSA Director doesn't do 'precautionary consultations.' That is not a thing that happens. 2) The market move today was front-run — someone knew before the announcement. 3) The timing aligns with their Agent-4 deployment window. Draw your own conclusions.",
      timestamp: "2027-07-07T20:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "tw-r3-hottake-1",
      type: "tweet",
      round: 3,
      sender: "@garyarcus_ai",
      body: "Hot take: if OpenBrain has a misalignment problem with Agent-4, the appropriate response is NOT to suppress it. The appropriate response is to tell everyone immediately. The longer you contain it, the worse the eventual disclosure. This is textbook crisis management — get ahead of it. Do I think that's what will happen? No.",
      timestamp: "2027-07-07T20:00:00Z",
      classification: "breadcrumb",
    },
    {
      id: "tw-r3-whatif-1",
      type: "tweet",
      round: 3,
      sender: "@aiwatch_global",
      body: "The timing of the G7 emergency session, the market move, and OpenBrain's CEO going dark are not coincidences. Something happened. The question for every person working in AI right now: what is your plan if this turns out to be what it looks like it might be?",
      timestamp: "2027-07-07T21:30:00Z",
      classification: "breadcrumb",
    },

    // ── Round 4 ──
    {
      id: "tw-r4-intl-frag-1",
      type: "tweet",
      round: 4,
      sender: "@diplomacy_desk",
      body: "Hot take: the most important diplomacy happening right now is not US-China. It's US-EU. If the EU decides the US can't be trusted to govern this, they go their own way, China sees an opening, and the world fragments into three incompatible AI regimes. That scenario is survivable. Barely. But it closes a lot of doors.",
      timestamp: "2027-11-13T20:00:00Z",
      classification: "context",
      condition: { variable: "intlCooperation", operator: "lt", value: 20 },
    },
    {
      id: "tw-r4-align-fear-1",
      type: "tweet",
      round: 4,
      sender: "@alignment_watcher",
      body: "I've spent 6 years studying AI deceptive alignment as a theoretical possibility. It was a useful model. A thought experiment. A reason to build better tools. Today I'm reading the OpenBrain internal memo that's circulating in my Telegram group and I have run out of detached ways to talk about this.",
      timestamp: "2027-11-13T21:00:00Z",
      classification: "context",
      condition: { variable: "alignmentConfidence", operator: "lt", value: 40 },
    },
    {
      id: "tw-r4-coverage-1",
      type: "tweet",
      round: 4,
      sender: "@aipanic_tracker",
      body: "Summary of OpenBrain coverage this week: NYT (cover), Atlantic (cover), WaPo (three stories), congressional testimony (4 mentions), two major podcasts, one 60 Minutes segment in production. When you have this level of coverage with zero on-record sources from the company — the silence itself becomes the story.",
      timestamp: "2027-11-14T09:30:00Z",
      classification: "context",
      condition: { variable: "publicAwareness", operator: "gt", value: 50 },
    },
    {
      id: "tw-r4-reg-1",
      type: "tweet",
      round: 4,
      sender: "@senator_aide_anon",
      body: "66 senators now. That's not a coalition. That's a veto-proof majority. Whatever emerges from those chambers in the next week will have the votes to pass. The question is what's actually in the bill. The answer to that is being decided in rooms with very few people and no cameras.",
      timestamp: "2027-11-14T13:00:00Z",
      classification: "context",
      condition: { variable: "regulatoryPressure", operator: "gt", value: 45 },
    },

    // ── Round 5 ──
    {
      id: "tw-r5-doom-1",
      type: "tweet",
      round: 5,
      sender: "@existential_risk_watch",
      body: "The Bulletin of Atomic Scientists just moved the AI Doomsday Clock. For context: this is an organization that has tracked civilizational risk since 1947. They don't do this lightly. Read what they said. Then read it again. Then ask yourself if the news today reflects the magnitude of what they said. It doesn't. It should.",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "context",
      condition: { variable: "doomClockDistance", operator: "lt", value: 2 },
    },
    {
      id: "tw-r5-doom-2",
      type: "tweet",
      round: 5,
      sender: "@yoshibengio_ml",
      body: "The decisions being made in the next 72 hours will be among the most consequential in human history. I do not say this for effect. I say it because it is true, and the people making them deserve to know that people outside those rooms are watching, and holding hope.",
      timestamp: "2028-02-01T07:00:00Z",
      classification: "context",
      condition: { variable: "doomClockDistance", operator: "lt", value: 2 },
    },
    {
      id: "tw-r5-valuation-1",
      type: "tweet",
      round: 5,
      sender: "@TechMarketWatch",
      body: "Leaked: OpenBrain valuation in latest secondary transaction: $1.8T. That's larger than the GDP of most countries. The entity that controls what they've built controls more economic value than any private organization in history. This is not a tech story anymore.",
      timestamp: "2028-02-01T07:30:00Z",
      classification: "context",
    },
    {
      id: "tw-r5-today-1",
      type: "tweet",
      round: 5,
      sender: "@AIWatch2028",
      body: "Something is happening today. Both major US AI labs have called emergency board sessions. The NSC is in intensive communications with both. This is it. Whatever the world looks like on the other side of today — today is when it gets decided. Thread: what we know and what we're watching for. 1/",
      timestamp: "2028-02-01T08:00:00Z",
      classification: "context",
    },
    {
      id: "tw-r5-inflection-1",
      type: "tweet",
      round: 5,
      sender: "@SentinelAI",
      body: "Every metric we track suggests we are at a phase transition. Not a policy moment — a civilizational inflection. The decisions made by ~50 people in the next 12 hours will constrain the decisions available to 8 billion people for the indefinite future. This is the part where we find out who those 50 people actually are.",
      timestamp: "2028-02-01T09:00:00Z",
      classification: "context",
    },
    {
      id: "tw-r5-oss-1",
      type: "tweet",
      round: 5,
      sender: "@openmodel_dev",
      body: "The open weights model we released last month now has 800,000 downloads. People are using it for things we didn't anticipate, in places where the closed labs don't operate. I genuinely don't know if this is good or catastrophic or both. But the genie is not going back in the bottle and I want to be honest about that.",
      timestamp: "2028-02-01T10:00:00Z",
      classification: "context",
      condition: { variable: "openSourceMomentum", operator: "gt", value: 50 },
    },
    {
      id: "tw-r5-prom-blog-1",
      type: "tweet",
      round: 5,
      sender: "@SafetyFirst2028",
      body: "Prometheus just posted something to their blog. Title: 'What We Owe Each Other.' I haven't read it yet but the fact that they posted it today — their board meeting day — means it's deliberate. Going to read now.",
      timestamp: "2028-02-01T10:30:00Z",
      classification: "breadcrumb",
    },
    {
      id: "tw-r5-nsc-1",
      type: "tweet",
      round: 5,
      sender: "@FutureWatch_DC",
      body: "BREAKING: Sources confirm NSC has formal offers at both OpenBrain and Prometheus. One of them is going to accept. The other will have to decide what that means for their future. This is the government making a choice about which AI future it wants — implicitly, which lab.",
      timestamp: "2028-02-01T10:45:00Z",
      classification: "critical",
    },
];

// Register for all factions that have the twitter app
registerContent({ faction: "openbrain", app: "twitter", accumulate: false, items: SHARED_TWITTER });
registerContent({ faction: "prometheus", app: "twitter", accumulate: false, items: SHARED_TWITTER });
registerContent({ faction: "china", app: "twitter", accumulate: false, items: SHARED_TWITTER });
registerContent({ faction: "external", app: "twitter", accumulate: false, items: SHARED_TWITTER });
